import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Setelah website atau aplikasi diluncurkan, pertanyaan yang paling sering muncul adalah: apakah ini berhasil? Jawaban yang memuaskan jarang datang dari perasaan atau dari jumlah pesan yang masuk. Jawaban yang bisa dipercaya datang dari data tentang bagaimana orang benar-benar memakai produk Anda: dari mana mereka datang, apa yang mereka lakukan, di mana mereka berhenti, dan apakah mereka kembali." },
  { type: "p", text: "Sayangnya, banyak bisnis memasang alat analitik lalu hanya melihat dasbor bawaan yang penuh angka tanpa arah. Jumlah kunjungan naik, tetapi penjualan tidak. Unduhan aplikasi tinggi, tetapi pengguna hilang setelah sehari. Tanpa rencana yang jelas, data yang terkumpul tidak menjawab pertanyaan bisnis, dan keputusan tetap berdasarkan tebakan." },
  { type: "p", text: "Artikel ini membahas cara menyusun analitik untuk website dan aplikasi mobile yang benar-benar membantu keputusan. Kami membahas cara memulai dari pertanyaan bisnis, menyusun rencana pelacakan, metrik yang layak dipantau, corong dan retensi, kualitas data, privasi dan persetujuan pengguna, pengujian perubahan, serta kebiasaan meninjau data. Kami tidak memakai angka rekaan tentang tolok ukur; yang kami tawarkan adalah prinsip dan daftar periksa yang bisa diterapkan pada berbagai skala." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Mulai dari pertanyaan bisnis yang ingin dijawab, bukan dari alat atau jumlah data yang bisa dikumpulkan",
      "Susun rencana pelacakan tertulis: peristiwa apa yang dicatat, apa artinya, dan siapa yang memakainya",
      "Pilih sedikit metrik yang terkait langsung dengan tujuan bisnis, bukan puluhan angka yang tampak mengesankan",
      "Hormati privasi: kumpulkan seperlunya, minta persetujuan yang sah, dan patuhi ketentuan yang berlaku",
      "Jadikan data sebagai bahan percobaan dan keputusan rutin, bukan laporan yang hanya dibaca sekali",
    ],
  },
  { type: "h2", text: "Mulai dari pertanyaan, bukan dari alat" },
  { type: "p", text: "Kesalahan paling umum dalam analitik adalah memasang alat terlebih dahulu dan berharap wawasan muncul sendiri. Alat hanya mengumpulkan dan menampilkan; menentukan apa yang penting tetap tugas Anda. Data tanpa pertanyaan seperti perpustakaan tanpa katalog: semua ada di sana, tetapi tidak ada yang bisa ditemukan." },
  { type: "p", text: "Mulailah dengan menuliskan pertanyaan bisnis yang ingin dijawab. Pertanyaan yang baik spesifik dan terkait keputusan. Misalnya, dari mana pembeli terbaik kami datang sehingga anggaran promosi bisa diarahkan ke sana? Di langkah mana pelanggan meninggalkan keranjang sehingga perbaikan bisa difokuskan? Fitur mana yang dipakai pengguna setia sehingga pengembangan berikutnya bisa diprioritaskan? Kapan pengguna baru berhenti memakai aplikasi sehingga alur perkenalan bisa diperbaiki?" },
  { type: "ol", items: [
    "Tuliskan tiga sampai lima pertanyaan bisnis terpenting untuk kuartal ini",
    "Untuk tiap pertanyaan, tentukan keputusan yang akan diambil berdasarkan jawabannya",
    "Tentukan data apa yang diperlukan untuk menjawab dan dari mana datangnya",
    "Baru kemudian pilih alat dan atur pelacakannya",
  ] },
  { type: "p", text: "Urutan ini juga mencegah pengumpulan data berlebihan. Setiap potong data yang dikumpulkan punya biaya: waktu pengembangan, penyimpanan, beban kepatuhan, dan risiko bila bocor. Data yang tidak menjawab pertanyaan apa pun sebaiknya tidak dikumpulkan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43",
    alt: "Layar menampilkan grafik klik dan tayangan dengan garis biru berfluktuasi",
    caption: "Grafik hanya berguna bila terkait pertanyaan yang jelas dan keputusan yang akan diambil.",
  },
  { type: "h2", text: "Rencana pelacakan: kamus untuk data Anda" },
  { type: "p", text: "Rencana pelacakan adalah dokumen yang mencantumkan setiap peristiwa yang dicatat, kapan dicatat, properti apa yang menyertainya, dan untuk apa dipakai. Ia seperti kamus yang menyatukan pemahaman tim bisnis, desain, dan pengembang. Tanpa dokumen ini, peristiwa diberi nama berbeda-beda oleh orang berbeda, makna berubah antarversi, dan laporan menjadi sulit dibandingkan dari waktu ke waktu." },
  { type: "p", text: "Rancang peristiwa berdasarkan tindakan bermakna pengguna, bukan setiap klik. Peristiwa seperti mendaftar, melihat produk, menambahkan ke keranjang, memulai pembayaran, menyelesaikan pembelian, dan mengundang teman biasanya lebih berguna daripada ratusan klik tombol kecil. Beri nama yang konsisten dan mudah dipahami, misalnya pola yang sama untuk semua peristiwa." },
  { type: "ul", items: [
    "Nama peristiwa: ringkas, seragam, dan menjelaskan tindakan",
    "Kapan dipicu: kondisi yang jelas, misalnya setelah server mengonfirmasi, bukan saat tombol ditekan",
    "Properti: informasi pendukung seperti kategori produk, nilai pesanan, atau jenis paket",
    "Identitas: bagaimana pengguna dikenali lintas perangkat dan sesi, dengan tetap menghormati privasi",
    "Pemilik: siapa yang bertanggung jawab atas definisi dan siapa yang memakai datanya",
    "Tujuan: pertanyaan bisnis yang dijawab oleh peristiwa ini",
  ] },
  { type: "p", text: "Simpan rencana pelacakan sebagai dokumen hidup dan perbarui setiap kali fitur berubah. Libatkan pengembang sejak perancangan fitur agar pelacakan menjadi bagian dari definisi selesai, bukan tambalan setelah peluncuran yang sering terlupakan." },
  { type: "h2", text: "Metrik yang layak dipantau" },
  { type: "p", text: "Godaan terbesar adalah memantau metrik yang tampak mengesankan tetapi tidak berhubungan dengan hasil bisnis. Jumlah kunjungan, tayangan, dan unduhan mudah naik dan enak dilaporkan, tetapi tidak menjamin pendapatan atau kepuasan. Bedakan antara metrik yang menenangkan dan metrik yang bisa ditindaklanjuti." },
  { type: "h3", text: "Akuisisi: dari mana pengguna datang" },
  { type: "p", text: "Metrik akuisisi menunjukkan saluran yang membawa orang ke produk Anda. Yang lebih penting daripada jumlah adalah kualitas: saluran mana yang membawa pengguna yang melakukan tindakan bernilai, bukan hanya mampir. Hubungkan sumber kunjungan dengan hasil akhir seperti pendaftaran atau pembelian agar anggaran tidak mengalir ke saluran yang ramai tetapi tidak menghasilkan." },
  { type: "h3", text: "Aktivasi: momen pengguna merasakan nilai" },
  { type: "p", text: "Aktivasi adalah titik ketika pengguna baru merasakan manfaat utama produk, misalnya menyelesaikan pesanan pertama, menambahkan data pertama, atau menyelesaikan tugas inti. Tentukan peristiwa yang menandai aktivasi untuk produk Anda dan pantau proporsi pengguna baru yang mencapainya serta berapa lama. Aktivasi yang lemah biasanya berarti alur perkenalan perlu diperbaiki." },
  { type: "h3", text: "Retensi: apakah mereka kembali" },
  { type: "p", text: "Retensi mengukur apakah pengguna kembali setelah kunjungan pertama. Bagi banyak produk ini adalah indikator kesehatan terpenting, karena menarik pengguna baru yang terus bocor lewat pintu belakang adalah usaha sia-sia. Analisis kelompok, yaitu membandingkan perilaku pengguna yang bergabung pada periode yang sama, memperlihatkan apakah perubahan produk benar-benar memperbaiki retensi dari waktu ke waktu." },
  { type: "h3", text: "Pendapatan dan nilai" },
  { type: "p", text: "Untuk bisnis yang menjual, pantau nilai rata-rata pesanan, frekuensi pembelian, dan nilai total pelanggan sepanjang hubungan. Metrik ini membantu menilai berapa yang pantas dikeluarkan untuk memperoleh pelanggan baru. Lengkapi dengan metrik biaya dan margin agar tidak mengejar pendapatan yang sebenarnya merugi." },
  { type: "callout", title: "Metrik yang baik memicu tindakan", text: "Jika sebuah angka naik atau turun dan tidak ada yang tahu apa yang harus dilakukan, angka itu mungkin hanya hiasan. Pilih metrik yang jika berubah, tim tahu langkah berikutnya." },
  { type: "h2", text: "Corong dan alur: menemukan titik bocor" },
  { type: "p", text: "Corong menggambarkan urutan langkah yang dilalui pengguna menuju tujuan, misalnya dari melihat produk hingga membayar. Di setiap langkah, sebagian pengguna berhenti. Dengan melihat di langkah mana penurunan terbesar, Anda tahu di mana perbaikan paling berpengaruh. Penurunan besar pada pengisian alamat mungkin menandakan formulir terlalu panjang, sedangkan penurunan pada pembayaran mungkin menunjuk pada pilihan metode yang kurang atau biaya kirim yang mengejutkan." },
  { type: "ul", items: [
    "Tentukan langkah-langkah corong yang benar-benar mencerminkan alur pengguna",
    "Bandingkan corong menurut perangkat, saluran, dan jenis pengguna untuk menemukan perbedaan",
    "Gabungkan data kuantitatif dengan pengamatan langsung, seperti rekaman sesi atau uji pengguna, untuk memahami mengapa",
    "Prioritaskan perbaikan di langkah dengan penurunan besar dan volume pengguna tinggi",
    "Ukur ulang setelah perubahan untuk memastikan perbaikan nyata, bukan kebetulan",
  ] },
  { type: "p", text: "Angka menunjukkan di mana masalahnya, tetapi jarang menjelaskan mengapa. Untuk memahami sebabnya, kombinasikan dengan umpan balik kualitatif: wawancara singkat dengan pengguna, ulasan, pertanyaan ke layanan pelanggan, dan menonton orang sungguhan mencoba produk Anda. Perpaduan dua jenis informasi inilah yang menghasilkan perbaikan tepat sasaran." },
  { type: "h2", text: "Kualitas data: dasar dari semua yang lain" },
  { type: "p", text: "Keputusan sebaik datanya. Data yang salah lebih berbahaya daripada tidak ada data karena memberi rasa percaya diri yang keliru. Masalah umum meliputi peristiwa yang tercatat ganda, peristiwa yang tidak tercatat di perangkat atau versi tertentu, identitas pengguna yang terpecah, dan lalu lintas dari mesin otomatis yang mencemari angka." },
  { type: "ul", items: [
    "Uji pelacakan sebelum rilis: pastikan peristiwa muncul dengan properti yang benar di semua platform",
    "Bandingkan angka analitik dengan sumber kebenaran, seperti jumlah pesanan di basis data, dan selidiki selisih besar",
    "Pantau kesehatan pelacakan: peringatan bila peristiwa penting tiba-tiba turun drastis",
    "Saring lalu lintas dari mesin otomatis dan pengujian internal agar tidak mencampur data",
    "Catat perubahan pelacakan beserta tanggalnya agar lonjakan atau penurunan bisa dijelaskan",
    "Waspadai pemblokir pelacak dan pengaturan privasi yang membuat sebagian pengguna tidak terhitung",
  ] },
  { type: "p", text: "Sadari bahwa data analitik hampir selalu merupakan perkiraan, bukan hitungan sempurna. Selisih kecil antarsumber wajar. Yang penting adalah konsistensi: cara mengukur yang sama dari waktu ke waktu sehingga tren dan perbandingan tetap bermakna, walau angka mutlaknya tidak sepenuhnya tepat." },
  { type: "h2", text: "Privasi dan persetujuan pengguna" },
  { type: "p", text: "Analitik berkaitan langsung dengan data pribadi, sehingga privasi harus menjadi bagian dari rancangan sejak awal. Kumpulkan hanya data yang diperlukan untuk menjawab pertanyaan bisnis. Jelaskan kepada pengguna apa yang dikumpulkan dan untuk apa, dengan bahasa yang mudah dipahami. Pada kondisi yang mengharuskan, minta persetujuan yang sah sebelum melacak dan hormati pilihan pengguna untuk menolak." },
  { type: "ul", items: [
    "Kumpulkan seminimal mungkin dan hindari data sensitif kecuali benar-benar diperlukan dan diizinkan",
    "Hindari memasukkan data pribadi, seperti nama atau nomor kontak, ke dalam properti peristiwa atau alamat halaman",
    "Sediakan pemberitahuan privasi yang jelas dan mekanisme persetujuan yang sesuai ketentuan",
    "Hormati pilihan pengguna dan sediakan cara mudah untuk mencabut persetujuan",
    "Tetapkan masa simpan data analitik dan hapus yang sudah tidak diperlukan",
    "Batasi siapa yang dapat mengakses data tingkat pengguna dan catat akses tersebut",
    "Periksa ketentuan perlindungan data pribadi yang berlaku saat ini, termasuk bila memakai penyedia analitik di luar negeri",
  ] },
  { type: "p", text: "Privasi bukan hanya kewajiban hukum, tetapi juga soal kepercayaan. Pengguna yang merasa dilacak berlebihan akan pergi, dan insiden kebocoran data merusak reputasi lebih lama daripada keuntungan jangka pendek yang diperoleh dari data tambahan. Pendekatan yang menghormati privasi dan tetap menjawab pertanyaan bisnis hampir selalu tersedia, misalnya memakai data agregat atau anonim bila identitas individu tidak diperlukan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1551288049-bebda4e38f71",
    alt: "Dashboard berisi beberapa grafik data yang ditampilkan berdampingan",
    caption: "Dasbor yang baik menampilkan sedikit angka yang berkaitan dengan keputusan, bukan semua angka yang bisa diambil.",
  },
  { type: "h2", text: "Dasbor yang dibaca, bukan dipajang" },
  { type: "p", text: "Dasbor yang penuh grafik jarang dibaca. Dasbor yang efektif menjawab beberapa pertanyaan penting dengan jelas dan sesuai audiensnya. Pemilik bisnis butuh gambaran ringkas tentang pendapatan, pelanggan baru, dan tren utama. Tim produk butuh detail penggunaan fitur dan retensi. Tim pemasaran butuh kinerja saluran dan biaya per hasil." },
  { type: "ul", items: [
    "Batasi jumlah grafik dan beri judul yang menyebut pertanyaan yang dijawab",
    "Tampilkan perbandingan dengan periode sebelumnya agar angka punya konteks",
    "Cantumkan tanggal pembaruan terakhir dan definisi tiap metrik",
    "Pisahkan ringkasan eksekutif dari tampilan rinci untuk analisis",
    "Kirim ringkasan rutin kepada pihak yang membutuhkan alih-alih menunggu mereka membuka dasbor",
    "Hapus grafik yang tidak pernah dilihat atau tidak pernah memicu keputusan",
  ] },
  { type: "p", text: "Tentukan irama tinjauan. Mingguan untuk indikator operasional dan pemasaran, bulanan untuk gambaran yang lebih strategis, dan setiap kali setelah perubahan besar untuk memeriksa dampaknya. Catat keputusan yang diambil dari tiap tinjauan agar data terhubung dengan tindakan nyata dan hasilnya bisa dinilai kemudian." },
  { type: "h2", text: "Menguji perubahan dengan percobaan" },
  { type: "p", text: "Setelah menemukan masalah, wajar ingin segera memperbaikinya. Namun perubahan yang tampak baik belum tentu memperbaiki hasil. Percobaan terkendali, seperti menampilkan dua versi halaman kepada kelompok pengguna berbeda secara acak, membantu memastikan bahwa perubahan benar-benar menghasilkan perbaikan, bukan kebetulan atau pengaruh musim." },
  { type: "ol", items: [
    "Rumuskan hipotesis yang jelas: perubahan apa, diharapkan memengaruhi metrik apa, dan mengapa",
    "Tentukan metrik utama dan batas keberhasilan sebelum percobaan dimulai",
    "Bagi pengguna secara acak dan jaga agar kelompok sebanding",
    "Jalankan cukup lama dan cukup besar agar hasil tidak sekadar kebetulan, melewati siklus mingguan",
    "Jangan mengintip lalu menghentikan lebih awal hanya karena hasil sementara tampak bagus",
    "Catat hasil, termasuk percobaan yang gagal, agar pelajaran tidak hilang",
  ] },
  { type: "p", text: "Bila lalu lintas Anda masih kecil, percobaan statistik mungkin tidak cukup andal. Dalam kasus itu, andalkan pengamatan kualitatif, perubahan bertahap dengan pengukuran sebelum dan sesudah, serta kehati-hatian dalam menarik kesimpulan. Kejujuran tentang apa yang bisa dan tidak bisa disimpulkan dari data jauh lebih berharga daripada angka yang terlihat meyakinkan." },
  { type: "h2", text: "Memilih alat sesuai kebutuhan" },
  { type: "p", text: "Pasar alat analitik sangat luas, dari yang gratis dan sederhana hingga platform perusahaan yang rumit. Pilih berdasarkan pertanyaan yang ingin dijawab, kemampuan tim, dan ketentuan data. Untuk kebanyakan bisnis kecil dan menengah, satu alat analitik web atau produk yang mapan ditambah akses langsung ke basis data sendiri sudah memadai." },
  { type: "ul", items: [
    "Pastikan alat mendukung platform Anda, baik web maupun aplikasi mobile, dengan cara pelacakan yang konsisten",
    "Periksa di mana data disimpan, siapa yang memilikinya, dan bagaimana mengekspornya bila Anda berpindah alat",
    "Pertimbangkan dampak pada kecepatan halaman dan ukuran aplikasi dari skrip pelacakan",
    "Nilai kemudahan bagi tim nonteknis untuk membuat laporan sendiri tanpa selalu bergantung pada pengembang",
    "Perhatikan biaya yang bisa membesar seiring volume peristiwa",
    "Hindari memasang banyak alat yang tumpang tindih sehingga angkanya saling bertentangan",
  ] },
  { type: "p", text: "Jangan lupakan data yang sudah Anda miliki. Basis data transaksi, sistem kasir, CRM, dan ERP sering memuat jawaban yang lebih akurat untuk pertanyaan tertentu daripada alat pelacakan perilaku. Menggabungkan keduanya, misalnya mengaitkan sumber kunjungan dengan pesanan nyata, memberi gambaran yang lebih utuh." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Memasang alat tanpa pertanyaan bisnis dan tanpa rencana pelacakan",
    "Mengejar metrik yang tampak besar tetapi tidak berkaitan dengan hasil",
    "Tidak menguji pelacakan sehingga keputusan diambil dari data yang salah",
    "Mengumpulkan data pribadi berlebihan tanpa pemberitahuan dan persetujuan yang memadai",
    "Menarik kesimpulan dari data beberapa hari atau jumlah pengguna yang sangat kecil",
    "Membuat dasbor indah yang tidak pernah memicu keputusan",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Tuliskan tiga pertanyaan bisnis terpenting dan keputusan yang akan bergantung pada jawabannya",
    "Daftar peristiwa yang diperlukan dan buat rencana pelacakan satu halaman",
    "Uji pelacakan dari ujung ke ujung dan bandingkan dengan sumber kebenaran, seperti jumlah pesanan",
    "Periksa pemberitahuan privasi dan mekanisme persetujuan, dan perbaiki bila belum sesuai",
    "Buat dasbor ringkas dengan lima sampai tujuh metrik dan jadwalkan tinjauan mingguan",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Analitik yang baik bukan tentang mengumpulkan sebanyak mungkin data, melainkan tentang menjawab pertanyaan bisnis yang benar dengan data yang dapat dipercaya. Rencana pelacakan yang jelas, metrik yang terkait tujuan, kualitas data yang dijaga, penghormatan terhadap privasi, dan kebiasaan meninjau serta menguji perubahan membuat data menjadi dasar keputusan, bukan hiasan laporan." },
  { type: "p", text: "Mulailah kecil dengan pertanyaan yang paling penting, ukur dengan jujur, dan tindaklanjuti. Dengan begitu website dan aplikasi Anda berkembang berdasarkan bukti tentang apa yang benar-benar dibutuhkan pengguna." },
  {
    type: "cta",
    title: "Ingin website atau aplikasi yang dilengkapi analitik dan pelaporan yang menjawab pertanyaan bisnis Anda?",
    text: "Tim AG·SORA membangun website dan aplikasi lengkap dengan rencana pelacakan, dasbor yang jelas, dan praktik privasi yang bertanggung jawab. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
