import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Aplikasi mobile sering dirancang dan diuji pada ponsel terbaru dengan jaringan cepat di kantor. Pelanggan Anda mungkin memakai ponsel berusia beberapa tahun dengan memori terbatas, penyimpanan yang hampir penuh, dan sinyal yang naik turun di jalan, di pasar, atau di daerah yang jauh dari menara. Pengalaman yang mulus bagi tim pengembang bisa menjadi menjengkelkan bagi pengguna sesungguhnya." },
  { type: "p", text: "Di pasar seperti Indonesia, keragaman perangkat dan kualitas jaringan sangat lebar. Aplikasi yang lambat dibuka, boros kuota, atau menghabiskan baterai akan cepat dihapus. Banyak pengguna menghapus aplikasi bukan karena tidak butuh, melainkan karena ruang penyimpanan mereka hanya cukup untuk beberapa aplikasi yang paling berguna." },
  { type: "p", text: "Artikel ini membahas cara merancang dan memelihara aplikasi mobile yang tetap nyaman di perangkat sederhana dan jaringan lambat: ukuran aplikasi, kecepatan membuka, pemakaian data, baterai, kerja tanpa jaringan, dan cara mengujinya. Tidak ada angka rekaan; fokusnya adalah prinsip dan kebiasaan kerja yang bisa diterapkan sejak awal." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Rancang dan uji untuk perangkat dan jaringan yang paling umum di pelanggan Anda, bukan yang terbaik",
      "Ukuran aplikasi, waktu buka, dan pemakaian data adalah bagian dari pengalaman pengguna",
      "Biarkan aplikasi tetap berguna saat jaringan lambat atau terputus",
      "Hemat baterai dan memori dengan menunda pekerjaan yang tidak mendesak",
      "Ukur kinerja pada perangkat nyata dan pantau terus setelah rilis",
    ],
  },
  { type: "h2", text: "Memahami perangkat dan jaringan pelanggan Anda" },
  { type: "p", text: "Mulailah dari data, bukan dari asumsi. Lihat statistik pengguna aplikasi atau website Anda untuk mengetahui merek, versi sistem operasi, ukuran layar, dan jenis jaringan yang paling banyak dipakai. Data ini sering mengejutkan: perangkat yang dianggap lama ternyata dipakai oleh sebagian besar pelanggan." },
  { type: "p", text: "Dari data itu, tetapkan perangkat acuan: ponsel dengan spesifikasi sederhana yang mewakili pengguna kebanyakan. Perangkat ini menjadi tolok ukur. Bila aplikasi nyaman di perangkat acuan, ia hampir pasti nyaman di perangkat yang lebih baik. Tidak sebaliknya." },
  { type: "p", text: "Pertimbangkan juga konteks pemakaian. Pengguna di lapangan, di kendaraan, atau di area dengan sinyal lemah punya kebutuhan berbeda dari pengguna di rumah dengan jaringan tetap. Pahami di mana dan kapan aplikasi Anda sebenarnya dipakai." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1512428559087-560fa5ceab42",
    alt: "Seseorang memegang ponsel Android putih",
    caption: "Uji aplikasi pada perangkat yang benar-benar dipakai pelanggan, bukan hanya pada ponsel terbaru tim pengembang.",
  },
  { type: "h2", text: "Ukuran aplikasi: ruang penyimpanan adalah sumber daya langka" },
  { type: "p", text: "Banyak pengguna memiliki penyimpanan yang hampir penuh. Aplikasi yang berukuran besar lebih sulit dipasang dan lebih cepat dihapus saat ruang dibutuhkan. Ukuran juga memengaruhi biaya kuota untuk mengunduh dan memperbarui, yang bagi sebagian pengguna cukup terasa." },
  { type: "p", text: "Kurangi ukuran dengan beberapa cara: kompres dan sesuaikan gambar, hapus sumber daya dan pustaka yang tidak dipakai, hindari menyertakan font atau aset berlebih, dan manfaatkan fitur pengiriman modular yang menyediakan bagian aplikasi sesuai kebutuhan perangkat. Setiap pustaka tambahan sebaiknya dipertanyakan manfaatnya." },
  { type: "p", text: "Pertimbangkan versi ringan atau aplikasi web progresif bila kebutuhan Anda sederhana. Untuk fungsi seperti katalog atau pemesanan, pengalaman web yang cepat sering lebih sesuai bagi pengguna yang enggan memasang aplikasi lagi." },
  { type: "h2", text: "Kecepatan membuka dan respons" },
  { type: "p", text: "Waktu dari ikon ditekan sampai pengguna bisa bertindak sangat menentukan kesan pertama. Pada perangkat sederhana, proses awal yang berat seperti memuat banyak data, menginisialisasi banyak pustaka, atau menampilkan layar pembuka yang panjang terasa jauh lebih lambat." },
  { type: "p", text: "Tampilkan konten yang paling penting lebih dulu dan tunda sisanya. Tampilkan kerangka layar atau data terakhir yang tersimpan sementara pembaruan dimuat di latar belakang, sehingga pengguna tidak menatap layar kosong. Inisialisasi layanan yang tidak dibutuhkan pada layar pertama hanya ketika diperlukan." },
  { type: "p", text: "Perhatikan juga respons terhadap sentuhan. Daftar panjang yang tersendat, animasi berat, dan tombol yang tidak memberi umpan balik membuat aplikasi terasa rusak. Gunakan daftar yang memuat bertahap, kurangi animasi pada perangkat yang kesulitan, dan beri tanda bahwa tindakan sedang diproses." },
  { type: "h2", text: "Hemat data dan tangguh pada jaringan lambat" },
  { type: "p", text: "Kuota data bukan sumber daya tak terbatas bagi banyak pengguna. Kirim hanya data yang diperlukan, minta jumlah yang wajar per halaman, kompres respons, dan simpan sementara data yang jarang berubah agar tidak diunduh ulang setiap kali. Gambar yang diunduh sebaiknya disesuaikan ukurannya dengan layar perangkat." },
  { type: "p", text: "Jaringan lambat dan putus-sambung menuntut ketangguhan. Beri batas waktu yang wajar pada permintaan, ulangi dengan jeda yang bertambah, dan jangan membuat pengguna menunggu tanpa kabar. Tampilkan status yang jujur seperti jaringan lambat dan tawarkan untuk mencoba lagi, bukan indikator berputar yang tak berujung." },
  { type: "p", text: "Pertimbangkan pilihan hemat data yang bisa diaktifkan pengguna: gambar berkualitas lebih rendah, pemutaran otomatis dimatikan, atau sinkronisasi hanya lewat Wi-Fi untuk berkas besar. Pilihan kecil ini dihargai pengguna yang mengatur kuotanya dengan ketat." },
  { type: "callout", title: "Jaringan lambat bukan keadaan luar biasa", text: "Bagi banyak pengguna, jaringan yang lambat atau terputus adalah keadaan sehari-hari. Rancang aplikasi seolah-olah itu normal, bukan pengecualian yang ditangani sebagai kasus langka." },
  { type: "h2", text: "Tetap berguna tanpa jaringan" },
  { type: "p", text: "Banyak aplikasi tidak perlu mati total saat jaringan hilang. Katalog yang sudah dilihat, riwayat pesanan, atau formulir yang sedang diisi dapat tetap tersedia dari penyimpanan lokal. Pengguna yang masih bisa membaca dan menyiapkan tindakan akan jauh lebih sabar daripada yang disambut pesan kesalahan." },
  { type: "p", text: "Untuk tindakan yang menulis data, seperti mengirim pesanan atau laporan, pertimbangkan antrean lokal yang mengirim otomatis ketika jaringan kembali. Tampilkan dengan jelas apa yang sudah terkirim dan apa yang masih menunggu agar pengguna tidak mengulang atau ragu." },
  { type: "p", text: "Konsep kerja tanpa jaringan membawa tantangan sendiri: konflik ketika data berubah di dua tempat dan kebutuhan menyinkronkan dengan aman. Rancang aturannya sejak awal, dan pilih fungsi yang benar-benar diuntungkan oleh kerja tanpa jaringan, bukan semuanya sekaligus." },
  { type: "h2", text: "Baterai dan memori" },
  { type: "p", text: "Aplikasi yang menguras baterai cepat dicurigai dan dihapus. Penyebab umum adalah pembaruan lokasi yang terus-menerus, pekerjaan latar belakang yang terlalu sering, animasi yang tidak berhenti, dan permintaan jaringan yang berulang tanpa perlu. Minta lokasi hanya saat dibutuhkan dan dengan ketelitian seperlunya." },
  { type: "p", text: "Pada perangkat dengan memori kecil, sistem dapat menutup aplikasi di latar belakang kapan saja. Simpan keadaan pengguna secara berkala agar ketika aplikasi dibuka kembali, ia kembali ke posisi semula, bukan memulai dari awal. Lepaskan sumber daya besar seperti gambar yang sudah tidak terlihat." },
  { type: "p", text: "Jadwalkan pekerjaan berat, seperti sinkronisasi besar atau pengunggahan berkas, pada saat perangkat sedang mengisi daya dan tersambung Wi-Fi bila memungkinkan. Pengguna tidak akan menyadarinya, tetapi baterai dan kuotanya terselamatkan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1555774698-0b77e0d5fac6",
    alt: "Tangan memegang ponsel yang menampilkan layar utama penuh ikon aplikasi",
    caption: "Setiap aplikasi bersaing memperebutkan ruang, memori, dan baterai yang terbatas di ponsel pengguna.",
  },
  { type: "h2", text: "Antarmuka yang ramah perangkat sederhana" },
  { type: "p", text: "Layar kecil dan resolusi rendah membutuhkan tata letak yang sederhana. Hindari elemen yang terlalu rapat, teks yang terlalu kecil, dan target sentuh yang sulit ditekan. Tombol dan tautan sebaiknya cukup besar untuk jempol, dengan jarak yang memadai agar tidak salah tekan." },
  { type: "p", text: "Kurangi efek visual yang mahal seperti bayangan berlapis, transparansi bertumpuk, dan animasi berat pada perangkat yang terbatas. Antarmuka bersih dengan kontras yang jelas bukan hanya lebih ringan, tetapi juga lebih mudah dibaca di bawah sinar matahari dan oleh pengguna dengan penglihatan berbeda." },
  { type: "p", text: "Pertimbangkan juga bahasa dan literasi digital pengguna. Gunakan kata sederhana, alur yang pendek, dan petunjuk yang jelas. Aplikasi yang mudah dipakai oleh pengguna paling awam hampir selalu mudah dipakai oleh semua orang." },
  { type: "h2", text: "Menguji pada kondisi nyata" },
  { type: "p", text: "Pengujian pada emulator di komputer pengembang tidak cukup. Siapkan beberapa perangkat nyata yang mewakili pelanggan, dari yang sederhana sampai yang menengah, dan uji alur-alur penting di dalamnya: membuka aplikasi, mencari, memesan, dan membayar." },
  { type: "p", text: "Simulasikan jaringan buruk. Banyak alat pengembang dapat membatasi kecepatan dan menambah jeda atau kehilangan paket. Coba juga dengan sinyal yang benar-benar lemah, memasuki dan keluar dari terowongan atau lift, dan mode pesawat di tengah proses. Kejutan terbesar sering muncul pada kondisi yang tampaknya sepele." },
  { type: "p", text: "Setelah rilis, pantau data kinerja dari perangkat nyata: waktu buka, kegagalan, dan penutupan mendadak, dipecah per jenis perangkat dan versi. Data ini mengungkap masalah yang tidak pernah muncul pada perangkat uji Anda dan menjadi dasar prioritas perbaikan." },
  { type: "h2", text: "Pembaruan yang tidak membebani pengguna" },
  { type: "p", text: "Pembaruan yang sering dan besar menguras kuota dan membuat pengguna menundanya. Rilis perubahan dalam ukuran yang wajar, dan gunakan mekanisme pembaruan yang hanya mengunduh bagian yang berubah bila tersedia. Jelaskan di catatan rilis apa yang berubah dalam bahasa yang dipahami pengguna." },
  { type: "p", text: "Dukung beberapa versi sistem operasi lama selama masih dipakai banyak pelanggan, dan umumkan jauh hari sebelum menghentikan dukungan. Memutus dukungan mendadak berarti kehilangan pelanggan yang tidak bisa atau tidak mau mengganti ponsel." },
  { type: "p", text: "Siapkan mekanisme untuk menangani versi lama yang masih beredar, misalnya pesan ajakan memperbarui yang tidak memaksa kecuali ada alasan keamanan. Server sebaiknya tetap melayani versi lama selama masa transisi yang wajar." },
  { type: "h2", text: "Anggaran kinerja: menjaga aplikasi tetap ringan seiring waktu" },
  { type: "p", text: "Aplikasi jarang menjadi lambat karena satu keputusan besar; ia melambat sedikit demi sedikit, setiap kali ada fitur, pustaka, atau gambar baru yang tampak tidak berbahaya. Untuk melawannya, tetapkan anggaran kinerja: batas yang disepakati untuk ukuran aplikasi, waktu buka pada perangkat acuan, dan pemakaian data pada alur utama." },
  { type: "p", text: "Periksa anggaran itu setiap kali rilis. Bila suatu perubahan melampaui batas, tim harus memutuskan: mengoptimalkannya, mengganti sesuatu yang lain, atau secara sadar menaikkan batas dengan alasan yang jelas. Kebiasaan ini mengubah kinerja dari hal yang diperbaiki sesekali menjadi hal yang dijaga terus-menerus." },
  { type: "p", text: "Libatkan seluruh tim, bukan hanya pengembang. Desainer yang memilih animasi, pemasar yang meminta pustaka pelacakan, dan manajer produk yang menambah fitur semuanya memengaruhi bobot aplikasi. Anggaran yang dipahami bersama membuat kompromi dibicarakan secara terbuka." },
  { type: "h2", text: "Pengguna yang beragam dan perangkat yang dipakai bersama" },
  { type: "p", text: "Di banyak keluarga dan usaha kecil, satu ponsel dipakai bergantian oleh beberapa orang, atau pengguna mengganti nomor dan perangkat cukup sering. Rancang proses masuk dan pemulihan akun yang tidak bergantung pada satu perangkat atau satu nomor saja, dan sediakan cara aman untuk keluar dari akun." },
  { type: "p", text: "Perhatikan juga kebutuhan aksesibilitas: ukuran teks yang bisa diperbesar, kontras warna yang memadai, dan label yang dapat dibaca oleh pembaca layar. Praktik ini membantu pengguna dengan keterbatasan penglihatan, juga membantu semua orang yang memakai ponsel di bawah sinar matahari atau dengan layar yang retak." },
  { type: "p", text: "Pertimbangkan keamanan di perangkat yang mungkin hilang atau dipinjam. Hindari menyimpan data sensitif secara terbuka di perangkat, dan sediakan pengunci atau verifikasi tambahan untuk tindakan bernilai tinggi seperti pembayaran." },
  { type: "h2", text: "Menimbang kompromi dengan jujur" },
  { type: "p", text: "Merancang untuk perangkat sederhana berarti kadang tidak memakai efek atau fitur yang menarik. Itu bukan kemunduran, melainkan pilihan yang disengaja. Tanyakan pada setiap fitur: berapa banyak pelanggan yang diuntungkan, dan berapa banyak yang dirugikan oleh bobot tambahannya?" },
  { type: "p", text: "Sering kali ada jalan tengah: fitur yang lebih kaya diaktifkan hanya pada perangkat yang mampu, sementara perangkat sederhana mendapat versi yang lebih ringan dengan fungsi inti yang sama. Pendekatan bertingkat ini menjaga semua pelanggan terlayani tanpa mengorbankan pengalaman bagi yang punya perangkat lebih baik." },
  { type: "h2", text: "Mendengar langsung dari pengguna" },
  { type: "p", text: "Data teknis memberi tahu apa yang terjadi, tetapi tidak selalu mengapa. Sediakan cara mudah bagi pengguna untuk melaporkan masalah dari dalam aplikasi, termasuk informasi perangkat dan versi yang disertakan otomatis, dengan persetujuan mereka. Laporan yang disertai konteks jauh lebih mudah dipecahkan." },
  { type: "p", text: "Baca ulasan di toko aplikasi dengan teliti. Keluhan seperti lemot, boros kuota, atau panas sering menjadi petunjuk paling jujur tentang pengalaman di perangkat nyata. Tanggapi dengan sopan, dan beri tahu pengguna ketika masalah yang mereka laporkan sudah diperbaiki." },
  { type: "h2", text: "Dampak bisnis dari aplikasi yang ringan" },
  { type: "p", text: "Aplikasi yang ringan bukan sekadar kebanggaan teknis; ia berdampak langsung pada hasil bisnis. Aplikasi yang cepat dibuka dan tidak boros kuota lebih sering dipakai, lebih jarang dihapus, dan lebih mudah direkomendasikan. Pelanggan yang tetap memasang aplikasi Anda adalah pelanggan yang tetap terjangkau oleh notifikasi, penawaran, dan layanan Anda." },
  { type: "p", text: "Sebaliknya, pengalaman lambat sering tidak terlihat dalam laporan. Pengguna yang menyerah di tengah pembayaran karena sinyal lemah tidak mengirim keluhan; mereka hanya hilang. Karena itu, kinerja layak diperlakukan sebagai bagian dari rencana produk dan target bisnis, bukan sekadar urusan teknis yang dikerjakan bila sempat." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menguji hanya pada ponsel terbaru dengan jaringan kantor yang cepat",
    "Menambahkan pustaka besar untuk fungsi kecil sehingga ukuran aplikasi membengkak",
    "Memuat semua data sekaligus saat aplikasi dibuka",
    "Menampilkan indikator berputar tanpa batas waktu dan tanpa pesan yang jujur",
    "Meminta lokasi dan menjalankan pekerjaan latar belakang secara terus-menerus",
    "Menghentikan dukungan versi lama tanpa pemberitahuan dan masa transisi",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Periksa data pengguna untuk mengetahui perangkat dan versi sistem operasi yang paling umum",
    "Pilih satu atau dua ponsel sederhana sebagai perangkat acuan untuk pengujian",
    "Ukur ukuran aplikasi, waktu buka, dan pemakaian data pada alur utama",
    "Uji alur penting dengan jaringan yang dibatasi atau diputus",
    "Daftar tiga perbaikan dengan dampak terbesar dan masukkan ke rencana pengembangan",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Aplikasi yang baik bukan yang paling banyak fitur atau paling mewah, melainkan yang bisa dipakai nyaman oleh pelanggan Anda dalam keadaan sehari-hari mereka. Ponsel sederhana dan jaringan lambat bukan pengecualian yang boleh diabaikan; bagi banyak pelanggan, itulah kenyataannya." },
  { type: "p", text: "Dengan memahami perangkat pelanggan, menjaga aplikasi tetap ringan, tangguh terhadap jaringan buruk, dan mengujinya pada kondisi nyata, Anda menjangkau lebih banyak orang dan mengurangi alasan mereka meninggalkan aplikasi Anda." },
  {
    type: "cta",
    title: "Aplikasi Anda lambat atau sering dihapus pengguna?",
    text: "Tim AG·SORA membangun dan mengoptimalkan aplikasi mobile yang ringan, tangguh pada jaringan lambat, dan diuji pada perangkat nyata pelanggan Anda. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/mobile",
    label: "Konsultasi gratis",
  },
];
