import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Sebagian pekerjaan terpenting di banyak perusahaan terjadi jauh dari meja kantor. Tenaga penjual mengunjungi toko pelanggan, teknisi memperbaiki mesin di lokasi, pengemudi mengantar barang, dan petugas survei memeriksa keadaan di lapangan. Merekalah yang bertemu pelanggan dan menghasilkan pendapatan, tetapi sering justru merekalah yang paling sedikit didukung oleh sistem perusahaan." },
  { type: "p", text: "Di banyak tempat, tim lapangan masih bekerja dengan kertas, foto di galeri ponsel, dan laporan lewat grup obrolan. Pesanan ditulis di buku lalu diketik ulang admin keesokan harinya. Laporan kunjungan dikirim sebagai pesan panjang yang tidak pernah direkap. Kantor tidak tahu apa yang terjadi sampai sore hari, dan tim lapangan tidak tahu stok, harga terbaru, atau riwayat pelanggan yang sedang mereka hadapi." },
  { type: "p", text: "Artikel ini membahas cara merancang aplikasi mobile untuk tim lapangan: penjual, teknisi, pengantar, dan petugas survei. Kami membahas pekerjaan yang layak dipindahkan ke aplikasi, kerja tanpa sinyal, bukti kunjungan, hubungan dengan ERP dan CRM, privasi dan keamanan, serta cara agar aplikasi benar-benar dipakai. Tidak ada angka rekaan; yang kami tawarkan adalah prinsip dan daftar periksa dari sudut pandang pemilik bisnis." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Aplikasi lapangan berhasil bila memudahkan pekerjaan orang yang memakainya, bukan sekadar mengawasinya",
      "Rancang untuk sinyal lemah: data penting tersimpan di perangkat dan dikirim ketika jaringan kembali",
      "Catat bukti di tempat kejadian: foto, tanda tangan, lokasi, dan waktu",
      "Hubungkan dengan ERP dan CRM agar pesanan dan laporan tidak diketik ulang",
      "Jelaskan dengan terbuka data lokasi apa yang dikumpulkan dan untuk apa",
    ],
  },
  { type: "h2", text: "Jarak antara lapangan dan kantor" },
  { type: "p", text: "Masalah utama pekerjaan lapangan adalah jarak informasi. Kantor memiliki data: harga, stok, piutang pelanggan, riwayat perbaikan, dan jadwal. Lapangan memiliki kenyataan: apa yang diminta pelanggan, keadaan mesin, barang pesaing di rak, dan alasan pesanan batal. Selama keduanya hanya terhubung lewat telepon dan obrolan, masing-masing bekerja dengan gambaran yang tidak lengkap." },
  { type: "p", text: "Jarak itu menimbulkan biaya yang jarang dihitung. Penjual menjanjikan barang yang ternyata kosong. Teknisi datang tanpa suku cadang yang tepat dan harus kembali esok hari. Admin menghabiskan pagi menyalin pesanan dari foto tulisan tangan. Tagihan terlambat dibuat karena berita acara pekerjaan belum sampai ke kantor." },
  { type: "p", text: "Aplikasi mobile menutup jarak itu dengan dua arah. Data kantor sampai ke tangan orang lapangan pada saat ia membutuhkannya, dan kejadian di lapangan sampai ke sistem kantor pada saat terjadi. Nilai aplikasi terletak pada pertukaran dua arah ini, bukan pada sekadar mengganti kertas dengan layar." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492",
    alt: "Pemandangan udara deretan truk kargo yang diparkir di area distribusi",
    caption: "Semakin banyak orang dan kendaraan yang bekerja di luar kantor, semakin mahal jarak informasi di antaranya.",
  },
  { type: "h2", text: "Pekerjaan yang layak dipindahkan ke aplikasi" },
  { type: "p", text: "Tidak semua hal perlu masuk aplikasi pada versi pertama. Pilih pekerjaan yang paling sering dilakukan, paling sering salah, atau paling lama tertunda sampai ke kantor. Biasanya pekerjaan itu termasuk dalam beberapa kelompok berikut." },
  { type: "ul", items: [
    "Jadwal dan daftar kunjungan hari ini beserta alamat dan petunjuk arah",
    "Informasi pelanggan: riwayat pesanan, piutang, catatan kunjungan sebelumnya",
    "Pembuatan pesanan atau penawaran langsung di tempat dengan harga dan stok terbaru",
    "Perintah kerja servis: keluhan, tindakan, suku cadang yang dipakai, hasil",
    "Bukti serah terima barang atau penyelesaian pekerjaan",
    "Formulir survei dan pemeriksaan dengan daftar periksa baku",
    "Penagihan dan pencatatan pembayaran yang diterima di lapangan",
  ] },
  { type: "p", text: "Mulailah dari satu peran dan satu alur yang lengkap dari awal sampai akhir. Aplikasi yang menyelesaikan satu pekerjaan dengan tuntas lebih berguna daripada aplikasi yang menyentuh sepuluh pekerjaan setengah jalan dan tetap memerlukan kertas untuk sisanya." },
  { type: "h2", text: "Merancang untuk keadaan lapangan" },
  { type: "p", text: "Orang lapangan memakai aplikasi dalam keadaan yang sangat berbeda dari pekerja kantor. Mereka berdiri, kadang di bawah terik matahari, dengan satu tangan memegang barang. Mereka diburu waktu dan pelanggan menunggu di depannya. Rancangan yang nyaman di meja kerja bisa sama sekali tidak terpakai di gudang pelanggan." },
  { type: "p", text: "Karena itu layar harus sederhana. Tombol besar, tulisan yang terbaca di cahaya terang, dan langkah sesedikit mungkin. Gantikan mengetik dengan memilih, memindai, dan memotret. Isi otomatis apa pun yang sudah diketahui sistem, seperti tanggal, lokasi, dan data pelanggan. Setiap kolom yang wajib diisi harus punya alasan kuat." },
  { type: "p", text: "Perhatikan pula perangkatnya. Tim lapangan sering memakai ponsel kelas menengah dengan baterai yang harus bertahan seharian. Aplikasi yang boros daya, berat, atau memakan banyak kuota akan dimatikan. Uji aplikasi pada perangkat yang benar-benar dipakai tim, bukan hanya pada ponsel terbaru milik pengembang." },
  { type: "h2", text: "Bekerja tanpa sinyal" },
  { type: "p", text: "Lapangan penuh dengan tempat tanpa jaringan: ruang bawah tanah, gudang berdinding logam, kawasan pabrik, dan daerah terpencil. Aplikasi yang berhenti bekerja ketika sinyal hilang akan cepat ditinggalkan, karena orang lapangan tidak bisa menunggu. Bagi banyak tim, kemampuan bekerja luring bukan fitur tambahan, melainkan syarat." },
  { type: "p", text: "Rancangan luring berarti data yang diperlukan hari itu, seperti daftar kunjungan, data pelanggan, dan katalog, diunduh ke perangkat sebelumnya. Pekerjaan yang dicatat tersimpan di perangkat lalu dikirim otomatis ketika jaringan tersedia. Pengguna harus bisa melihat dengan jelas mana yang sudah terkirim dan mana yang masih menunggu." },
  { type: "p", text: "Bagian yang paling sulit adalah menangani pertentangan data. Bagaimana bila dua orang mengubah catatan yang sama, atau stok yang tampak tersedia saat luring ternyata sudah habis? Aturan untuk keadaan ini harus diputuskan bersama pengembang sejak awal, karena menyangkut cara bisnis Anda bekerja, bukan hanya soal teknis." },
  { type: "callout", title: "Jangan sampai pekerjaan hilang", text: "Kepercayaan tim pada aplikasi hancur ketika laporan yang sudah diisi lenyap karena sinyal putus. Simpan setiap masukan ke perangkat saat itu juga, dan jangan pernah bergantung pada jaringan untuk menyimpan pekerjaan yang sedang dikerjakan." },
  { type: "h2", text: "Bukti di tempat kejadian" },
  { type: "p", text: "Salah satu manfaat terbesar aplikasi lapangan adalah bukti yang dicatat langsung di tempat. Foto barang yang diserahkan, foto keadaan mesin sebelum dan sesudah perbaikan, tanda tangan penerima di layar, serta lokasi dan waktu yang tercatat otomatis mengubah perdebatan menjadi fakta." },
  { type: "p", text: "Bukti ini mempercepat arus uang. Berita acara yang ditandatangani di ponsel sampai ke bagian penagihan pada menit yang sama, sehingga tagihan bisa dibuat hari itu juga. Sengketa tentang barang yang katanya tidak diterima atau pekerjaan yang katanya belum selesai dapat dijawab dengan catatan yang jelas." },
  { type: "p", text: "Agar bukti berguna, tautkan langsung ke transaksinya. Foto yang tersimpan di galeri ponsel pribadi karyawan tidak bisa dicari tiga bulan kemudian. Foto yang diambil lewat aplikasi dan melekat pada nomor pengiriman atau perintah kerja dapat ditemukan dalam hitungan detik oleh siapa pun yang berwenang." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1533292362155-d79af6b08b77",
    alt: "Seseorang menggunakan Google Maps di ponsel",
    caption: "Lokasi membantu merencanakan rute dan membuktikan kunjungan, asalkan penggunaannya dijelaskan dengan terbuka.",
  },
  { type: "h2", text: "Lokasi: manfaat dan batas kewajarannya" },
  { type: "p", text: "Data lokasi berguna untuk banyak hal: menyusun urutan kunjungan yang hemat perjalanan, memberi perkiraan waktu tiba kepada pelanggan, mencatat bukti kehadiran di lokasi, dan menugaskan pekerjaan mendadak kepada petugas terdekat. Namun data lokasi juga yang paling mudah menimbulkan rasa diawasi." },
  { type: "p", text: "Bedakan pencatatan lokasi pada saat kejadian dari pelacakan terus-menerus. Mencatat titik saat petugas memulai dan menyelesaikan kunjungan biasanya sudah memenuhi kebutuhan bisnis. Pelacakan sepanjang hari memerlukan alasan yang lebih kuat, misalnya untuk armada pengiriman, dan sebaiknya hanya aktif selama jam kerja." },
  { type: "p", text: "Jelaskan kepada tim data apa yang dikumpulkan, kapan, siapa yang melihat, dan untuk tujuan apa. Tuangkan dalam kebijakan tertulis dan patuhi ketentuan ketenagakerjaan serta pelindungan data pribadi yang berlaku. Keterbukaan ini bukan sekadar kewajiban; aplikasi yang dianggap alat mata-mata akan dilawan dengan berbagai cara kreatif." },
  { type: "h2", text: "Hubungan dengan ERP dan CRM" },
  { type: "p", text: "Aplikasi lapangan yang berdiri sendiri hanya memindahkan pekerjaan mengetik ulang dari kertas ke layar lain. Manfaat sebenarnya muncul ketika aplikasi terhubung dengan sistem inti. Pesanan yang dibuat penjual langsung menjadi pesanan penjualan di ERP, memotong stok, dan muncul di antrean gudang tanpa campur tangan admin." },
  { type: "p", text: "Dari arah sebaliknya, aplikasi menarik data yang membuat orang lapangan lebih siap: harga khusus per pelanggan, batas kredit, tagihan yang belum dibayar, stok tersedia, dan riwayat perbaikan suatu mesin. Penjual yang tahu pelanggannya masih memiliki tagihan tertunggak akan berbicara dengan cara yang berbeda." },
  { type: "p", text: "Sambungan ini memerlukan antarmuka data yang rapi di sisi sistem inti dan data induk yang bersih. Kode barang dan kode pelanggan yang sama harus dipakai di semua tempat. Sebelum membangun aplikasi, periksa apakah sistem Anda saat ini dapat menyediakan data yang diperlukan; bila belum, pekerjaan itu perlu masuk ke dalam rencana." },
  { type: "h2", text: "Sisi kantor: penjadwalan dan pemantauan" },
  { type: "p", text: "Aplikasi lapangan selalu memiliki pasangan di kantor: layar untuk menyusun jadwal, menugaskan pekerjaan, dan memantau kemajuan. Penyelia perlu melihat dengan cepat pekerjaan mana yang belum ditugaskan, mana yang terlambat, dan siapa yang masih punya waktu. Tanpa sisi kantor yang baik, aplikasi lapangan hanya menjadi alat pencatat." },
  { type: "p", text: "Rancang pemantauan berdasarkan pengecualian. Penyelia tidak perlu mengawasi setiap gerakan; ia perlu diberi tahu ketika ada yang menyimpang, seperti kunjungan yang terlewat, pekerjaan yang jauh melampaui perkiraan waktu, atau pelanggan yang menolak menerima barang. Dengan begitu perhatian diarahkan ke tempat yang memerlukannya." },
  { type: "p", text: "Pelanggan juga dapat diberi sedikit jendela ke dalam proses ini: pemberitahuan bahwa teknisi sedang dalam perjalanan, perkiraan waktu tiba, dan salinan berita acara setelah pekerjaan selesai. Hal sederhana seperti ini mengurangi telepon bertanya dan memberi kesan perusahaan yang tertata." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0",
    alt: "Layar laptop menampilkan grafik data operasional bisnis",
    caption: "Data dari lapangan baru bernilai ketika dirangkum menjadi gambaran yang bisa dipakai untuk memutuskan.",
  },
  { type: "h2", text: "Keamanan perangkat dan data" },
  { type: "p", text: "Ponsel lapangan membawa data pelanggan, harga, dan kadang uang hasil penagihan. Ponsel juga mudah hilang, jatuh, atau dicuri. Rancangan keamanan harus berangkat dari anggapan bahwa suatu hari sebuah perangkat akan jatuh ke tangan orang lain." },
  { type: "ul", items: [
    "Wajibkan kunci layar pada perangkat yang memasang aplikasi",
    "Batasi data yang tersimpan di perangkat hanya pada yang diperlukan untuk pekerjaan orang itu",
    "Sediakan cara mencabut akses dan menghapus data aplikasi dari jarak jauh",
    "Atur hak akses per peran sehingga penjual hanya melihat pelanggan di wilayahnya",
    "Catat tindakan penting seperti perubahan harga, pemberian diskon, dan penerimaan uang",
    "Cabut akses segera ketika karyawan keluar atau berganti peran",
  ] },
  { type: "p", text: "Putuskan pula apakah perangkat disediakan perusahaan atau milik pribadi karyawan. Perangkat perusahaan lebih mudah dikendalikan tetapi menambah biaya. Perangkat pribadi lebih murah tetapi memerlukan batas yang jelas antara data kerja dan data pribadi, serta kesepakatan tentang apa yang boleh dilakukan perusahaan pada perangkat itu." },
  { type: "h2", text: "Agar aplikasi benar-benar dipakai" },
  { type: "p", text: "Banyak aplikasi lapangan gagal bukan karena teknologinya, melainkan karena tidak dipakai. Orang lapangan menilai dengan cepat apakah sebuah alat membantu atau merepotkan. Jika aplikasi menambah pekerjaan tanpa memberi manfaat bagi mereka sendiri, mereka akan mengisinya seadanya di akhir hari atau mencari cara menghindarinya." },
  { type: "p", text: "Libatkan beberapa orang lapangan sejak tahap rancangan. Mereka tahu urutan kerja yang sebenarnya dan hambatan yang tidak terlihat dari kantor. Pastikan aplikasi memberi sesuatu kepada penggunanya: informasi yang memudahkan penjualan, perhitungan insentif yang transparan, atau berkurangnya laporan yang harus ditulis malam hari." },
  { type: "p", text: "Jalankan uji coba dengan kelompok kecil di keadaan nyata, perbaiki berdasarkan masukan mereka, lalu perluas. Hentikan cara lama pada tanggal yang jelas setelah aplikasi stabil. Selama laporan lewat obrolan masih diterima, sebagian orang akan terus memakainya dan data Anda tetap terbelah dua." },
  { type: "h2", text: "Aplikasi khusus atau produk jadi" },
  { type: "p", text: "Ada produk jadi untuk kebutuhan lapangan yang umum, seperti otomasi tenaga penjual dan manajemen servis. Produk seperti ini cepat dipasang dan cocok bila alur kerja Anda mendekati alur standar. Periksa kemampuannya bekerja luring, kemudahan menghubungkannya dengan sistem Anda, dan biaya per pengguna ketika tim bertambah." },
  { type: "p", text: "Aplikasi yang dibangun khusus menjadi masuk akal ketika alur kerja Anda adalah keunggulan bisnis, ketika hubungan dengan ERP harus sangat erat, atau ketika produk jadi memaksa tim mengikuti cara kerja yang tidak cocok. Biayanya lebih besar di awal, tetapi Anda memiliki alat yang mengikuti proses Anda." },
  { type: "p", text: "Apa pun pilihannya, mulailah dari proses, bukan dari fitur. Gambarkan sehari kerja seorang penjual atau teknisi dari pagi sampai sore, tandai titik yang lambat dan rawan salah, lalu nilai setiap pilihan berdasarkan seberapa baik ia memperbaiki titik-titik itu." },
  { type: "h2", text: "Ukuran yang layak dipantau" },
  { type: "ul", items: [
    "Jumlah kunjungan atau pekerjaan yang selesai per orang per hari",
    "Proporsi kunjungan terjadwal yang benar-benar terlaksana",
    "Waktu dari pekerjaan selesai sampai tagihan dibuat",
    "Proporsi pekerjaan servis yang selesai pada kunjungan pertama",
    "Jumlah pesanan yang harus dikoreksi karena salah harga atau stok kosong",
    "Proporsi anggota tim yang memakai aplikasi setiap hari kerja",
  ] },
  { type: "p", text: "Gunakan angka ini untuk memperbaiki proses, bukan untuk menghukum perorangan. Kunjungan yang sering tidak terlaksana bisa disebabkan rute yang tidak masuk akal. Pekerjaan yang jarang selesai pada kunjungan pertama bisa disebabkan suku cadang yang tidak tersedia. Ukuran yang dipakai dengan adil membuat tim mau mencatat dengan jujur." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Merancang aplikasi dari kantor tanpa melibatkan orang lapangan",
    "Mengandalkan sinyal yang selalu ada",
    "Mewajibkan terlalu banyak isian pada setiap kunjungan",
    "Melacak lokasi terus-menerus tanpa penjelasan dan tanpa kebijakan",
    "Membiarkan aplikasi berdiri sendiri tanpa hubungan dengan ERP atau CRM",
    "Tetap menerima laporan lewat obrolan setelah aplikasi diluncurkan",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Ikuti satu orang lapangan selama sehari dan catat setiap hal yang ia tulis, tanyakan, dan tunggu",
    "Pilih satu alur yang paling sering dan paling lambat sampai ke kantor sebagai sasaran pertama",
    "Daftar data dari sistem kantor yang seharusnya tersedia di tangan orang lapangan",
    "Periksa apakah ERP atau CRM Anda dapat menyediakan dan menerima data tersebut",
    "Tulis rancangan kebijakan penggunaan data lokasi dan bahas bersama tim",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Aplikasi mobile untuk tim lapangan bernilai ketika menutup jarak antara tempat pekerjaan dilakukan dan tempat data disimpan. Orang lapangan mendapat informasi yang membuat mereka lebih siap, kantor mendapat kejadian pada saat terjadi, dan pelanggan mendapat layanan yang lebih pasti. Tagihan keluar lebih cepat, kesalahan berkurang, dan laporan tidak lagi ditulis ulang." },
  { type: "p", text: "Kuncinya adalah merancang dari sudut pandang orang yang memegang ponsel itu: sederhana, tahan terhadap sinyal buruk, dan terasa membantu. Bila mereka merasakan manfaatnya, data yang baik akan mengikuti dengan sendirinya." },
  {
    type: "cta",
    title: "Tim lapangan Anda masih melapor lewat kertas dan grup obrolan?",
    text: "Tim AG·SORA membangun aplikasi mobile untuk penjual, teknisi, dan pengantar yang bekerja tanpa sinyal, mencatat bukti di tempat, dan terhubung langsung dengan ERP serta CRM Anda. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/mobile",
    label: "Konsultasi gratis",
  },
];
