import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Setiap beberapa tahun, muncul teknologi baru yang dijanjikan akan mengubah cara orang berbelanja. Realitas tertambah atau AR, yang menempelkan objek digital ke pandangan dunia nyata lewat kamera ponsel, dan realitas virtual atau VR, yang membenamkan pengguna dalam dunia buatan lewat headset, adalah dua di antaranya. Demonstrasi yang memukau mudah ditemukan: mencoba kacamata lewat kamera, melihat sofa di ruang tamu sebelum membeli, atau berjalan di toko virtual." },
  { type: "p", text: "Bagi pemilik bisnis, pertanyaan pentingnya bukan \"apakah teknologi ini keren?\", melainkan \"apakah ini menyelesaikan masalah nyata pelanggan saya dengan biaya yang masuk akal?\" Jawabannya berbeda untuk tiap bisnis. Untuk sebagian, AR memangkas keraguan membeli dan mengurangi retur. Untuk yang lain, ia hanya hiasan mahal yang dipakai sekali lalu dilupakan." },
  { type: "p", text: "Artikel ini membahas AR dan VR dengan kepala dingin dari sudut pandang bisnis. Kami menjelaskan apa bedanya, kasus penggunaan yang masuk akal untuk ritel dan layanan, hambatan teknis dan biaya yang sering diabaikan, serta cara menguji dengan risiko kecil. Kami sengaja tidak mengutip angka kenaikan penjualan atau tingkat adopsi karena angka semacam itu sering bergantung pada konteks, dan kami tidak mau menjanjikan hasil yang tidak bisa dipastikan." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "AR menambahkan elemen digital ke dunia nyata lewat layar ponsel; VR menggantikan dunia nyata dengan lingkungan buatan lewat headset",
      "Untuk kebanyakan bisnis, AR di ponsel lebih realistis daripada VR karena tidak memerlukan perangkat tambahan bagi pelanggan",
      "Kasus yang masuk akal: melihat ukuran dan penempatan produk, mencoba tampilan, dan membantu pelanggan memahami produk yang rumit",
      "Biaya yang sering terlewat: pembuatan model tiga dimensi, pemeliharaan, kompatibilitas perangkat, dan pemasaran agar fitur benar-benar dipakai",
      "Mulailah dari masalah pelanggan, uji dengan sedikit produk, ukur dampaknya, lalu putuskan apakah diperluas",
    ],
  },
  { type: "h2", text: "Membedakan AR, VR, dan istilah yang sering tercampur" },
  { type: "p", text: "Istilah-istilah dalam bidang ini sering dipakai bergantian secara keliru, padahal pengalaman penggunanya sangat berbeda. Memahami perbedaannya adalah langkah pertama menilai mana yang relevan bagi bisnis Anda." },
  { type: "p", text: "Realitas tertambah, atau AR, menampilkan objek digital di atas tampilan dunia nyata. Pengguna melihat ruangannya sendiri lewat kamera ponsel, lalu objek seperti sebuah kursi tampak berdiri di lantai. Karena hanya butuh ponsel yang sudah dimiliki hampir semua orang, AR relatif mudah dijangkau." },
  { type: "p", text: "Realitas virtual, atau VR, menggantikan pandangan dunia nyata dengan lingkungan yang sepenuhnya buatan. Pengguna biasanya memakai headset dan terputus dari ruangan sekitarnya. VR memberi pengalaman membenamkan yang kuat, tetapi membutuhkan perangkat khusus yang tidak dimiliki kebanyakan pelanggan." },
  { type: "p", text: "Ada juga istilah realitas campuran yang menggabungkan keduanya, serta istilah umum seperti pengalaman imersif. Untuk keperluan keputusan bisnis, cukup bedakan dua hal: apakah pelanggan bisa memakainya dengan perangkat yang sudah ia miliki, atau butuh perangkat tambahan. Pertanyaan sederhana ini sering langsung mempersempit pilihan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1535223289827-42f1e9919769",
    alt: "Seseorang mengenakan headset realitas virtual dengan ekspresi terkejut",
    caption: "Pengalaman virtual bisa memukau, tetapi memukau bukan berarti menghasilkan penjualan; ujilah dengan pelanggan nyata.",
  },
  { type: "h2", text: "Mengapa AR di ponsel biasanya lebih realistis bagi bisnis" },
  { type: "p", text: "Untuk sebagian besar bisnis kecil dan menengah, AR berbasis ponsel adalah titik awal yang jauh lebih masuk akal daripada VR. Alasannya praktis. Pelanggan tidak perlu membeli apa pun. Pengalaman bisa dibuka lewat aplikasi atau, pada banyak perangkat, lewat browser tanpa memasang aplikasi tambahan. Dan konteks penggunaannya alami: orang sudah memegang ponsel saat berbelanja." },
  { type: "p", text: "VR, sebaliknya, menghadapi hambatan jangkauan. Hanya sebagian kecil pelanggan memiliki headset, sehingga pengalaman VR di rumah menjangkau segmen sempit. VR di toko atau pameran mengatasi hal itu dengan menyediakan perangkat, tetapi menambah biaya perangkat, ruang, dan petugas pendamping. VR memang cocok untuk kasus tertentu seperti pelatihan, simulasi, atau pengalaman acara, namun jarang menjadi saluran penjualan massal." },
  { type: "p", text: "Ini bukan berarti VR tidak berguna. Untuk pelatihan karyawan pada situasi berbahaya atau mahal untuk ditiru, atau untuk memperlihatkan properti yang belum dibangun kepada calon pembeli yang serius, VR bisa memberi nilai nyata. Pertanyaannya tetap sama: apakah ia menyelesaikan masalah spesifik dengan cara yang lebih baik daripada alternatif yang lebih sederhana, seperti foto, video, atau denah?" },
  { type: "h2", text: "Kasus penggunaan yang masuk akal" },
  { type: "p", text: "Tidak semua produk cocok dengan AR atau VR. Teknologi ini paling berguna ketika pelanggan menghadapi keraguan yang bisa dijawab dengan visualisasi. Beberapa kasus di bawah ini tergolong masuk akal." },
  {
    type: "ul",
    items: [
      "Melihat ukuran dan penempatan: furnitur, peralatan rumah, atau dekorasi yang perlu dibayangkan di ruang sendiri",
      "Mencoba tampilan: kacamata, riasan, jam tangan, atau aksesori yang dicoba secara virtual sebelum dibeli",
      "Memahami produk yang rumit: mesin, peralatan, atau produk teknis yang penjelasannya lebih mudah lewat model yang bisa diputar dan dibongkar",
      "Panduan pemasangan atau perawatan: petunjuk visual yang menempel pada produk sungguhan",
      "Pameran dan penjualan proyek besar: menampilkan produk atau properti yang terlalu besar atau belum ada secara fisik",
      "Pelatihan: simulasi prosedur bagi karyawan baru tanpa risiko dan biaya bahan nyata",
    ],
  },
  { type: "p", text: "Untuk produk yang keputusan pembeliannya sederhana, misalnya kebutuhan sehari-hari yang harganya murah, AR hampir tidak menambah nilai. Pelanggan tidak butuh melihat sebungkus mi di ruang tamunya. Teknologi seharusnya menjawab pertanyaan nyata, bukan mencari pertanyaan untuk dijawab." },
  { type: "h3", text: "Uji sederhana: apakah ini mengurangi keraguan" },
  { type: "p", text: "Ajukan satu pertanyaan sebelum berinvestasi: apa keraguan terbesar yang membuat pelanggan menunda atau membatalkan pembelian, dan apakah visualisasi tiga dimensi benar-benar menjawabnya? Jika keraguan terbesar adalah harga, ongkir, atau kepercayaan pada toko, AR tidak akan membantu. Jika keraguannya adalah \"apakah ini muat di ruangan saya?\" atau \"apakah ini cocok di wajah saya?\", AR berpotensi relevan. Tanyakan langsung kepada pelanggan atau periksa alasan retur Anda untuk menemukan jawabannya." },
  { type: "h2", text: "Biaya dan hambatan yang sering terlewat" },
  { type: "p", text: "Demonstrasi AR yang mulus menyembunyikan banyak pekerjaan di baliknya. Memahami biaya sebenarnya mencegah kejutan di tengah proyek." },
  { type: "p", text: "Pertama, model tiga dimensi. Setiap produk yang akan ditampilkan perlu dibuatkan model digital yang akurat dalam ukuran dan tampilan. Untuk katalog besar, ini pekerjaan signifikan, baik dibuat manual oleh desainer maupun dipindai dari produk fisik. Model yang tidak akurat justru merugikan: pelanggan yang membeli berdasarkan tampilan AR yang meleset akan kecewa dan mengembalikan barang." },
  { type: "p", text: "Kedua, kompatibilitas perangkat. Tidak semua ponsel mendukung fitur AR dengan sama baik. Perangkat lama atau murah bisa mengalami tampilan yang kasar, pelacakan yang meleset, atau tidak berfungsi sama sekali. Karena itu, uji pada beragam perangkat yang mewakili pelanggan Anda, bukan hanya ponsel terbaru tim pengembang." },
  { type: "p", text: "Ketiga, pemeliharaan. Teknologi dan sistem operasi berubah, dan fitur yang berjalan hari ini bisa bermasalah setelah pembaruan. Produk baru harus ditambahkan, produk lama diperbarui. Anggarkan biaya pemeliharaan berkelanjutan, bukan hanya biaya pembuatan awal." },
  { type: "p", text: "Keempat, pemasaran dan penemuan fitur. Fitur AR yang tersembunyi di sudut halaman tidak akan dipakai siapa pun. Anda perlu menempatkannya di tempat yang terlihat, menjelaskan manfaatnya dengan singkat, dan memastikan pelanggan mengerti cara memakainya. Banyak proyek AR gagal bukan karena teknologinya buruk, tetapi karena tidak ada yang tahu fiturnya ada." },
  {
    type: "callout",
    title: "Hitung total biaya kepemilikan",
    text: "Jangan hanya menghitung biaya pembuatan. Masukkan biaya model tiga dimensi per produk, pengujian perangkat, pemeliharaan, dan promosi. Bandingkan dengan manfaat yang realistis, seperti pengurangan retur atau keyakinan membeli, bukan dengan angka dari presentasi vendor.",
  },
  { type: "h2", text: "Alternatif yang lebih sederhana dan sering cukup" },
  { type: "p", text: "Sebelum membangun fitur AR, pertimbangkan apakah alternatif yang lebih sederhana menjawab keraguan yang sama. Foto yang diambil dari berbagai sudut, dengan benda pembanding agar skala terasa, sering sudah banyak membantu. Video singkat yang menunjukkan produk dipakai di ruangan nyata menjawab banyak pertanyaan. Gambar ukuran yang jelas dengan dimensi tertulis, serta panduan memilih ukuran, mengurangi kesalahan beli." },
  { type: "p", text: "Untuk produk yang bisa dilihat dari segala arah, tampilan putar tiga ratus enam puluh derajat atau penampil model tiga dimensi di halaman produk memberikan sebagian manfaat AR dengan biaya dan kompleksitas lebih rendah. Pelanggan bisa memutar dan memperbesar produk tanpa harus mengarahkan kamera ke ruangan mereka." },
  { type: "p", text: "Alternatif-alternatif ini juga lebih tahan lama. Ia tidak bergantung pada dukungan perangkat tertentu dan bisa dibuat dengan keahlian yang lebih mudah ditemukan. Jika ternyata pelanggan memberi respons baik pada visual yang lebih kaya, itu bisa menjadi sinyal bahwa investasi AR layak dipertimbangkan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1497366216548-37526070297c",
    alt: "Lorong kantor modern yang lengang dengan dinding kaca",
    caption: "Ruang fisik yang kosong bisa dibayangkan lewat AR, tetapi untuk banyak bisnis foto dan denah yang baik sudah menjawab pertanyaan yang sama.",
  },
  { type: "h2", text: "Peran AR dan VR dalam pengalaman toko fisik" },
  { type: "p", text: "Di toko fisik, AR dan VR bisa berperan sebagai pelengkap, bukan pengganti. Layar interaktif yang memperlihatkan variasi warna produk yang tidak semuanya dipajang, cermin pintar untuk mencoba riasan, atau katalog virtual untuk produk yang terlalu besar untuk disimpan semuanya di toko adalah contoh yang masuk akal. Teknologi ini memperluas apa yang bisa ditawarkan toko tanpa menambah stok fisik." },
  { type: "p", text: "Namun hati-hati dengan teknologi yang menjadi pusat perhatian melebihi layanan dasar. Toko yang punya cermin pintar mahal tetapi antrean kasirnya panjang telah salah menempatkan prioritas. Fondasi pelayanan, yaitu stok yang akurat, kasir yang cepat, dan staf yang membantu, tetap yang utama. Teknologi imersif baru bernilai jika fondasi itu sudah kuat." },
  { type: "p", text: "Perhatikan pula pengalaman pelanggan yang tidak nyaman dengan teknologi. Sebagian orang tidak ingin difoto atau diperlihatkan kameranya di ruang publik, sebagian pusing saat memakai headset, dan sebagian lain hanya merasa canggung. Selalu sediakan jalur biasa yang tidak memaksa pelanggan memakai teknologi." },
  { type: "h2", text: "Privasi dan keamanan data" },
  { type: "p", text: "Fitur AR yang memakai kamera menyentuh isu privasi. Jika aplikasi Anda mengakses kamera untuk melacak wajah atau ruangan, beri tahu pelanggan dengan jelas apa yang dilakukan dengan gambar tersebut. Sebaiknya pemrosesan dilakukan di perangkat pelanggan tanpa mengunggah gambar, dan jika ada yang disimpan, jelaskan tujuan serta lamanya. Minta izin kamera pada saat fitur akan dipakai, disertai penjelasan manfaatnya, bukan di detik pertama aplikasi dibuka." },
  { type: "p", text: "Data wajah atau tubuh yang dipakai untuk uji coba virtual dapat tergolong data pribadi yang sensitif. Patuhi ketentuan perlindungan data pribadi yang berlaku dan rujuklah ketentuan terbaru dari otoritas yang berwenang, jangan mengandalkan ringkasan yang mungkin sudah usang. Prinsip yang aman: kumpulkan seminimal mungkin, simpan sesingkat mungkin, dan beri pelanggan kendali." },
  { type: "h2", text: "Cara menguji dengan risiko kecil" },
  { type: "p", text: "Daripada langsung membangun fitur besar, uji gagasan dengan langkah kecil. Pilih satu atau beberapa produk yang paling mungkin terbantu, misalnya yang paling sering diretur karena soal ukuran atau penempatan. Buat versi sederhana untuk produk-produk itu saja, dan tempatkan di halaman produk yang jelas terlihat." },
  { type: "p", text: "Tentukan sejak awal bagaimana Anda akan mengukur keberhasilan. Pilih indikator yang masuk akal, misalnya berapa banyak pengunjung yang memakai fitur, apakah produk dengan fitur itu lebih sering dibeli dibanding yang tanpa fitur, dan apakah tingkat retur untuk produk itu menurun. Bandingkan dengan produk serupa tanpa fitur AR, dan beri waktu cukup agar polanya terlihat. Jangan menyimpulkan dari beberapa hari pertama saja." },
  { type: "p", text: "Kumpulkan juga umpan balik kualitatif. Tanyakan kepada pelanggan apakah fitur itu membantu, apa yang membingungkan, dan apa yang mereka harapkan. Dari sini Anda belajar apakah masalahnya ada pada teknologi, penempatan fitur, atau memang tidak dibutuhkan. Jika hasilnya meyakinkan, perluas bertahap; jika tidak, Anda berhenti dengan kerugian kecil dan pelajaran berharga." },
  { type: "h2", text: "Melihat tren teknologi dengan kepala dingin" },
  { type: "p", text: "AR dan VR hanyalah salah satu dari banyak teknologi yang datang dengan gelombang antusiasme. Pola yang sama berlaku untuk tren lain: ada janji besar, ada kasus penggunaan yang benar-benar bermanfaat, dan ada banyak eksperimen yang berakhir sebagai hiasan. Sikap yang sehat adalah penasaran tetapi disiplin. Pelajari perkembangannya, tetapi ukur setiap investasi dengan pertanyaan yang sama: masalah pelanggan apa yang dipecahkan, berapa biaya sebenarnya, dan bagaimana kita tahu itu berhasil?" },
  { type: "p", text: "Ingatlah bahwa bisnis Anda mungkin masih punya peluang yang jauh lebih sederhana dan lebih berdampak: website yang cepat, pembayaran yang mulus, stok yang akurat, dan layanan pelanggan yang responsif. Perbaikan dasar seperti ini sering memberi hasil lebih besar daripada teknologi baru yang memukau. Teknologi imersif paling baik dipandang sebagai lapisan tambahan di atas fondasi yang sudah kokoh." },
  { type: "h2", text: "Langkah praktis menilai AR atau VR untuk bisnis Anda" },
  {
    type: "ol",
    items: [
      "Identifikasi keraguan terbesar pelanggan sebelum membeli, dan periksa alasan retur Anda",
      "Tanyakan apakah visualisasi tiga dimensi benar-benar menjawab keraguan itu, atau ada alternatif sederhana yang cukup",
      "Utamakan AR berbasis ponsel dibanding VR kecuali ada kasus khusus seperti pelatihan atau pameran",
      "Hitung total biaya: model tiga dimensi, pengujian perangkat, pemeliharaan, dan promosi",
      "Uji dengan beberapa produk terpilih dan tentukan indikator keberhasilan sebelum mulai",
      "Perhatikan privasi, minta izin kamera pada saat yang tepat, dan siapkan jalur biasa bagi yang tidak ingin memakainya",
    ],
  },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "AR dan VR bukan sihir, dan bukan pula sekadar mainan. Seperti teknologi lainnya, nilainya ditentukan oleh seberapa tepat ia dipasangkan dengan masalah nyata. Untuk produk yang keputusan belinya bergantung pada bayangan ukuran, tampilan, atau pemahaman teknis, AR di ponsel bisa menjadi alat yang berguna. Untuk banyak produk lain, foto yang baik, video singkat, dan panduan yang jelas sudah cukup dan jauh lebih murah." },
  { type: "p", text: "Pendekatan yang aman adalah memulai dari pelanggan, bukan dari teknologi. Tanyakan apa yang menghambat mereka, uji solusi dengan skala kecil, dan perluas hanya jika datanya mendukung. Dengan cara itu, Anda mendapat manfaat dari tren teknologi tanpa terseret biayanya yang tersembunyi." },
  {
    type: "cta",
    title: "Ingin menjajaki aplikasi atau pengalaman digital baru untuk bisnis Anda?",
    text: "Tim AG·SORA membantu menilai gagasan teknologi baru, membangun prototipe sederhana, dan memastikan investasi Anda menjawab kebutuhan pelanggan yang nyata. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/mobile",
    label: "Konsultasi gratis",
  },
];
