import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Istilah headless commerce, composable, dan jamstack makin sering muncul dalam penawaran agensi dan vendor. Bagi pemilik bisnis yang hanya ingin toko online atau website perusahaan yang berjalan baik, istilah-istilah itu terdengar seperti pekerjaan rumah tambahan. Pertanyaan yang wajar muncul: apakah kami perlu itu, atau hanya sedang dijual sesuatu yang lebih rumit dari kebutuhan kami?" },
  { type: "p", text: "Jawabannya bergantung pada situasi. Pendekatan headless memberi kebebasan besar dalam tampilan dan kecepatan, tetapi juga menambah bagian yang harus dibangun, dihubungkan, dan dirawat. Memilihnya tanpa alasan yang jelas sama berisikonya dengan menolaknya ketika bisnis Anda sebenarnya sudah menabrak batas platform yang ada." },
  { type: "p", text: "Artikel ini menjelaskan apa yang dimaksud dengan arsitektur headless dengan bahasa awam, kapan ia masuk akal, kapan sebaiknya dihindari, dan bagaimana mengambil keputusan tanpa terbawa tren. Kami tidak mengklaim angka kecepatan atau penghematan tertentu, karena hasilnya sangat bergantung pada bagaimana sistem dibangun dan dirawat." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Headless berarti tampilan (depan) dipisahkan dari sistem pengelola data dan transaksi (belakang)",
      "Pemisahan ini memberi fleksibilitas, tetapi menambah komponen yang harus dirawat",
      "Bagi banyak bisnis, platform terpadu yang dikonfigurasi dengan baik sudah lebih dari cukup",
      "Headless layak dipertimbangkan bila Anda perlu banyak kanal, tampilan sangat khusus, atau integrasi yang rumit",
      "Mulailah dari masalah bisnis yang nyata, bukan dari nama teknologinya",
    ],
  },
  { type: "h2", text: "Apa itu arsitektur headless, dengan bahasa sederhana" },
  { type: "p", text: "Bayangkan restoran. Di dapur ada koki, bahan, dan resep; di ruang makan ada meja, menu, dan pelayan. Pada platform toko online tradisional, dapur dan ruang makan berada dalam satu paket yang dirancang bersama: Anda memilih tema, mengisi produk, dan semuanya berjalan. Tampilannya terikat pada sistem di belakangnya." },
  { type: "p", text: "Pada arsitektur headless, ruang makan dibangun terpisah dari dapur. Sistem belakang menyimpan produk, harga, stok, dan pesanan, lalu menyediakan data itu lewat antarmuka pemrograman atau API. Tampilan depan, yaitu website, aplikasi mobile, kios, atau layar lain, mengambil data tersebut lewat API dan menampilkannya dengan bebas." },
  { type: "p", text: "Kata head di sini merujuk pada tampilan depan. Sistem tanpa kepala berarti sistem belakang tidak lagi menentukan tampilan. Anda boleh memasang satu kepala, dua kepala, atau lebih, dan menggantinya tanpa membongkar dapur. Itulah inti idenya, dan juga sumber kerumitannya." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6",
    alt: "Baris kode program ditampilkan besar di layar monitor",
    caption: "Pada pendekatan headless, tampilan depan dibangun sebagai aplikasi sendiri yang mengambil data lewat API.",
  },
  { type: "h2", text: "Apa yang sebenarnya Anda dapatkan" },
  { type: "p", text: "Keuntungan pertama adalah kebebasan tampilan. Tema platform jadi bisa disesuaikan sampai batas tertentu, tetapi ada hal yang sulit diubah tanpa merusak struktur. Dengan tampilan depan yang dibangun sendiri, desainer dan pengembang dapat menyusun pengalaman yang sepenuhnya mengikuti kebutuhan merek dan pelanggan Anda." },
  { type: "p", text: "Keuntungan kedua adalah satu sumber data untuk banyak kanal. Produk, harga, dan stok disimpan sekali, lalu dipakai oleh website, aplikasi mobile, layar di toko, dan kanal lain. Perubahan harga tidak perlu diketik di beberapa tempat, dan risiko angka yang berbeda antarkanal berkurang." },
  { type: "p", text: "Keuntungan ketiga adalah kebebasan memilih dan mengganti komponen. Anda bisa memakai satu sistem untuk katalog, layanan lain untuk pencarian, dan layanan berbeda untuk konten. Bila satu komponen tidak lagi cocok, Anda menggantinya tanpa membangun ulang semuanya. Kebebasan ini nyata, tetapi hanya berguna bila tim Anda mampu mengelola banyak komponen sekaligus." },
  { type: "p", text: "Keuntungan keempat, yang sering dibicarakan, adalah performa. Tampilan depan yang dibangun dengan teknik modern dapat disajikan dengan sangat cepat. Namun kecepatan bukan hadiah otomatis dari arsitektur ini; website headless yang dibangun sembarangan tetap bisa lambat, dan platform terpadu yang dirawat baik tetap bisa cukup cepat." },
  { type: "h2", text: "Harga yang harus dibayar" },
  { type: "p", text: "Dalam platform terpadu, banyak hal sudah tersedia: keranjang, checkout, akun pelanggan, pratinjau, dan sering kali ekosistem plugin. Pada pendekatan headless, bagian-bagian ini harus dibangun atau dirangkai. Fitur yang di platform terpadu cukup dicentang, di sini bisa menjadi pekerjaan pengembangan berminggu-minggu." },
  { type: "p", text: "Ada juga biaya koordinasi. Setiap komponen punya pembaruan, batas pemakaian, dan cara gagal sendiri. Ketika ada masalah, pertanyaan pertama adalah di bagian mana masalah itu terjadi. Tim perlu memahami seluruh rangkaian, bukan hanya satu produk, dan perlu pemantauan yang menyeluruh." },
  { type: "p", text: "Selain itu ada ketergantungan pada orang. Platform terpadu dapat dikelola oleh staf non-teknis dengan bantuan sesekali. Arsitektur headless hampir selalu memerlukan pengembang yang terlibat berkelanjutan. Bila pengembang yang membangunnya pergi dan tidak ada dokumentasi, bisnis Anda berada dalam posisi sulit." },
  { type: "callout", title: "Kebebasan bukan tujuan", text: "Kebebasan memilih tampilan dan komponen hanya bernilai bila Anda memang punya kebutuhan yang tidak bisa dipenuhi platform yang ada. Tanpa kebutuhan itu, kebebasan hanya berarti lebih banyak keputusan dan lebih banyak yang harus dirawat." },
  { type: "h2", text: "Kapan headless masuk akal" },
  { type: "p", text: "Pendekatan ini layak dipertimbangkan ketika Anda perlu melayani banyak kanal dari satu sumber data, misalnya website, aplikasi mobile, layar di toko, dan portal mitra yang semuanya menampilkan katalog yang sama. Mengelola data di beberapa platform terpisah akan cepat menjadi beban." },
  { type: "p", text: "Ia juga masuk akal ketika pengalaman pengguna adalah pembeda utama bisnis Anda. Konfigurator produk yang rumit, alur pemesanan khas industri, atau halaman yang sangat interaktif sering menabrak batas tema platform. Di sini kebebasan tampilan benar-benar menghasilkan nilai." },
  { type: "p", text: "Alasan ketiga adalah integrasi yang kompleks. Bila website harus berbicara dengan ERP, sistem gudang, dan layanan lain secara mendalam, memiliki lapisan sendiri yang menjadi penghubung dapat lebih bersih daripada menumpuk plugin. Alasan keempat adalah kebutuhan skala dan keandalan khusus yang tidak bisa dipenuhi paket platform biasa." },
  { type: "h2", text: "Kapan sebaiknya tidak" },
  { type: "p", text: "Bila Anda baru memulai dan produknya puluhan sampai ratusan, platform terpadu hampir pasti pilihan yang lebih bijak. Waktu dan dana lebih baik dipakai untuk memvalidasi bisnis, memperbaiki foto produk, dan memasarkan, bukan merakit arsitektur yang kebutuhannya belum terbukti." },
  { type: "p", text: "Bila tim Anda kecil dan tidak punya pengembang tetap, headless menjadi risiko. Setiap perubahan kecil memerlukan bantuan teknis dan setiap gangguan menunggu orang yang paham. Platform terpadu memberi kemandirian yang lebih besar kepada staf non-teknis." },
  { type: "p", text: "Bila alasan utamanya hanya karena sedang tren atau karena pesaing melakukannya, tahan dulu. Tanyakan apa masalah konkret yang tidak bisa diselesaikan dengan konfigurasi yang ada. Banyak masalah yang dikira keterbatasan platform sebenarnya adalah soal konten, foto, atau struktur halaman yang belum dirapikan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1547658719-da2b51169166",
    alt: "Meja kerja dengan monitor, tablet, dan ponsel yang menampilkan rancangan halaman web",
    caption: "Satu sumber data dapat melayani berbagai tampilan, tetapi setiap tampilan tambahan berarti pekerjaan tambahan.",
  },
  { type: "h2", text: "Jalan tengah: konfigurasi dan peningkatan bertahap" },
  { type: "p", text: "Pilihannya tidak hanya platform terpadu atau headless penuh. Banyak bisnis cocok dengan jalan tengah: tetap memakai platform terpadu, tetapi mengganti bagian tertentu yang paling bermasalah. Misalnya, memakai layanan pencarian khusus, membangun halaman produk tertentu dengan tampilan khusus, atau menambahkan aplikasi mobile yang membaca data dari platform yang sama." },
  { type: "p", text: "Pendekatan bertahap ini mengurangi risiko. Anda mendapat manfaat di bagian yang paling terasa, sambil mempertahankan fondasi yang sudah berjalan. Bila kemudian terbukti perlu, Anda dapat memindahkan lebih banyak bagian secara bertahap, bukan membongkar semuanya sekaligus." },
  { type: "p", text: "Di sisi lain, jalan tengah menuntut disiplin terhadap batas. Tetapkan dengan jelas mana yang dikelola di platform dan mana yang di lapisan khusus, agar tidak ada data ganda yang saling bertentangan. Dokumentasikan alirannya sejak awal." },
  { type: "h2", text: "Hal teknis yang perlu dipastikan sejak awal" },
  { type: "p", text: "Pertama, SEO. Tampilan depan yang dibangun sendiri harus tetap menyajikan konten yang bisa dibaca mesin pencari, dengan judul, deskripsi, data terstruktur, dan peta situs yang benar. Pastikan pengembang memahami hal ini sejak rancangan, karena memperbaikinya belakangan jauh lebih mahal." },
  { type: "p", text: "Kedua, pratinjau dan alur kerja konten. Tim pemasaran perlu dapat melihat hasil sebelum terbit dan menerbitkan tanpa meminta pengembang. Tanpa itu, kebebasan teknis justru memperlambat pekerjaan sehari-hari. Ketiga, keamanan: setiap API, kunci akses, dan layanan pihak ketiga adalah permukaan yang perlu dijaga." },
  { type: "p", text: "Keempat, pemantauan dan penanganan gangguan. Karena ada banyak bagian, tentukan siapa yang dipanggil ketika checkout gagal dan bagaimana mengetahui bagian mana yang bermasalah. Kelima, kepemilikan: pastikan akun, kode, dan domain atas nama bisnis Anda, bukan vendor." },
  { type: "ul", items: [
    "Konten tetap dapat dirayapi mesin pencari dan memuat data terstruktur yang benar",
    "Ada pratinjau dan alur terbit yang bisa dipakai staf non-teknis",
    "Pemantauan menyeluruh dengan pemberitahuan untuk alur penting seperti checkout",
    "Dokumentasi arsitektur, akun layanan, dan cara pemulihan tersimpan di tempat yang aman",
    "Kode, akun, dan domain dimiliki bisnis, bukan hanya vendor",
  ] },
  { type: "h2", text: "Dua gambaran situasi hipotetis" },
  { type: "p", text: "Bayangkan sebuah toko perlengkapan rumah dengan ratusan produk, satu website, dan tim tiga orang. Masalah mereka adalah foto produk yang kurang konsisten dan deskripsi yang tipis. Memindahkan toko ke arsitektur headless tidak menyentuh akar masalah itu. Investasi yang lebih tepat adalah merapikan katalog, memperbaiki foto, dan menyempurnakan halaman produk di platform yang ada." },
  { type: "p", text: "Sekarang bayangkan produsen yang menjual mebel dengan banyak pilihan bahan, ukuran, dan warna, dilayani lewat website, aplikasi, dan tim sales yang memakai tablet di lapangan. Mereka memerlukan konfigurator khusus dan satu sumber data harga yang dipakai ketiga kanal. Di sini pemisahan depan dan belakang memberi nilai nyata, dan biaya tambahan dapat dibenarkan." },
  { type: "p", text: "Kedua gambaran ini sengaja dibuat berlawanan agar terlihat bahwa jawabannya bukan soal besar atau kecilnya bisnis, melainkan soal bentuk masalahnya. Bisnis kecil dengan kebutuhan khusus bisa saja diuntungkan, dan bisnis besar dengan kebutuhan biasa bisa saja cukup dengan platform terpadu." },
  { type: "h2", text: "Dampaknya pada tim dan cara kerja sehari-hari" },
  { type: "p", text: "Perubahan arsitektur selalu berdampak pada orang. Pada platform terpadu, staf toko biasanya mengubah harga, membuat halaman promo, dan menata banner sendiri lewat satu panel. Pada arsitektur headless, sebagian pekerjaan itu pindah ke sistem konten atau ke kode, sehingga ada pembagian peran yang baru antara pemasaran, operasional, dan pengembang." },
  { type: "p", text: "Rancang pembagian itu sejak awal. Tentukan hal apa yang boleh diubah staf sendiri, hal apa yang memerlukan pengembang, dan berapa lama permintaan perubahan dilayani. Tanpa kesepakatan ini, kampanye yang seharusnya naik tayang hari ini bisa tertahan seminggu karena menunggu jadwal pengembang." },
  { type: "p", text: "Pertimbangkan pula kebutuhan pelatihan. Staf yang terbiasa dengan satu panel kini mungkin harus memakai dua atau tiga alat berbeda. Sediakan panduan singkat dan contoh nyata, dan jangan menganggap peralihan alat sebagai hal sepele; di sinilah banyak proyek kehilangan semangat tim pemakainya." },
  { type: "h2", text: "Biaya yang perlu dihitung dengan jujur" },
  { type: "p", text: "Saat membandingkan pilihan, jangan hanya melihat biaya pembangunan. Hitung juga biaya langganan setiap komponen, biaya hosting, biaya pengembang untuk perubahan rutin, biaya pemantauan, dan biaya ketika ada gangguan. Pada platform terpadu, sebagian biaya ini sudah termasuk dalam satu tagihan; pada rangkaian komponen, ia tersebar di beberapa tagihan." },
  { type: "p", text: "Hitung pula biaya kesempatan. Waktu tim yang dipakai untuk merakit dan merawat arsitektur adalah waktu yang tidak dipakai untuk menambah produk, memperbaiki layanan, atau memasarkan. Ini bukan alasan untuk selalu menolak pendekatan yang lebih rumit, tetapi alasan untuk memastikan manfaatnya sepadan." },
  { type: "p", text: "Sebuah latihan sederhana membantu: tuliskan biaya total kepemilikan untuk tiga tahun pada dua atau tiga pilihan, lalu tuliskan juga apa yang Anda harapkan didapat dari tiap pilihan dalam bentuk kemampuan bisnis, bukan istilah teknis. Bila selisih biayanya besar tetapi selisih kemampuannya kecil, jawabannya biasanya sudah terlihat." },
  { type: "h2", text: "Cara mengambil keputusan" },
  { type: "p", text: "Mulailah dengan menuliskan masalah, bukan solusi. Contoh masalah yang baik: halaman produk kami tidak bisa menampilkan konfigurasi yang dibutuhkan pelanggan, atau stok di tiga kanal sering tidak sinkron. Contoh yang kurang baik: kami ingin memakai teknologi terbaru." },
  { type: "p", text: "Lalu periksa apakah masalah itu bisa diselesaikan dengan konfigurasi, plugin yang matang, atau peningkatan bertahap. Bila jawabannya ya, itu hampir selalu jalur yang lebih murah dan lebih cepat. Bila tidak, barulah bandingkan beberapa pilihan arsitektur dengan menghitung biaya pembangunan sekaligus biaya perawatan selama beberapa tahun." },
  { type: "p", text: "Terakhir, minta calon vendor menjelaskan siapa yang akan merawat sistem setelah diluncurkan dan berapa biayanya. Vendor yang jujur akan membahas kekurangan pendekatan yang mereka tawarkan, bukan hanya keunggulannya. Itu salah satu tanda yang paling bisa diandalkan dalam memilih mitra." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Memilih headless karena tren, bukan karena kebutuhan yang terdefinisi",
    "Mengabaikan biaya perawatan jangka panjang dan ketergantungan pada pengembang tertentu",
    "Membangun ulang fitur dasar yang sebenarnya sudah tersedia dan matang di platform",
    "Melupakan SEO, pratinjau konten, dan alur kerja tim pemasaran",
    "Tidak mendokumentasikan arsitektur sehingga sulit diteruskan orang lain",
    "Menyimpan data yang sama di dua tempat tanpa aturan sumber kebenaran",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Tuliskan tiga masalah terbesar pada website atau toko online Anda saat ini",
    "Untuk setiap masalah, periksa apakah bisa diselesaikan dengan konfigurasi atau peningkatan bertahap",
    "Hitung berapa kanal yang benar-benar perlu dilayani dalam dua tahun ke depan",
    "Tanyakan kepada vendor siapa yang merawat sistem dan berapa biayanya setelah peluncuran",
    "Bila perlu, rancang uji coba kecil pada satu bagian sebelum memutuskan perubahan besar",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Arsitektur headless adalah alat yang kuat untuk bisnis yang memang membutuhkannya: banyak kanal, pengalaman yang sangat khusus, atau integrasi yang mendalam. Namun ia bukan tanda kemajuan dengan sendirinya. Banyak bisnis berjalan sangat baik dengan platform terpadu yang dikonfigurasi dengan cermat." },
  { type: "p", text: "Keputusan yang baik lahir dari masalah yang jelas, perhitungan biaya jangka panjang, dan kesiapan merawat apa yang dibangun. Bila ketiganya ada, pilihan arsitektur biasanya menjadi jelas dengan sendirinya." },
  {
    type: "cta",
    title: "Bingung memilih arsitektur website untuk bisnis Anda?",
    text: "Tim AG·SORA membantu menilai kebutuhan Anda secara jujur, dari platform terpadu yang dikonfigurasi baik hingga arsitektur khusus bila memang diperlukan. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
