import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Banyak perusahaan membuat blog dengan semangat tinggi, menulis beberapa artikel tentang berita internal atau ucapan hari raya, lalu membiarkannya berdebu berbulan-bulan. Hasilnya, blog dianggap tidak berguna. Padahal masalahnya jarang pada blog sebagai media, melainkan pada apa yang ditulis, untuk siapa, dan bagaimana tulisan itu terhubung dengan tujuan bisnis." },
  { type: "p", text: "Blog yang dikelola dengan benar bekerja seperti tenaga penjual yang tidak pernah tidur. Calon pelanggan yang sedang mencari jawaban di mesin pencari menemukan artikel Anda, membaca penjelasan yang membantu, lalu mulai memercayai perusahaan yang menulisnya. Ketika mereka siap membeli, perusahaan yang sudah memberi manfaat lebih dulu punya keunggulan dibanding yang baru muncul di saat terakhir." },
  { type: "p", text: "Artikel ini membahas cara menjadikan blog perusahaan sebagai sumber prospek yang nyata: memilih topik dari pertanyaan pelanggan, memahami niat di balik pencarian, menulis artikel yang berguna, menata kalender dan proses kerja, menghubungkan tulisan dengan ajakan bertindak, dan mengukur hasil. Kami tidak memakai angka rekaan tentang berapa prospek yang akan datang, karena hasil sangat bergantung pada industri, persaingan, dan konsistensi. Yang kami tawarkan adalah metode yang bisa Anda jalankan dan ukur sendiri." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Blog efektif bila menjawab pertanyaan nyata calon pelanggan, bukan membicarakan perusahaan sendiri",
      "Pilih topik dari pertanyaan yang sering diajukan tim penjualan dan layanan pelanggan, lalu periksa apa yang dicari orang di mesin pencari",
      "Tulis sesuai niat pencarian: ada yang ingin belajar, membandingkan, atau siap membeli, dan tiap niat butuh jenis artikel berbeda",
      "Konsistensi lebih penting daripada volume; tetapkan ritme yang bisa dipertahankan dan perbarui artikel lama",
      "Hubungkan tiap artikel dengan langkah berikutnya yang jelas, lalu ukur prospek dan perbaiki berdasarkan data",
    ],
  },
  { type: "h2", text: "Mengapa blog bisa menjadi mesin prospek" },
  { type: "p", text: "Orang jarang langsung memutuskan membeli jasa atau produk yang cukup mahal atau rumit. Mereka biasanya melalui proses: menyadari masalah, mencari tahu solusinya, membandingkan pilihan, baru kemudian memutuskan. Di setiap tahap itu, mereka bertanya kepada mesin pencari, dan jawabannya sebagian besar datang dari artikel yang ditulis perusahaan atau pakar." },
  { type: "p", text: "Blog menempatkan perusahaan Anda di sepanjang perjalanan itu. Artikel yang menjelaskan cara memilih sistem kasir, misalnya, menjangkau pemilik toko yang baru menyadari bahwa pencatatan manual merepotkan, jauh sebelum mereka siap menghubungi vendor mana pun. Dengan memberi penjelasan yang jujur dan membantu, Anda membangun kepercayaan, dan kepercayaan adalah mata uang utama dalam penjualan jasa dan produk bernilai tinggi." },
  { type: "p", text: "Ada keuntungan lain. Artikel yang baik terus bekerja lama setelah ditulis, berbeda dari iklan yang berhenti begitu anggaran habis. Satu artikel yang menjawab pertanyaan penting bisa mendatangkan pembaca dari waktu ke waktu, asalkan tetap relevan dan diperbarui. Karena itu, blog adalah aset yang nilainya menumpuk, bukan biaya yang hangus setiap bulan." },
  { type: "p", text: "Meski begitu, blog bukan jalan pintas. Ia membutuhkan waktu untuk terlihat hasilnya, dan hasilnya tidak bisa dijanjikan dengan pasti. Orang yang mengharapkan lonjakan prospek dalam dua minggu akan kecewa. Pandanglah blog sebagai investasi jangka menengah yang dibangun dengan konsisten." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8",
    alt: "Laptop di atas meja menampilkan halaman situs dengan tulisan tentang pengalaman yang sederhana",
    caption: "Halaman yang menjawab kebutuhan pembaca dengan bahasa sederhana lebih berpeluang dipercaya daripada halaman yang hanya memuji diri sendiri.",
  },
  { type: "h2", text: "Mulai dari pelanggan, bukan dari perusahaan" },
  { type: "p", text: "Kesalahan paling umum dalam blog perusahaan adalah menulis tentang apa yang ingin dikatakan perusahaan, bukan apa yang ingin diketahui pelanggan. Berita tentang peresmian kantor atau penghargaan internal tidak salah, tetapi jarang menarik orang yang sedang mencari solusi. Untuk menjadi mesin prospek, blog harus berpusat pada masalah dan pertanyaan pelanggan." },
  { type: "p", text: "Sumber topik terbaik sudah ada di dalam perusahaan Anda. Tanyakan kepada tim penjualan: pertanyaan apa yang paling sering diajukan calon pelanggan di percakapan pertama? Apa yang sering mereka salah pahami? Keberatan apa yang sering muncul? Tanyakan kepada layanan pelanggan: masalah apa yang paling sering dilaporkan dan bagaimana menyelesaikannya? Setiap pertanyaan yang diajukan berulang-ulang adalah kandidat artikel yang hampir pasti dicari orang lain juga." },
  { type: "p", text: "Sumber lain adalah mesin pencari itu sendiri. Ketikkan pertanyaan yang relevan dan perhatikan saran pencarian otomatis, bagian pertanyaan terkait, dan hasil yang muncul. Perhatikan pula bagaimana orang menyebut masalahnya, karena sering berbeda dengan istilah internal Anda. Pelanggan mungkin mencari \"cara mencatat stok toko\" sementara perusahaan menyebutnya \"manajemen inventori\". Menulis dengan bahasa pelanggan membuat artikel lebih mudah ditemukan." },
  { type: "h3", text: "Pilar topik yang selaras dengan bisnis" },
  { type: "p", text: "Rancang beberapa pilar topik yang berhubungan langsung dengan produk atau jasa Anda. Untuk perusahaan pengembang software, pilarnya mungkin sistem kasir, ERP, aplikasi mobile, dan keamanan data. Di setiap pilar, tulis serangkaian artikel yang saling berkaitan, dari pengantar untuk pemula hingga pembahasan mendalam. Struktur ini menunjukkan kepakaran dan memudahkan pembaca menjelajah dari satu artikel ke artikel lain." },
  { type: "h2", text: "Memahami niat di balik pencarian" },
  { type: "p", text: "Orang mencari dengan tujuan berbeda, dan artikel yang baik cocok dengan tujuannya. Memahami niat pencarian membantu Anda memutuskan jenis artikel, nada penulisan, dan ajakan bertindak yang sesuai." },
  {
    type: "ol",
    items: [
      "Niat belajar: orang ingin memahami sesuatu, misalnya \"apa itu ERP\" atau \"cara menghitung stok minimum\"; artikel penjelasan yang jelas dan lengkap paling cocok",
      "Niat membandingkan: orang menimbang pilihan, misalnya \"software jadi atau custom\" atau \"ERP cloud atau on-premise\"; artikel perbandingan yang adil dengan kriteria jelas membantu",
      "Niat mencari solusi spesifik: orang sudah tahu masalahnya dan mencari cara, misalnya \"cara menyatukan stok toko dan marketplace\"; panduan langkah demi langkah paling tepat",
      "Niat siap bertindak: orang sudah hampir memutuskan, misalnya mencari penyedia jasa tertentu atau harga; halaman layanan dan ajakan kontak yang jelas lebih relevan",
    ],
  },
  { type: "p", text: "Banyak blog hanya menyasar niat belajar, yang bagus untuk jangkauan tetapi jarang langsung menghasilkan prospek. Artikel perbandingan dan panduan solusi sering mempertemukan Anda dengan orang yang lebih dekat dengan keputusan. Campuran keempat niat, dengan penekanan pada yang paling dekat dengan bisnis Anda, memberi hasil lebih seimbang." },
  { type: "p", text: "Perhatikan juga apakah pencarian itu cocok dengan kemampuan Anda. Jika Anda tidak bisa memberikan jawaban terbaik tentang suatu topik, lebih baik fokus pada topik yang bisa Anda bahas dengan pengalaman dan kedalaman nyata. Mesin pencari dan pembaca sama-sama menghargai artikel yang jelas ditulis oleh orang yang paham." },
  { type: "h2", text: "Menulis artikel yang benar-benar berguna" },
  { type: "p", text: "Artikel yang baik menjawab pertanyaan pembaca dengan jelas, lengkap, dan jujur. Mulailah dengan menjawab inti pertanyaan di awal, lalu perdalam. Pembaca yang menemukan jawaban dalam beberapa paragraf pertama akan lebih percaya dan lebih mau membaca sisanya. Hindari pendahuluan bertele-tele yang menunda manfaat." },
  { type: "p", text: "Susun artikel dengan struktur yang mudah dipindai. Gunakan judul bagian yang deskriptif, paragraf pendek, daftar untuk langkah atau perbandingan, dan ringkasan di awal untuk pembaca yang terburu-buru. Sertakan contoh konkret dan situasi nyata yang dikenali pembaca. Tambahkan gambar atau diagram yang menjelaskan, bukan sekadar menghias, dan beri teks alternatif yang menggambarkan isi gambar." },
  { type: "p", text: "Jujur adalah kunci kepercayaan. Akui keterbatasan, sebutkan kapan solusi Anda bukan pilihan terbaik, dan hindari klaim yang berlebihan atau angka yang tidak bisa dipertanggungjawabkan. Pembaca makin cermat membedakan konten yang tulus dari yang sekadar memasarkan. Artikel yang berani menyatakan \"ini tidak cocok untuk semua orang\" sering justru lebih dipercaya." },
  { type: "p", text: "Terakhir, tulis dengan suara manusia. Gunakan bahasa yang sama dengan yang dipakai pelanggan Anda, bukan jargon internal atau kalimat yang kaku. Jika memakai bantuan alat otomatis untuk menyusun draf, tetap periksa fakta, sesuaikan dengan pengalaman nyata perusahaan, dan pastikan hasilnya benar-benar bermanfaat, bukan sekadar mengisi halaman. Isi yang dangkal dan generik tidak membedakan Anda dari ribuan situs lain." },
  {
    type: "callout",
    title: "Uji sebelum terbit",
    text: "Tanyakan pada diri sendiri: jika pembaca hanya membaca artikel ini dan tidak menghubungi kami, apakah ia tetap mendapat manfaat? Jika jawabannya ya, artikel itu kemungkinan layak diterbitkan.",
  },
  { type: "h2", text: "Dasar optimasi mesin pencari yang perlu diperhatikan" },
  { type: "p", text: "Artikel bagus pun perlu ditemukan. Beberapa praktik dasar optimasi mesin pencari membantu tanpa mengorbankan kualitas tulisan. Pilih satu topik utama per artikel dan pastikan ia tercermin pada judul, judul bagian, dan paragraf awal secara alami. Tulis judul yang jelas dan menarik untuk diklik, serta deskripsi singkat yang menggambarkan isi." },
  { type: "p", text: "Gunakan alamat halaman yang pendek dan deskriptif. Tautkan antar-artikel yang terkait agar pembaca dan mesin pencari memahami hubungannya. Pastikan halaman cepat dimuat dan nyaman di ponsel, karena kebanyakan pembaca datang dari perangkat seluler. Tambahkan data terstruktur yang sesuai agar hasil pencarian lebih informatif, dan pastikan peta situs memuat semua artikel sehingga mudah ditemukan perayap." },
  { type: "p", text: "Jangan terjebak menjejalkan kata kunci secara berlebihan. Mesin pencari modern cukup pandai memahami makna, dan tulisan yang dipaksakan menurunkan kualitas bagi pembaca. Bila Anda menulis untuk membantu manusia dengan jelas, kebanyakan kebutuhan optimasi terpenuhi secara alami. Topik ini kami bahas lebih lanjut dalam artikel tentang dasar SEO untuk website perusahaan." },
  { type: "h2", text: "Menyusun kalender dan proses kerja yang bisa dipertahankan" },
  { type: "p", text: "Blog yang berhenti setelah tiga artikel tidak akan menghasilkan apa-apa. Konsistensi lebih penting daripada volume. Lebih baik satu artikel bagus setiap dua minggu yang benar-benar dijalankan selama setahun daripada sepuluh artikel dalam sebulan lalu senyap." },
  { type: "p", text: "Tentukan ritme yang realistis berdasarkan sumber daya Anda. Siapa yang menulis? Siapa yang meninjau? Siapa yang menerbitkan dan mempromosikan? Jika semua itu dikerjakan satu orang di sela pekerjaan lain, ritme yang rendah tetapi stabil jauh lebih mungkin bertahan. Susun kalender topik beberapa bulan ke depan agar tidak kehabisan ide di tengah jalan, dan sisakan ruang untuk topik mendadak yang relevan." },
  { type: "p", text: "Buat alur kerja sederhana: gagasan, rangka, draf, tinjauan oleh orang yang paham topik, perbaikan, penerbitan, dan promosi. Tinjauan oleh ahli di dalam perusahaan, seperti konsultan atau pengembang, penting untuk menjaga ketepatan isi. Sediakan pula daftar periksa penerbitan agar hal-hal kecil seperti gambar, judul, tautan, dan deskripsi tidak terlewat." },
  { type: "h3", text: "Memperbarui artikel lama" },
  { type: "p", text: "Artikel yang sudah terbit tidak boleh dibiarkan selamanya. Informasi berubah, contoh menjadi usang, dan tautan putus. Jadwalkan peninjauan artikel secara berkala, terutama yang paling banyak dibaca atau yang paling dekat dengan bisnis Anda. Memperbarui dan memperkaya artikel lama sering lebih efektif daripada menulis yang baru, dan tanggal pembaruan yang jujur memberi sinyal kepada pembaca bahwa isinya masih segar." },
  { type: "h2", text: "Menghubungkan artikel dengan langkah berikutnya" },
  { type: "p", text: "Pembaca yang puas belum tentu menjadi prospek jika tidak ada jalan yang jelas menuju langkah berikutnya. Setiap artikel perlu ajakan bertindak yang relevan dengan isinya dan dengan tahap pembaca. Artikel pengantar mungkin mengajak membaca panduan lanjutan atau mengunduh daftar periksa. Artikel perbandingan mungkin mengajak berkonsultasi. Artikel solusi spesifik mungkin menawarkan bantuan langsung." },
  { type: "p", text: "Letakkan ajakan itu dengan wajar. Satu ajakan yang jelas di akhir, ditambah tautan kontekstual ke halaman layanan terkait di tengah tulisan jika memang relevan, lebih efektif daripada banyak spanduk yang mengganggu. Sebutkan manfaatnya bagi pembaca, bukan sekadar \"hubungi kami\". Pertimbangkan tawaran yang ringan seperti konsultasi awal tanpa biaya atau sumber daya yang bisa diunduh, karena orang yang belum siap membeli mungkin siap mengambil langkah kecil." },
  { type: "p", text: "Pastikan jalur konversinya berjalan baik. Formulir yang panjang, halaman kontak yang sulit ditemukan, atau pesan yang tidak dibalas cepat dapat menghilangkan prospek yang sudah Anda peroleh dengan susah payah. Respons yang cepat dan ramah terhadap pertanyaan yang masuk sering menjadi pembeda antara prospek yang hangat dan yang dingin." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1590650153855-d9e808231d41",
    alt: "Seorang perempuan berdiri di depan laptop di ruang kantor terbuka",
    caption: "Prospek dari blog perlu disambut dengan respons yang cepat dan ramah agar tidak menguap.",
  },
  { type: "h2", text: "Mengukur hasil tanpa terjebak angka semu" },
  { type: "p", text: "Pengukuran membantu menentukan apa yang perlu dipertahankan dan apa yang perlu diubah. Namun pilih indikator yang bermakna, bukan sekadar yang mudah dihitung. Jumlah kunjungan memberi gambaran jangkauan, tetapi tidak menunjukkan apakah kunjungan itu mendatangkan bisnis." },
  { type: "p", text: "Beberapa indikator yang berguna adalah kunjungan dari pencarian alami per artikel, waktu dan kedalaman membaca, jumlah klik pada ajakan bertindak, jumlah formulir atau pesan yang masuk dari halaman blog, dan, yang terpenting, apakah prospek dari blog akhirnya menjadi pelanggan. Hubungkan data ini dengan catatan penjualan agar Anda tahu artikel mana yang berkontribusi pada bisnis nyata, bukan hanya lalu lintas." },
  { type: "p", text: "Berikan waktu yang cukup sebelum menilai. Konten biasanya butuh beberapa bulan untuk mulai terlihat di mesin pencari, dan lebih lama untuk bersaing pada topik yang ramai. Tinjau tren, bukan angka harian. Perhatikan artikel yang berkinerja baik dan pelajari polanya: topik apa, format apa, panjang berapa. Gandakan yang berhasil dan hentikan atau perbaiki yang tidak." },
  { type: "p", text: "Jangan lupa menanyakan langsung kepada pelanggan baru bagaimana mereka mengenal perusahaan Anda. Jawaban sederhana seperti \"saya membaca artikel Anda tentang...\" adalah bukti paling jujur bahwa blog bekerja, dan sering menunjukkan pengaruh yang tidak tertangkap alat ukur." },
  { type: "h2", text: "Memanfaatkan ulang konten ke saluran lain" },
  { type: "p", text: "Satu artikel yang baik bisa dimanfaatkan berkali-kali. Ringkasannya bisa menjadi unggahan media sosial, poin-poinnya menjadi buletin email, dan pertanyaan di dalamnya menjadi bahan video pendek atau materi presentasi. Artikel panduan bisa dikemas menjadi daftar periksa yang diunduh, sekaligus cara mengumpulkan kontak pembaca yang tertarik dengan persetujuan mereka." },
  { type: "p", text: "Bagikan artikel kepada tim penjualan agar mereka bisa mengirimkannya kepada calon pelanggan yang menanyakan hal serupa. Artikel yang menjawab keberatan umum menghemat waktu penjelasan berulang dan menunjukkan bahwa perusahaan memahami masalah pelanggan. Dengan begitu blog tidak hanya menarik orang dari luar, tetapi juga memperkuat proses penjualan yang sudah berjalan." },
  { type: "h2", text: "Kesalahan umum dalam mengelola blog perusahaan" },
  { type: "p", text: "Beberapa kesalahan sering terulang. Menulis tentang diri sendiri alih-alih tentang masalah pelanggan adalah yang paling umum. Tidak konsisten, dengan lonjakan semangat lalu hilang berbulan-bulan, adalah yang kedua. Menulis terlalu dangkal dan generik sehingga tidak ada alasan orang memilih artikel Anda dibanding ribuan lainnya juga sering terjadi." },
  { type: "p", text: "Lainnya meliputi tidak menyertakan ajakan bertindak, tidak memperbarui artikel lama, tidak mengukur hasil, dan mengharapkan hasil instan. Ada pula yang menyalin tulisan dari sumber lain atau menjejalkan kata kunci demi mesin pencari, yang merusak kepercayaan pembaca dan berisiko merugikan peringkat. Hindari semuanya dengan kembali ke prinsip dasar: bantu pembaca, jujur, dan konsisten." },
  { type: "h2", text: "Langkah praktis memulai blog yang menghasilkan prospek" },
  {
    type: "ol",
    items: [
      "Kumpulkan sepuluh pertanyaan yang paling sering diajukan calon pelanggan kepada tim penjualan dan layanan Anda",
      "Periksa bagaimana orang mencari topik-topik itu dan jadikan pilar topik yang selaras dengan bisnis",
      "Pasangkan tiap topik dengan niat pencarian dan pilih jenis artikel yang sesuai",
      "Tetapkan ritme penerbitan yang realistis dan susun kalender beberapa bulan ke depan",
      "Tulis jawaban yang jelas, jujur, dan terstruktur, dengan ajakan bertindak yang relevan di setiap artikel",
      "Ukur kunjungan, klik, prospek, dan konversi, lalu tinjau dan perbarui artikel secara berkala",
    ],
  },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Blog perusahaan bukan sekadar papan pengumuman, melainkan aset yang bisa mendatangkan calon pelanggan secara berkelanjutan jika dikelola dengan benar. Kuncinya sederhana tetapi menuntut disiplin: memahami apa yang dicari pelanggan, menjawabnya dengan jujur dan jelas, menerbitkan secara konsisten, dan menghubungkannya dengan langkah berikutnya." },
  { type: "p", text: "Mulailah dari yang kecil dan jalankan dengan tekun. Beberapa artikel yang benar-benar membantu pembaca lebih bernilai daripada puluhan tulisan asal-asalan. Seiring waktu, kumpulan artikel itu menjadi perpustakaan pengetahuan yang membangun kepercayaan bahkan sebelum calon pelanggan pertama kali menghubungi Anda." },
  {
    type: "cta",
    title: "Ingin website dan blog yang benar-benar mendatangkan prospek?",
    text: "Tim AG·SORA membangun website yang cepat, ramah mesin pencari, dan siap mengelola konten blog sebagai sumber prospek. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
