import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Sebagian besar toko online mengeluarkan banyak tenaga dan biaya untuk mendatangkan pembeli baru, lalu hampir tidak melakukan apa-apa setelah pesanan pertama selesai. Pelanggan menerima barang, toko menerima uang, dan hubungan berhenti di situ. Bulan berikutnya toko kembali membayar iklan untuk mencari orang baru, padahal ratusan orang yang sudah pernah membeli dan puas tidak pernah disapa lagi." },
  { type: "p", text: "Email dan pesan otomatis adalah cara paling murah untuk memperbaiki keadaan itu. Berbeda dengan pengikut di media sosial, daftar kontak pelanggan adalah aset yang Anda miliki sendiri. Jangkauannya tidak bergantung pada perubahan algoritma, dan biayanya tidak naik setiap kali pesaing menaikkan tawaran iklan." },
  { type: "p", text: "Artikel ini membahas cara membangun email marketing dan otomasi untuk toko online secara bertanggung jawab. Kami membahas cara mengumpulkan kontak dengan izin, alur otomatis yang layak didahulukan, segmentasi, isi pesan, keterkiriman, hubungan dengan WhatsApp dan pemberitahuan aplikasi, serta cara mengukur hasilnya. Tidak ada angka rekaan tentang tingkat buka atau penjualan; hasil tiap toko berbeda dan hanya bisa diketahui dengan mengukur sendiri." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Daftar kontak yang dikumpulkan dengan izin adalah aset milik toko, tidak bergantung pada platform lain",
      "Dahulukan beberapa alur otomatis yang dipicu perilaku pelanggan sebelum mengirim siaran massal",
      "Segmentasi sederhana berdasarkan riwayat belanja membuat pesan terasa relevan",
      "Jaga reputasi pengirim dengan autentikasi domain, daftar yang bersih, dan frekuensi yang wajar",
      "Ukur dengan pendapatan dan pembelian ulang, bukan hanya dengan jumlah yang membuka pesan",
    ],
  },
  { type: "h2", text: "Mengapa kanal milik sendiri penting" },
  { type: "p", text: "Toko yang hanya mengandalkan iklan dan marketplace sebenarnya menyewa perhatian pelanggan. Selama membayar, pembeli datang. Begitu biaya naik atau aturan platform berubah, arus itu ikut berubah tanpa bisa Anda kendalikan. Daftar email dan nomor pelanggan yang dikumpulkan dengan izin memberi Anda jalur langsung yang tidak melewati perantara." },
  { type: "p", text: "Menjual kepada orang yang sudah pernah membeli juga umumnya lebih mudah daripada meyakinkan orang asing. Mereka sudah mengenal mutu barang Anda, sudah punya akun, dan sudah percaya bahwa paketnya akan sampai. Yang mereka perlukan sering hanya pengingat yang tepat pada saat yang tepat." },
  { type: "p", text: "Email memiliki sifat yang cocok untuk tugas ini. Ia bisa memuat penjelasan panjang, gambar produk, dan tautan langsung ke keranjang. Ia tidak mengganggu seperti panggilan telepon. Dan hampir setiap pembeli online memilikinya, karena alamat email diperlukan untuk menerima konfirmasi pesanan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
    alt: "Layar laptop menampilkan grafik dan laporan analitik bisnis",
    caption: "Kanal milik sendiri memungkinkan Anda mengukur hubungan dengan pelanggan dari pesan sampai pembelian.",
  },
  { type: "h2", text: "Mengumpulkan kontak dengan izin yang jelas" },
  { type: "p", text: "Dasar seluruh kegiatan ini adalah izin. Kirim pesan pemasaran hanya kepada orang yang dengan sadar bersedia menerimanya. Daftar yang dibeli atau dikumpulkan diam-diam bukan hanya bermasalah secara etika dan hukum; ia juga merusak reputasi pengirim Anda, karena penerima yang tidak merasa mendaftar akan menandai pesan Anda sebagai spam." },
  { type: "p", text: "Sediakan beberapa titik pendaftaran yang wajar: kotak centang yang tidak dicentang otomatis pada halaman pembayaran, formulir di bagian bawah situs, tawaran pada halaman produk yang stoknya habis, dan pendaftaran di aplikasi. Jelaskan apa yang akan diterima pelanggan dan seberapa sering. Janji yang jujur menghasilkan daftar yang lebih kecil tetapi lebih berharga." },
  { type: "p", text: "Bedakan pesan transaksi dari pesan pemasaran. Konfirmasi pesanan, bukti pembayaran, dan pemberitahuan pengiriman adalah bagian dari layanan. Promosi dan buletin adalah hal lain yang memerlukan persetujuan tersendiri. Sesuaikan praktik Anda dengan ketentuan pelindungan data pribadi yang berlaku, dan selalu sediakan cara berhenti berlangganan yang mudah di setiap pesan." },
  { type: "callout", title: "Berhenti berlangganan harus mudah", text: "Tautan berhenti berlangganan yang tersembunyi tidak menahan pelanggan; ia hanya mengubah orang yang ingin pergi menjadi orang yang melaporkan spam. Laporan spam merusak keterkiriman pesan Anda kepada pelanggan lain yang sebenarnya masih ingin menerima." },
  { type: "h2", text: "Pesan transaksi: yang paling sering dibaca" },
  { type: "p", text: "Pesan transaksi adalah pesan yang paling ditunggu pelanggan. Mereka ingin tahu pesanannya tercatat, pembayarannya diterima, dan paketnya sedang di jalan. Banyak toko membiarkan pesan ini apa adanya dari bawaan platform, padahal inilah titik sentuh yang paling pasti dilihat." },
  { type: "p", text: "Rapikan isinya terlebih dahulu: ringkasan pesanan yang jelas, alamat pengiriman, perkiraan waktu, nomor resi beserta tautan pelacakan, dan cara menghubungi toko. Gunakan nama pengirim dan tampilan yang konsisten dengan merek Anda. Pesan transaksi yang rapi mengurangi pertanyaan ke layanan pelanggan dan menambah rasa aman." },
  { type: "p", text: "Anda boleh menambahkan sedikit isi yang membantu, misalnya petunjuk perawatan barang atau cara pemakaian. Tahan diri untuk tidak menjejali pesan transaksi dengan promosi. Tujuan utamanya adalah memberi kepastian, dan aturan di banyak tempat membedakan dengan tegas antara pesan layanan dan pesan pemasaran." },
  { type: "h2", text: "Alur otomatis yang layak didahulukan" },
  { type: "p", text: "Alur otomatis adalah pesan yang terkirim sendiri ketika pelanggan melakukan atau tidak melakukan sesuatu. Sekali disiapkan, ia bekerja terus tanpa perlu dikirim manual. Bagi toko yang baru memulai, beberapa alur berikut biasanya memberi hasil paling terasa dibanding tenaga yang dikeluarkan." },
  { type: "ol", items: [
    "Sambutan: rangkaian pendek untuk pendaftar baru yang memperkenalkan toko dan produk andalan",
    "Keranjang tertinggal: pengingat bagi yang memasukkan barang tetapi belum menyelesaikan pembayaran",
    "Setelah pembelian: ucapan terima kasih, petunjuk pemakaian, lalu permintaan ulasan",
    "Pembelian ulang: pengingat ketika barang habis pakai diperkirakan mulai menipis",
    "Stok kembali tersedia: pemberitahuan bagi yang mendaftar pada produk yang sempat habis",
    "Menyapa kembali: pesan untuk pelanggan yang sudah lama tidak berbelanja",
  ] },
  { type: "p", text: "Mulailah dengan satu atau dua alur, perhatikan hasilnya, lalu tambahkan. Alur yang sederhana tetapi berjalan lebih bernilai daripada rancangan rumit yang tidak pernah selesai dibangun. Tinjau isinya secara berkala, karena pesan otomatis yang dibiarkan bertahun-tahun bisa menyebut produk, harga, atau kebijakan yang sudah tidak berlaku." },
  { type: "h2", text: "Keranjang tertinggal: mengingatkan tanpa mengganggu" },
  { type: "p", text: "Orang meninggalkan keranjang karena banyak sebab: terganggu hal lain, ingin membandingkan harga, kaget melihat ongkos kirim, atau sekadar belum yakin. Pengingat yang dikirim tidak lama setelah itu memberi kesempatan kedua. Sebutkan barang yang ditinggalkan, tampilkan gambarnya, dan sediakan tautan yang langsung membawa pelanggan kembali ke keranjangnya." },
  { type: "p", text: "Jangan langsung menawarkan diskon. Jika setiap keranjang yang ditinggal selalu dihadiahi potongan, pelanggan belajar meninggalkan keranjang dengan sengaja. Pengingat pertama cukup berisi bantuan: apakah ada pertanyaan, bagaimana kebijakan retur, dan cara menghubungi toko. Insentif, bila memang dipakai, sebaiknya terbatas dan tidak otomatis untuk semua orang." },
  { type: "p", text: "Batasi jumlah pengingat dan hentikan segera setelah pelanggan membeli. Pengingat yang masih datang setelah pesanan selesai menunjukkan sistem yang tidak terhubung dan membuat toko tampak ceroboh. Pastikan alur ini membaca status pesanan terbaru sebelum mengirim." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1512758017271-d7b84c2113f1",
    alt: "Papan tulis penuh catatan tempel kuning hasil sesi perencanaan",
    caption: "Alur otomatis sebaiknya digambar dulu sebagai perjalanan pelanggan sebelum dibangun di sistem.",
  },
  { type: "h2", text: "Segmentasi: pesan yang relevan" },
  { type: "p", text: "Mengirim pesan yang sama kepada semua orang adalah cara tercepat membuat orang berhenti membaca. Segmentasi berarti membagi daftar menurut ciri yang bermakna, lalu menyesuaikan pesan. Anda tidak memerlukan model yang rumit; data yang sudah dimiliki toko sudah cukup untuk memulai." },
  { type: "ul", items: [
    "Pernah membeli atau belum pernah membeli",
    "Kategori produk yang pernah dibeli atau sering dilihat",
    "Waktu sejak pembelian terakhir",
    "Jumlah pesanan: pembeli pertama, pembeli berulang, pelanggan setia",
    "Lokasi, bila pengiriman atau promosi berbeda per wilayah",
    "Bahasa yang dipilih pelanggan saat mendaftar",
  ] },
  { type: "p", text: "Segmentasi juga berarti tahu kapan tidak mengirim. Pelanggan yang baru saja membeli suatu barang tidak perlu ditawari barang yang sama dengan diskon keesokan harinya. Pelanggan yang sedang mengajukan keluhan sebaiknya dikeluarkan sementara dari promosi. Kepekaan seperti ini hanya mungkin bila data pesanan dan data pemasaran terhubung." },
  { type: "h2", text: "Isi dan nada pesan" },
  { type: "p", text: "Pesan yang baik menghormati waktu pembaca. Baris subjek menyatakan isi dengan jujur, tanpa huruf besar berlebihan dan tanpa janji yang tidak ditepati di dalam. Isi pesan memiliki satu tujuan utama dan satu ajakan yang jelas. Semakin banyak hal yang diminta dalam satu pesan, semakin kecil kemungkinan salah satunya dilakukan." },
  { type: "p", text: "Sebagian besar pesan dibaca di ponsel. Gunakan tata letak satu kolom, huruf yang cukup besar, tombol yang mudah disentuh, dan gambar yang ringan. Sertakan teks alternatif pada gambar, karena banyak aplikasi email tidak menampilkan gambar secara otomatis. Pesan harus tetap dapat dipahami walau gambarnya tidak muncul." },
  { type: "p", text: "Tidak semua pesan harus menjual. Panduan memilih ukuran, cara merawat produk, cerita di balik pembuatan barang, atau jawaban atas pertanyaan yang sering muncul memberi alasan bagi pelanggan untuk tetap membuka pesan Anda. Hubungan yang hanya berisi diskon melatih pelanggan menunggu diskon." },
  { type: "h2", text: "Keterkiriman: agar pesan sampai ke kotak masuk" },
  { type: "p", text: "Pesan yang bagus tidak berguna bila masuk ke folder spam. Penyedia layanan email menilai setiap pengirim berdasarkan reputasinya. Reputasi dibangun dari tanda teknis bahwa Anda memang berhak mengirim atas nama domain Anda, serta dari perilaku penerima terhadap pesan Anda." },
  { type: "ul", items: [
    "Kirim dari domain milik sendiri dan pasang autentikasi pengirim sesuai petunjuk penyedia layanan",
    "Pisahkan pengiriman pesan transaksi dari pesan pemasaran bila memungkinkan",
    "Bersihkan alamat yang berulang kali gagal terkirim",
    "Kurangi atau hentikan kiriman kepada yang sudah sangat lama tidak membuka",
    "Naikkan volume kiriman secara bertahap, jangan melonjak tiba-tiba",
    "Pantau keluhan spam dan cari tahu penyebabnya ketika naik",
  ] },
  { type: "p", text: "Daftar yang lebih kecil tetapi aktif hampir selalu lebih baik daripada daftar besar yang penuh alamat mati. Menghapus kontak yang tidak pernah menanggapi terasa seperti kehilangan, padahal sebenarnya melindungi kemampuan Anda menjangkau pelanggan yang masih peduli." },
  { type: "h2", text: "Frekuensi dan pilihan pelanggan" },
  { type: "p", text: "Tidak ada jumlah kiriman yang benar untuk semua toko. Toko dengan produk baru setiap minggu punya lebih banyak hal untuk disampaikan daripada toko yang menjual sedikit jenis barang tahan lama. Ukurannya adalah tanggapan pelanggan: bila angka berhenti berlangganan dan keluhan naik setiap kali Anda menambah kiriman, itu jawabannya." },
  { type: "p", text: "Beri pelanggan pilihan selain semua atau tidak sama sekali. Halaman preferensi yang memungkinkan mereka memilih jenis pesan dan seberapa sering sering kali menyelamatkan hubungan yang tadinya akan berakhir. Sebagian orang hanya ingin kabar produk baru, sebagian hanya ingin promosi besar." },
  { type: "h2", text: "Email, WhatsApp, dan pemberitahuan aplikasi" },
  { type: "p", text: "Email bukan satu-satunya kanal milik sendiri. Banyak pelanggan lebih cepat menanggapi pesan WhatsApp, dan pengguna aplikasi bisa dijangkau lewat pemberitahuan. Masing-masing punya sifat berbeda. Pesan instan terasa pribadi dan mendesak, sehingga cocok untuk hal penting dan singkat tetapi cepat terasa mengganggu bila dipakai untuk promosi rutin." },
  { type: "p", text: "Rancang semuanya sebagai satu sistem, bukan sebagai tim terpisah yang masing-masing mengirim sesukanya. Pelanggan yang menerima pengingat keranjang lewat email, WhatsApp, dan pemberitahuan aplikasi dalam satu jam akan merasa dikejar. Tetapkan kanal utama untuk setiap jenis pesan dan aturan agar kanal lain hanya dipakai bila yang pertama tidak ditanggapi." },
  { type: "p", text: "Setiap kanal memerlukan izin sendiri dan memiliki ketentuan penyedia layanannya sendiri. Persetujuan menerima email tidak otomatis berarti persetujuan menerima pesan promosi di WhatsApp. Catat izin per kanal di data pelanggan dan hormati pilihannya." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1686061592689-312bbfb5c055",
    alt: "Layar komputer menampilkan dasbor analitik dengan tabel retensi pengguna",
    caption: "Ukuran yang paling bermakna adalah apakah pelanggan kembali membeli, bukan sekadar membuka pesan.",
  },
  { type: "h2", text: "Mengukur hasil dengan jujur" },
  { type: "p", text: "Angka buka dan klik mudah dilihat, tetapi mudah menyesatkan. Perlindungan privasi di sejumlah aplikasi email membuat angka buka tidak lagi mencerminkan perilaku sebenarnya. Ukuran yang lebih bermakna adalah yang dekat dengan uang dan hubungan: pesanan dan pendapatan yang berasal dari pesan, proporsi pelanggan yang membeli lagi, serta angka berhenti berlangganan dan keluhan." },
  { type: "p", text: "Berhati-hatilah menafsirkan pendapatan yang dikaitkan dengan email. Sebagian pelanggan yang mengeklik pengingat mungkin tetap akan membeli tanpa diingatkan. Cara yang lebih jujur untuk mengetahui pengaruh sebenarnya adalah menahan sebagian kecil pelanggan dari suatu alur selama beberapa waktu, lalu membandingkan perilaku kedua kelompok." },
  { type: "p", text: "Uji satu hal dalam satu waktu: baris subjek, waktu kirim, atau isi ajakan. Catat hasilnya dan terapkan yang terbukti lebih baik. Perbaikan kecil yang dilakukan terus-menerus pada alur otomatis menumpuk hasilnya, karena alur itu bekerja setiap hari." },
  { type: "h2", text: "Memilih alat dan menghubungkannya dengan toko" },
  { type: "p", text: "Alat email marketing sangat beragam, dari fitur bawaan platform toko hingga layanan khusus. Yang paling menentukan bukan jumlah fitur, melainkan seberapa baik alat itu terhubung dengan data toko Anda: pelanggan, pesanan, produk, dan isi keranjang. Tanpa sambungan itu, alur otomatis dan segmentasi tidak bisa berjalan." },
  { type: "p", text: "Periksa bagaimana biaya dihitung, karena banyak layanan menagih berdasarkan jumlah kontak atau jumlah kiriman, dan biayanya bisa tumbuh cepat. Periksa pula kemudahan mengekspor data. Daftar kontak adalah aset Anda; pastikan Anda bisa membawanya bila kelak berpindah alat." },
  { type: "p", text: "Untuk toko yang dibangun khusus, integrasi dengan alat pemasaran sebaiknya dirancang sejak awal: peristiwa apa yang dikirim, data apa yang disertakan, dan bagaimana izin pelanggan disinkronkan dua arah. Perubahan izin di satu tempat harus langsung berlaku di tempat lain." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Membeli daftar kontak atau menambahkan orang tanpa persetujuan",
    "Mengirim pesan yang sama kepada semua orang tanpa segmentasi",
    "Menyembunyikan tautan berhenti berlangganan",
    "Menawarkan diskon otomatis pada setiap keranjang yang ditinggal",
    "Membiarkan alur otomatis bertahun-tahun tanpa ditinjau isinya",
    "Menilai keberhasilan hanya dari angka buka",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Periksa dan rapikan pesan konfirmasi pesanan serta pemberitahuan pengiriman",
    "Pastikan formulir pendaftaran meminta izin dengan jelas dan tidak dicentang otomatis",
    "Pasang autentikasi pengirim pada domain toko sesuai petunjuk penyedia layanan",
    "Bangun satu alur sambutan dan satu alur setelah pembelian",
    "Tetapkan ukuran yang akan dipantau: pembelian ulang, pendapatan dari pesan, dan angka berhenti berlangganan",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Email marketing yang baik bukan soal mengirim sebanyak mungkin, melainkan soal mengirim pesan yang tepat kepada orang yang bersedia menerimanya pada saat yang masuk akal. Dilakukan dengan izin, relevansi, dan rasa hormat, kanal ini mengubah pembeli sekali menjadi pelanggan yang kembali dengan biaya yang jauh lebih rendah daripada terus mencari orang baru." },
  { type: "p", text: "Mulailah dari pesan transaksi, tambahkan beberapa alur otomatis, hubungkan dengan data toko, dan ukur hasilnya dengan jujur. Dasar yang rapi itu akan terus bekerja untuk toko Anda setiap hari, termasuk ketika anggaran iklan sedang ditahan." },
  {
    type: "cta",
    title: "Ingin toko online yang terhubung dengan pemasaran otomatis dan data pelanggan?",
    text: "Tim AG·SORA membangun toko online dan CRM dengan data pelanggan yang rapi, alur pesan otomatis, pencatatan izin per kanal, dan laporan pembelian ulang. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/crm",
    label: "Konsultasi gratis",
  },
];
