import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Ketika pemilik toko memilih sistem kasir baru, perhatian hampir selalu tertuju pada perangkat lunaknya: fitur laporan, integrasi pembayaran, dan kemudahan penggunaan. Hal-hal itu memang penting. Tetapi ada lapisan di bawahnya yang menentukan apakah semua fitur itu benar-benar bisa dipakai pada jam sibuk: jaringan, listrik, dan perangkat keras. Sistem yang hebat di demo bisa lumpuh di toko jika wifi sering putus atau tablet kasir kehabisan baterai di tengah antrean." },
  { type: "p", text: "Gangguan infrastruktur punya sifat yang menjengkelkan. Ia jarang datang saat toko sepi. Biasanya muncul tepat ketika antrean mengular, ketika pelanggan sudah memegang barang dan menunggu membayar. Satu menit sistem tidak merespons terasa seperti sepuluh menit bagi pelanggan yang menunggu, dan sebagian akan meninggalkan keranjangnya begitu saja." },
  { type: "p", text: "Artikel ini membahas fondasi fisik di balik sistem toko: koneksi internet, jaringan lokal, perangkat kasir dan pendukungnya, listrik, keamanan, serta perawatan. Kami menulisnya untuk pemilik toko dan manajer operasional, bukan teknisi jaringan. Kami tidak menyebut merek atau harga tertentu karena berubah cepat dan berbeda antar wilayah; yang kami tawarkan adalah cara berpikir, pertanyaan yang perlu diajukan, dan daftar periksa yang bisa Anda terapkan di toko Anda sendiri." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Sistem kasir hanya setangguh infrastruktur di bawahnya: internet, jaringan lokal, listrik, dan perangkat",
      "Rencanakan koneksi berdasarkan kebutuhan nyata toko, dan siapkan jalur cadangan agar satu gangguan tidak menghentikan penjualan",
      "Pisahkan jaringan untuk operasional dan jaringan tamu, serta amankan akses ke perangkat dan router",
      "Pilih perangkat berdasarkan ketahanan, kemudahan perawatan, dan kecocokan dengan perangkat lunak, bukan hanya harga",
      "Siapkan prosedur untuk gangguan, jadwalkan perawatan rutin, dan catat semua aset agar penggantian terencana",
    ],
  },
  { type: "h2", text: "Mengapa infrastruktur menentukan pengalaman pelanggan" },
  { type: "p", text: "Pelanggan tidak peduli apakah penyebab antrean panjang adalah perangkat lunak, wifi, atau printer struk. Mereka hanya merasakan bahwa toko Anda lambat. Karena itu, infrastruktur adalah bagian dari pengalaman pelanggan, bukan urusan teknis di belakang layar. Toko dengan produk bagus tetapi pembayaran sering macet akan terus kehilangan penjualan dan reputasi." },
  { type: "p", text: "Infrastruktur juga memengaruhi karyawan. Perangkat yang lambat, sering hang, atau perlu dihidupkan ulang berkali-kali membuat kasir frustrasi dan lebih mudah melakukan kesalahan. Kasir yang terbiasa dengan sistem yang andal bekerja lebih tenang dan lebih cepat, yang pada akhirnya terlihat dari kepuasan pelanggan." },
  { type: "p", text: "Ada pula sisi data. Jika koneksi sering terputus dan transaksi tidak tersimpan dengan benar, laporan penjualan dan stok menjadi tidak akurat. Selisih kecil yang berulang menumpuk menjadi masalah pencatatan yang sulit ditelusuri. Infrastruktur yang andal menjaga data tetap bersih sejak titik pertama transaksi terjadi." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8",
    alt: "Kabel jaringan biru dan abu-abu tertancap pada panel patch",
    caption: "Di balik kasir yang lancar ada kabel, perangkat jaringan, dan listrik yang ditata dengan rapi.",
  },
  { type: "h2", text: "Memetakan kebutuhan toko Anda" },
  { type: "p", text: "Sebelum membeli apa pun, petakan dulu apa yang sebenarnya perlu terhubung. Gambarlah denah sederhana toko dan tandai titik-titik yang membutuhkan koneksi atau listrik: meja kasir, rak, gudang kecil, ruang kantor, pintu masuk, dan area yang dipakai pelanggan. Catat pula perangkat apa yang harus online sepanjang waktu dan mana yang hanya sesekali." },
  { type: "p", text: "Daftar perangkat yang umum di toko ritel mencakup perangkat kasir berupa komputer, tablet, atau terminal khusus, pemindai barcode, printer struk, laci uang, mesin pembayaran kartu atau QRIS, tablet untuk stok, kamera pengawas, dan kadang layar tampilan harga atau iklan. Masing-masing punya kebutuhan koneksi dan daya berbeda. Mengetahui jumlah dan jenisnya membantu Anda memperkirakan kapasitas jaringan yang dibutuhkan." },
  { type: "p", text: "Pertimbangkan juga pertumbuhan. Jika Anda berencana membuka cabang, menambah kasir, atau menambah jenis perangkat dalam setahun ke depan, rancang infrastruktur dengan ruang untuk tumbuh. Menarik kabel tambahan saat pemasangan awal jauh lebih murah daripada membongkar dinding kemudian." },
  { type: "h2", text: "Koneksi internet: pilihan dan cadangan" },
  { type: "p", text: "Sebagian besar sistem kasir modern berbasis cloud atau setidaknya membutuhkan internet untuk sinkronisasi data, pembayaran digital, dan pembaruan stok. Jadi koneksi internet adalah pembuluh darah toko. Beberapa pertimbangan membantu memilih dan mengamankannya." },
  {
    type: "ol",
    items: [
      "Periksa penyedia layanan yang tersedia di lokasi Anda dan bandingkan keandalannya, bukan hanya kecepatan di iklan",
      "Pilih paket sesuai kebutuhan nyata; toko dengan beberapa kasir dan pembayaran digital biasanya lebih bergantung pada kestabilan daripada kecepatan puncak",
      "Tanyakan kepada pemilik toko lain di area yang sama tentang pengalaman mereka dengan penyedia tertentu",
      "Siapkan jalur cadangan dari penyedia berbeda, misalnya koneksi kabel utama dengan cadangan jaringan seluler",
      "Pastikan perangkat router mendukung peralihan otomatis ke jalur cadangan jika memungkinkan",
    ],
  },
  { type: "p", text: "Jalur cadangan sering dianggap berlebihan sampai gangguan pertama terjadi. Satu penyedia bisa mengalami gangguan area selama berjam-jam, dan toko Anda tidak bisa berbuat apa-apa. Dengan koneksi cadangan, bahkan yang sederhana, penjualan tetap berjalan. Biaya cadangan umumnya jauh lebih kecil daripada penjualan yang hilang dalam satu hari gangguan." },
  { type: "h3", text: "Mode offline pada perangkat lunak" },
  { type: "p", text: "Pilihlah sistem kasir yang tetap bisa mencatat transaksi ketika internet putus, lalu menyinkronkannya setelah koneksi pulih. Fitur ini menyelamatkan toko dari kelumpuhan total. Pahami batasnya: pembayaran digital umumnya membutuhkan koneksi, jadi mode offline lebih berguna untuk tunai dan pencatatan. Uji secara nyata dengan sengaja memutus koneksi, dan pastikan kasir tahu apa yang harus dilakukan. Topik ini terkait dengan pembahasan kami tentang kapan aplikasi perlu bekerja offline." },
  { type: "h2", text: "Jaringan lokal di dalam toko" },
  { type: "p", text: "Internet yang bagus tidak berguna jika jaringan di dalam toko buruk. Banyak masalah yang dikira \"internet lambat\" sebenarnya berasal dari jaringan lokal: router murah yang kewalahan, sinyal wifi yang lemah di sudut tertentu, atau terlalu banyak perangkat berebut satu jalur." },
  { type: "p", text: "Untuk perangkat yang tidak berpindah, seperti komputer kasir dan printer, sambungan kabel biasanya lebih stabil dan lebih cepat daripada wifi. Gunakan wifi untuk perangkat bergerak seperti tablet stok dan ponsel pelayan. Jika toko cukup luas, satu router tidak akan menjangkau seluruh area; pertimbangkan beberapa titik akses yang ditempatkan strategis, lalu uji kekuatan sinyal di sudut-sudut yang sering dipakai." },
  { type: "p", text: "Pisahkan jaringan operasional dari jaringan tamu. Jika toko menyediakan wifi gratis untuk pelanggan, jangan biarkan mereka berada di jaringan yang sama dengan perangkat kasir. Pemisahan ini melindungi data dan mencegah pelanggan mengganggu, baik sengaja maupun tidak, perangkat penting. Banyak router modern mendukung jaringan tamu terpisah dengan pengaturan sederhana." },
  { type: "h3", text: "Mengelola alamat dan nama perangkat" },
  { type: "p", text: "Beri nama jelas pada setiap perangkat dan, bila perlu, tetapkan alamat jaringan yang tetap untuk perangkat penting seperti printer. Perangkat yang alamatnya berganti-ganti sering menyebabkan printer yang tiba-tiba tidak terhubung dan kebingungan bagi siapa pun yang mencoba memperbaikinya. Catat konfigurasi ini dalam dokumen sederhana yang disimpan aman." },
  { type: "h2", text: "Memilih perangkat kasir dan pendukungnya" },
  { type: "p", text: "Memilih perangkat bukan sekadar membandingkan harga. Perangkat toko bekerja keras: dipakai seharian, terkena debu, minuman yang tumpah, dan perlakuan kurang lembut. Pilih dengan mempertimbangkan ketahanan dan kecocokan, bukan hanya spesifikasi di atas kertas." },
  { type: "p", text: "Pertimbangkan kecocokan dengan perangkat lunak kasir Anda. Pastikan pemindai, printer, laci uang, dan mesin pembayaran didukung resmi oleh sistem yang Anda pakai. Membeli perangkat yang ternyata tidak kompatibel adalah kesalahan mahal yang cukup sering terjadi. Tanyakan daftar perangkat yang didukung kepada penyedia perangkat lunak sebelum membeli." },
  { type: "p", text: "Pikirkan juga kemudahan perawatan dan penggantian. Perangkat yang suku cadangnya mudah didapat dan penggantiannya cepat lebih berharga daripada perangkat canggih yang rusak lalu harus menunggu berminggu-minggu. Untuk perangkat kritis seperti printer struk dan pemindai, banyak toko menyimpan satu unit cadangan agar penggantian bisa dilakukan dalam hitungan menit." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1604754742629-3e5728249d73",
    alt: "Teknisi memasang komponen di dalam casing komputer",
    caption: "Perangkat yang mudah dirawat dan diganti menjaga toko tetap melayani saat terjadi kerusakan.",
  },
  { type: "h3", text: "Komputer, tablet, atau terminal khusus" },
  { type: "p", text: "Ketiganya punya kelebihan masing-masing. Komputer biasa fleksibel dan mudah diperbaiki, tetapi lebih mudah terganggu hal di luar urusan kasir. Tablet ringkas dan hemat tempat, cocok untuk toko kecil dan kafe, tetapi perlu penyangga yang kokoh dan manajemen daya yang baik. Terminal khusus kasir biasanya lebih tahan banting dan terpadu, dengan harga yang sering lebih tinggi. Pilih yang sesuai skala dan lingkungan kerja toko Anda, dan batasi perangkat kasir agar hanya menjalankan aplikasi yang diperlukan supaya lebih stabil dan aman." },
  { type: "h2", text: "Listrik dan daya cadangan" },
  { type: "p", text: "Listrik sering menjadi titik lemah yang terlupakan. Pemadaman singkat atau naik-turunnya tegangan bisa mematikan perangkat tiba-tiba, merusak data yang sedang ditulis, bahkan merusak perangkat. Perlindungan dasar tidak mahal tetapi sangat berharga." },
  { type: "p", text: "Gunakan penstabil atau pelindung lonjakan untuk perangkat penting. Pasang catu daya cadangan, atau UPS, pada router, modem, dan perangkat kasir utama agar toko bisa menyelesaikan transaksi dan mematikan sistem dengan aman ketika listrik padam sebentar. Untuk wilayah dengan pemadaman yang sering, pertimbangkan solusi daya cadangan yang lebih besar sesuai kebutuhan." },
  { type: "p", text: "Atur kabel dengan rapi dan aman. Kabel yang menjuntai di lantai membahayakan karyawan dan pelanggan, serta mudah tercabut. Gunakan penutup atau saluran kabel, dan beri label pada kabel dan colokan penting agar mudah dikenali ketika perlu perbaikan. Hindari menumpuk terlalu banyak perangkat pada satu stopkontak, dan jauhkan sambungan listrik dari area yang rawan basah." },
  { type: "h2", text: "Keamanan perangkat dan jaringan" },
  { type: "p", text: "Perangkat toko menyimpan dan memproses data penting: transaksi, stok, dan kadang data pelanggan. Pengamanan dasar melindungi bisnis Anda dari penyalahgunaan, baik dari luar maupun dari dalam." },
  {
    type: "callout",
    title: "Dasar keamanan toko",
    text: "Ganti kata sandi bawaan semua perangkat jaringan, batasi siapa yang memegang akses administrator, perbarui perangkat lunak secara berkala, dan jangan biarkan perangkat kasir dipakai untuk keperluan pribadi seperti menjelajah internet atau memasang aplikasi sembarangan.",
  },
  { type: "p", text: "Beberapa praktik tambahan membantu. Gunakan akun terpisah untuk tiap kasir dan manajer dengan hak akses sesuai peran, agar setiap tindakan bisa ditelusuri. Kunci router dan perangkat jaringan di tempat yang tidak mudah dijangkau umum. Jika memakai kamera pengawas, amankan aksesnya dengan kata sandi yang kuat dan batasi siapa yang bisa melihat rekaman. Untuk mesin pembayaran, ikuti petunjuk penyedia dan jangan pernah menyimpan data kartu di perangkat sendiri." },
  { type: "p", text: "Jika toko mencatat data pelanggan, seperti nomor telepon untuk program loyalitas, perlakukan sebagai data pribadi dan patuhi ketentuan yang berlaku. Rujuklah ketentuan terbaru dari otoritas yang berwenang, jangan mengandalkan ringkasan yang mungkin sudah usang. Strategi cadangan data juga penting; kami membahasnya di artikel tentang strategi backup data bisnis." },
  { type: "h2", text: "Prosedur saat terjadi gangguan" },
  { type: "p", text: "Gangguan pasti terjadi, sekecil apa pun kemungkinannya. Perbedaan antara toko yang tetap tenang dan toko yang panik terletak pada kesiapan. Tulis prosedur darurat sederhana dan pastikan semua karyawan tahu isinya." },
  { type: "p", text: "Prosedur itu menjawab pertanyaan seperti: apa yang dilakukan kasir jika sistem tidak merespons, bagaimana mencatat transaksi sementara dengan tangan, siapa yang dihubungi dan nomor telepon berapa, dan bagaimana data manual dimasukkan ke sistem setelah pulih. Tempelkan ringkasannya di dekat meja kasir. Lakukan latihan singkat sesekali agar prosedur tidak hanya tertulis, tetapi benar-benar dipahami." },
  { type: "p", text: "Siapkan juga daftar kontak darurat: penyedia internet, teknisi, penyedia perangkat lunak kasir, dan penyedia mesin pembayaran. Saat gangguan terjadi, waktu yang dihabiskan mencari nomor telepon adalah waktu yang berharga. Catat juga langkah pemecahan masalah dasar, seperti memeriksa kabel, menghidupkan ulang router, dan memastikan perangkat terhubung ke jaringan yang benar, yang sering menyelesaikan sebagian besar masalah ringan tanpa perlu memanggil teknisi." },
  { type: "h2", text: "Perawatan rutin dan pencatatan aset" },
  { type: "p", text: "Infrastruktur yang baik bukan sekali pasang lalu dilupakan. Jadwalkan perawatan rutin yang sederhana: membersihkan debu dari perangkat, memeriksa kabel dan sambungan, memperbarui perangkat lunak dan firmware, menguji koneksi cadangan, dan memeriksa baterai catu daya cadangan. Perawatan kecil yang konsisten mencegah kerusakan besar yang tidak terduga." },
  { type: "p", text: "Catat semua aset dalam daftar sederhana: jenis perangkat, merek, tanggal pembelian, lokasi, masa garansi, dan riwayat perbaikan. Daftar ini membantu Anda merencanakan penggantian sebelum perangkat rusak, mengajukan klaim garansi, dan mengetahui perangkat mana yang paling sering bermasalah. Penggantian terencana jauh lebih murah dan tenang daripada penggantian darurat di tengah hari sibuk." },
  { type: "p", text: "Jika Anda mengelola beberapa cabang, standarkan perangkat dan konfigurasi sejauh mungkin. Cabang dengan perangkat dan pengaturan seragam lebih mudah dirawat, dan karyawan yang berpindah cabang tidak perlu belajar ulang. Standarisasi juga memudahkan penyediaan suku cadang bersama." },
  { type: "h2", text: "Menyiapkan toko baru atau merombak toko lama" },
  { type: "p", text: "Untuk toko yang baru dibuka, perencanaan infrastruktur sebaiknya dimulai saat desain tata ruang, bukan setelah dekorasi selesai. Tentukan lokasi meja kasir, jalur kabel, titik daya, dan penempatan router sejak awal. Koordinasikan dengan kontraktor agar saluran kabel tertanam rapi, bukan ditempel belakangan." },
  { type: "p", text: "Untuk toko yang sudah berjalan, perbaikan bisa dilakukan bertahap. Mulai dari yang paling sering menimbulkan masalah: ganti router lama, tambahkan catu daya cadangan, rapikan kabel, dan siapkan koneksi cadangan. Catat gangguan yang terjadi dalam beberapa minggu untuk mengetahui sumber masalah yang sebenarnya sebelum mengeluarkan uang untuk solusi yang salah sasaran." },
  { type: "h2", text: "Langkah praktis memperkuat infrastruktur toko" },
  {
    type: "ol",
    items: [
      "Buat denah toko dan daftar semua perangkat yang perlu terhubung atau berdaya",
      "Evaluasi koneksi internet saat ini dan siapkan jalur cadangan dari penyedia berbeda",
      "Gunakan kabel untuk perangkat tetap, rapikan jaringan wifi, dan pisahkan jaringan tamu dari jaringan operasional",
      "Pastikan semua perangkat kompatibel dengan sistem kasir, dan siapkan unit cadangan untuk yang kritis",
      "Pasang perlindungan listrik dan catu daya cadangan pada perangkat inti",
      "Tulis prosedur gangguan, jadwalkan perawatan rutin, dan catat semua aset",
    ],
  },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Sistem kasir yang baik membutuhkan fondasi fisik yang baik. Investasi pada jaringan yang stabil, listrik yang terlindungi, perangkat yang tepat, dan prosedur yang jelas jarang terlihat oleh pelanggan, tetapi hasilnya dirasakan setiap hari berupa antrean yang lancar, data yang akurat, dan karyawan yang bekerja tenang. Sebaliknya, kelalaian pada fondasi ini baru terasa ketika sudah mahal." },
  { type: "p", text: "Jika toko Anda sedang berkembang atau berencana beralih ke sistem kasir baru, luangkan waktu menilai infrastruktur sebelum memilih perangkat lunak. Dengan fondasi yang kuat, fitur-fitur canggih di atasnya benar-benar dapat dimanfaatkan." },
  {
    type: "cta",
    title: "Ingin sistem kasir yang lancar dari perangkat hingga laporan?",
    text: "Tim AG·SORA membantu merancang sistem POS, memilih perangkat yang tepat, dan memastikan toko Anda siap melayani di jam tersibuk. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/pos",
    label: "Konsultasi gratis",
  },
];
