import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Begitu sebuah bisnis memutuskan menjual lewat website atau aplikasi, pertanyaan berikutnya hampir selalu sama: bagaimana pelanggan membayar? Di toko fisik, jawabannya sederhana, ada kasir dan uang berpindah tangan. Di dunia online, uang bergerak lewat beberapa pihak sekaligus: pelanggan, bank atau dompet digital, penyedia layanan pembayaran, dan akhirnya rekening bisnis Anda. Jembatan yang menghubungkan semuanya itu disebut payment gateway." },
  { type: "p", text: "Memasang payment gateway sekilas tampak seperti pekerjaan teknis semata, tetapi keputusannya menyentuh banyak aspek bisnis. Metode pembayaran yang tersedia memengaruhi seberapa banyak pelanggan menyelesaikan pesanan. Alur status transaksi menentukan apakah stok dan pesanan Anda tetap akurat. Cara dana dicairkan memengaruhi arus kas. Dan penanganan keamanan menentukan seberapa besar risiko yang Anda tanggung jika terjadi masalah." },
  { type: "p", text: "Artikel ini ditulis untuk pemilik bisnis dan pengambil keputusan, bukan untuk programmer. Kita membahas apa yang sebenarnya dilakukan payment gateway, cara memilih yang cocok, metode pembayaran yang perlu dipertimbangkan, bagaimana alur transaksi berjalan di balik layar, serta hal-hal yang sering terlewat seperti rekonsiliasi, refund, dan pengujian. Kami tidak menyebut tarif atau biaya tertentu karena berbeda antar penyedia dan berubah dari waktu ke waktu; selalu bandingkan syarat terbaru dari penyedia yang Anda pertimbangkan." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Payment gateway menghubungkan toko Anda dengan bank, dompet digital, dan jaringan kartu sehingga pembayaran bisa diterima dan dicatat otomatis",
      "Pilih penyedia berdasarkan metode pembayaran yang dipakai pelanggan Anda, kejelasan biaya, kecepatan pencairan, dan kualitas dokumentasi serta dukungannya",
      "Jangan percaya hanya pada halaman \"berhasil\" di browser; gunakan notifikasi server ke server untuk memastikan status pembayaran sebenarnya",
      "Siapkan rekonsiliasi, penanganan refund, dan pengujian di lingkungan percobaan sebelum membuka pembayaran sungguhan",
      "Biarkan data kartu ditangani penyedia terpercaya, jangan disimpan di server Anda sendiri",
    ],
  },
  { type: "h2", text: "Apa yang sebenarnya dilakukan payment gateway" },
  { type: "p", text: "Payment gateway adalah layanan yang menerima permintaan pembayaran dari website atau aplikasi Anda, meneruskannya ke pihak yang tepat seperti bank, dompet digital, atau jaringan kartu, lalu mengembalikan hasilnya. Anda tidak perlu menjalin kerja sama langsung dengan puluhan bank dan dompet digital satu per satu; penyedia gateway sudah menyediakan koneksi itu dalam satu pintu." },
  { type: "p", text: "Pada praktiknya, gateway menangani beberapa pekerjaan sekaligus. Ia menampilkan atau menyediakan antarmuka pembayaran, memverifikasi transaksi dengan pihak bank atau dompet digital, mencatat status pembayaran, dan mengirimkan kabar ke sistem Anda ketika pembayaran berhasil, gagal, atau kedaluwarsa. Sebagian penyedia juga mengurus pencairan dana ke rekening bisnis dan menyediakan laporan transaksi." },
  { type: "p", text: "Penting dipahami bahwa gateway berbeda dari rekening bank bisnis Anda. Gateway adalah perantara. Dana yang dibayar pelanggan biasanya ditampung dahulu oleh penyedia, lalu dicairkan ke rekening Anda sesuai jadwal dan ketentuan penyedia tersebut. Jadwal itu berpengaruh pada arus kas, jadi periksa dengan teliti sebelum memilih." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1553729459-efe14ef6055d",
    alt: "Tangan memegang setumpuk uang kertas",
    caption: "Di balik tombol bayar ada rantai panjang yang memastikan uang pelanggan tercatat tepat dan sampai ke rekening bisnis.",
  },
  { type: "h2", text: "Metode pembayaran yang perlu dipertimbangkan" },
  { type: "p", text: "Tidak semua pelanggan membayar dengan cara yang sama. Menyediakan metode yang akrab bagi pelanggan Anda sering kali lebih berpengaruh pada keberhasilan transaksi daripada desain tombolnya. Berikut beberapa kelompok metode yang umum ditawarkan gateway di Indonesia." },
  {
    type: "ul",
    items: [
      "Transfer bank atau virtual account: pelanggan mendapat nomor khusus untuk transfer, dan pembayaran dicocokkan otomatis oleh sistem",
      "Dompet digital: pembayaran lewat aplikasi dompet yang sudah dimiliki pelanggan",
      "QRIS: satu kode yang bisa dibaca banyak aplikasi pembayaran, praktis untuk pembayaran di layar maupun di tempat",
      "Kartu debit dan kredit: familier bagi sebagian pelanggan, dengan lapisan verifikasi tambahan dari bank",
      "Gerai ritel atau pembayaran tunai: berguna bagi pelanggan yang belum nyaman membayar secara digital",
      "Cicilan atau bayar nanti: dapat membantu pembelian bernilai besar, dengan syarat dan biaya tersendiri",
    ],
  },
  { type: "p", text: "Daripada menyalakan semua metode sekaligus, mulailah dari yang paling dipakai pelanggan Anda. Tanyakan langsung kepada pelanggan, atau lihat metode yang mereka pakai di saluran lain. Terlalu banyak pilihan bisa membingungkan, sementara terlalu sedikit membuat sebagian pelanggan mundur. Anda bisa menambah metode seiring bertambahnya data." },
  { type: "h3", text: "Biaya per metode bisa berbeda" },
  { type: "p", text: "Setiap metode pembayaran biasanya punya struktur biaya sendiri, misalnya biaya tetap per transaksi atau persentase dari nilai transaksi. Karena itu, hitung dampaknya terhadap margin Anda untuk tiap metode, terutama jika margin produk tipis. Beberapa bisnis memutuskan menyerap biaya, yang lain menaikkan harga sedikit, dan sebagian memberi pelanggan pilihan. Apa pun keputusannya, buatlah transparan agar tidak menimbulkan kejutan di akhir." },
  { type: "h2", text: "Cara memilih penyedia payment gateway" },
  { type: "p", text: "Memilih penyedia sebaiknya dilakukan dengan daftar kriteria, bukan hanya dari iklan atau rekomendasi teman. Kriteria berikut membantu membandingkan secara adil." },
  {
    type: "ol",
    items: [
      "Kesesuaian metode: apakah penyedia mendukung metode yang dipakai pelanggan Anda",
      "Kejelasan biaya: apakah semua biaya tercantum jelas, termasuk biaya pendaftaran, per transaksi, refund, dan pencairan",
      "Jadwal pencairan: berapa lama dana tiba di rekening Anda dan apakah ada batas minimum",
      "Dokumentasi dan alat pengembang: apakah panduan integrasinya jelas, tersedia lingkungan percobaan, dan ada pustaka untuk teknologi yang Anda pakai",
      "Keandalan dan dukungan: bagaimana rekam jejak ketersediaan layanan dan seberapa cepat tim dukungan merespons",
      "Fitur pendukung: tautan pembayaran, tagihan berulang, dasbor laporan, dan integrasi dengan platform toko yang Anda gunakan",
      "Persyaratan dokumen: dokumen legalitas apa yang diminta untuk akun bisnis dan berapa lama proses verifikasinya",
    ],
  },
  { type: "p", text: "Jika Anda memakai platform toko jadi, periksa terlebih dahulu penyedia mana yang sudah punya integrasi resmi di platform itu. Integrasi siap pakai biasanya lebih cepat dan murah daripada membangun dari nol. Jika Anda membangun aplikasi atau website custom, kualitas dokumentasi dan lingkungan percobaan menjadi pertimbangan yang jauh lebih penting karena tim pengembang akan bergantung padanya." },
  { type: "h3", text: "Proses verifikasi akun bisnis" },
  { type: "p", text: "Hampir semua penyedia meminta verifikasi sebelum akun bisa menerima pembayaran sungguhan. Proses ini biasanya mencakup data usaha, dokumen legalitas, dan rekening tujuan pencairan. Mulailah proses ini lebih awal, karena verifikasi bisa memakan waktu dan sering menjadi penghambat peluncuran yang tak disangka. Sambil menunggu, tim pengembang dapat bekerja di lingkungan percobaan." },
  { type: "h2", text: "Bagaimana alur pembayaran berjalan di balik layar" },
  { type: "p", text: "Memahami alur dasarnya membantu Anda mengajukan pertanyaan yang tepat kepada tim teknis atau vendor. Secara sederhana, satu transaksi online melewati beberapa tahap." },
  {
    type: "ol",
    items: [
      "Pelanggan menyelesaikan keranjang dan memilih metode pembayaran",
      "Sistem Anda membuat catatan pesanan dengan status menunggu pembayaran, lalu meminta gateway membuat transaksi",
      "Gateway mengembalikan tautan, kode, atau nomor pembayaran, dan pelanggan diarahkan untuk membayar",
      "Pelanggan membayar lewat bank, dompet digital, atau kartu",
      "Gateway menerima hasilnya dan mengirim notifikasi ke sistem Anda",
      "Sistem Anda memverifikasi notifikasi itu, mengubah status pesanan menjadi dibayar, mengurangi stok, dan memicu pengiriman",
    ],
  },
  { type: "p", text: "Tahap kelima dan keenam adalah yang paling sering salah dirancang. Banyak implementasi pemula hanya mengandalkan halaman \"pembayaran berhasil\" yang dilihat pelanggan di browser. Padahal pelanggan bisa menutup halaman sebelum kembali ke toko Anda, koneksi bisa putus, atau halaman itu bisa dipalsukan. Cara yang benar adalah mengandalkan notifikasi server ke server dari gateway, sering disebut webhook atau callback, sebagai sumber kebenaran status pembayaran." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1586880244406-556ebe35f282",
    alt: "Laptop menampilkan halaman beranda platform toko online",
    caption: "Banyak platform toko online menyediakan integrasi gateway siap pakai, yang bisa memangkas waktu peluncuran.",
  },
  { type: "h3", text: "Mengapa notifikasi server ke server penting" },
  { type: "p", text: "Notifikasi ini dikirim langsung dari sistem gateway ke sistem Anda, tidak lewat browser pelanggan, sehingga lebih bisa diandalkan. Sistem Anda perlu memverifikasi bahwa notifikasi itu benar-benar berasal dari gateway, misalnya dengan memeriksa tanda tangan atau token yang disepakati, lalu mencocokkan jumlah dan nomor pesanan. Notifikasi juga bisa terkirim lebih dari sekali atau datang tidak berurutan, jadi sistem harus dirancang agar memproses notifikasi yang sama berulang kali tidak menimbulkan efek ganda, misalnya mengirim barang dua kali." },
  {
    type: "callout",
    title: "Prinsip yang aman",
    text: "Anggap status pembayaran baru sah setelah dikonfirmasi oleh gateway lewat jalur server ke server, bukan karena pelanggan mengaku sudah membayar atau karena halaman tertentu terbuka di browsernya.",
  },
  { type: "h2", text: "Memahami status transaksi" },
  { type: "p", text: "Sebuah transaksi tidak hanya \"berhasil\" atau \"gagal\". Ada beberapa keadaan di antaranya, dan sistem Anda perlu siap menangani semuanya. Status yang umum meliputi menunggu pembayaran, berhasil, gagal, kedaluwarsa karena pelanggan tidak membayar sampai batas waktu, dibatalkan, dan dikembalikan sebagian atau penuh." },
  { type: "p", text: "Setiap status punya konsekuensi pada bisnis. Pesanan yang menunggu pembayaran biasanya menahan stok untuk sementara. Jika pelanggan tidak membayar sampai batas waktu, stok perlu dilepaskan kembali agar bisa dibeli orang lain. Pesanan yang gagal bayar sebaiknya memberi kesempatan mencoba kembali tanpa harus mengulang seluruh keranjang. Pesanan yang dikembalikan dananya perlu menyesuaikan stok dan catatan keuangan." },
  { type: "p", text: "Tentukan batas waktu pembayaran yang masuk akal. Terlalu pendek membuat pelanggan terburu-buru, terlalu panjang membuat stok tertahan lama untuk barang yang mungkin tidak jadi dibeli. Tidak ada angka yang cocok untuk semua; sesuaikan dengan jenis barang, ketersediaan stok, dan kebiasaan pelanggan Anda." },
  { type: "h2", text: "Pengalaman pembayaran yang meningkatkan konversi" },
  { type: "p", text: "Gateway yang terpasang dengan benar belum tentu menghasilkan penjualan jika pengalaman membayarnya buruk. Beberapa hal kecil berpengaruh besar. Tampilkan total biaya secara jelas sebelum pelanggan membayar, termasuk ongkos kirim dan biaya lain. Minimalkan jumlah langkah dan isian. Pastikan halaman pembayaran cepat dan nyaman di ponsel, karena banyak pelanggan membayar lewat ponsel." },
  { type: "p", text: "Pilihan antara halaman pembayaran milik gateway yang dialihkan dan formulir yang tertanam di situs Anda juga perlu dipertimbangkan. Halaman milik gateway lebih mudah dan lebih aman karena data sensitif tidak melewati server Anda, tetapi tampilannya kurang bisa disesuaikan. Formulir tertanam memberi kendali tampilan lebih besar, namun menambah tanggung jawab keamanan. Untuk kebanyakan bisnis kecil dan menengah, opsi yang dikelola penyedia adalah titik awal yang lebih aman." },
  { type: "h3", text: "Menangani pembayaran gagal" },
  { type: "p", text: "Pembayaran gagal adalah hal wajar: saldo kurang, koneksi terputus, atau verifikasi bank tidak lolos. Bedakan antara kegagalan yang bisa dicoba lagi dan yang tidak, lalu tampilkan pesan yang membantu, bukan sekadar \"terjadi kesalahan\". Berikan jalan keluar yang mudah, seperti mencoba metode lain atau menghubungi Anda, agar pelanggan tidak langsung pergi." },
  { type: "h2", text: "Keamanan: jangan simpan data kartu sendiri" },
  { type: "p", text: "Data kartu pembayaran adalah informasi yang sangat sensitif dan diatur ketat oleh standar industri. Menyimpan dan memprosesnya sendiri mengharuskan Anda memenuhi persyaratan keamanan yang berat. Karena itu, praktik yang dianjurkan bagi hampir semua bisnis adalah membiarkan penyedia gateway yang menangani data kartu, sehingga data itu tidak pernah menyentuh server Anda." },
  { type: "p", text: "Selain data kartu, ada beberapa praktik keamanan lain yang perlu diperhatikan. Simpan kunci rahasia dan token API di tempat yang aman, bukan di dalam kode yang terlihat publik atau di aplikasi di ponsel pelanggan. Pisahkan kunci untuk lingkungan percobaan dan lingkungan sungguhan. Batasi siapa saja yang punya akses ke dasbor gateway, aktifkan verifikasi dua langkah, dan tinjau akses secara berkala. Catat transaksi dan peristiwa penting agar mudah diselidiki jika ada kejanggalan." },
  { type: "p", text: "Aturan perlindungan data pribadi dan ketentuan pembayaran bisa berubah. Rujuklah ketentuan terbaru dari otoritas dan penyedia layanan Anda, dan jangan mengandalkan ringkasan yang mungkin sudah usang." },
  { type: "h2", text: "Rekonsiliasi: mencocokkan uang dan catatan" },
  { type: "p", text: "Rekonsiliasi adalah proses mencocokkan catatan transaksi di sistem Anda dengan laporan dari gateway dan dana yang benar-benar masuk ke rekening. Ini sering diabaikan sampai ada selisih yang sulit dilacak. Biasakan melakukannya secara rutin, misalnya harian atau mingguan tergantung volume transaksi." },
  { type: "p", text: "Hal yang perlu dicocokkan meliputi jumlah transaksi berhasil, total nilai, potongan biaya penyedia, refund, dan pencairan. Perhatikan bahwa dana yang masuk ke rekening biasanya sudah dipotong biaya dan dicairkan dalam satu paket untuk beberapa transaksi, sehingga mencocokkannya satu per satu butuh laporan rinci dari penyedia." },
  { type: "p", text: "Jika volume transaksi sudah besar, pertimbangkan mengotomatiskan rekonsiliasi. Sistem yang tersambung dengan data gateway dan modul keuangan bisa menandai selisih secara otomatis, sehingga tim keuangan hanya menangani pengecualian, bukan mencocokkan ratusan baris dengan tangan. Ini juga membantu menjaga laporan keuangan tetap akurat, sejalan dengan topik arus kas yang sering kami bahas di blog ini." },
  { type: "h2", text: "Refund, sengketa, dan layanan pelanggan" },
  { type: "p", text: "Tidak ada bisnis yang bebas dari pengembalian dana. Rancang alurnya sejak awal: siapa yang berwenang menyetujui, bagaimana refund dilakukan lewat gateway, berapa lama dana kembali ke pelanggan, dan bagaimana stok serta catatan keuangan disesuaikan. Beberapa metode pembayaran punya batasan atau waktu proses berbeda untuk refund, jadi sampaikan estimasi yang jujur kepada pelanggan." },
  { type: "p", text: "Sengketa atau klaim dari pemegang kartu, sering disebut chargeback, juga bisa terjadi untuk pembayaran kartu. Simpan bukti transaksi dan pengiriman yang rapi, seperti nota, resi, dan komunikasi dengan pelanggan, agar mudah menanggapi jika ada sengketa. Kebijakan yang jelas soal pengembalian dan pengiriman mengurangi kemungkinan sengketa sejak awal." },
  { type: "p", text: "Siapkan juga jalur bantuan yang mudah. Pelanggan yang sudah membayar tetapi belum menerima konfirmasi akan panik. Halaman status pesanan, email konfirmasi otomatis, dan kontak yang cepat ditanggapi menenangkan pelanggan dan mengurangi beban tim." },
  { type: "h2", text: "Menguji sebelum peluncuran" },
  { type: "p", text: "Hampir semua penyedia menyediakan lingkungan percobaan atau sandbox dengan data uji, sehingga Anda bisa mencoba seluruh alur tanpa memakai uang sungguhan. Manfaatkan itu secara menyeluruh. Uji bukan hanya skenario berhasil, tetapi juga pembayaran gagal, kedaluwarsa, notifikasi ganda, notifikasi terlambat, refund, dan pembayaran sebagian." },
  { type: "p", text: "Setelah lolos di lingkungan percobaan, lakukan uji terbatas dengan transaksi sungguhan bernilai kecil sebelum membuka untuk semua pelanggan. Pastikan seluruh rangkaian berjalan: pesanan tercatat, stok berkurang, email konfirmasi terkirim, dana tercatat di dasbor, dan laporan sesuai. Libatkan orang dari tim operasional dan keuangan, bukan hanya pengembang, karena merekalah yang akan memakai hasilnya sehari-hari." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d",
    alt: "Tangan mengetik di keyboard laptop",
    caption: "Pengujian yang teliti terhadap setiap skenario pembayaran lebih murah daripada memperbaiki masalah setelah pelanggan sungguhan terdampak.",
  },
  { type: "h2", text: "Kesalahan yang sering terjadi" },
  { type: "p", text: "Beberapa kesalahan berulang kali muncul pada proyek integrasi pembayaran. Mengandalkan halaman \"berhasil\" di browser sebagai bukti pembayaran adalah yang paling umum. Menyimpan kunci rahasia di tempat yang bisa dilihat publik adalah yang paling berbahaya. Tidak menangani notifikasi ganda sering menyebabkan pesanan atau pengiriman ganda. Tidak menyiapkan alur refund membuat tim kebingungan ketika permintaan pertama datang. Melewatkan rekonsiliasi membuat selisih kecil menumpuk menjadi masalah besar. Dan meluncurkan tanpa menguji skenario gagal membuat pelanggan menjadi penguji tanpa mereka sadari." },
  { type: "p", text: "Hampir semua kesalahan ini bisa dicegah dengan perencanaan yang cukup dan pengujian yang serius. Jika Anda bekerja dengan vendor atau tim pengembang, tanyakan secara spesifik bagaimana mereka menangani setiap poin di atas. Jawaban yang jelas dan rinci adalah tanda yang baik, sedangkan jawaban yang kabur patut diwaspadai." },
  { type: "h2", text: "Langkah praktis memulai" },
  {
    type: "ol",
    items: [
      "Daftar metode pembayaran yang dipakai pelanggan Anda, lalu bandingkan dua atau tiga penyedia berdasarkan kriteria di atas",
      "Mulai proses verifikasi akun bisnis lebih awal karena bisa memakan waktu",
      "Rancang alur status pesanan dari menunggu pembayaran sampai selesai, termasuk kedaluwarsa dan refund",
      "Pastikan integrasi memakai notifikasi server ke server dan memverifikasi keasliannya",
      "Uji semua skenario di lingkungan percobaan, lalu lakukan uji terbatas dengan transaksi kecil",
      "Jadwalkan rekonsiliasi rutin dan tentukan siapa yang bertanggung jawab",
    ],
  },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Payment gateway adalah salah satu komponen terpenting dalam bisnis online, karena di sinilah minat pelanggan berubah menjadi uang. Integrasi yang dirancang dengan baik membuat pembayaran terasa mulus bagi pelanggan, status pesanan tetap akurat, dan keuangan tertata. Integrasi yang asal-asalan menimbulkan pesanan yang salah status, selisih dana yang sulit dilacak, dan pelanggan yang kehilangan kepercayaan." },
  { type: "p", text: "Kabar baiknya, Anda tidak harus menguasai semua detail teknis. Cukup pahami prinsipnya, ajukan pertanyaan yang tepat, dan pastikan tim atau vendor Anda menjawabnya dengan jelas. Mulailah dari metode yang paling dipakai pelanggan, bangun alur yang andal, dan perluas seiring bisnis Anda tumbuh." },
  {
    type: "cta",
    title: "Butuh website atau aplikasi dengan pembayaran online yang andal?",
    text: "AG·SORA merancang dan membangun integrasi pembayaran yang aman, tersambung dengan stok, pesanan, dan laporan keuangan Anda. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
