import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Internet of Things, atau IoT, sering terdengar seperti urusan pabrik raksasa dan kota pintar. Padahal intinya sederhana: perangkat kecil yang mengukur sesuatu di dunia nyata, seperti suhu, gerakan, kelembapan, atau jumlah, lalu mengirim hasilnya lewat jaringan ke sistem yang bisa dibaca dan ditindaklanjuti. Bagi bisnis kecil dan menengah, teknologi ini kini cukup murah dan matang untuk menyelesaikan masalah sehari-hari yang sebelumnya dikerjakan dengan mata dan catatan tangan." },
  { type: "p", text: "Namun IoT juga penuh janji berlebihan. Banyak proyek berhenti setelah pemasangan sensor karena tidak ada yang tahu bagaimana memakai datanya, baterai habis tanpa ada yang memperhatikan, jaringan tidak stabil, atau keamanan diabaikan sehingga perangkat menjadi pintu masuk bagi pihak tak berwenang. Sensor bukan solusi; ia hanya sumber data. Nilainya muncul ketika data itu mengubah keputusan atau tindakan." },
  { type: "p", text: "Artikel ini membahas IoT dan sensor dari sudut pandang pemilik bisnis kecil. Kami membahas kasus yang masuk akal, komponen sistem, pilihan konektivitas dan daya, hubungan dengan aplikasi dan ERP, keamanan, biaya yang sering terlupa, serta cara memulai dengan uji coba kecil. Kami tidak memakai angka rekaan tentang penghematan atau pengembalian investasi; yang kami tawarkan adalah cara berpikir dan daftar periksa yang bisa Anda gunakan sebelum membeli perangkat apa pun." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Mulai dari masalah nyata yang bisa diukur dan berdampak pada uang, waktu, atau risiko, bukan dari perangkatnya",
      "Sistem IoT terdiri dari sensor, konektivitas, platform penyimpan data, dan aturan tindakan; semuanya harus dirancang bersama",
      "Pilih konektivitas dan sumber daya sesuai lokasi, jarak, dan seberapa sering data dibutuhkan",
      "Amankan perangkat sejak awal: kata sandi unik, pembaruan, dan pemisahan jaringan",
      "Uji coba pada skala kecil dengan ukuran keberhasilan yang jelas sebelum dipasang di seluruh lokasi",
    ],
  },
  { type: "h2", text: "Apa itu IoT dalam bahasa bisnis" },
  { type: "p", text: "Bayangkan seseorang yang setiap jam membuka pintu pendingin untuk memeriksa termometer lalu mencatatnya di buku. Pekerjaan itu membosankan, mudah terlewat, dan hanya memberi tahu bahwa suhu bermasalah setelah masalahnya terjadi. Sensor suhu yang mengirim bacaan secara berkala, menyimpannya, dan memberi peringatan ketika suhu keluar dari batas aman mengerjakan hal yang sama tanpa lelah, dan bisa memberi tahu sebelum barang rusak." },
  { type: "p", text: "Itulah inti IoT dalam konteks bisnis: mengubah pengamatan manual yang jarang dan berpotensi keliru menjadi pengukuran otomatis yang terus-menerus. Tiga manfaat yang paling sering muncul adalah visibilitas, otomatisasi, dan pencegahan. Visibilitas berarti Anda tahu apa yang terjadi di tempat yang tidak selalu Anda datangi. Otomatisasi berarti sistem melakukan tindakan sederhana sendiri. Pencegahan berarti masalah terdeteksi sebelum menjadi kerugian." },
  { type: "p", text: "Penting untuk diingat bahwa IoT hanya sebagian dari rantai. Sensor di ujung hanyalah titik awal. Yang menentukan nilai adalah apa yang terjadi setelah data diterima: siapa yang diberi tahu, tindakan apa yang diambil, dan apakah hasilnya dicatat untuk perbaikan berikutnya." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    alt: "Papan sirkuit elektronik dengan chip dan komponen, tampak dekat",
    caption: "Sensor dan papan sirkuit hanyalah awal; nilai muncul dari data yang diubah menjadi keputusan.",
  },
  { type: "h2", text: "Kasus penggunaan yang masuk akal untuk bisnis kecil" },
  { type: "p", text: "Kasus terbaik biasanya yang menjawab pertanyaan sederhana: apakah ada sesuatu yang keluar dari batas normal di tempat yang tidak bisa dipantau terus-menerus? Berikut beberapa kategori yang sering relevan, dengan penekanan pada masalah, bukan perangkat." },
  { type: "ul", items: [
    "Pemantauan suhu dan kelembapan untuk pendingin, gudang makanan, obat, atau barang sensitif, dengan peringatan bila keluar dari batas",
    "Pemantauan energi untuk melihat pola pemakaian listrik per area atau mesin dan menemukan pemborosan atau peralatan yang menyala tanpa perlu",
    "Pemantauan peralatan, seperti getaran, jam kerja, atau arus mesin, untuk memperkirakan kapan perlu perawatan sebelum rusak",
    "Penghitungan pengunjung atau antrean untuk memahami jam sibuk, mengatur jadwal pegawai, dan menilai efek promosi di toko fisik",
    "Pelacakan aset dan inventori memakai penanda atau pemindai untuk mengetahui letak dan jumlah barang berharga atau alat",
    "Pemantauan lingkungan, seperti kebocoran air, asap, atau pintu terbuka, di lokasi yang jarang dikunjungi",
    "Pertanian dan perikanan skala kecil, seperti kelembapan tanah, kualitas air, dan suhu kandang",
    "Pemantauan armada atau pengiriman untuk memantau lokasi dan kondisi kendaraan atau muatan tertentu",
  ] },
  { type: "p", text: "Uji setiap gagasan dengan tiga pertanyaan. Pertama, apakah ada kerugian atau biaya nyata dari masalah ini sekarang? Kedua, apakah data dari sensor akan mengubah keputusan atau tindakan seseorang? Ketiga, apakah ada cara yang lebih murah dan sama efektifnya, seperti prosedur sederhana atau perangkat lunak yang sudah ada? Jika jawabannya meragukan, tunda dulu. Sensor yang dipasang tanpa tujuan akan menjadi pajangan mahal." },
  { type: "h2", text: "Komponen sebuah sistem IoT" },
  { type: "p", text: "Sistem IoT sederhana terdiri dari beberapa lapisan. Memahami lapisan-lapisan ini membantu Anda menilai penawaran vendor dan menyadari bahwa membeli sensor hanyalah sebagian dari pekerjaan." },
  { type: "ol", items: [
    "Sensor dan perangkat: mengukur kondisi fisik dan, pada sebagian kasus, menggerakkan sesuatu seperti relai atau katup",
    "Konektivitas: cara perangkat mengirim data, melalui jaringan nirkabel lokal, jaringan seluler, atau jaringan khusus berdaya rendah",
    "Gerbang atau penghubung: perangkat perantara yang mengumpulkan data dari banyak sensor dan meneruskannya ke internet",
    "Platform data: tempat data disimpan, diolah, dan diakses, baik di layanan cloud maupun server sendiri",
    "Aturan dan peringatan: logika yang memutuskan kapan mengirim pemberitahuan atau memicu tindakan",
    "Antarmuka pengguna: dasbor, aplikasi, atau laporan yang dibaca dan ditindaklanjuti orang",
    "Integrasi: sambungan ke sistem lain, seperti ERP, sistem tiket pemeliharaan, atau aplikasi pesan",
  ] },
  { type: "p", text: "Banyak proyek gagal karena hanya memikirkan satu lapisan. Sensor murah yang tidak punya cara andal mengirim data, atau platform bagus yang tidak punya aturan tindakan, sama-sama tidak menyelesaikan masalah. Rancang dari ujung ke ujung: dari kejadian di lapangan sampai tindakan nyata dan pencatatannya." },
  { type: "h2", text: "Memilih konektivitas yang tepat" },
  { type: "p", text: "Konektivitas sering menjadi sumber masalah terbesar. Pilihan terbaik bergantung pada lokasi pemasangan, jarak, jumlah perangkat, kebutuhan frekuensi data, dan ketersediaan listrik. Tidak ada pilihan yang menang di semua situasi." },
  { type: "ul", items: [
    "Jaringan nirkabel lokal: mudah dan murah untuk lokasi dalam bangunan dengan sinyal baik, tetapi menguras daya dan sinyal bisa tidak stabil di area luas atau berpenghalang",
    "Jaringan seluler: menjangkau tempat tanpa jaringan lokal dan cocok untuk perangkat bergerak, tetapi ada biaya langganan dan konsumsi daya lebih besar",
    "Jaringan berdaya rendah jarak jauh: cocok untuk sensor sederhana yang mengirim data kecil dan jarang dengan baterai bertahan lama, tetapi memerlukan infrastruktur dan terbatas untuk data besar",
    "Koneksi kabel: paling stabil dan mengalirkan daya sekaligus pada sebagian teknologi, tetapi pemasangannya lebih sulit dan mahal",
    "Perangkat dengan penyimpanan lokal: mencatat data sendiri dan mengirim berkala, berguna ketika koneksi sering putus",
  ] },
  { type: "p", text: "Pikirkan apa yang terjadi saat koneksi putus. Sensor yang baik menyimpan data sementara dan mengirimkannya saat jaringan kembali, sehingga tidak ada celah pada catatan. Untuk pemantauan yang menyangkut keselamatan atau kerugian besar, pertimbangkan jalur peringatan cadangan atau sinyal lokal seperti bunyi alarm di tempat, bukan hanya pemberitahuan lewat internet." },
  { type: "h3", text: "Daya: baterai, listrik, atau panel surya" },
  { type: "p", text: "Sumber daya menentukan kemudahan perawatan. Perangkat berdaya listrik tetap tidak merepotkan tetapi membutuhkan stopkontak dan kabel. Perangkat berbaterai fleksibel dalam penempatan, tetapi baterai akan habis dan harus diganti, dan baterai yang mati diam-diam adalah penyebab paling umum sensor berhenti melapor tanpa ada yang sadar. Rancang pemantauan kesehatan perangkat itu sendiri: peringatan ketika baterai lemah atau sensor berhenti mengirim data lebih lama dari wajar." },
  { type: "h2", text: "Dari data sensor menjadi tindakan" },
  { type: "p", text: "Data mentah dari sensor nyaris tidak berguna bagi pemilik bisnis. Angka suhu setiap menit selama sebulan hanyalah tumpukan angka. Yang berguna adalah ringkasan dan peringatan: berapa lama suhu di atas batas kemarin, kapan pintu pendingin paling sering terbuka, atau mesin mana yang berjalan di luar pola normal." },
  { type: "ol", items: [
    "Tentukan kondisi yang dianggap normal dan batas yang berarti masalah, bersama orang yang paham bidangnya",
    "Tetapkan siapa yang diberi tahu untuk tiap jenis peringatan dan lewat saluran apa",
    "Tetapkan tindakan baku yang harus diambil ketika peringatan datang, dan siapa yang bertanggung jawab",
    "Atur peringatan agar tidak terlalu sering sehingga diabaikan, dengan syarat durasi dan ambang bertahap",
    "Catat setiap kejadian beserta tindakan yang diambil untuk bahan evaluasi dan, bila perlu, bukti kepatuhan",
    "Tinjau data secara berkala untuk menemukan pola dan peluang perbaikan, bukan hanya bereaksi pada alarm",
  ] },
  { type: "p", text: "Pada sebagian kasus, sistem dapat bertindak otomatis, misalnya mematikan peralatan ketika terdeteksi kebocoran atau menyalakan pendingin cadangan ketika suhu naik. Otomatisasi seperti ini sangat bernilai tetapi juga membawa risiko: aturan yang salah atau data yang keliru dapat memicu tindakan yang merugikan. Mulailah dengan peringatan kepada manusia, lalu otomatiskan setelah sistem terbukti andal, dan selalu sediakan cara mengambil alih secara manual." },
  { type: "callout", title: "Sensor tanpa tindakan hanyalah biaya", text: "Sebelum memasang perangkat, tuliskan siapa yang akan menerima peringatan, tindakan apa yang diambil, dan bagaimana mengetahui bahwa tindakan itu berhasil. Jika tidak ada jawabannya, pasang nanti." },
  { type: "h2", text: "Menghubungkan IoT dengan aplikasi dan ERP" },
  { type: "p", text: "Nilai IoT melipat ketika datanya terhubung dengan sistem bisnis. Peringatan perawatan dari sensor mesin dapat membuat tiket kerja otomatis di sistem pemeliharaan. Data suhu penyimpanan dapat dilampirkan pada catatan batch di ERP sebagai bukti kondisi barang. Jumlah pengunjung dapat dibandingkan dengan transaksi kasir untuk menghitung tingkat pembelian. Tanpa sambungan itu, data sensor menjadi pulau terpisah yang dibaca seseorang di layar lain." },
  { type: "ul", items: [
    "Gunakan antarmuka pemrograman yang terdokumentasi dan format data yang umum agar mudah terhubung",
    "Pastikan setiap perangkat dan lokasi memiliki identitas yang konsisten dengan data induk di ERP",
    "Tentukan seberapa rinci dan sering data perlu diteruskan ke sistem bisnis; tidak semua pembacaan perlu disimpan di ERP",
    "Pisahkan data mentah volume tinggi dari ringkasan yang relevan bagi proses bisnis",
    "Catat dari mana tiap data berasal dan versi aturan yang menghasilkannya agar bisa ditelusuri",
  ] },
  { type: "p", text: "Bila Anda berencana mengembangkan aplikasi seluler untuk teknisi atau pengawas lapangan, IoT dan aplikasi saling melengkapi. Teknisi menerima peringatan di ponsel, melihat riwayat sensor, mengonfirmasi tindakan, dan memotret hasil perbaikan. Semua tercatat dan terhubung ke perangkat yang sama sehingga riwayatnya utuh." },
  { type: "h2", text: "Keamanan: perangkat kecil, risiko besar" },
  { type: "p", text: "Perangkat IoT sering diabaikan dalam urusan keamanan karena tampak sepele, padahal justru sering menjadi titik terlemah. Perangkat dengan kata sandi bawaan yang tidak diganti, perangkat lunak yang tidak pernah diperbarui, atau jaringan yang terbuka dapat dimanfaatkan penyerang untuk masuk ke jaringan bisnis atau dipakai menyerang pihak lain. Karena banyak sensor dipasang lalu dilupakan, celah ini bisa bertahan bertahun-tahun." },
  { type: "ul", items: [
    "Ganti semua kata sandi bawaan dan gunakan kredensial unik untuk tiap perangkat atau kelompok",
    "Pisahkan perangkat IoT pada jaringan tersendiri sehingga tidak bisa menjangkau komputer kasir atau data keuangan",
    "Pilih perangkat dari pembuat yang menyediakan pembaruan keamanan dan jelaskan sampai kapan dukungannya",
    "Pastikan data dikirim dengan enkripsi dan akses ke platform dilindungi autentikasi berlapis",
    "Nonaktifkan layanan dan port yang tidak diperlukan pada perangkat dan gerbang",
    "Buat inventaris perangkat dan jadwalkan pemeriksaan serta pembaruan berkala",
    "Rencanakan cara menonaktifkan atau mengganti perangkat yang hilang, rusak, atau dicurigai disusupi",
  ] },
  { type: "p", text: "Pertimbangkan juga privasi. Sensor yang menghitung orang atau merekam gambar dan suara menyangkut data pribadi. Beri tahu pihak yang terdampak, kumpulkan hanya yang diperlukan, dan periksa ketentuan perlindungan data pribadi yang berlaku saat ini. Alternatif yang lebih ramah privasi, seperti penghitungan anonim tanpa menyimpan gambar, sering tersedia dan cukup untuk tujuan bisnis." },
  { type: "h2", text: "Biaya yang sering terlupakan" },
  { type: "p", text: "Harga perangkat hanya sebagian kecil dari biaya sebenarnya. Banyak proyek meleset dari anggaran karena komponen biaya lain tidak diperhitungkan sejak awal. Susun perkiraan biaya total selama beberapa tahun, bukan hanya biaya pembelian." },
  { type: "ul", items: [
    "Perangkat dan aksesori, termasuk cadangan untuk penggantian",
    "Pemasangan, kabel, dan penyesuaian di lokasi, yang sering lebih mahal daripada perangkatnya",
    "Konektivitas: biaya langganan seluler, penyedia jaringan, atau peningkatan jaringan lokal",
    "Platform dan penyimpanan data, yang biasanya ditagih menurut jumlah perangkat atau volume data",
    "Pengembangan dasbor, aturan peringatan, dan integrasi dengan sistem lain",
    "Perawatan: penggantian baterai, kalibrasi sensor, pembaruan perangkat lunak, dan perbaikan",
    "Waktu tim untuk menanggapi peringatan dan meninjau data",
    "Pelatihan dan penyesuaian prosedur kerja",
  ] },
  { type: "p", text: "Bandingkan biaya total itu dengan nilai yang dilindungi atau dihasilkan, tetapi berhati-hatilah dengan klaim penghematan yang terlalu optimistis. Hitung dari masalah nyata yang sudah Anda alami, seperti kerugian barang rusak yang pernah terjadi atau jam kerja yang dihabiskan untuk pengecekan manual, bukan dari angka rata-rata industri yang belum tentu berlaku bagi Anda." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    alt: "Meja kerja dengan sketsa rancangan teknik, kotak perkakas, dan seseorang yang menggambar",
    caption: "Perencanaan di atas kertas sebelum membeli perangkat menghemat banyak biaya perubahan di lapangan.",
  },
  { type: "h2", text: "Memulai dengan uji coba kecil" },
  { type: "p", text: "Cara paling aman memulai IoT adalah dengan uji coba terbatas yang dirancang untuk belajar. Pilih satu masalah yang jelas dan satu lokasi atau beberapa perangkat. Tentukan sejak awal bagaimana Anda akan menilai keberhasilannya dan berapa lama uji coba berlangsung. Uji coba yang baik menjawab pertanyaan: apakah data ini andal, apakah orang bertindak berdasarkan data itu, dan apakah manfaatnya sepadan dengan biaya dan upaya." },
  { type: "ol", items: [
    "Pilih satu masalah dengan dampak jelas dan penanggung jawab yang bersedia",
    "Tentukan ukuran keberhasilan yang konkret, misalnya jumlah kejadian yang terdeteksi lebih awal dibanding sebelumnya",
    "Pasang sejumlah kecil perangkat dan catat kendala: sinyal, daya, penempatan, dan kalibrasi",
    "Jalankan beberapa minggu sambil membandingkan dengan cara lama untuk menguji keakuratan",
    "Kumpulkan masukan dari orang yang menerima peringatan tentang kegunaan dan gangguannya",
    "Putuskan: perluas, ubah, atau hentikan, berdasarkan bukti dari uji coba",
  ] },
  { type: "p", text: "Pilih vendor yang bersedia menjelaskan sistem secara jujur, termasuk batasannya. Waspadai janji bahwa satu perangkat dapat menyelesaikan segala hal. Mintalah demonstrasi pada kondisi nyata lokasi Anda, bukan hanya di ruang pamer, dan tanyakan apa yang terjadi bila vendor berhenti beroperasi atau perangkat tidak lagi didukung. Hindari terkunci pada format tertutup yang menyulitkan Anda berpindah." },
  { type: "h2", text: "Memelihara sistem setelah terpasang" },
  { type: "p", text: "IoT bukan proyek sekali pasang. Sensor bergeser dari kalibrasinya, baterai habis, kabel rusak, firmware perlu diperbarui, dan lingkungan berubah. Tanpa pemeliharaan, data yang awalnya andal pelan-pelan menjadi menyesatkan, dan itu lebih berbahaya daripada tidak ada data karena memberi rasa aman palsu." },
  { type: "ul", items: [
    "Tetapkan penanggung jawab perangkat dan jadwal pemeriksaan fisik berkala",
    "Pantau kesehatan perangkat: baterai, kekuatan sinyal, dan terakhir kali mengirim data",
    "Kalibrasi ulang sensor sesuai anjuran pembuat dan catat tanggalnya",
    "Siapkan suku cadang dan prosedur penggantian cepat untuk perangkat kritis",
    "Perbarui perangkat lunak secara terencana dan uji sebelum diterapkan luas",
    "Tinjau secara berkala apakah sensor dan aturan peringatan masih sesuai kebutuhan bisnis",
  ] },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Membeli perangkat sebelum menentukan masalah dan tindakan yang akan diambil",
    "Mengabaikan konektivitas dan daya sampai perangkat sudah terpasang",
    "Mengirim terlalu banyak peringatan sehingga semuanya diabaikan",
    "Membiarkan kata sandi bawaan dan perangkat lunak tidak diperbarui",
    "Tidak memantau kesehatan sensor sehingga data basi tidak disadari",
    "Memasang di seluruh lokasi sekaligus tanpa uji coba",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Tuliskan tiga masalah operasional yang saat ini diatasi dengan pengecekan manual atau baru diketahui setelah terlambat",
    "Pilih satu dengan dampak terbesar dan tentukan siapa yang akan bertindak atas datanya",
    "Tentukan kondisi normal, batas masalah, dan tindakan baku ketika batas terlampaui",
    "Kunjungi lokasi pemasangan untuk memeriksa sinyal, listrik, dan kondisi fisik",
    "Rancang uji coba kecil beberapa minggu dengan ukuran keberhasilan yang jelas",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "IoT dan sensor dapat memberi bisnis kecil kemampuan yang dulu hanya dimiliki perusahaan besar: melihat apa yang terjadi di lapangan secara terus-menerus dan bereaksi sebelum masalah membesar. Namun nilainya tidak datang dari perangkat, melainkan dari masalah yang jelas, rancangan dari ujung ke ujung, keamanan yang diperhatikan, dan pemeliharaan yang konsisten." },
  { type: "p", text: "Mulailah dari satu masalah nyata, uji dalam skala kecil, dan hubungkan datanya dengan tindakan dan sistem bisnis Anda. Dengan begitu teknologi ini menjadi alat yang bekerja untuk Anda, bukan kumpulan perangkat yang dipasang lalu dilupakan." },
  {
    type: "cta",
    title: "Ingin menghubungkan data lapangan dengan aplikasi dan sistem bisnis Anda?",
    text: "Tim AG·SORA membangun aplikasi, dasbor, dan integrasi yang mengubah data sensor menjadi peringatan dan tindakan yang bisa dipakai tim Anda. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/custom-software",
    label: "Konsultasi gratis",
  },
];
