import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Banyak pemilik toko online menghabiskan waktu berminggu-minggu memilih tema tampilan, warna, dan logo, tetapi hanya beberapa jam menyusun katalog produk. Padahal katalog adalah inti dari toko online. Pelanggan datang untuk menemukan barang, membandingkannya, dan memutuskan membeli. Jika nama produk tidak konsisten, foto tidak seragam, varian membingungkan, atau stok tidak sinkron, tampilan secantik apa pun tidak akan menyelamatkan penjualan." },
  { type: "p", text: "Katalog yang rapi juga bukan sekadar urusan tampilan. Data produk mengalir ke banyak tempat: halaman toko, pencarian internal, mesin pencari, marketplace, sistem kasir, gudang, laporan keuangan, hingga iklan. Satu kesalahan di data produk, misalnya kode barang ganda, akan menyebar ke semua tempat itu dan sulit dibersihkan ketika jumlah produk sudah ratusan atau ribuan." },
  { type: "p", text: "Artikel ini membahas cara membangun katalog produk yang terstruktur untuk toko online dan aplikasi belanja. Kami membahas model data produk, penamaan, kategori dan atribut, varian, foto dan deskripsi, harga dan stok, serta cara merawat katalog dari waktu ke waktu. Kami tidak memakai angka rekaan tentang peningkatan penjualan; yang kami tawarkan adalah prinsip dan daftar periksa yang bisa diterapkan pada toko dengan skala apa pun." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Pisahkan produk (apa yang dijual) dari varian (ukuran, warna, kemasan) dan dari kode stok yang dihitung gudang",
      "Gunakan kode barang yang unik, stabil, dan tidak pernah dipakai ulang untuk barang lain",
      "Tentukan aturan penamaan dan atribut sebelum mengunggah produk dalam jumlah besar",
      "Foto dan deskripsi harus menjawab pertanyaan pelanggan yang tidak bisa menyentuh barangnya",
      "Satu sumber data produk yang dipakai bersama oleh toko, kasir, dan gudang mencegah selisih",
    ],
  },
  { type: "h2", text: "Mengapa katalog menentukan hasil toko online" },
  { type: "p", text: "Di toko fisik, pelanggan bisa memegang barang, bertanya kepada pramuniaga, dan melihat rak sebelah. Di toko online, semua itu digantikan oleh data produk. Foto menggantikan sentuhan, deskripsi menggantikan penjelasan pramuniaga, filter dan kategori menggantikan lorong rak. Artinya kualitas data produk adalah kualitas pelayanan Anda." },
  { type: "p", text: "Ada tiga dampak langsung dari katalog yang buruk. Pertama, pelanggan tidak menemukan barang yang sebenarnya tersedia karena nama atau kategorinya tidak sesuai kata yang mereka cari. Kedua, pelanggan ragu membeli karena informasi tidak lengkap, misalnya ukuran, bahan, atau kompatibilitas tidak dijelaskan. Ketiga, tim internal menghabiskan waktu menjawab pertanyaan berulang dan memperbaiki pesanan yang salah kirim akibat varian yang membingungkan." },
  { type: "p", text: "Dampak tidak langsungnya sama penting. Mesin pencari membaca nama, deskripsi, dan struktur halaman produk. Katalog yang konsisten membuat halaman lebih mudah dipahami dan dibedakan satu sama lain. Sebaliknya, ratusan halaman dengan deskripsi hampir sama akan bersaing satu sama lain dan mengaburkan sinyal yang ingin Anda kirim." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da",
    alt: "Tas belanja merah dan hitam berjajar di atas latar gelap",
    caption: "Pelanggan online tidak bisa memegang barang; data produk yang rapi menjadi pengganti etalase.",
  },
  { type: "h2", text: "Memahami model data produk" },
  { type: "p", text: "Kesalahan paling umum dalam menyusun katalog adalah memperlakukan semuanya sebagai satu daftar datar. Satu kaus dalam lima ukuran dan empat warna lalu tercatat sebagai dua puluh produk terpisah dengan nama hampir sama. Akibatnya halaman toko dipenuhi duplikat, ulasan terpecah, dan pencarian menampilkan hasil berulang." },
  { type: "p", text: "Model yang lebih sehat membedakan tiga lapisan. Lapisan pertama adalah produk induk: konsep barang yang dijual, lengkap dengan nama, deskripsi umum, kategori, dan foto utama. Lapisan kedua adalah varian: kombinasi pilihan yang bisa dibeli, seperti ukuran dan warna, masing-masing dengan harga, foto, dan stok sendiri bila perlu. Lapisan ketiga adalah unit stok yang dihitung di gudang, yang biasanya satu-satu dengan varian tetapi bisa berbeda ketika ada paket atau satuan kemasan." },
  { type: "p", text: "Dengan pemisahan ini, halaman toko menampilkan satu produk dengan pilihan varian, ulasan terkumpul di satu tempat, dan stok dihitung per varian. Kasir di toko fisik memindai kode varian yang sama sehingga stok online dan offline berasal dari sumber yang sama. Bila Anda memakai sistem ERP atau kasir, pastikan struktur ini cocok dengan cara sistem tersebut menyimpan barang sebelum mulai mengimpor data." },
  { type: "h3", text: "Produk paket dan bundel" },
  { type: "p", text: "Paket, misalnya satu set perlengkapan berisi tiga barang, perlu perlakuan khusus. Tentukan apakah paket memiliki stok sendiri atau stoknya diturunkan dari komponen. Jika diturunkan, penjualan satu paket harus mengurangi stok tiap komponen, dan stok paket yang ditampilkan adalah jumlah paket lengkap yang masih bisa dirakit. Tanpa aturan ini, toko bisa menjual paket yang komponennya sudah habis." },
  { type: "h2", text: "Kode barang yang unik dan stabil" },
  { type: "p", text: "Kode barang atau SKU adalah kunci yang menghubungkan semua sistem. Karena itu aturannya harus ketat. Setiap varian memiliki satu kode yang unik, tidak berubah selama barang itu ada, dan tidak pernah dipakai ulang untuk barang lain meskipun barang lama sudah dihentikan. Memakai ulang kode membuat riwayat penjualan, stok, dan laporan keuangan bercampur antara dua barang berbeda." },
  { type: "p", text: "Hindari kode yang mengandung informasi yang bisa berubah, misalnya harga atau nama pemasok, karena begitu informasinya berubah kode menjadi menyesatkan. Kode yang terlalu panjang dan rumit juga menyulitkan petugas gudang saat memasukkan manual. Banyak bisnis memilih kombinasi singkat yang menandai kelompok barang dan nomor urut, lalu menyimpan atribut lain di kolom terpisah." },
  { type: "p", text: "Barcode adalah hal terpisah dari SKU. Satu varian bisa memiliki beberapa barcode, misalnya barcode pabrikan dan barcode internal. Simpan keduanya dan hubungkan ke kode varian yang sama, agar pemindaian di kasir dan gudang selalu menemukan barang yang benar." },
  { type: "h2", text: "Aturan penamaan yang konsisten" },
  { type: "p", text: "Nama produk dibaca oleh pelanggan, oleh pencarian internal toko, dan oleh mesin pencari. Susunan nama yang konsisten membuat ketiganya bekerja lebih baik. Tentukan pola yang sama untuk seluruh katalog, misalnya jenis barang diikuti merek, model, dan ciri pembeda utama, sedangkan ukuran dan warna ditaruh sebagai varian, bukan di dalam nama." },
  { type: "p", text: "Tulis nama dengan kata yang dipakai pelanggan, bukan istilah internal. Singkatan gudang, kode pemasok, dan istilah teknis yang hanya dipahami tim sebaiknya tidak muncul di halaman publik. Jika ada dua sebutan yang sama-sama umum, masukkan yang kedua ke deskripsi atau kolom kata kunci pencarian agar tetap ditemukan." },
  { type: "p", text: "Konsistensi juga mencakup huruf kapital, tanda baca, dan satuan. Memilih satu cara menulis, misalnya satuan berat selalu dalam bentuk yang sama, tampak sepele tetapi menghemat banyak waktu saat penyaringan dan impor data. Tulis aturan itu dalam satu dokumen pendek yang dipegang siapa pun yang menambah produk." },
  { type: "h2", text: "Kategori dan atribut yang memudahkan pencarian" },
  { type: "p", text: "Kategori menjawab pertanyaan di mana pelanggan mencari barang. Atribut menjawab bagaimana mereka menyaringnya. Keduanya sebaiknya dirancang dari sudut pandang pelanggan, bukan dari struktur gudang atau pemasok. Seorang pembeli yang mencari perlengkapan dapur tidak peduli barang itu dipasok oleh divisi mana." },
  { type: "p", text: "Jaga kedalaman kategori tetap dangkal. Dua sampai tiga tingkat biasanya cukup. Kategori yang terlalu dalam membuat pelanggan harus mengklik berkali-kali, sedangkan kategori yang terlalu lebar tanpa penyaring membuat daftar tak berujung. Gunakan atribut seperti ukuran, bahan, merek, kisaran harga, dan kompatibilitas sebagai penyaring, bukan membuat kategori baru untuk setiap kombinasi." },
  { type: "ol", items: [
    "Tentukan kategori utama dari kebiasaan belanja pelanggan, bukan dari struktur internal perusahaan",
    "Tetapkan daftar atribut baku untuk tiap kategori dan jenis nilainya (angka, pilihan, atau teks bebas)",
    "Gunakan pilihan tertutup untuk atribut yang akan dipakai sebagai penyaring agar nilainya seragam",
    "Izinkan satu produk muncul di lebih dari satu kategori bila memang relevan, tanpa menggandakan datanya",
    "Tinjau kategori secara berkala dan gabungkan yang jarang dipakai",
  ] },
  { type: "p", text: "Atribut bernilai bebas seperti kolom teks yang diisi sesuka hati cepat menjadi sumber kekacauan. Satu tim bisa menulis warna dengan lima ejaan berbeda sehingga penyaring tidak bekerja. Pilihan tertutup memastikan satu nilai selalu ditulis dengan cara yang sama." },
  { type: "h2", text: "Foto produk yang menjawab keraguan" },
  { type: "p", text: "Foto adalah pengganti sentuhan pelanggan. Foto yang baik menunjukkan barang dari beberapa sudut, memperlihatkan ukuran relatif terhadap benda yang dikenal, dan menampilkan detail yang penting bagi keputusan, seperti tekstur, sambungan, atau label. Latar yang bersih dan pencahayaan yang konsisten membuat katalog terlihat profesional dan memudahkan perbandingan antarproduk." },
  { type: "p", text: "Seragamkan rasio dan ukuran gambar agar tampilan daftar produk tidak melompat-lompat. Beri nama berkas yang bermakna, isi teks alternatif yang menjelaskan isi gambar, dan kompres gambar secukupnya agar halaman tetap cepat dimuat. Halaman yang lambat membuat pelanggan pergi sebelum sempat melihat foto yang Anda siapkan dengan susah payah." },
  { type: "p", text: "Foto varian sebaiknya dikaitkan dengan varian yang sesuai, sehingga ketika pelanggan memilih warna tertentu gambar ikut berganti. Jangan menampilkan foto warna biru untuk varian merah hanya karena belum sempat difoto. Ketidaksesuaian antara foto dan barang yang tiba adalah salah satu penyebab retur yang paling mudah dicegah." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2",
    alt: "Ponsel yang menampilkan aplikasi belanja online di atas meja",
    caption: "Sebagian besar pelanggan membuka katalog dari ponsel, jadi foto dan teks harus nyaman dibaca di layar kecil.",
  },
  { type: "h2", text: "Deskripsi yang informatif, bukan sekadar menarik" },
  { type: "p", text: "Deskripsi yang baik menjawab pertanyaan yang akan diajukan pelanggan kepada pramuniaga jika mereka berdiri di depan rak. Untuk apa barang ini, terbuat dari apa, ukurannya berapa, bagaimana merawatnya, apa isi kemasan, dan apa yang tidak termasuk. Tulis hal yang pasti dulu, baru kalimat yang membangun suasana." },
  { type: "p", text: "Pisahkan teks menjadi bagian yang mudah dipindai: ringkasan singkat di atas, daftar spesifikasi, lalu keterangan tambahan. Orang jarang membaca paragraf panjang pada halaman produk; mereka memindai mencari satu informasi tertentu. Daftar spesifikasi yang rapi juga memudahkan perbandingan antarbarang." },
  { type: "p", text: "Hindari menyalin deskripsi pemasok apa adanya. Selain terdengar sama dengan toko lain, mesin pencari cenderung memperlakukannya sebagai konten duplikat. Tambahkan informasi yang benar-benar berguna dari pengalaman Anda sendiri, seperti saran penggunaan atau perbandingan dengan produk serupa di toko Anda." },
  { type: "p", text: "Jangan menjanjikan hal yang tidak bisa dipenuhi. Klaim berlebihan tentang manfaat atau kualitas hanya memancing retur dan ulasan buruk. Untuk produk yang diatur ketentuan tertentu, seperti makanan, kosmetik, atau perangkat elektronik, periksa aturan label dan klaim yang berlaku saat ini dari pihak berwenang dan jangan mengandalkan ingatan." },
  { type: "h2", text: "Harga, promo, dan stok yang bisa dipercaya" },
  { type: "p", text: "Harga dan stok adalah dua data yang paling cepat berubah dan paling merusak kepercayaan bila salah. Pelanggan yang membayar lalu diberi tahu barang habis akan kecewa jauh lebih dalam daripada pelanggan yang sejak awal melihat tulisan stok habis. Karena itu, stok yang tampil di toko harus berasal dari sumber yang sama dengan stok yang dipakai gudang dan kasir." },
  { type: "p", text: "Pisahkan harga normal, harga promo, dan periode berlakunya. Promo yang disimpan dengan menimpa harga normal sering lupa dikembalikan. Dengan menyimpan promo sebagai aturan bertanggal, harga kembali otomatis ketika periode berakhir, dan laporan bisa membandingkan penjualan sebelum, selama, dan sesudah promo." },
  { type: "p", text: "Tentukan juga kebijakan stok pengaman untuk barang yang dijual di beberapa kanal sekaligus. Jika toko fisik, toko online, dan marketplace berbagi stok, sinkronisasi yang terlambat bisa menyebabkan barang terakhir terjual dua kali. Sisihkan sebagian stok kecil sebagai penyangga, atau pastikan pembaruan stok berlangsung cukup cepat untuk barang yang laris." },
  { type: "h2", text: "Satu sumber data untuk semua kanal" },
  { type: "p", text: "Masalah terbesar katalog yang berkembang adalah data yang hidup di banyak tempat: satu lembar kerja untuk toko online, satu daftar di sistem kasir, satu catatan lagi di gudang. Setiap perubahan harus dilakukan berkali-kali, dan cepat atau lambat ketiganya berbeda." },
  { type: "p", text: "Tentukan satu sistem sebagai sumber kebenaran data produk, lalu biarkan sistem lain membaca atau menerima salinannya secara otomatis. Dalam banyak bisnis, sumber itu adalah ERP atau sistem manajemen produk; pada toko yang lebih kecil, bisa berupa platform toko online itu sendiri asalkan kasir dan gudang terhubung ke sana. Yang penting adalah arah aliran data jelas dan tidak ada dua orang yang mengedit hal yang sama di dua tempat." },
  { type: "p", text: "Jika Anda menjual juga di marketplace, ketahui bahwa tiap marketplace memiliki aturan kategori, atribut wajib, dan batasan judul sendiri. Sebaiknya simpan data induk yang lengkap di sistem Anda, lalu buat tampilan terpisah per kanal yang menyesuaikan batasan tiap marketplace tanpa mengubah data induk." },
  { type: "callout", title: "Satu barang, satu identitas", text: "Setiap varian cukup memiliki satu kode unik yang dipakai oleh toko online, kasir, gudang, dan laporan. Begitu satu barang punya dua identitas, selisih stok hanya soal waktu." },
  { type: "h2", text: "Migrasi dan pembersihan katalog yang sudah ada" },
  { type: "p", text: "Jika katalog Anda sudah berantakan, memperbaikinya tidak harus berarti mengulang dari nol. Mulailah dengan mengekspor seluruh data produk ke satu tabel dan memeriksa pola masalahnya: kode ganda, nama tidak konsisten, kategori kosong, foto hilang, atau atribut yang tidak terisi. Kelompokkan masalah menurut jenisnya sehingga perbaikan bisa dilakukan secara massal." },
  { type: "p", text: "Urutkan pekerjaan berdasarkan dampak. Barang terlaris dan barang dengan margin terbesar dibereskan lebih dulu karena memberi hasil paling cepat. Barang yang jarang terjual dan hampir pasti akan dihentikan tidak perlu dipoles; sebaiknya diarsipkan atau dihapus dari tampilan. Katalog yang lebih kecil dan rapi sering menghasilkan lebih baik daripada katalog besar yang setengah terawat." },
  { type: "p", text: "Lakukan impor dalam kelompok kecil dan periksa hasilnya sebelum melanjutkan. Mengimpor ribuan baris sekaligus tanpa pengujian sering menimbulkan kesalahan massal yang sulit ditarik kembali. Simpan salinan data sebelum impor, dan siapkan daftar pemeriksaan sederhana, seperti jumlah produk, jumlah varian, total stok, dan beberapa contoh acak yang dicocokkan dengan sumber." },
  { type: "h2", text: "Merawat katalog dari waktu ke waktu" },
  { type: "p", text: "Katalog adalah dokumen hidup. Produk baru datang, barang lama dihentikan, pemasok mengganti kemasan, dan harga berubah. Tanpa kebiasaan perawatan, katalog yang rapi hari ini akan berantakan dalam beberapa bulan. Tetapkan siapa yang bertanggung jawab atas data produk, dan beri mereka alur kerja yang jelas untuk menambah, mengubah, dan menghentikan barang." },
  { type: "ul", items: [
    "Buat formulir penambahan produk dengan kolom wajib agar tidak ada produk terbit tanpa foto, kategori, atau berat untuk ongkos kirim",
    "Jadwalkan pemeriksaan berkala untuk produk tanpa penjualan, tanpa stok, atau tanpa foto yang layak",
    "Catat perubahan penting pada harga dan atribut beserta siapa yang melakukannya",
    "Gunakan status yang jelas, seperti draf, aktif, dan diarsipkan, alih-alih menghapus produk yang pernah terjual",
    "Tinjau kata yang dicari pelanggan di kolom pencarian toko untuk menemukan nama atau kategori yang perlu diperbaiki",
  ] },
  { type: "p", text: "Kolom pencarian internal adalah sumber umpan balik yang sering terlewat. Kata yang diketik pelanggan tetapi tidak menghasilkan apa-apa menunjukkan barang yang belum Anda jual, atau barang yang Anda jual dengan nama yang tidak mereka kenali. Memeriksanya setiap minggu memberi daftar perbaikan yang langsung berguna." },
  { type: "h2", text: "Mengukur apakah katalog berfungsi" },
  { type: "p", text: "Tanpa pengukuran, perbaikan katalog hanya menjadi urusan selera. Beberapa indikator sederhana cukup untuk memberi arah. Perhatikan proporsi pencarian internal yang tidak menghasilkan apa-apa, halaman produk yang sering dilihat tetapi jarang dibeli, tingkat retur karena barang tidak sesuai deskripsi, dan jumlah pertanyaan pelanggan yang menanyakan hal yang seharusnya sudah ada di halaman." },
  { type: "p", text: "Setiap indikator menunjuk ke perbaikan tertentu. Pencarian kosong menandakan kebutuhan sinonim atau produk baru. Halaman ramai tetapi sepi pembelian menandakan harga, foto, atau informasi yang belum meyakinkan. Retur karena tidak sesuai menandakan foto atau deskripsi yang menyesatkan. Pertanyaan berulang menandakan informasi yang perlu dipindahkan ke halaman." },
  { type: "p", text: "Ukur sebelum dan sesudah setiap perbaikan besar, dan beri jeda cukup lama agar hasilnya bisa dibaca. Karena musim, promo, dan iklan ikut memengaruhi, jangan terburu-buru menyimpulkan dari data beberapa hari. Bandingkan periode yang sepadan, dan catat perubahan lain yang terjadi pada waktu yang sama." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Membuat produk terpisah untuk setiap ukuran dan warna sehingga halaman duplikat memenuhi toko",
    "Memakai ulang kode barang lama untuk barang baru sehingga riwayat laporan bercampur",
    "Mengunggah ribuan produk sebelum aturan penamaan dan atribut disepakati",
    "Menyalin foto dan deskripsi pemasok tanpa penyesuaian dan tanpa memastikan hak pakainya",
    "Menyimpan stok dan harga di lebih dari satu tempat yang diedit secara manual",
    "Membiarkan produk yang sudah tidak dijual tetap tampil sehingga pelanggan kecewa saat memesan",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Ekspor seluruh daftar produk dan hitung berapa kode ganda, nama tidak konsisten, dan foto yang hilang",
    "Tulis satu halaman aturan: format kode barang, pola nama, daftar atribut baku, dan standar foto",
    "Pilih satu sistem sebagai sumber data produk dan petakan siapa yang boleh mengubahnya",
    "Bereskan lima puluh produk terlaris terlebih dahulu dan amati dampaknya pada pencarian dan pertanyaan pelanggan",
    "Jadwalkan pemeriksaan katalog bulanan dengan penanggung jawab yang jelas",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Katalog produk yang terstruktur adalah fondasi toko online yang bisa tumbuh tanpa kekacauan. Model data yang memisahkan produk dan varian, kode barang yang stabil, aturan penamaan yang konsisten, foto dan deskripsi yang jujur, serta satu sumber data untuk semua kanal membuat pelanggan lebih mudah menemukan dan memercayai barang Anda." },
  { type: "p", text: "Mulailah dari aturan sederhana yang ditulis dan dipatuhi, lalu rapikan bagian yang paling berdampak lebih dulu. Dengan katalog yang terawat, tampilan toko, iklan, dan sistem kasir bekerja di atas data yang sama dan saling menguatkan." },
  {
    type: "cta",
    title: "Ingin toko online dengan katalog yang rapi dan terhubung ke kasir serta stok?",
    text: "Tim AG·SORA membangun toko online dan sistem pendukungnya dengan model data produk yang bersih, kode barang yang konsisten, dan sinkronisasi stok antar kanal. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
