import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Ketika toko online baru menerima beberapa pesanan sehari, semuanya bisa ditangani dengan ingatan dan obrolan. Pemilik melihat pemberitahuan, mengambil barang dari rak, membungkus, lalu mengantarnya ke kurir. Cara ini terasa cukup sampai suatu hari pesanan datang lima puluh sekaligus dari website, marketplace, dan WhatsApp, dan tiba-tiba tidak ada yang tahu pasti pesanan mana yang sudah dibayar, mana yang sudah dikemas, dan mana yang terlewat." },
  { type: "p", text: "Masalah pada titik itu jarang terletak pada kurangnya orang. Masalahnya adalah pesanan tidak memiliki alur yang jelas. Setiap orang memegang potongan informasi yang berbeda, status hanya ada di kepala, dan kesalahan baru ketahuan ketika pelanggan mengeluh. Menambah tenaga tanpa memperbaiki alur hanya menambah jumlah orang yang kebingungan." },
  { type: "p", text: "Artikel ini membahas manajemen pesanan dari saat pesanan masuk sampai barang diterima pelanggan. Kami membahas penyatuan pesanan dari berbagai kanal, status dan pemiliknya, verifikasi pembayaran, alokasi stok, pengambilan dan pengemasan, penyerahan ke kurir, penanganan pengecualian, dan ukuran kinerja yang layak dipantau. Tidak ada angka rekaan di sini; yang kami tawarkan adalah kerangka kerja yang bisa disesuaikan dengan skala toko Anda." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Satukan pesanan dari semua kanal ke satu daftar kerja dengan nomor rujukan yang konsisten",
      "Tetapkan status pesanan yang sedikit, jelas, dan masing-masing punya pemilik",
      "Kunci stok saat pesanan dibuat agar barang yang sama tidak terjual dua kali",
      "Pakai pemindaian saat mengambil dan mengemas untuk mencegah salah kirim",
      "Tangani pengecualian lewat antrean khusus, bukan lewat obrolan yang tercecer",
    ],
  },
  { type: "h2", text: "Pesanan adalah janji yang harus ditepati" },
  { type: "p", text: "Bagi pelanggan, menekan tombol beli berarti menerima sebuah janji: barang tertentu, dalam jumlah tertentu, akan tiba di alamat tertentu dalam waktu yang wajar. Segala hal yang terjadi di belakang layar setelah itu adalah upaya menepati janji tersebut. Manajemen pesanan yang baik membuat janji itu ditepati secara konsisten, bukan hanya ketika tim sedang tidak sibuk." },
  { type: "p", text: "Kegagalan menepati janji jarang berupa bencana besar. Biasanya ia berupa hal kecil yang berulang: warna tertukar, satu barang tertinggal dari paket, pesanan terkirim dua hari lebih lambat tanpa kabar, atau pesanan yang dibatalkan karena stok ternyata habis. Masing-masing tampak sepele, tetapi bersama-sama membentuk kesan apakah toko Anda bisa diandalkan." },
  { type: "p", text: "Karena itu manajemen pesanan bukan urusan gudang semata. Ia menghubungkan penjualan, pembayaran, stok, pengiriman, dan layanan pelanggan. Toko yang merancangnya sebagai satu alur utuh akan jauh lebih tenang saat ramai daripada toko yang membiarkan setiap bagian bekerja dengan catatannya sendiri." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1553413077-190dd305871c",
    alt: "Lorong gudang dengan rak tinggi berisi tumpukan kardus",
    caption: "Alur pesanan yang jelas membuat barang berpindah dari rak ke kurir tanpa menebak-nebak.",
  },
  { type: "h2", text: "Menyatukan pesanan dari semua kanal" },
  { type: "p", text: "Kebanyakan toko berjualan di lebih dari satu tempat: website sendiri, satu atau dua marketplace, media sosial, dan pesanan langsung lewat obrolan. Jika setiap kanal dikerjakan dari layarnya masing-masing, tim harus berpindah-pindah, dan pesanan dari kanal yang jarang dibuka paling mudah terlewat." },
  { type: "p", text: "Langkah pertama adalah mengumpulkan semua pesanan ke satu daftar kerja. Untuk kanal yang menyediakan sambungan data, pesanan bisa ditarik otomatis. Untuk pesanan lewat obrolan, sediakan cara cepat bagi admin untuk memasukkannya ke sistem yang sama, bukan ke catatan terpisah. Yang penting, gudang hanya melihat satu antrean." },
  { type: "p", text: "Beri setiap pesanan nomor rujukan internal yang konsisten sambil tetap menyimpan nomor asli dari kanalnya. Nomor internal dipakai tim untuk berkomunikasi, sedangkan nomor kanal dipakai saat menjawab pelanggan atau mencocokkan pencairan dana. Tanpa keduanya, pertanyaan sederhana seperti pesanan atas nama siapa ini akan memakan waktu." },
  { type: "h2", text: "Status pesanan yang sedikit dan jelas" },
  { type: "p", text: "Status adalah bahasa bersama seluruh tim. Terlalu sedikit status membuat pesanan yang berbeda keadaannya tampak sama. Terlalu banyak status membuat orang malas memperbaruinya. Tujuh atau delapan status yang benar-benar menggambarkan perpindahan tanggung jawab biasanya sudah memadai." },
  { type: "ol", items: [
    "Menunggu pembayaran: pesanan dibuat, dana belum diterima",
    "Dibayar: dana terkonfirmasi, pesanan siap diproses",
    "Diproses: barang sedang diambil dari rak",
    "Dikemas: paket selesai dan menunggu penjemputan",
    "Dikirim: paket sudah diserahkan ke kurir dan memiliki nomor resi",
    "Diterima: kurir mengonfirmasi paket sampai",
    "Selesai: masa komplain lewat tanpa masalah",
    "Bermasalah: memerlukan keputusan manusia sebelum bisa lanjut",
  ] },
  { type: "p", text: "Setiap status sebaiknya punya pemilik yang jelas dan batas waktu wajar. Pesanan yang berhenti terlalu lama di satu status harus terlihat menonjol di layar. Dengan begitu penyelia tidak perlu memeriksa satu per satu; ia cukup melihat pesanan mana yang melewati batas dan menanyakan sebabnya." },
  { type: "h2", text: "Verifikasi pembayaran tanpa pemeriksaan manual" },
  { type: "p", text: "Memeriksa mutasi rekening satu per satu lalu mencocokkannya dengan pesanan adalah pekerjaan yang lambat dan rawan keliru. Dua pesanan dengan nominal sama mudah tertukar, dan bukti transfer berupa gambar bisa dipalsukan. Selama verifikasi dilakukan manual, kecepatan seluruh alur dibatasi oleh kecepatan satu orang membuka aplikasi bank." },
  { type: "p", text: "Sambungan dengan penyedia pembayaran memungkinkan status berubah otomatis begitu dana diterima. Pesanan langsung masuk ke antrean gudang tanpa menunggu admin. Untuk transfer bank, nomor rekening virtual atau kode unik per pesanan membuat pencocokan tidak lagi bergantung pada tebakan." },
  { type: "p", text: "Tetapkan pula batas waktu pembayaran. Pesanan yang tidak dibayar dalam batas tersebut sebaiknya dibatalkan otomatis dan stoknya dilepas. Kirim pengingat sebelum batas habis. Tanpa aturan ini, barang laris bisa tertahan oleh pesanan yang tidak pernah dibayar sementara pembeli lain melihatnya sebagai habis." },
  { type: "h2", text: "Alokasi stok: mencegah barang terjual dua kali" },
  { type: "p", text: "Salah satu sumber pembatalan yang paling menjengkelkan adalah menjual barang yang ternyata sudah tidak ada. Hal ini terjadi ketika stok baru dikurangi saat barang dikemas, padahal di antara waktu pesanan dan pengemasan ada pesanan lain yang masuk untuk barang yang sama." },
  { type: "p", text: "Cara mencegahnya adalah membedakan stok fisik dari stok yang tersedia untuk dijual. Begitu pesanan dibuat atau dibayar, jumlahnya dicadangkan sehingga stok tersedia langsung berkurang walau barang masih di rak. Angka stok tersedia inilah yang ditampilkan ke semua kanal penjualan." },
  { type: "p", text: "Bila Anda memiliki lebih dari satu lokasi penyimpanan, sistem juga perlu memutuskan dari lokasi mana pesanan dipenuhi. Aturannya bisa sederhana, misalnya lokasi terdekat dengan alamat pembeli yang memiliki semua barang. Yang penting aturan itu tertulis dan dijalankan sistem, bukan diputuskan ulang setiap kali oleh orang yang berbeda." },
  { type: "callout", title: "Stok penyangga untuk barang laris", text: "Untuk barang yang bergerak sangat cepat atau dijual di banyak kanal, pertimbangkan menyisakan sedikit stok yang tidak ditampilkan. Penyangga ini menyerap selisih waktu sinkronisasi dan selisih hitung, sehingga pembatalan karena stok habis berkurang." },
  { type: "h2", text: "Pengambilan barang yang rapi" },
  { type: "p", text: "Pengambilan barang dari rak adalah tahap yang paling banyak memakan langkah kaki. Daftar ambil yang baik menyebutkan lokasi rak, nama barang, varian, dan jumlah, serta diurutkan mengikuti jalur gudang agar petugas tidak bolak-balik. Lokasi rak yang diberi kode dan tercatat di sistem adalah prasyaratnya." },
  { type: "p", text: "Ketika pesanan sedikit, mengambil per pesanan masih wajar. Ketika pesanan banyak, mengambil barang untuk beberapa pesanan sekaligus lalu memilahnya di meja kemas jauh lebih hemat waktu. Pilih cara yang sesuai dengan jumlah pesanan dan ukuran gudang Anda, lalu ubah ketika volumenya berubah." },
  { type: "p", text: "Varian yang mirip adalah sumber salah ambil terbesar: ukuran M dan L, warna hitam dan biru tua, isi 250 dan 500 gram. Pisahkan penyimpanan varian yang mirip, beri label besar, dan bila memungkinkan pakai pemindaian kode batang saat mengambil. Pemindaian menangkap kesalahan sebelum barang masuk ke kardus." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55",
    alt: "Dua orang menyerahkan sebuah paket kardus yang sudah dilakban",
    caption: "Paket yang berpindah tangan dengan catatan yang jelas lebih mudah dilacak ketika ada pertanyaan.",
  },
  { type: "h2", text: "Pengemasan dan pemeriksaan akhir" },
  { type: "p", text: "Meja kemas adalah kesempatan terakhir menemukan kesalahan sebelum paket meninggalkan gudang. Petugas kemas sebaiknya memeriksa isi terhadap pesanan, bukan sekadar membungkus apa yang diserahkan kepadanya. Pemindaian setiap barang terhadap daftar pesanan menjadikan pemeriksaan ini cepat dan tidak bergantung pada ketelitian mata." },
  { type: "ul", items: [
    "Cocokkan barang, varian, dan jumlah dengan pesanan sebelum kardus ditutup",
    "Pakai bahan kemas yang sesuai dengan jenis barang, terutama barang pecah belah dan cairan",
    "Sertakan nota atau slip isi paket agar pelanggan bisa memeriksa saat membuka",
    "Tempel label pengiriman yang dicetak sistem, bukan ditulis tangan",
    "Timbang paket dan catat beratnya untuk dicocokkan dengan tagihan kurir",
    "Foto paket bernilai tinggi sebelum ditutup sebagai bukti bila ada sengketa",
  ] },
  { type: "p", text: "Standar kemasan yang tertulis membantu petugas baru bekerja sama baiknya dengan petugas lama. Tentukan ukuran kardus untuk tiap kelompok barang dan jumlah pelindung yang dipakai. Kemasan yang terlalu besar menaikkan ongkos kirim, sedangkan kemasan yang terlalu tipis menaikkan retur karena barang rusak." },
  { type: "h2", text: "Penyerahan ke kurir dan pelacakan" },
  { type: "p", text: "Saat paket diserahkan ke kurir, tanggung jawab berpindah, dan perpindahan itu perlu tercatat. Buat daftar serah terima per kurir per penjemputan, lalu pindai setiap paket saat diserahkan. Daftar ini menjadi bukti ketika kurir menyatakan tidak pernah menerima suatu paket." },
  { type: "p", text: "Nomor resi sebaiknya dibuat lewat sambungan dengan jasa pengiriman dan langsung tersimpan di pesanan. Begitu resi tersedia, kirim pemberitahuan kepada pelanggan lengkap dengan tautan pelacakan. Sebagian besar pertanyaan paket saya sampai di mana hilang dengan sendirinya bila pelanggan bisa memeriksanya sendiri." },
  { type: "p", text: "Pantau pula paket yang sudah dikirim tetapi tidak bergerak selama beberapa hari. Menghubungi kurir sebelum pelanggan mengeluh mengubah pengalaman buruk menjadi kesan bahwa toko Anda peduli. Tugas ini mudah diotomatiskan bila status pengiriman ditarik rutin dari sistem kurir." },
  { type: "h2", text: "Pesanan yang tidak berjalan mulus" },
  { type: "p", text: "Sebagian pesanan tidak akan mengikuti alur biasa. Alamat tidak lengkap, barang ternyata cacat saat diambil, pelanggan meminta mengubah varian, sebagian barang tersedia sedangkan sisanya belum, atau paket dikembalikan kurir karena penerima tidak ada. Kasus seperti ini wajar; yang berbahaya adalah bila mereka tidak punya tempat." },
  { type: "p", text: "Sediakan status bermasalah beserta alasannya, dan tunjuk orang yang bertanggung jawab mengosongkan antrean itu setiap hari. Pesanan bermasalah yang dibiarkan menggantung adalah sumber keluhan terbesar, karena pelanggan sudah membayar tetapi tidak menerima barang maupun kabar." },
  { type: "p", text: "Tentukan sejak awal kebijakan untuk situasi yang sering muncul. Apakah pesanan boleh dikirim sebagian. Sampai tahap mana pelanggan masih boleh mengubah atau membatalkan pesanan. Siapa yang menanggung ongkos kirim ulang bila alamat salah. Aturan yang jelas membuat admin bisa memutuskan dengan cepat tanpa menunggu pemilik." },
  { type: "h2", text: "Komunikasi dengan pelanggan selama proses" },
  { type: "p", text: "Pelanggan tidak melihat gudang Anda. Yang mereka lihat hanyalah pesan yang Anda kirim. Pemberitahuan pada saat yang tepat membuat proses terasa terkendali: konfirmasi pesanan, konfirmasi pembayaran, pemberitahuan pengiriman dengan nomor resi, dan konfirmasi sampai." },
  { type: "p", text: "Kabar buruk yang disampaikan lebih awal jauh lebih mudah diterima daripada kabar buruk yang ditemukan sendiri oleh pelanggan. Jika pesanan akan terlambat, katakan sebelum tenggat lewat dan tawarkan pilihan: menunggu, mengganti barang, atau membatalkan dengan pengembalian dana. Pelanggan yang diberi pilihan jarang marah." },
  { type: "p", text: "Sediakan halaman status pesanan yang bisa dibuka pelanggan kapan saja, baik di website maupun di aplikasi. Halaman ini mengurangi beban layanan pelanggan sekaligus menunjukkan bahwa toko Anda bekerja dengan sistem, bukan dengan ingatan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7",
    alt: "Truk pengiriman melaju di jalan raya di bawah langit cerah",
    caption: "Setelah paket berada di jalan, pelacakan dan kabar yang jujur menjaga kepercayaan pelanggan.",
  },
  { type: "h2", text: "Kapan memerlukan sistem manajemen pesanan" },
  { type: "p", text: "Lembar kerja bersama cukup untuk tahap awal. Tanda bahwa Anda sudah melewati batasnya biasanya jelas: pesanan terlewat saat ramai, stok di marketplace sering tidak cocok dengan gudang, admin menghabiskan waktu menyalin data antarlayar, dan tidak ada yang bisa menjawab cepat berapa pesanan yang belum dikirim hari ini." },
  { type: "p", text: "Sistem manajemen pesanan menyatukan pesanan, stok, dan pengiriman dalam satu tempat. Sebagian toko cukup dengan fitur bawaan platform toko online mereka. Toko dengan banyak kanal, beberapa gudang, atau aturan khusus biasanya memerlukan sistem tersendiri yang terhubung dengan toko, marketplace, kurir, dan pembukuan atau ERP." },
  { type: "p", text: "Saat menilai pilihan, perhatikan sambungan yang tersedia, kemudahan dipakai petugas gudang di perangkat sederhana, kemampuan menangani pengecualian, dan laporan yang dihasilkan. Sistem yang hebat di atas kertas tetapi lambat dipakai di meja kemas akan ditinggalkan dan tim kembali ke cara lama." },
  { type: "h2", text: "Ukuran kinerja yang layak dipantau" },
  { type: "ul", items: [
    "Waktu dari pesanan dibayar sampai diserahkan ke kurir",
    "Jumlah pesanan yang melewati batas waktu pada tiap status",
    "Proporsi pesanan yang salah kirim atau kurang barang",
    "Proporsi pesanan yang dibatalkan karena stok habis",
    "Jumlah pesanan berstatus bermasalah dan umur rata-ratanya",
    "Jumlah pertanyaan pelanggan tentang status pesanan",
  ] },
  { type: "p", text: "Pantau angka-angka ini secara berkala dan cari polanya, bukan sekadar nilainya. Keterlambatan yang selalu terjadi pada hari tertentu menunjukkan masalah jadwal. Salah kirim yang berulang pada produk tertentu menunjukkan masalah penyimpanan atau label. Ukuran baru berguna bila diikuti perbaikan pada sumbernya." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Mengerjakan tiap kanal dari layar terpisah sehingga pesanan mudah terlewat",
    "Mengurangi stok baru saat barang dikemas, bukan saat pesanan dibuat",
    "Menulis label pengiriman dengan tangan",
    "Membiarkan pesanan bermasalah tanpa pemilik dan tanpa batas waktu",
    "Baru memberi kabar keterlambatan setelah pelanggan bertanya",
    "Menambah orang sebelum merapikan alur",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Gambarkan alur pesanan Anda saat ini dari masuk sampai terkirim, termasuk siapa melakukan apa",
    "Tetapkan daftar status dan batas waktu wajar untuk masing-masing",
    "Kumpulkan pesanan dari semua kanal ke satu daftar kerja, walau awalnya masih semi manual",
    "Beri kode lokasi pada rak dan pisahkan varian yang mirip",
    "Buat antrean pesanan bermasalah dan tunjuk penanggung jawab hariannya",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Manajemen pesanan yang baik hampir tidak terlihat oleh pelanggan. Yang mereka rasakan hanyalah barang yang benar, tiba tepat waktu, dengan kabar yang jelas di sepanjang jalan. Di balik pengalaman sederhana itu ada alur yang dirancang: satu antrean, status yang jelas, stok yang terkunci, pemeriksaan sebelum kirim, dan tempat khusus untuk masalah." },
  { type: "p", text: "Rapikan alurnya terlebih dahulu, baru kemudian tambahkan alat dan orang. Toko yang melakukannya dengan urutan itu bisa menangani lonjakan pesanan tanpa panik, dan tumbuh tanpa mengorbankan kepercayaan yang sudah dibangun." },
  {
    type: "cta",
    title: "Pesanan mulai sulit dikendalikan dari banyak kanal sekaligus?",
    text: "Tim AG·SORA membangun sistem pesanan yang menyatukan website, marketplace, stok, dan pengiriman dalam satu alur, lengkap dengan pemindaian di gudang dan pelacakan untuk pelanggan. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/custom-software",
    label: "Konsultasi gratis",
  },
];
