import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Ketika bisnis kecil, mengelola pemasok terasa sederhana: pemilik mengenal setiap pemasok, mengingat harga terakhir, dan tahu siapa yang sering terlambat. Seiring pertumbuhan, ingatan itu tidak lagi cukup. Pemasok bertambah, barang yang dibeli bervariasi, dan beberapa orang di bagian berbeda memesan dari pemasok yang sama tanpa saling tahu." },
  { type: "p", text: "Akibatnya muncul masalah yang berulang: harga beli yang tidak seragam, pesanan yang terlambat tanpa ada yang mencatat, tagihan ganda, dan keputusan memilih pemasok yang didasarkan pada kedekatan, bukan data. Pembelian biasanya menyerap bagian terbesar dari uang yang keluar dari bisnis, sehingga perbaikan kecil di sini berdampak besar pada laba." },
  { type: "p", text: "Artikel ini membahas cara mengelola pemasok secara terstruktur dengan bantuan ERP: data induk pemasok, proses pengadaan, penilaian kinerja, pengelolaan kontrak dan harga, hingga risiko ketergantungan. Kami tidak memakai angka rekaan; yang kami berikan adalah kerangka kerja yang bisa Anda terapkan sesuai skala bisnis Anda." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Data pemasok yang rapi dan tunggal adalah fondasi seluruh proses pembelian",
      "Pisahkan tugas meminta, menyetujui, menerima, dan membayar agar kesalahan dan kecurangan lebih sulit terjadi",
      "Nilai pemasok dengan indikator yang terukur: ketepatan waktu, mutu, harga, dan responsivitas",
      "Simpan kontrak dan kesepakatan harga di sistem, bukan di ingatan atau di surel pribadi",
      "Kelola risiko ketergantungan pada satu pemasok sebelum menjadi masalah",
    ],
  },
  { type: "h2", text: "Mengapa pemasok perlu dikelola, bukan sekadar dihubungi" },
  { type: "p", text: "Pemasok adalah perpanjangan operasi Anda. Ketika bahan baku terlambat, produksi berhenti. Ketika barang dagangan cacat, pelanggan yang menanggung dan Andalah yang menerima keluhannya. Karena itu, mutu dan ketepatan pemasok secara langsung menentukan mutu dan ketepatan bisnis Anda sendiri." },
  { type: "p", text: "Tanpa pengelolaan, informasi tentang pemasok tersebar di kepala orang, di grup percakapan, dan di tumpukan faktur. Orang baru yang mengambil alih pembelian harus memulai dari nol, dan pemilik tidak punya cara cepat untuk menjawab pertanyaan sederhana seperti pemasok mana yang paling sering terlambat bulan ini." },
  { type: "p", text: "Pengelolaan pemasok yang baik bukan berarti birokrasi tambahan. Intinya adalah memastikan informasi yang penting tersedia di satu tempat, keputusan dibuat dengan data, dan hubungan dengan pemasok tetap sehat. Pemasok yang diperlakukan jelas dan dibayar tepat waktu biasanya juga lebih bersedia membantu saat Anda membutuhkan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1521791136064-7986c2920216",
    alt: "Dua orang berjabat tangan di ruang kantor",
    caption: "Hubungan dengan pemasok yang sehat bergantung pada kejelasan aturan dan ketepatan pembayaran.",
  },
  { type: "h2", text: "Data induk pemasok: satu catatan yang bisa dipercaya" },
  { type: "p", text: "Mulailah dari data induk. Setiap pemasok memiliki satu catatan yang memuat nama resmi, alamat, kontak, identitas pajak, rekening bank, syarat pembayaran, mata uang, dan barang atau jasa yang disediakan. Satu pemasok, satu catatan; hindari pemasok yang sama tercatat dengan tiga ejaan berbeda." },
  { type: "p", text: "Duplikasi data pemasok bukan sekadar soal kerapian. Ia membuka celah tagihan ganda, kesulitan menghitung total pembelian per pemasok, dan, pada kasus terburuk, pembayaran ke rekening yang keliru. Tetapkan aturan pemeriksaan sebelum pemasok baru dibuat: apakah sudah ada di sistem dengan nama lain?" },
  { type: "p", text: "Batasi siapa yang boleh membuat dan mengubah data pemasok, terutama rekening bank. Perubahan rekening adalah salah satu modus penipuan yang paling umum, jadi setiap perubahan sebaiknya diverifikasi lewat jalur kedua, misalnya menelepon kontak yang sudah dikenal, dan dicatat siapa yang menyetujuinya." },
  { type: "h2", text: "Proses pengadaan dari permintaan sampai pembayaran" },
  { type: "p", text: "Alur pengadaan yang sehat umumnya melalui beberapa langkah: permintaan pembelian dari pengguna, persetujuan, pesanan pembelian ke pemasok, penerimaan barang, pencocokan tagihan, lalu pembayaran. Setiap langkah meninggalkan jejak di sistem sehingga siapa pun dapat melihat posisi suatu pesanan." },
  { type: "p", text: "Pemisahan tugas adalah prinsip penting di sini. Orang yang meminta barang sebaiknya bukan orang yang menyetujui, dan orang yang menerima barang sebaiknya bukan orang yang membayar tagihan. Pemisahan ini bukan tanda tidak percaya, melainkan pengaman agar kesalahan jujur dan penyalahgunaan sama-sama lebih mudah terdeteksi." },
  { type: "p", text: "Sesuaikan kerumitan dengan nilai transaksi. Pembelian alat tulis tidak perlu melalui tiga tingkat persetujuan, sedangkan pembelian mesin tentu perlu. Tetapkan batas nilai untuk tiap tingkat persetujuan dan tuliskan dalam kebijakan yang diterapkan oleh sistem, bukan oleh kebiasaan semata." },
  { type: "callout", title: "Pencocokan tiga arah", text: "Sebelum tagihan dibayar, cocokkan tiga dokumen: pesanan pembelian, bukti penerimaan barang, dan tagihan pemasok. Bila ketiganya cocok, tagihan layak dibayar. Bila tidak, selisihnya harus dijelaskan lebih dulu. Banyak ERP melakukan pencocokan ini otomatis dan hanya menandai yang menyimpang." },
  { type: "h2", text: "Harga, kontrak, dan kesepakatan" },
  { type: "p", text: "Harga beli yang berbeda-beda untuk barang yang sama adalah kebocoran yang sering tidak disadari. Simpan daftar harga yang disepakati per pemasok per barang, lengkap dengan masa berlakunya, sehingga saat pesanan dibuat sistem langsung menampilkan harga yang benar dan memberi peringatan bila ada penyimpangan." },
  { type: "p", text: "Kontrak dan kesepakatan lain, seperti syarat pembayaran, jaminan mutu, dan denda keterlambatan, sebaiknya disimpan di sistem sebagai lampiran pada catatan pemasok, lengkap dengan tanggal berakhirnya. Pengingat otomatis sebelum kontrak berakhir mencegah kesepakatan lapuk tanpa diketahui, atau diperpanjang otomatis padahal ada pilihan yang lebih baik." },
  { type: "p", text: "Gunakan data historis untuk bernegosiasi. Bila sistem menunjukkan total pembelian Anda dari satu pemasok selama setahun, Anda punya dasar untuk meminta harga atau syarat yang lebih baik. Sebaliknya, data yang sama membantu menilai apakah pemasok yang lebih mahal memang memberi nilai tambah." },
  { type: "h2", text: "Menilai kinerja pemasok dengan indikator sederhana" },
  { type: "p", text: "Penilaian tidak perlu rumit untuk bermanfaat. Empat indikator dasar biasanya sudah cukup: ketepatan waktu pengiriman, kesesuaian jumlah dan mutu barang, konsistensi harga, serta responsivitas ketika ada masalah. Sebagian besar dapat dihitung otomatis dari data penerimaan barang yang sudah ada." },
  { type: "ul", items: [
    "Ketepatan waktu: berapa persen pesanan tiba sesuai tanggal yang dijanjikan",
    "Kesesuaian: seberapa sering jumlah atau spesifikasi yang tiba berbeda dari pesanan",
    "Mutu: berapa banyak barang yang ditolak atau diretur karena cacat",
    "Harga: apakah harga tagihan konsisten dengan kesepakatan",
    "Responsivitas: seberapa cepat pemasok menanggapi pertanyaan dan menyelesaikan keluhan",
  ] },
  { type: "p", text: "Bagikan hasil penilaian kepada pemasok secara berkala. Pemasok yang baik akan menghargai umpan balik yang jelas dan berbasis data, dan sering kali memperbaiki dirinya sendiri. Pemasok yang tidak memperbaiki meski sudah diberi tahu memberi Anda alasan yang objektif untuk mencari alternatif." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1553413077-190dd305871c",
    alt: "Lorong gudang dengan rak tinggi berisi tumpukan kardus",
    caption: "Data penerimaan barang di gudang menjadi bahan utama untuk menilai ketepatan dan kesesuaian pemasok.",
  },
  { type: "h2", text: "Mengelola risiko ketergantungan" },
  { type: "p", text: "Ketergantungan pada satu pemasok untuk barang penting adalah risiko yang sering baru terasa ketika sudah terlambat. Bila pemasok itu mengalami gangguan, menaikkan harga sepihak, atau berhenti beroperasi, bisnis Anda ikut terguncang. Petakan barang kritis dan periksa berapa banyak pilihan pemasok yang Anda miliki untuk masing-masing." },
  { type: "p", text: "Memiliki pemasok cadangan tidak selalu berarti memecah pembelian secara merata. Pada banyak kasus, cukup memiliki pemasok alternatif yang sudah dikenal, sudah pernah menerima pesanan kecil, dan siap meningkatkan volume bila diperlukan. Menguji pemasok cadangan dengan pesanan kecil lebih murah daripada mencarinya dalam keadaan darurat." },
  { type: "p", text: "Perhatikan juga risiko lain: ketergantungan pada satu lokasi, satu jalur pengiriman, atau satu mata uang. Catat risiko ini dalam daftar sederhana dan tinjau secara berkala. Tujuannya bukan menghilangkan semua risiko, melainkan memastikan Anda tidak terkejut oleh risiko yang sebenarnya bisa diperkirakan." },
  { type: "h2", text: "Hubungan dengan stok dan arus kas" },
  { type: "p", text: "Pengelolaan pemasok terkait erat dengan perencanaan stok. Waktu tunggu pemasok, jumlah pesanan minimum, dan kebiasaan keterlambatan harus tercermin dalam perhitungan titik pesan ulang. Bila pemasok sering terlambat dua hari tetapi sistem mengasumsikan tepat waktu, stok pengaman Anda akan selalu kurang." },
  { type: "p", text: "Syarat pembayaran memengaruhi arus kas secara langsung. Pemasok yang memberi tempo pembayaran lebih panjang membantu modal kerja Anda, tetapi pembayaran yang terlambat merusak hubungan. Jadwalkan pembayaran berdasarkan jatuh tempo dan manfaatkan potongan pembayaran lebih awal hanya bila memang menguntungkan secara hitungan." },
  { type: "p", text: "Dengan ERP, data utang usaha, jadwal pembayaran, dan perkiraan kas berada dalam satu sistem. Pemilik dapat melihat berapa kewajiban yang jatuh tempo minggu depan dan memutuskan pembayaran mana yang didahulukan, bukan menebak berdasarkan saldo rekening hari ini." },
  { type: "h2", text: "Menerima pemasok baru dengan benar" },
  { type: "p", text: "Proses penerimaan pemasok baru adalah kesempatan terbaik untuk mencegah masalah. Sebelum pesanan pertama, kumpulkan dokumen dasar seperti identitas usaha, identitas pajak, rekening atas nama usaha, serta referensi atau contoh barang bila relevan. Dokumen yang lengkap di awal menghemat banyak urusan ketika tagihan pertama datang." },
  { type: "p", text: "Mulailah dengan pesanan kecil bila pemasok belum dikenal. Pesanan percobaan memperlihatkan ketepatan, mutu kemasan, dan cara pemasok berkomunikasi dengan biaya risiko yang rendah. Catat hasilnya di sistem sehingga keputusan menaikkan volume didasarkan pada pengalaman, bukan pada janji penjual." },
  { type: "p", text: "Jelaskan juga aturan main Anda sejak awal: jadwal pembayaran, cara mengirim tagihan, alamat dan jam penerimaan barang, serta bagaimana barang cacat ditangani. Pemasok yang tahu aturannya sejak hari pertama jarang menimbulkan kejutan." },
  { type: "h2", text: "Pembelian barang tidak langsung dan jasa" },
  { type: "p", text: "Banyak bisnis hanya menertibkan pembelian bahan baku atau barang dagangan, sementara pembelian lain berjalan bebas: alat tulis, perawatan, perjalanan, langganan perangkat lunak, jasa konsultan. Jumlahnya sering lebih besar daripada yang disangka, dan justru di sinilah pengeluaran paling mudah bocor." },
  { type: "p", text: "Terapkan alur yang lebih ringan untuk kategori ini, tetapi tetap tercatat. Misalnya, anggaran per bagian, persetujuan atasan untuk nilai tertentu, dan kewajiban melampirkan bukti. Langganan berulang perlu daftar tersendiri dengan tanggal perpanjangan agar tidak ada yang berjalan tanpa pernah ditinjau." },
  { type: "p", text: "Untuk jasa, penerimaan tidak berupa barang di gudang, melainkan konfirmasi bahwa pekerjaan selesai sesuai kesepakatan. Tentukan siapa yang berwenang mengonfirmasi, karena tagihan jasa sering dibayar hanya karena pengirimnya rajin menagih." },
  { type: "h2", text: "Menangani retur, klaim, dan perselisihan" },
  { type: "p", text: "Barang cacat, jumlah kurang, dan harga yang berbeda dari kesepakatan pasti terjadi. Yang membedakan bisnis yang rapi adalah cara menanganinya. Catat setiap kasus di sistem terkait pesanan dan pemasoknya, lengkap dengan foto atau bukti, tanggal pelaporan, dan hasil penyelesaiannya." },
  { type: "p", text: "Catatan ini berguna dalam tiga hal. Pertama, mempercepat penyelesaian karena semua bukti tersedia. Kedua, memberi bahan penilaian kinerja pemasok. Ketiga, memastikan nota kredit atau penggantian barang benar-benar diterima, bukan terlupakan di tengah kesibukan." },
  { type: "p", text: "Pastikan tagihan yang sedang diperselisihkan ditandai agar tidak terbayar otomatis. Banyak pembayaran ganda dan pembayaran berlebih terjadi karena tagihan bermasalah tetap masuk antrean pembayaran rutin." },
  { type: "h2", text: "Portal pemasok dan integrasi" },
  { type: "p", text: "Setelah dasar-dasarnya berjalan, Anda bisa mengurangi pekerjaan manual dengan portal pemasok. Pemasok dapat melihat pesanan yang masuk, mengonfirmasi tanggal pengiriman, mengunggah tagihan, dan memeriksa status pembayaran sendiri. Pertanyaan seperti kapan tagihan saya dibayar berkurang drastis karena jawabannya bisa dilihat langsung." },
  { type: "p", text: "Integrasi lain yang membantu adalah penghubungan dengan sistem gudang dan keuangan sehingga penerimaan barang otomatis memperbarui stok dan utang usaha. Pada pemasok yang besar, pertukaran dokumen elektronik dapat menghilangkan pengetikan ulang. Mulailah dari pemasok dengan volume transaksi terbesar karena manfaatnya paling cepat terasa." },
  { type: "p", text: "Apa pun bentuknya, jangan mengorbankan kontrol demi kecepatan. Pemasok yang mengunggah tagihan sendiri tetap perlu melalui pencocokan tiga arah, dan perubahan data rekening tetap perlu verifikasi." },
  { type: "h2", text: "Menjaga hubungan yang adil dan berkelanjutan" },
  { type: "p", text: "Penilaian dan kontrol bukan berarti memperlakukan pemasok sebagai pihak yang harus dicurigai. Hubungan yang baik berjalan dua arah: Anda memberi kepastian pesanan dan pembayaran tepat waktu, mereka memberi mutu dan kejelasan. Pemasok yang merasa diperlakukan adil lebih mungkin memprioritaskan Anda ketika bahan langka atau jadwal padat." },
  { type: "p", text: "Komunikasikan perubahan sedini mungkin, misalnya perubahan jumlah pesanan atau spesifikasi. Perubahan mendadak tanpa pemberitahuan adalah sumber keterlambatan dan perselisihan yang paling sering sebenarnya berasal dari pihak pembeli. Sistem yang membagikan perkiraan kebutuhan beberapa minggu ke depan membantu pemasok merencanakan produksinya." },
  { type: "p", text: "Bila perlu mengakhiri hubungan, lakukan dengan baik dan berdasarkan catatan yang jelas. Catatan kinerja yang objektif membuat keputusan ini lebih mudah dijelaskan, dan menjaga nama baik bisnis Anda di mata pemasok lain yang mungkin menjadi mitra di masa depan." },
  { type: "h2", text: "Ritme peninjauan yang realistis" },
  { type: "p", text: "Pengelolaan pemasok yang baik tidak memerlukan rapat panjang. Cukup tetapkan ritme sederhana: tinjauan mingguan atas pesanan yang terlambat dan tagihan yang tertahan, tinjauan bulanan atas indikator kinerja lima pemasok terbesar, dan tinjauan tahunan atas kontrak serta harga. Setiap tinjauan punya pemilik dan catatan hasil yang singkat." },
  { type: "p", text: "Dalam tinjauan tahunan, tanyakan tiga hal. Apakah pemasok ini masih yang terbaik untuk kebutuhan kami? Apakah ada pemasok baru yang layak dicoba? Apakah syarat dan harga masih mencerminkan volume yang kami beli? Jawaban yang jujur sering membuka peluang penghematan sekaligus perbaikan mutu." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Membiarkan pemasok yang sama tercatat beberapa kali dengan nama berbeda",
    "Mengizinkan satu orang meminta, menyetujui, menerima, dan membayar",
    "Tidak memverifikasi perubahan rekening bank pemasok lewat jalur kedua",
    "Menyimpan kontrak dan kesepakatan harga hanya di surel atau ingatan perorangan",
    "Memilih pemasok hanya berdasarkan harga termurah tanpa melihat mutu dan ketepatan",
    "Tidak pernah memberi umpan balik kepada pemasok berdasarkan data",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Kumpulkan semua daftar pemasok yang tersebar dan gabungkan menjadi satu daftar bersih",
    "Tulis alur pengadaan yang berjalan saat ini dan tandai di mana pemisahan tugas belum ada",
    "Tetapkan siapa yang boleh mengubah data rekening bank pemasok dan bagaimana verifikasinya",
    "Pilih lima pemasok terbesar dan catat ketepatan waktu serta kesesuaian pengirimannya",
    "Identifikasi barang yang hanya dipasok satu pemasok dan rencanakan cadangannya",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Pemasok yang dikelola dengan baik membuat bisnis lebih tenang: pesanan datang tepat waktu, tagihan benar, dan harga bisa diprediksi. Pemasok yang dibiarkan tanpa pengelolaan membuat bisnis terus memadamkan api yang sebenarnya bisa dicegah." },
  { type: "p", text: "Mulailah dari data yang rapi dan alur yang jelas, lalu tambahkan penilaian dan pengelolaan risiko secara bertahap. ERP membantu menyatukan semuanya, tetapi nilainya baru terasa ketika kebiasaan tim ikut berubah." },
  {
    type: "cta",
    title: "Pembelian dan pemasok masih dikelola lewat catatan terpisah?",
    text: "Tim AG·SORA menerapkan ERP yang menyatukan data pemasok, pesanan pembelian, penerimaan barang, dan utang usaha, lengkap dengan persetujuan berjenjang dan penilaian pemasok. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/erp",
    label: "Konsultasi gratis",
  },
];
