import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Ketika bisnis memutuskan menerapkan ERP, perhatian biasanya tertuju pada fitur: modul apa saja yang ada, laporan apa yang bisa dihasilkan, dan seberapa mudah tampilannya. Jarang ada yang bertanya sejak awal, \"Data apa yang akan kita masukkan ke dalamnya, dan seberapa bersih data itu?\" Padahal di situlah banyak proyek ERP diam-diam goyah. Sistem yang canggih menerima data yang kacau akan menghasilkan laporan yang kacau pula, hanya saja lebih rapi tampilannya." },
  { type: "p", text: "Data induk atau master data adalah data inti yang dipakai berulang oleh hampir semua proses bisnis: daftar barang, pelanggan, pemasok, karyawan, gudang, dan akun keuangan. Setiap transaksi, seperti pesanan, faktur, atau pergerakan stok, mengacu pada data induk ini. Jika data induknya ganda, tidak konsisten, atau tidak lengkap, kesalahan menjalar ke seluruh transaksi dan laporan di atasnya." },
  { type: "p", text: "Artikel ini membahas mengapa data induk menentukan keberhasilan ERP, bagaimana menyusun kode barang dan data pelanggan serta pemasok, aturan penamaan yang praktis, dan cara menjaga data tetap bersih setelah sistem berjalan. Kami tidak menggunakan angka rekaan tentang seberapa besar kerugian akibat data buruk; yang kami tawarkan adalah pola kerja dan daftar periksa yang dapat Anda terapkan pada data bisnis Anda sendiri." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Data induk adalah fondasi ERP: barang, pelanggan, pemasok, dan data referensi lain yang dipakai di setiap transaksi",
      "Satu entitas harus punya satu catatan dengan satu kode yang unik, tidak berubah, dan tidak membawa makna yang bisa kedaluwarsa",
      "Tetapkan aturan penamaan dan format yang tertulis agar data konsisten, siapa pun yang mengisinya",
      "Bersihkan dan satukan data lama sebelum dimigrasikan; jangan memindahkan kekacauan ke sistem baru",
      "Tentukan siapa pemilik tiap jenis data dan bagaimana perubahannya disetujui, agar kebersihan data terjaga jangka panjang",
    ],
  },
  { type: "h2", text: "Apa itu data induk dan mengapa penting" },
  { type: "p", text: "Bayangkan dua jenis data dalam bisnis. Yang pertama adalah data transaksi: pesanan penjualan hari ini, faktur pembelian minggu lalu, pergerakan stok pagi tadi. Data ini terus bertambah dan jarang diubah setelah tercatat. Yang kedua adalah data induk: daftar barang yang dijual, daftar pelanggan yang dilayani, dan daftar pemasok tempat Anda membeli. Data ini relatif stabil tetapi dipakai berulang oleh setiap transaksi." },
  { type: "p", text: "Hubungannya seperti buku alamat dan surat. Surat, yaitu transaksi, hanya bisa terkirim dengan benar jika alamat di buku alamat, yaitu data induk, benar. Jika satu pelanggan tercatat tiga kali dengan nama berbeda, riwayat pembeliannya terpecah, tagihannya tersebar, dan Anda tidak bisa melihat seberapa besar sebenarnya pelanggan itu bagi bisnis Anda. Jika satu barang punya dua kode, stoknya terbelah dan laporan persediaan menyesatkan." },
  { type: "p", text: "Karena itu, kualitas data induk menentukan kualitas hampir semua yang dihasilkan ERP. Laporan penjualan per pelanggan, nilai persediaan, analisis margin per produk, dan perencanaan pembelian semuanya bergantung pada data induk yang akurat dan konsisten. Memperbaikinya setelah ribuan transaksi tercatat jauh lebih mahal daripada menyusunnya dengan benar sejak awal." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1542626991-cbc4e32524cc",
    alt: "Tangan menempelkan catatan tempel pada papan perencanaan yang penuh",
    caption: "Menyusun data induk dimulai dari perencanaan di atas kertas: apa yang dicatat, oleh siapa, dan dengan aturan apa.",
  },
  { type: "h2", text: "Jenis data induk yang perlu disiapkan" },
  { type: "p", text: "Setiap bisnis punya kombinasi data induk berbeda, tetapi beberapa jenis hampir selalu ada. Mengenali semuanya sejak awal membantu Anda merencanakan penyusunan data secara menyeluruh, bukan sepotong-sepotong." },
  {
    type: "ul",
    items: [
      "Barang atau produk: kode, nama, kategori, satuan, harga, dan atribut seperti ukuran atau varian",
      "Pelanggan: nama, alamat, kontak, syarat pembayaran, dan pengelompokan",
      "Pemasok: nama, kontak, syarat pembelian, dan barang yang biasa dipasok",
      "Gudang dan lokasi penyimpanan: daftar tempat stok berada dan strukturnya",
      "Karyawan dan jabatan: dasar untuk hak akses dan persetujuan",
      "Daftar akun keuangan: struktur pencatatan untuk laporan keuangan",
      "Data referensi pendukung: satuan ukuran, mata uang, pajak, metode pembayaran, dan wilayah",
    ],
  },
  { type: "p", text: "Dari semua itu, data barang biasanya paling rumit karena variasinya banyak dan paling banyak memengaruhi stok serta keuangan. Pelanggan dan pemasok mengikuti. Mulailah dari yang paling berdampak pada operasional harian Anda, tetapi rencanakan semuanya sejak awal." },
  { type: "h2", text: "Menyusun kode barang yang tahan lama" },
  { type: "p", text: "Kode barang adalah identitas barang di sistem. Kode yang baik membuat pencarian cepat, mencegah duplikasi, dan bertahan bertahun-tahun. Kode yang buruk menimbulkan kebingungan setiap hari. Beberapa prinsip membantu merancangnya." },
  {
    type: "ol",
    items: [
      "Satu barang, satu kode: jangan membuat kode baru untuk barang yang sama hanya karena beda pemasok atau beda gudang",
      "Kode unik dan tidak pernah dipakai ulang: bahkan setelah barang dihentikan, kodenya jangan diberikan ke barang lain",
      "Kode stabil: jangan ubah kode setelah ada transaksi, karena riwayat akan terputus",
      "Pisahkan identitas dari atribut: simpan ukuran, warna, atau kategori di kolom tersendiri, jangan memaksa semuanya masuk ke dalam kode",
      "Pertimbangkan kode yang mudah dibaca dan diketik, dengan panjang yang konsisten",
    ],
  },
  { type: "h3", text: "Kode bermakna atau kode berurutan" },
  { type: "p", text: "Ada dua pendekatan umum. Kode bermakna menyisipkan informasi di dalamnya, misalnya awalan kategori diikuti nomor. Kode ini mudah dikenali manusia, tetapi berisiko: jika kategori barang berubah, kode menjadi menyesatkan atau harus diganti. Kode berurutan hanyalah nomor unik tanpa makna, aman dari perubahan, tetapi kurang informatif bagi mata manusia." },
  { type: "p", text: "Banyak bisnis memilih jalan tengah: kode berurutan sebagai identitas utama, ditambah kolom atribut yang terstruktur untuk kategori, merek, dan varian, sehingga pencarian dan pengelompokan dilakukan lewat atribut, bukan lewat membaca kode. Jika Anda menggunakan barcode, selaraskan dengan kode internal agar pemindaian di gudang dan kasir langsung cocok dengan catatan sistem." },
  { type: "h3", text: "Menangani varian" },
  { type: "p", text: "Barang yang punya variasi, seperti kaos dengan beberapa ukuran dan warna, perlu perhatian khusus. Pisahkan barang induk dari variannya: satu barang induk dengan nama dan deskripsi, lalu beberapa varian dengan kode dan stok masing-masing. Dengan struktur ini, laporan bisa dilihat pada tingkat produk maupun tingkat varian, dan stok per ukuran tercatat tepat." },
  { type: "h2", text: "Data pelanggan dan pemasok yang bersih" },
  { type: "p", text: "Pelanggan dan pemasok adalah pihak luar yang berinteraksi dengan bisnis Anda, dan datanya sering bocor dari banyak arah: tim penjualan mencatat di satu tempat, bagian keuangan di tempat lain, dan gudang di tempat ketiga. Hasilnya duplikasi dan ketidakkonsistenan yang sulit diurai setelah menumpuk." },
  { type: "p", text: "Mulailah dengan menetapkan apa yang dianggap satu pihak. Apakah cabang berbeda dari perusahaan induknya diperlakukan sebagai pelanggan terpisah atau satu pelanggan dengan beberapa alamat? Keputusan ini memengaruhi penagihan, laporan, dan syarat pembayaran. Tetapkan juga data minimum yang wajib diisi, seperti nama resmi, alamat, kontak, dan syarat pembayaran, agar catatan tidak setengah jadi." },
  { type: "p", text: "Untuk mencegah duplikasi, biasakan mencari sebelum membuat. Sebelum menambah pelanggan baru, petugas wajib memeriksa apakah sudah ada catatan serupa. Sistem yang baik membantu dengan peringatan jika nama, nomor telepon, atau nomor identitas usaha mirip dengan catatan yang sudah ada. Pertimbangkan pula identitas unik yang tidak ambigu, seperti nomor identitas usaha untuk pelanggan perusahaan, sebagai kunci pembeda." },
  { type: "p", text: "Karena data pelanggan dan pemasok sering memuat informasi pribadi, perlakukan dengan hati-hati. Batasi siapa yang boleh melihat dan mengubahnya, dan patuhi ketentuan perlindungan data pribadi yang berlaku. Rujuklah ketentuan terbaru dari otoritas yang berwenang, jangan mengandalkan ringkasan yang mungkin sudah usang." },
  {
    type: "callout",
    title: "Cek sebelum membuat",
    text: "Aturan paling sederhana untuk menekan duplikasi adalah mewajibkan pencarian sebelum menambah catatan baru. Biasakan ini sebagai bagian dari prosedur, bukan imbauan.",
  },
  { type: "h2", text: "Aturan penamaan dan format yang konsisten" },
  { type: "p", text: "Tanpa aturan, data yang diisi banyak orang pasti beragam. Satu orang menulis \"PT Maju Jaya\", yang lain \"Maju Jaya, PT\", yang ketiga \"PT. MAJU JAYA\". Bagi manusia, ketiganya jelas sama; bagi sistem, itu tiga catatan berbeda. Aturan penamaan tertulis mencegah hal ini." },
  { type: "p", text: "Tentukan hal-hal seperti urutan penulisan nama perusahaan, penggunaan huruf besar dan kecil, singkatan yang dibolehkan, format alamat, format nomor telepon, dan satuan ukuran yang baku. Untuk barang, tentukan pola nama yang seragam, misalnya jenis barang diikuti merek, ukuran, lalu varian. Pola yang konsisten membuat pencarian dan pengurutan bekerja dengan baik." },
  { type: "p", text: "Gunakan pilihan terkontrol bila memungkinkan. Daripada membiarkan kolom satuan diisi bebas, sediakan daftar pilihan seperti buah, kotak, kilogram. Daftar pilihan menghilangkan variasi penulisan dan mempermudah laporan. Hal yang sama berlaku untuk kategori, wilayah, dan metode pembayaran." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1556155092-490a1ba16284",
    alt: "Tangan mengetik di laptop yang menampilkan dasbor tabel di sebuah kafe",
    caption: "Tampilan dasbor yang rapi hanya bisa dipercaya jika data induk di baliknya konsisten.",
  },
  { type: "h3", text: "Dokumentasikan dalam panduan singkat" },
  { type: "p", text: "Tuliskan aturan di atas dalam satu panduan singkat yang mudah dicari, lengkap dengan contoh benar dan salah. Panduan satu sampai dua halaman yang benar-benar dibaca lebih berguna daripada dokumen tebal yang dilupakan. Berikan kepada setiap orang yang akan menambah atau mengubah data, dan perbarui ketika aturan berubah." },
  { type: "h2", text: "Membersihkan data lama sebelum migrasi" },
  { type: "p", text: "Ketika bisnis pindah dari spreadsheet atau sistem lama ke ERP, godaan terbesar adalah memindahkan semuanya apa adanya. Padahal ini kesempatan terbaik untuk membersihkan. Data yang berantakan di sistem lama akan menjadi data yang berantakan di sistem baru, hanya dengan wajah yang lebih mahal." },
  { type: "p", text: "Mulailah dengan inventarisasi: di mana saja data induk Anda tersimpan? Biasanya tersebar di banyak spreadsheet, sistem kasir lama, program akuntansi, dan catatan pribadi karyawan. Kumpulkan semuanya dan bandingkan. Cari duplikasi, data tidak lengkap, format yang tidak konsisten, dan catatan yang sudah tidak aktif." },
  { type: "p", text: "Lalu bersihkan secara bertahap. Gabungkan catatan ganda dengan hati-hati, putuskan catatan mana yang menjadi induk dan pindahkan riwayat yang relevan. Lengkapi data wajib yang kosong. Seragamkan format sesuai aturan penamaan. Nonaktifkan, bukan hapus, barang dan pihak yang sudah tidak dipakai agar riwayat transaksinya tetap utuh. Dan jangan memigrasikan yang memang tidak diperlukan; sistem baru adalah momen yang tepat untuk melepas beban lama." },
  { type: "p", text: "Setelah dibersihkan, uji impor dengan sebagian kecil data lebih dulu. Periksa hasilnya di sistem baru, perbaiki aturan pemetaan jika ada masalah, lalu lakukan migrasi penuh. Topik migrasi data ini kami bahas lebih lengkap di artikel kami tentang persiapan migrasi data ke sistem baru." },
  { type: "h3", text: "Libatkan orang yang paling mengenal datanya" },
  { type: "p", text: "Pembersihan sebaiknya melibatkan mereka yang sehari-hari memakai data itu: petugas gudang yang tahu barang mana yang sebenarnya sama, tim penjualan yang paham pelanggan mana yang sudah tidak aktif, bagian pembelian yang kenal pemasok. Bantuan tim teknis penting untuk alat dan skrip, tetapi keputusan tentang isi data sebaiknya datang dari yang paling memahaminya." },
  { type: "h2", text: "Tata kelola: siapa memiliki data apa" },
  { type: "p", text: "Data yang bersih saat peluncuran bisa kembali kotor dalam beberapa bulan jika tidak ada yang bertanggung jawab. Tata kelola data terdengar berat, tetapi untuk bisnis kecil dan menengah cukup dirumuskan sederhana: tentukan pemilik tiap jenis data dan cara perubahannya disetujui." },
  { type: "p", text: "Pemilik data adalah orang atau bagian yang bertanggung jawab atas kebenarannya. Data barang mungkin dimiliki bagian gudang atau pembelian, data pelanggan oleh tim penjualan, data pemasok oleh bagian pembelian, dan daftar akun oleh keuangan. Pemilik tidak harus mengetik semuanya, tetapi merekalah yang memutuskan aturan dan menyetujui perubahan penting." },
  { type: "p", text: "Atur hak akses dengan prinsip sesedikit mungkin. Tidak semua orang perlu bisa membuat atau mengubah data induk. Semakin banyak orang yang bisa menambah barang atau pelanggan baru, semakin besar kemungkinan duplikasi. Pertimbangkan alur persetujuan untuk perubahan sensitif, seperti mengubah syarat pembayaran pelanggan atau rekening bank pemasok, karena perubahan semacam itu juga menyangkut risiko kecurangan. Catat siapa mengubah apa dan kapan, supaya ada jejak yang bisa ditelusuri." },
  { type: "p", text: "Jadwalkan pemeriksaan kebersihan data secara berkala, misalnya per kuartal. Cari catatan ganda baru, data wajib yang kosong, dan catatan yang sudah lama tidak dipakai. Pemeriksaan rutin kecil jauh lebih murah daripada pembersihan besar setahun sekali." },
  { type: "h2", text: "Dampak data induk pada laporan dan keputusan" },
  { type: "p", text: "Manfaat data induk yang rapi terasa langsung pada laporan. Laporan penjualan per pelanggan menjadi dapat dipercaya karena satu pelanggan hanya tercatat sekali. Analisis margin per produk bisa dilakukan karena satu barang punya satu catatan dengan biaya dan harga yang jelas. Perencanaan stok dan pembelian ulang menjadi akurat karena stok tidak terbelah antar kode yang berbeda." },
  { type: "p", text: "Sebaliknya, data induk yang buruk membuat manajer ragu pada angka di layar. Ketika dua laporan menunjukkan angka berbeda untuk hal yang sama, atau ketika orang harus mengoreksi laporan dengan tangan sebelum dipercaya, ERP kehilangan nilai utamanya. Orang akan kembali ke spreadsheet pribadi, dan data kembali tersebar. Kebersihan data induk adalah penjaga kepercayaan terhadap sistem." },
  { type: "h2", text: "Kesalahan umum yang perlu dihindari" },
  { type: "p", text: "Beberapa kesalahan sering terjadi. Membuat kode yang terlalu pintar, penuh makna tersirat yang cepat kedaluwarsa, adalah salah satunya. Membiarkan siapa saja menambah data tanpa aturan adalah yang lain. Memigrasikan data kotor dengan alasan akan dibersihkan nanti hampir selalu berarti tidak pernah dibersihkan. Mengabaikan varian sehingga stok per ukuran tidak tercatat, menghapus catatan lama alih-alih menonaktifkannya, dan tidak menunjuk pemilik data juga sering terjadi." },
  { type: "p", text: "Kesalahan lain adalah menganggap penyusunan data induk sebagai tugas teknis semata. Ia adalah pekerjaan bisnis yang butuh keputusan tentang definisi: apa itu pelanggan, apa itu satu barang, bagaimana varian dikelompokkan. Keputusan ini harus datang dari pemilik proses, dengan tim teknis sebagai pendukung." },
  { type: "h2", text: "Langkah praktis menyiapkan data induk" },
  {
    type: "ol",
    items: [
      "Inventarisasi semua tempat data barang, pelanggan, dan pemasok Anda tersimpan saat ini",
      "Tetapkan definisi dan aturan: apa yang dianggap satu barang, satu pelanggan, satu pemasok",
      "Rancang skema kode barang yang unik dan stabil, serta pisahkan atribut dari kode",
      "Tulis panduan penamaan dan format satu atau dua halaman, lengkap dengan contoh",
      "Bersihkan, gabungkan, dan lengkapi data lama sebelum migrasi, lalu uji impor dengan sampel kecil",
      "Tunjuk pemilik data, atur hak akses, dan jadwalkan pemeriksaan kebersihan berkala",
    ],
  },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "ERP yang berhasil bukan sekadar yang fiturnya lengkap, melainkan yang datanya dapat dipercaya. Data induk adalah fondasinya: jika fondasi itu retak, bangunan di atasnya akan terus bermasalah, seindah apa pun tampilannya. Waktu yang diinvestasikan untuk menyusun kode, aturan, dan tata kelola data sebelum peluncuran akan terbayar berkali-kali lewat laporan yang akurat dan keputusan yang lebih yakin." },
  { type: "p", text: "Jika bisnis Anda sedang mempertimbangkan ERP atau ingin merapikan data yang sudah menumpuk, mulailah dari data induk. Itu langkah yang tidak glamor, tetapi sering menjadi pembeda antara proyek yang berjalan mulus dan yang berlarut-larut." },
  {
    type: "cta",
    title: "Ingin menerapkan ERP dengan data yang rapi sejak awal?",
    text: "Tim AG·SORA membantu menyusun data induk, membersihkan data lama, dan memigrasikannya ke sistem ERP yang sesuai dengan proses bisnis Anda. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/erp",
    label: "Konsultasi gratis",
  },
];
