import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Pindah ke cloud sering dijual dengan janji sederhana: bayar sesuai pemakaian, tanpa membeli server, tanpa repot merawat perangkat keras. Janji itu benar, tetapi ada sisi lain yang jarang dibicarakan di awal. Karena tagihan mengikuti pemakaian, biaya bisa naik tanpa terasa seiring bertambahnya pengguna, data, dan fitur. Banyak bisnis terkejut ketika tagihan bulanan melonjak jauh dari perkiraan awal, padahal tidak ada keputusan besar yang diambil." },
  { type: "p", text: "Masalahnya biasanya bukan cloud itu mahal, melainkan biaya tidak diawasi. Sumber daya yang dibuat untuk percobaan dibiarkan menyala, penyimpanan menumpuk, ukuran server dipilih terlalu besar demi aman, dan tidak ada yang tahu siapa yang bertanggung jawab atas pos mana. Mengendalikan biaya cloud pada dasarnya adalah soal kebiasaan dan struktur, bukan soal mencari harga termurah." },
  { type: "p", text: "Artikel ini membahas cara memahami dan mengendalikan biaya cloud untuk bisnis kecil dan menengah. Kami membahas komponen tagihan, kebiasaan pemborosan yang umum, cara menyesuaikan ukuran, pilihan model harga, pengelolaan penyimpanan dan transfer data, pembatas dan peringatan anggaran, serta pertimbangan antara biaya dan keandalan. Kami tidak memakai angka rekaan tentang penghematan; yang kami tawarkan adalah prinsip dan daftar periksa yang bisa diterapkan pada penyedia mana pun." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Pahami dulu dari mana tagihan berasal sebelum mencoba menghemat",
      "Beri label pada setiap sumber daya agar jelas siapa pemilik dan tujuannya",
      "Sesuaikan ukuran dengan pemakaian nyata dan matikan yang tidak dipakai",
      "Pasang anggaran dan peringatan agar lonjakan terlihat dalam hitungan hari, bukan di akhir bulan",
      "Imbangi penghematan dengan keandalan dan keamanan; jangan memangkas yang melindungi bisnis",
    ],
  },
  { type: "h2", text: "Mengapa biaya cloud mudah membengkak" },
  { type: "p", text: "Di dunia server fisik, pengeluaran besar terjadi sekali dan melewati persetujuan. Di cloud, siapa pun dengan akses dapat menyalakan sumber daya baru dalam hitungan menit, tanpa melewati pengadaan. Kemudahan itu adalah kekuatan sekaligus jebakan. Setiap percobaan kecil yang lupa dimatikan terus menagih, dan karena nilainya kecil per jam, jarang ada yang memperhatikannya." },
  { type: "p", text: "Penyebab lain adalah pertumbuhan yang tidak disadari. Data yang disimpan terus bertambah dan jarang dihapus. Log yang dicatat setiap detik menumpuk. Cadangan dibuat harian tanpa kebijakan masa simpan. Fitur baru menambah panggilan antar layanan dan lalu lintas data. Masing-masing wajar, tetapi gabungannya membuat tagihan merangkak naik." },
  { type: "p", text: "Selain itu, struktur harga cloud memang rumit. Ada biaya komputasi, penyimpanan, basis data, transfer keluar, layanan terkelola, alamat jaringan, dan banyak lagi. Satu keputusan teknis yang tampak sepele, seperti menempatkan dua layanan di wilayah berbeda, dapat menimbulkan biaya transfer yang tidak terduga. Karena itu pemahaman dasar tentang komponen tagihan sangat berguna bahkan bagi pemilik bisnis nonteknis." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b",
    alt: "Papan sirkuit bercahaya dengan jalur-jalur rangkaian, tampak miring",
    caption: "Di balik layanan cloud ada perangkat nyata; setiap sumber daya yang menyala punya harga, dipakai atau tidak.",
  },
  { type: "h2", text: "Memahami komponen tagihan" },
  { type: "p", text: "Langkah pertama pengendalian adalah membaca tagihan seperti membaca laporan keuangan. Kelompokkan biaya ke dalam kategori besar, lalu lihat mana yang terbesar dan mana yang tumbuh paling cepat. Jangan mulai dari mengoptimalkan hal kecil yang tampak mudah; mulailah dari pos yang mendominasi." },
  { type: "ol", items: [
    "Komputasi: server virtual, kontainer, dan fungsi yang menjalankan aplikasi, ditagih menurut ukuran dan lama pemakaian",
    "Penyimpanan: berkas, gambar, cadangan, dan arsip, ditagih menurut volume dan kelas penyimpanan",
    "Basis data: layanan basis data terkelola, ditagih menurut ukuran, kapasitas, dan jumlah salinan",
    "Jaringan: transfer data keluar dari penyedia atau antarwilayah, alamat tetap, dan penyeimbang beban",
    "Layanan terkelola: antrean, pencarian, analitik, dan layanan lain yang ditagih menurut pemakaian masing-masing",
    "Dukungan dan lisensi: paket dukungan dari penyedia dan perangkat lunak berlisensi yang berjalan di atasnya",
  ] },
  { type: "p", text: "Banyak penyedia menyediakan alat untuk memecah tagihan per layanan, per proyek, atau per label. Gunakan fitur itu secara rutin, bukan hanya saat tagihan terasa terlalu tinggi. Meninjau tagihan setiap minggu memberi gambaran tren yang jauh lebih baik daripada kejutan setiap akhir bulan." },
  { type: "h2", text: "Memberi label dan menentukan pemilik" },
  { type: "p", text: "Tagihan yang hanya menampilkan satu angka besar tidak bisa ditindaklanjuti. Pemberian label atau tag pada setiap sumber daya mengubah angka itu menjadi informasi: sumber daya ini milik proyek apa, untuk lingkungan apa, siapa penanggung jawabnya, dan untuk tujuan apa. Dengan label yang konsisten, Anda bisa menjawab pertanyaan seperti berapa biaya lingkungan pengujian bulan ini atau berapa biaya satu pelanggan besar." },
  { type: "ul", items: [
    "Tetapkan daftar label baku, misalnya proyek, lingkungan, pemilik, dan pusat biaya",
    "Wajibkan label saat sumber daya dibuat, bukan menambahkan belakangan",
    "Periksa berkala sumber daya tanpa label atau tanpa pemilik yang jelas",
    "Tinjau sumber daya yang pemiliknya sudah tidak ada di perusahaan",
    "Gunakan akun atau proyek terpisah untuk produksi dan percobaan agar biaya tidak bercampur",
  ] },
  { type: "p", text: "Pemilik yang jelas juga mengubah budaya. Ketika biaya tiap tim terlihat, keputusan teknis mulai mempertimbangkan harga. Tujuannya bukan menghukum, melainkan membuat biaya menjadi bagian dari percakapan sehari-hari sehingga tim memilih solusi yang seimbang antara kinerja dan pengeluaran." },
  { type: "h2", text: "Menemukan dan menghentikan pemborosan" },
  { type: "p", text: "Dalam banyak lingkungan cloud, sebagian pengeluaran jatuh ke sumber daya yang tidak lagi dipakai. Pemborosan semacam ini adalah sasaran pertama karena menghapusnya tidak mengurangi layanan apa pun. Periksa secara berkala beberapa kategori yang paling sering menjadi biang." },
  { type: "ul", items: [
    "Server percobaan dan lingkungan pengembangan yang tetap menyala di luar jam kerja",
    "Disk dan penyimpanan yang tidak terpasang pada server mana pun",
    "Salinan cadangan lama yang melewati masa simpan yang dibutuhkan",
    "Alamat jaringan tetap dan penyeimbang beban yang tidak lagi melayani lalu lintas",
    "Basis data percobaan yang ditinggalkan setelah proyek selesai",
    "Log dan data analitik yang disimpan tanpa batas waktu padahal tidak pernah dibaca",
  ] },
  { type: "p", text: "Jadwalkan penghentian otomatis untuk lingkungan nonproduksi. Lingkungan pengembangan dan pengujian umumnya hanya dipakai pada jam kerja, sehingga mematikannya malam dan akhir pekan menghilangkan bagian besar dari biayanya tanpa mengganggu siapa pun. Pastikan prosesnya mudah dihidupkan kembali agar tim tidak keberatan." },
  { type: "p", text: "Sebelum menghapus sesuatu, pastikan tidak ada yang bergantung padanya. Ada kisah klasik tentang server yang tampak menganggur tetapi ternyata menjalankan tugas terjadwal penting setiap akhir bulan. Cara aman adalah menghentikan dulu, menunggu beberapa waktu, dan baru menghapus jika tidak ada yang mengeluh. Simpan salinan data penting sebelum menghapus." },
  { type: "h2", text: "Menyesuaikan ukuran dengan kebutuhan nyata" },
  { type: "p", text: "Orang cenderung memilih ukuran server lebih besar dari yang dibutuhkan demi rasa aman, lalu tidak pernah memeriksanya lagi. Padahal cloud memungkinkan perubahan ukuran dengan relatif mudah. Lihat data pemakaian prosesor, memori, dan lalu lintas selama periode yang cukup mewakili, termasuk puncak musiman. Jika pemakaian rata-rata selalu jauh di bawah kapasitas dan puncaknya pun masih longgar, ukuran bisa diturunkan." },
  { type: "p", text: "Lakukan penurunan ukuran bertahap dan pantau dampaknya. Turunkan satu tingkat, amati beberapa hari, lalu putuskan apakah perlu lanjut. Hindari memangkas hingga tidak ada penyangga sama sekali, karena lonjakan trafik tak terduga bisa membuat layanan lambat atau mati tepat ketika pelanggan paling banyak." },
  { type: "p", text: "Pertimbangkan juga skala otomatis untuk beban yang naik turun. Alih-alih menyediakan kapasitas puncak sepanjang waktu, sistem menambah kapasitas saat ramai dan menguranginya saat sepi. Namun skala otomatis perlu dirancang dan diuji dengan baik, karena aturan yang salah bisa menambah kapasitas berlebihan ketika terjadi kesalahan, yang justru menaikkan tagihan." },
  { type: "h3", text: "Memilih jenis layanan yang sesuai" },
  { type: "p", text: "Tidak semua beban kerja cocok dengan server yang menyala terus. Tugas yang hanya berjalan sesekali, seperti membuat laporan malam atau memproses unggahan, kadang lebih murah dijalankan sebagai fungsi atau tugas berjadwal yang hanya ditagih saat berjalan. Sebaliknya, beban stabil yang berjalan sepanjang hari biasanya lebih murah di server dengan harga komitmen. Pilih berdasarkan pola beban, bukan mengikuti tren." },
  { type: "h2", text: "Memilih model harga yang tepat" },
  { type: "p", text: "Sebagian besar penyedia menawarkan beberapa model harga untuk sumber daya yang sama. Harga sesuai permintaan memberi fleksibilitas penuh tanpa komitmen, tetapi biasanya paling mahal per satuan. Komitmen jangka tertentu atau komitmen pemakaian menawarkan tarif lebih rendah sebagai imbalan janji menggunakan kapasitas tertentu. Kapasitas sisa yang bisa diambil kembali oleh penyedia menawarkan harga terendah, tetapi cocok hanya untuk pekerjaan yang tahan terhadap gangguan." },
  { type: "ul", items: [
    "Sesuai permintaan: cocok untuk beban yang belum pasti atau baru dimulai",
    "Komitmen jangka tertentu: cocok untuk beban stabil yang yakin akan berjalan lama, seperti basis data utama",
    "Kapasitas sisa: cocok untuk pemrosesan data besar atau tugas yang bisa dilanjutkan bila terhenti",
    "Paket gabungan atau diskon volume: layak ditanyakan bila pengeluaran sudah cukup besar",
  ] },
  { type: "p", text: "Berhati-hatilah dengan komitmen. Komitmen yang terlalu besar atau terlalu lama bisa menjadi beban bila kebutuhan berubah. Mulailah dengan komitmen untuk bagian yang paling stabil, dan biarkan sisanya fleksibel. Baca syarat pembatalan dan perubahan sebelum menandatangani, dan catat tanggal berakhirnya agar tidak berlanjut otomatis tanpa dipertimbangkan." },
  { type: "h2", text: "Mengelola penyimpanan dan transfer data" },
  { type: "p", text: "Penyimpanan tampak murah per unit, tetapi volumenya tumbuh diam-diam. Terapkan kebijakan siklus hidup: data yang sering diakses disimpan di kelas yang cepat, data yang jarang dibuka dipindahkan ke kelas yang lebih murah, dan data yang sudah melewati masa wajib simpan dihapus. Banyak penyedia mendukung aturan otomatis untuk ini sehingga tidak perlu dikerjakan manual." },
  { type: "p", text: "Tinjau juga apa yang sebenarnya perlu disimpan. Gambar berukuran asli yang besar bisa dikompres dan dibuat dalam beberapa ukuran. Log yang rinci mungkin cukup disimpan beberapa minggu, lalu diringkas. Cadangan harian mungkin cukup dipertahankan untuk periode tertentu, dengan cadangan bulanan untuk jangka lebih panjang. Pertimbangkan kebutuhan hukum dan bisnis sebelum memutuskan masa simpan, dan periksa ketentuan yang berlaku saat ini bila menyangkut data pribadi atau keuangan." },
  { type: "p", text: "Transfer data keluar dari penyedia sering menjadi biaya kejutan. Lalu lintas dalam satu wilayah biasanya murah atau gratis, sedangkan lalu lintas ke internet atau ke wilayah lain ditagih. Letakkan layanan yang sering berkomunikasi di wilayah yang sama, gunakan jaringan pengiriman konten untuk berkas statis, dan kompres respons. Perhatikan pula biaya jika suatu saat Anda ingin memindahkan data besar ke penyedia lain." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
    alt: "Layar laptop menampilkan grafik dan laporan analitik bisnis",
    caption: "Biaya cloud baru bisa dikendalikan ketika tren per layanan dan per proyek terlihat jelas.",
  },
  { type: "h2", text: "Anggaran, peringatan, dan kebiasaan tinjauan" },
  { type: "p", text: "Pengendalian biaya yang paling efektif adalah yang tidak bergantung pada ingatan. Pasang anggaran bulanan per proyek atau per lingkungan, lalu atur peringatan pada beberapa ambang, misalnya ketika pemakaian mencapai separuh, tiga perempat, dan seluruh anggaran, serta ketika proyeksi akhir bulan melampaui anggaran. Peringatan sebaiknya masuk ke saluran yang dibaca tim, bukan hanya ke kotak surel satu orang." },
  { type: "p", text: "Pasang juga deteksi anomali bila tersedia. Lonjakan mendadak biasanya menandakan sesuatu yang salah: kode yang masuk gelung tak terbatas, kunci akses yang bocor dan dipakai penyerang untuk menambang, atau pengunggahan data besar yang tidak disengaja. Mengetahui dalam hitungan jam jauh lebih murah daripada menemukan di akhir bulan." },
  { type: "ol", items: [
    "Setiap minggu: lihat tren biaya per layanan dan bandingkan dengan minggu sebelumnya",
    "Setiap bulan: tinjau sumber daya tanpa label, pemakaian rendah, dan peluang penurunan ukuran",
    "Setiap kuartal: nilai ulang model harga dan komitmen, serta bandingkan biaya dengan pertumbuhan bisnis",
    "Setiap kali ada fitur besar: perkirakan dampaknya pada biaya sebelum diluncurkan",
    "Setiap tahun: tinjau arsitektur dan pilihan penyedia secara menyeluruh",
  ] },
  { type: "callout", title: "Biaya adalah metrik, bukan kejutan", text: "Perlakukan biaya cloud seperti metrik operasional lain: dipantau rutin, punya pemilik, punya ambang peringatan, dan dikaitkan dengan nilai bisnis yang dihasilkannya." },
  { type: "h2", text: "Menghubungkan biaya dengan nilai bisnis" },
  { type: "p", text: "Angka tagihan mutlak kurang bermakna tanpa pembanding. Tagihan yang naik karena bisnis tumbuh adalah kabar baik, sedangkan tagihan yang naik tanpa pertumbuhan menandakan pemborosan. Hubungkan biaya dengan ukuran yang bermakna bagi bisnis, seperti biaya per pesanan, per pengguna aktif, atau per transaksi. Tren ukuran satuan ini menunjukkan apakah sistem makin efisien atau tidak." },
  { type: "p", text: "Pendekatan ini juga membantu menentukan harga dan keputusan produk. Jika Anda tahu berapa biaya melayani satu pelanggan, Anda bisa menilai apakah paket harga tertentu masih menguntungkan, fitur mana yang mahal tetapi jarang dipakai, dan pelanggan mana yang membebani sistem secara tidak proporsional. Tanpa data itu, keputusan harga hanya tebakan." },
  { type: "h2", text: "Jangan menghemat dengan mengorbankan keandalan dan keamanan" },
  { type: "p", text: "Dorongan menghemat bisa menyesatkan. Memangkas cadangan, mematikan redundansi, atau menunda pembaruan keamanan memang menurunkan tagihan, tetapi membuka risiko yang biaya akibatnya jauh lebih besar. Tentukan terlebih dahulu bagian mana yang melindungi bisnis, seperti cadangan, pemantauan, pemisahan akses, dan salinan data di lokasi terpisah, lalu hemat dari bagian lain." },
  { type: "p", text: "Pertimbangan serupa berlaku untuk kapasitas penyangga. Sistem yang berjalan terlalu mepet kapasitas rentan terhadap lonjakan tiba-tiba dan membuat setiap gangguan kecil menjadi besar. Sedikit kapasitas cadangan adalah harga yang wajar untuk ketenangan dan kinerja yang stabil. Ukurannya sebaiknya diputuskan dengan data dan kesepakatan tentang seberapa lama bisnis boleh terganggu." },
  { type: "p", text: "Keamanan juga berkaitan langsung dengan biaya. Kunci akses yang bocor sering dimanfaatkan untuk menyalakan sumber daya besar yang menghasilkan tagihan mengejutkan. Praktik dasar seperti hak akses minimal, rotasi kunci, autentikasi berlapis, dan pembatasan penyalahgunaan bukan hanya soal keamanan, tetapi juga perlindungan anggaran." },
  { type: "h2", text: "Kapan layak mempertimbangkan opsi lain" },
  { type: "p", text: "Cloud bukan satu-satunya pilihan, dan bukan selalu yang termurah. Untuk beban yang sangat stabil, sangat besar, dan sudah dipahami, kadang menjalankan perangkat sendiri atau menyewa server khusus lebih murah, dengan konsekuensi tanggung jawab perawatan yang lebih besar. Untuk bisnis kecil, layanan terkelola atau platform siap pakai sering lebih ekonomis bila waktu tim dihitung." },
  { type: "p", text: "Pertimbangkan ketergantungan pada penyedia. Semakin dalam Anda memakai layanan khas satu penyedia, semakin sulit dan mahal berpindah. Itu bukan alasan menghindarinya sama sekali, karena layanan terkelola sering menghemat waktu besar, tetapi sebaiknya menjadi keputusan sadar dengan memahami biaya keluarnya. Dokumentasikan arsitektur agar pilihan berpindah tetap terbuka." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Membiarkan siapa pun membuat sumber daya tanpa label dan tanpa pemilik",
    "Menyalakan lingkungan percobaan dan lupa mematikannya",
    "Memilih ukuran besar demi aman dan tidak pernah meninjaunya kembali",
    "Mengambil komitmen jangka panjang sebelum beban kerja stabil",
    "Menunggu tagihan akhir bulan untuk mengetahui adanya lonjakan",
    "Menghemat dengan memangkas cadangan atau pemantauan",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Unduh rincian tagihan satu bulan terakhir dan urutkan dari yang terbesar",
    "Tetapkan daftar label baku dan perbaiki sumber daya yang belum berlabel",
    "Matikan atau jadwalkan penghentian lingkungan percobaan di luar jam kerja",
    "Pasang anggaran dan peringatan pada ambang bertahap serta deteksi lonjakan",
    "Jadwalkan tinjauan biaya mingguan singkat dengan penanggung jawab yang jelas",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Biaya cloud yang sehat tidak lahir dari satu kali penghematan besar, melainkan dari kebiasaan kecil yang konsisten: membaca tagihan, memberi label, mematikan yang tidak dipakai, menyesuaikan ukuran, memilih model harga yang tepat, dan memasang peringatan. Semua itu dilakukan tanpa mengorbankan keandalan dan keamanan yang melindungi bisnis." },
  { type: "p", text: "Mulailah dari pos terbesar, beri setiap sumber daya pemilik, dan hubungkan biaya dengan nilai bisnis. Dengan begitu cloud tetap menjadi alat yang membantu bisnis tumbuh, bukan sumber kejutan setiap akhir bulan." },
  {
    type: "cta",
    title: "Ingin infrastruktur cloud yang dirancang efisien dan terkendali biayanya?",
    text: "Tim AG·SORA membantu merancang, memigrasikan, dan merawat sistem di cloud dengan pemantauan biaya, arsitektur yang efisien, dan keamanan yang tepat. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/custom-software",
    label: "Konsultasi gratis",
  },
];
