import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Banyak pemilik bisnis membayangkan peluncuran aplikasi mobile sebagai satu tombol: aplikasi selesai dibuat, ditekan unggah, lalu keesokan harinya pelanggan bisa memasangnya. Kenyataannya, antara aplikasi yang sudah jadi dan aplikasi yang bisa diunduh publik ada serangkaian pekerjaan yang tidak ada hubungannya dengan menulis kode, tetapi sama menentukannya." },
  { type: "p", text: "Toko aplikasi milik Apple dan Google adalah pintu yang dijaga. Keduanya menetapkan syarat tentang akun penerbit, informasi yang harus diisi, cara aplikasi menangani data pengguna, hingga cara aplikasi menerima pembayaran. Aplikasi yang tidak memenuhinya ditolak atau ditahan, sering tepat beberapa hari sebelum tanggal peluncuran yang sudah diumumkan ke pelanggan." },
  { type: "p", text: "Artikel ini membahas apa saja yang perlu disiapkan pemilik bisnis untuk merilis aplikasi ke App Store dan Google Play, serta cara mengelola pembaruan sesudahnya. Kami membahas kepemilikan akun, materi halaman toko, privasi, proses tinjauan, pengujian sebelum rilis, peluncuran bertahap, dan pemeliharaan. Ketentuan kedua toko berubah dari waktu ke waktu, jadi rujuklah pedoman resmi terbaru untuk rincian; yang kami sampaikan di sini adalah kerangka persiapannya." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Akun penerbit harus dimiliki bisnis Anda sendiri, bukan pengembang atau karyawan perorangan",
      "Siapkan materi halaman toko sejak awal: nama, deskripsi, tangkapan layar, dan kebijakan privasi",
      "Pelajari pedoman tinjauan sebelum membangun fitur, terutama soal data pribadi dan pembayaran",
      "Uji lewat jalur uji resmi dan luncurkan bertahap agar masalah tertangkap lebih dini",
      "Anggarkan pemeliharaan rutin karena sistem operasi dan aturan toko terus berubah",
    ],
  },
  { type: "h2", text: "Merilis aplikasi adalah proyek tersendiri" },
  { type: "p", text: "Tim yang baru pertama kali merilis aplikasi sering menyisakan hanya beberapa hari untuk urusan toko aplikasi. Ini hampir selalu terlalu sedikit. Pendaftaran akun bisa memerlukan verifikasi identitas dan dokumen badan usaha. Tinjauan pertama bisa menghasilkan permintaan perbaikan. Materi visual perlu dibuat untuk beberapa ukuran layar. Semua ini memakan waktu yang tidak bisa dipercepat dengan menambah programmer." },
  { type: "p", text: "Karena itu masukkan pekerjaan rilis ke dalam rencana proyek sejak hari pertama, lengkap dengan penanggung jawabnya. Sebagian pekerjaan, seperti pendaftaran akun dan penulisan kebijakan privasi, bisa dimulai jauh sebelum aplikasi selesai. Menjalankannya sejajar dengan pengembangan menghindarkan Anda dari minggu terakhir yang penuh kejutan." },
  { type: "p", text: "Jangan umumkan tanggal peluncuran pasti kepada publik sebelum aplikasi lolos tinjauan. Lebih aman mengumumkan rentang waktu, lalu menetapkan tanggal setelah aplikasi disetujui dan siap dirilis. Kedua toko memungkinkan Anda menahan aplikasi yang sudah disetujui dan merilisnya pada saat yang Anda pilih." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1555774698-0b77e0d5fac6",
    alt: "Tangan memegang ponsel yang menampilkan layar utama penuh ikon aplikasi",
    caption: "Agar ikon aplikasi Anda sampai ke layar pelanggan, ia harus melewati pintu toko aplikasi lebih dulu.",
  },
  { type: "h2", text: "Akun penerbit: siapa pemiliknya" },
  { type: "p", text: "Untuk menerbitkan aplikasi, Anda memerlukan akun penerbit di masing-masing toko. Akun inilah yang secara resmi memiliki aplikasi, ulasan, data unduhan, dan hubungan dengan penggunanya. Keputusan terpenting di tahap ini sangat sederhana, tetapi sering keliru: akun harus atas nama bisnis Anda, dengan alamat surel yang dikendalikan perusahaan." },
  { type: "p", text: "Aplikasi yang diterbitkan lewat akun pribadi pengembang atau akun milik vendor menempatkan Anda dalam posisi lemah. Jika hubungan kerja berakhir kurang baik, memindahkan aplikasi ke akun lain memang mungkin, tetapi memerlukan kerja sama pemilik akun lama. Dalam keadaan terburuk, Anda harus menerbitkan aplikasi baru dan meminta semua pengguna memasang ulang." },
  { type: "p", text: "Daftarkan akun sebagai organisasi bila memenuhi syarat, sehingga nama perusahaan yang tampil sebagai penerbit. Undang pengembang atau vendor sebagai anggota dengan hak akses yang sesuai perannya. Simpan kredensial utama dan kunci penandatanganan aplikasi di tempat yang dikelola perusahaan, dan aktifkan verifikasi dua langkah." },
  { type: "callout", title: "Kunci penandatanganan adalah aset", text: "Setiap pembaruan harus ditandatangani dengan kunci yang sama dengan versi sebelumnya. Kehilangan kunci atau membiarkannya hanya dipegang pihak luar dapat membuat Anda tidak bisa memperbarui aplikasi sendiri. Tanyakan kepada pengembang di mana kunci disimpan dan siapa yang bisa mengaksesnya." },
  { type: "h2", text: "Materi halaman toko" },
  { type: "p", text: "Halaman aplikasi di toko adalah etalase. Di sanalah calon pengguna memutuskan memasang atau tidak, sering hanya dalam beberapa detik. Materinya meliputi nama aplikasi, deskripsi singkat dan panjang, ikon, tangkapan layar untuk beberapa ukuran perangkat, kategori, informasi kontak, serta tautan ke kebijakan privasi." },
  { type: "ul", items: [
    "Nama yang mudah dikenali dan sesuai dengan merek bisnis Anda",
    "Kalimat pembuka deskripsi yang langsung menyebut manfaat utama bagi pengguna",
    "Tangkapan layar yang menunjukkan layar nyata aplikasi, dimulai dari fitur terpenting",
    "Ikon yang tetap jelas dalam ukuran kecil dan di latar terang maupun gelap",
    "Alamat surel dukungan yang benar-benar dipantau",
    "Versi bahasa lain bila Anda melayani pengguna di lebih dari satu bahasa",
  ] },
  { type: "p", text: "Tulis deskripsi dengan bahasa pelanggan, bukan bahasa internal. Hindari klaim yang tidak bisa dibuktikan dan jangan menyebut nama merek lain secara menyesatkan; keduanya bisa menjadi alasan penolakan. Tangkapan layar harus menggambarkan aplikasi yang sebenarnya, karena gambar yang menjanjikan fitur yang tidak ada mengundang ulasan buruk." },
  { type: "h2", text: "Privasi dan izin akses perangkat" },
  { type: "p", text: "Kedua toko meminta penerbit menyatakan data apa yang dikumpulkan aplikasi, untuk tujuan apa, dan apakah dibagikan ke pihak lain. Pernyataan ini tampil di halaman toko dan harus sesuai dengan perilaku aplikasi yang sebenarnya, termasuk data yang dikumpulkan oleh pustaka pihak ketiga yang dipasang pengembang untuk analitik atau iklan." },
  { type: "p", text: "Minta izin akses perangkat hanya bila benar-benar diperlukan dan pada saat yang masuk akal. Aplikasi yang langsung meminta akses lokasi, kontak, kamera, dan pemberitahuan pada layar pertama membuat pengguna curiga dan sering memicu pertanyaan dari peninjau. Jelaskan alasannya dengan kalimat singkat sebelum dialog izin muncul." },
  { type: "p", text: "Siapkan pula hal yang sering terlupa: halaman kebijakan privasi yang bisa dibuka publik, serta cara bagi pengguna untuk menghapus akun dan datanya bila aplikasi Anda memungkinkan pembuatan akun. Sesuaikan semuanya dengan ketentuan pelindungan data pribadi yang berlaku, dan mintalah nasihat hukum untuk hal yang tidak Anda yakini." },
  { type: "h2", text: "Proses tinjauan dan alasan penolakan yang umum" },
  { type: "p", text: "Setiap aplikasi dan setiap pembaruan ditinjau sebelum tampil. Lama tinjauan tidak tetap dan tidak bisa dijamin, sehingga jangan merencanakan rilis dengan asumsi waktu yang ketat. Peninjau memeriksa apakah aplikasi berfungsi, sesuai dengan deskripsinya, aman bagi pengguna, dan mematuhi pedoman toko." },
  { type: "ul", items: [
    "Aplikasi macet atau menampilkan layar kosong saat diuji peninjau",
    "Peninjau tidak bisa masuk karena tidak diberi akun uji coba",
    "Isi aplikasi terlalu tipis, misalnya hanya membungkus situs web tanpa nilai tambah",
    "Pernyataan data dan izin akses tidak sesuai dengan perilaku aplikasi",
    "Cara pembayaran untuk produk digital tidak mengikuti ketentuan toko",
    "Deskripsi atau tangkapan layar menyesatkan atau menyebut fitur yang belum ada",
  ] },
  { type: "p", text: "Sediakan akun uji coba beserta petunjuk singkat bagi peninjau, terutama bila aplikasi Anda memerlukan pendaftaran, kode undangan, atau perangkat tambahan. Jika aplikasi ditolak, baca alasannya dengan tenang dan jawab secara spesifik. Penolakan adalah hal biasa; kebanyakan selesai dengan perbaikan kecil atau penjelasan tambahan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b",
    alt: "Tangan menulis daftar periksa di buku catatan",
    caption: "Daftar periksa rilis mencegah hal kecil yang terlewat berubah menjadi penolakan.",
  },
  { type: "h2", text: "Pembayaran di dalam aplikasi" },
  { type: "p", text: "Aturan pembayaran adalah bagian yang paling sering mengejutkan pemilik bisnis. Secara garis besar, toko aplikasi membedakan penjualan barang dan jasa fisik dari penjualan konten atau fitur digital yang dinikmati di dalam aplikasi. Untuk kelompok kedua, toko umumnya mewajibkan sistem pembayaran mereka sendiri dan mengenakan komisi." },
  { type: "p", text: "Perbedaan ini memengaruhi model bisnis. Aplikasi toko yang menjual pakaian atau makanan biasanya dapat memakai penyedia pembayaran pilihannya. Aplikasi yang menjual langganan konten, kursus digital, atau fitur premium perlu memperhitungkan komisi toko ke dalam harga. Rincian aturan dan pengecualiannya berbeda antarnegara dan berubah dari waktu ke waktu." },
  { type: "p", text: "Karena itu bahas model pendapatan dengan pengembang sebelum fitur pembayaran dibangun, dan periksa pedoman resmi terbaru kedua toko. Mengubah alur pembayaran setelah aplikasi ditolak jauh lebih mahal daripada merancangnya dengan benar sejak awal." },
  { type: "h2", text: "Menguji sebelum rilis publik" },
  { type: "p", text: "Kedua toko menyediakan jalur uji resmi yang memungkinkan Anda membagikan aplikasi kepada sekelompok orang sebelum dirilis ke publik. Manfaatkan jalur ini. Uji coba di perangkat pengembang tidak sama dengan uji coba di ponsel karyawan dan pelanggan nyata dengan berbagai merek, ukuran layar, versi sistem operasi, dan kualitas jaringan." },
  { type: "ol", items: [
    "Uji internal oleh tim sendiri untuk menangkap kesalahan yang mencolok",
    "Uji tertutup oleh sekelompok karyawan atau pelanggan terpilih dengan skenario nyata",
    "Perbaikan berdasarkan masukan dan laporan kerusakan",
    "Uji ulang pada alur terpenting: pendaftaran, masuk, transaksi, dan pemberitahuan",
    "Persetujuan rilis oleh penanggung jawab bisnis, bukan hanya oleh pengembang",
  ] },
  { type: "p", text: "Pasang alat pelaporan kerusakan dan analitik dasar sebelum rilis, bukan sesudahnya. Tanpa keduanya Anda hanya tahu ada masalah ketika ulasan bintang satu muncul, dan pengembang tidak punya data untuk menemukan sebabnya." },
  { type: "h2", text: "Peluncuran bertahap dan penomoran versi" },
  { type: "p", text: "Aplikasi tidak harus langsung dirilis ke seluruh pengguna. Peluncuran bertahap memungkinkan versi baru diterima sebagian kecil pengguna terlebih dahulu, lalu diperluas bila tidak ada lonjakan kerusakan atau keluhan. Bila ada masalah, peluncuran bisa dihentikan sebelum dampaknya meluas." },
  { type: "p", text: "Ingat bahwa aplikasi mobile tidak bisa ditarik kembali seperti website. Versi yang sudah terpasang tetap ada di ponsel pengguna sampai mereka memperbarui. Perbaikan pun harus melewati tinjauan lagi. Karena itu kesalahan di aplikasi mobile lebih lama dampaknya, dan kehati-hatian sebelum rilis lebih berharga." },
  { type: "p", text: "Pakai penomoran versi yang konsisten dan tulis catatan perubahan yang jujur dan bermanfaat. Simpan catatan internal tentang isi setiap versi. Rancang juga cara memaksa atau menyarankan pembaruan dari sisi server, sehingga versi lama yang bermasalah atau tidak lagi kompatibel dapat diarahkan untuk memperbarui." },
  { type: "h2", text: "Setelah rilis: ulasan, peringkat, dan dukungan" },
  { type: "p", text: "Rilis bukan garis akhir. Ulasan dan peringkat di toko aplikasi memengaruhi keputusan calon pengguna dan kedudukan aplikasi di hasil pencarian toko. Pantau ulasan secara rutin dan balas dengan sopan, terutama ulasan yang menyebut masalah. Balasan yang menunjukkan masalah sudah diperbaiki sering membuat pengguna mengubah penilaiannya." },
  { type: "p", text: "Minta penilaian pada saat yang tepat, misalnya setelah pengguna berhasil menyelesaikan transaksi, dan gunakan mekanisme resmi yang disediakan sistem operasi. Jangan meminta terlalu sering dan jangan menjanjikan imbalan untuk ulasan positif; praktik itu melanggar pedoman." },
  { type: "p", text: "Sediakan jalur dukungan di dalam aplikasi agar keluhan sampai kepada Anda sebelum menjadi ulasan publik. Tombol bantuan yang mengarah ke obrolan, surel, atau formulir sederhana sudah cukup, asalkan benar-benar dijawab." },
  { type: "h2", text: "Pemeliharaan: aplikasi tidak pernah benar-benar selesai" },
  { type: "p", text: "Sistem operasi ponsel diperbarui secara berkala, perangkat baru muncul dengan ukuran layar berbeda, dan toko aplikasi menaikkan persyaratan teknis minimum dari waktu ke waktu. Aplikasi yang tidak diperbarui lama-kelamaan menampilkan peringatan, kehilangan fungsi tertentu, atau bahkan tidak lagi bisa dipasang pada perangkat baru." },
  { type: "p", text: "Pustaka pihak ketiga yang dipakai aplikasi juga perlu diperbarui, terutama yang menyangkut keamanan dan pembayaran. Anggarkan pemeliharaan rutin sejak awal sebagai biaya tetap memiliki aplikasi, bukan sebagai kejadian tak terduga. Sepakati dengan pengembang siapa yang memantau pengumuman perubahan dari kedua toko." },
  { type: "p", text: "Periksa surel yang terdaftar di akun penerbit secara teratur. Pemberitahuan tentang perubahan kebijakan, permintaan pembaruan informasi, atau peringatan pelanggaran dikirim ke sana, sering dengan tenggat. Akun yang surelnya tidak pernah dibaca berisiko membuat aplikasi diturunkan tanpa Anda sadari." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1522542550221-31fd19575a2d",
    alt: "Sketsa wireframe berwarna dari beberapa tata letak layar aplikasi",
    caption: "Tangkapan layar di halaman toko sebaiknya dirancang, bukan sekadar diambil seadanya.",
  },
  { type: "h2", text: "Alternatif selain toko aplikasi publik" },
  { type: "p", text: "Tidak semua aplikasi perlu tampil di toko publik. Aplikasi untuk karyawan atau mitra terbatas dapat disebarkan lewat jalur distribusi tertutup yang disediakan kedua platform bagi organisasi. Jalur ini tetap punya syarat, tetapi aplikasi tidak muncul di pencarian umum." },
  { type: "p", text: "Untuk kebutuhan tertentu, aplikasi web progresif bisa menjadi pilihan yang lebih ringan. Ia berjalan di peramban, bisa dipasang ke layar utama, dan diperbarui tanpa tinjauan toko. Kekurangannya adalah akses ke kemampuan perangkat yang lebih terbatas dan tidak adanya kehadiran di toko aplikasi, tempat sebagian pengguna terbiasa mencari." },
  { type: "p", text: "Pilih jalur berdasarkan siapa penggunanya dan apa yang mereka butuhkan. Aplikasi belanja untuk pelanggan umum hampir pasti perlu hadir di kedua toko. Alat kerja internal untuk dua puluh karyawan mungkin tidak." },
  { type: "p", text: "Apa pun jalurnya, tunjuk satu orang di pihak bisnis sebagai pemilik rilis. Orang ini tidak harus memahami kode, tetapi ia memegang daftar periksa, mengetahui status tinjauan, menyetujui materi halaman toko, dan memutuskan kapan versi baru boleh diluncurkan. Tanpa pemilik yang jelas, urusan rilis cenderung jatuh di antara pengembang dan tim pemasaran, dan masing-masing mengira pihak lain sudah mengurusnya." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menerbitkan aplikasi lewat akun pribadi pengembang atau akun vendor",
    "Mengumumkan tanggal peluncuran pasti sebelum aplikasi lolos tinjauan",
    "Menyiapkan tangkapan layar dan deskripsi pada hari terakhir",
    "Tidak memberi akun uji coba kepada peninjau",
    "Merancang pembayaran tanpa membaca ketentuan toko",
    "Tidak menganggarkan pemeliharaan setelah rilis",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Periksa atas nama siapa akun penerbit Anda terdaftar dan siapa yang memegang kunci penandatanganan",
    "Daftarkan akun organisasi dengan surel perusahaan bila belum ada",
    "Baca pedoman tinjauan resmi kedua toko bersama pengembang, khususnya bagian privasi dan pembayaran",
    "Tulis draf deskripsi dan daftar tangkapan layar yang ingin ditampilkan",
    "Tetapkan kelompok penguji tertutup dan skenario yang akan mereka jalankan",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Merilis aplikasi ke App Store dan Google Play adalah pekerjaan yang bisa diperkirakan asalkan dipersiapkan. Kepemilikan akun yang benar, materi toko yang jujur dan menarik, perlakuan data yang transparan, pengujian lewat jalur resmi, dan peluncuran bertahap membuat hari peluncuran berjalan tenang." },
  { type: "p", text: "Perlakukan toko aplikasi sebagai mitra yang punya aturan, bukan sebagai hambatan di menit terakhir. Bisnis yang memahami aturan itu sejak awal menghemat waktu, menghindari penolakan yang bisa dicegah, dan memberi kesan pertama yang baik kepada pengguna barunya." },
  {
    type: "cta",
    title: "Berencana meluncurkan aplikasi mobile untuk bisnis Anda?",
    text: "Tim AG·SORA membangun aplikasi iOS dan Android sekaligus mendampingi proses rilis: akun penerbit atas nama bisnis Anda, materi halaman toko, pengujian, hingga pemeliharaan setelah peluncuran. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/mobile",
    label: "Konsultasi gratis",
  },
];
