import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Sebagian besar bisnis memulai setiap bulan dari nol. Penjualan bulan lalu sudah menjadi sejarah, dan pendapatan bulan ini harus dicari lagi satu transaksi demi satu transaksi. Model langganan menawarkan sesuatu yang berbeda: pelanggan setuju membayar secara berkala, sehingga sebagian pendapatan bulan depan sudah bisa diperkirakan hari ini." },
  { type: "p", text: "Daya tarik itu membuat langganan menyebar jauh di luar perangkat lunak. Kopi dan kebutuhan rumah tangga dikirim rutin, pusat kebugaran dan kelas daring menagih bulanan, bengkel menawarkan paket perawatan tahunan, dan pemasok menjual bahan habis pakai dengan jadwal tetap. Hampir setiap bisnis dengan kebutuhan pelanggan yang berulang bisa mempertimbangkannya." },
  { type: "p", text: "Namun langganan bukan sekadar mengubah tombol beli menjadi tombol berlangganan. Ia mengubah cara menagih, cara mencatat pendapatan, cara melayani, dan cara mengukur keberhasilan. Artikel ini membahas apa yang perlu disiapkan: kecocokan model, harga dan paket, sistem tagihan berulang, pembayaran yang gagal, pembatalan, pencatatan, dan ukuran yang perlu dipantau. Tidak ada angka rekaan di sini; yang kami tawarkan adalah kerangka berpikir." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Langganan cocok bila kebutuhan pelanggan memang berulang dan nilainya terasa di setiap periode",
      "Rancang paket yang sederhana dengan pembeda yang mudah dipahami",
      "Tagihan berulang memerlukan sistem yang menangani siklus, perubahan paket, dan pembayaran gagal",
      "Pembatalan yang mudah dan jujur lebih sehat daripada menahan pelanggan dengan mempersulit",
      "Pantau pelanggan yang berhenti dan sebabnya sama serius dengan memantau pelanggan baru",
    ],
  },
  { type: "h2", text: "Mengapa pendapatan berulang menarik" },
  { type: "p", text: "Pendapatan yang bisa diperkirakan memudahkan hampir semua keputusan. Anda dapat merencanakan stok, jumlah karyawan, dan investasi dengan lebih yakin karena tahu kira-kira berapa yang akan masuk. Arus kas menjadi lebih rata, tidak lagi naik turun tajam mengikuti musim atau promosi." },
  { type: "p", text: "Langganan juga mengubah hubungan dengan pelanggan. Dalam penjualan satuan, perhatian berpusat pada saat transaksi. Dalam langganan, perhatian berpindah ke masa setelahnya, karena pelanggan memperbarui keputusannya setiap periode. Bisnis terdorong untuk terus memberi nilai, dan itu biasanya menghasilkan produk serta layanan yang lebih baik." },
  { type: "p", text: "Sisi lainnya juga perlu dipahami. Pendapatan dari seorang pelanggan baru tiba sedikit demi sedikit, sedangkan biaya mendapatkannya dikeluarkan di depan. Bisnis langganan yang tumbuh cepat bisa justru kekurangan kas bila pelanggan berhenti sebelum biaya itu kembali. Model ini menghadiahi kesabaran dan menghukum pertumbuhan yang tidak diikuti retensi." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1543286386-713bdd548da4",
    alt: "Kertas berisi grafik garis naik di samping penggaris dan pena di meja kayu",
    caption: "Pendapatan berulang tumbuh dengan menumpuk, asalkan pelanggan yang sudah ada tetap bertahan.",
  },
  { type: "h2", text: "Apakah bisnis Anda cocok" },
  { type: "p", text: "Langganan berhasil ketika mengikuti pola kebutuhan yang sudah ada, bukan ketika dipaksakan. Ajukan pertanyaan sederhana: apakah pelanggan memang memerlukan produk atau jasa ini berulang kali, dengan jarak yang kurang lebih teratur? Jika jawabannya ya, langganan menghilangkan kerepotan memesan ulang. Jika tidak, pelanggan akan merasa terjebak membayar sesuatu yang tidak dipakai." },
  { type: "ul", items: [
    "Barang habis pakai yang dibeli rutin: bahan makanan, perlengkapan kebersihan, bahan produksi",
    "Akses ke layanan atau fasilitas: perangkat lunak, kelas, keanggotaan",
    "Perawatan dan dukungan berkala: servis mesin, pemeliharaan website dan aplikasi",
    "Konten atau kurasi yang diperbarui terus: materi belajar, pilihan produk bulanan",
    "Pemakaian yang diukur: penyimpanan, jumlah transaksi, jumlah pengguna",
  ] },
  { type: "p", text: "Uji dulu sebelum mengubah seluruh bisnis. Tawarkan langganan sebagai pilihan di samping pembelian biasa kepada sebagian pelanggan dan amati siapa yang mengambil, berapa lama bertahan, dan apa keluhannya. Hasil uji kecil ini jauh lebih bisa dipercaya daripada perkiraan di atas kertas." },
  { type: "h2", text: "Merancang paket dan harga" },
  { type: "p", text: "Paket yang baik mudah dijelaskan dalam satu kalimat. Tiga pilihan dengan pembeda yang jelas biasanya lebih mudah diputuskan pelanggan daripada tujuh pilihan dengan tabel perbandingan panjang. Pembeda antarpaket sebaiknya berupa hal yang nilainya dipahami pelanggan, seperti jumlah, frekuensi, tingkat layanan, atau fitur tertentu." },
  { type: "p", text: "Tentukan satuan yang menjadi dasar harga. Apakah Anda menagih jumlah tetap per periode, per pengguna, per pemakaian, atau gabungannya? Harga tetap paling mudah dipahami dan diperkirakan. Harga berdasarkan pemakaian terasa adil tetapi membuat tagihan sulit ditebak, sehingga pelanggan perlu cara memantau pemakaiannya sebelum tagihan datang." },
  { type: "p", text: "Pilihan periode juga penting. Tagihan bulanan menurunkan hambatan untuk memulai. Tagihan tahunan memperbaiki arus kas dan mengurangi pelanggan yang berhenti, biasanya dengan imbalan harga lebih rendah. Banyak bisnis menawarkan keduanya. Apa pun strukturnya, tampilkan harga lengkap dengan pajak dan biaya lain secara jelas sebelum pelanggan membayar." },
  { type: "callout", title: "Harga bisa diubah, kepercayaan sulit dipulihkan", text: "Kenaikan harga adalah hal wajar, tetapi caranya menentukan. Beri tahu pelanggan jauh hari, jelaskan alasannya, dan beri jalan keluar yang mudah bagi yang tidak setuju. Perubahan yang ditemukan pelanggan sendiri di mutasi rekeningnya merusak hubungan yang dibangun bertahun-tahun." },
  { type: "h2", text: "Mesin tagihan berulang" },
  { type: "p", text: "Menagih secara berkala terdengar sederhana sampai Anda menemui kasus nyata. Pelanggan mendaftar di tengah bulan. Pelanggan naik paket di hari kelima belas. Pelanggan meminta jeda dua bulan. Kupon berlaku tiga periode pertama. Tagihan gagal lalu berhasil seminggu kemudian. Setiap kasus memerlukan aturan, dan aturan itu harus dijalankan sistem dengan cara yang sama setiap kali." },
  { type: "ul", items: [
    "Kapan siklus tagihan dimulai: tanggal pendaftaran atau tanggal tetap untuk semua pelanggan",
    "Bagaimana perhitungan saat pelanggan naik atau turun paket di tengah periode",
    "Bagaimana masa percobaan berakhir dan apa yang diberitahukan sebelumnya",
    "Bagaimana kupon dan diskon berlaku serta kapan berakhir",
    "Apa yang terjadi pada akses atau pengiriman ketika pembayaran tertunda",
    "Bagaimana jeda, pembatalan, dan pengaktifan kembali diperlakukan",
  ] },
  { type: "p", text: "Ada layanan tagihan berlangganan yang menangani sebagian besar kerumitan ini, dan ada penyedia pembayaran yang menawarkan fitur tagihan berulang. Untuk kebutuhan sederhana, keduanya memadai. Bila aturan Anda khas, misalnya gabungan langganan barang fisik dengan jadwal pengiriman dan stok, sistem yang dibangun khusus dan terhubung ke ERP sering lebih tepat." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1",
    alt: "Pelanggan menempelkan kartu pembayaran ke mesin pembaca nontunai",
    caption: "Metode pembayaran yang dipilih menentukan seberapa mulus tagihan berikutnya bisa ditarik.",
  },
  { type: "h2", text: "Metode pembayaran untuk tagihan berulang" },
  { type: "p", text: "Tidak semua metode pembayaran mendukung penarikan otomatis. Kartu dan sebagian dompet digital dapat ditagih berulang setelah pelanggan memberi persetujuan sekali. Transfer bank dan pembayaran lewat kode umumnya memerlukan tindakan pelanggan setiap periode, sehingga Anda perlu mengirim tagihan dan pengingat." },
  { type: "p", text: "Pilihan ini berpengaruh besar pada tingkat keberhasilan penagihan. Penarikan otomatis menghilangkan lupa bayar, tetapi tidak semua pelanggan memiliki atau mau memakai metode yang mendukungnya. Tagihan manual menjangkau lebih banyak orang, tetapi setiap periode menjadi kesempatan bagi pelanggan untuk menunda. Banyak bisnis menyediakan keduanya dan mendorong pelanggan memilih penarikan otomatis." },
  { type: "p", text: "Jangan pernah menyimpan data kartu di sistem Anda sendiri. Serahkan penyimpanan kepada penyedia pembayaran yang memegang sertifikasi keamanan untuk itu, dan simpan hanya penanda yang mereka berikan. Pastikan persetujuan pelanggan atas penarikan berulang dicatat dengan jelas, dan ikuti ketentuan penyedia pembayaran serta aturan yang berlaku." },
  { type: "h2", text: "Pembayaran gagal dan penagihan ulang" },
  { type: "p", text: "Sebagian tagihan berulang pasti gagal: kartu kedaluwarsa, saldo tidak cukup, batas kredit terlampaui, atau bank menolak karena alasan keamanan. Pelanggan seperti ini tidak berniat berhenti; mereka sering tidak tahu pembayarannya gagal. Jika langganannya langsung dihentikan, Anda kehilangan pelanggan yang sebenarnya masih ingin membayar." },
  { type: "p", text: "Rancang urutan penanganan. Coba tagih ulang beberapa kali dengan jeda yang wajar. Beri tahu pelanggan dengan pesan yang jelas dan tautan langsung untuk memperbarui metode pembayaran. Beri masa tenggang sebelum akses dihentikan atau pengiriman ditahan. Ingatkan sebelum kartu kedaluwarsa agar masalah dicegah sebelum terjadi." },
  { type: "p", text: "Nada pesan sangat menentukan. Pelanggan yang pembayarannya gagal karena kartu kedaluwarsa bukan penunggak. Pesan yang membantu, bukan yang menuduh, membuat mereka memperbarui data dengan senang hati. Tetapkan pula batas yang jelas kapan langganan dianggap berakhir, agar tidak ada akun menggantung berbulan-bulan." },
  { type: "h2", text: "Pembatalan dan jeda" },
  { type: "p", text: "Godaan terbesar dalam bisnis langganan adalah mempersulit pembatalan. Tombol yang disembunyikan, keharusan menelepon pada jam kerja, atau rangkaian layar bujukan yang panjang mungkin menahan sebagian orang sebulan lebih lama. Namun cara itu juga menghasilkan keluhan, sengketa pembayaran, ulasan buruk, dan pelanggan yang tidak akan pernah kembali." },
  { type: "p", text: "Buat pembatalan semudah pendaftaran, dan jelaskan apa yang terjadi sesudahnya: sampai kapan akses berlaku, apakah ada pengembalian dana, dan bagaimana data pelanggan diperlakukan. Aturan perlindungan konsumen di berbagai tempat makin tegas tentang hal ini, jadi periksa ketentuan yang berlaku bagi bisnis Anda." },
  { type: "p", text: "Tawarkan pilihan selain berhenti sepenuhnya. Banyak pelanggan sebenarnya hanya perlu jeda karena bepergian atau masih punya stok, turun ke paket lebih kecil, atau mengubah frekuensi pengiriman. Tanyakan alasan berhenti dengan satu pertanyaan singkat. Jawaban itu adalah bahan perbaikan yang paling jujur." },
  { type: "h2", text: "Pencatatan pendapatan dan pajak" },
  { type: "p", text: "Langganan mengubah waktu pengakuan pendapatan. Uang yang diterima di muka untuk langganan setahun belum sepenuhnya menjadi pendapatan pada hari diterima; sebagian besarnya masih merupakan kewajiban memberi layanan pada bulan-bulan berikutnya. Mencatat seluruhnya sebagai pendapatan bulan ini membuat laporan tampak sangat baik sekarang dan sangat buruk kemudian." },
  { type: "p", text: "Sistem pembukuan atau ERP perlu mampu mencatat pendapatan diterima di muka dan mengakuinya bertahap sesuai periode layanan. Faktur, bukti pembayaran, dan pengembalian dana harus terhubung dengan langganan yang bersangkutan agar rekonsiliasi dengan pencairan dari penyedia pembayaran bisa dilakukan tanpa mencocokkan satu per satu." },
  { type: "p", text: "Perlakuan pajak atas langganan, terutama untuk produk digital dan penjualan lintas wilayah, dapat berbeda dari penjualan biasa dan berubah dari waktu ke waktu. Bahas dengan konsultan pajak dan akuntan Anda sebelum meluncurkan, dan pastikan faktur yang dihasilkan sistem memenuhi ketentuan yang berlaku." },
  { type: "h2", text: "Layanan mandiri untuk pelanggan" },
  { type: "p", text: "Pelanggan berlangganan sering perlu melakukan hal kecil: mengganti kartu, mengubah alamat, mengunduh faktur, menunda pengiriman, atau naik paket. Bila setiap hal itu harus lewat layanan pelanggan, biaya dukungan tumbuh seiring jumlah pelanggan dan pelanggan pun kesal menunggu." },
  { type: "p", text: "Sediakan halaman akun di website atau aplikasi tempat pelanggan mengurus semuanya sendiri. Tampilkan dengan jelas paket yang aktif, tanggal dan jumlah tagihan berikutnya, riwayat pembayaran, serta tombol untuk mengubah atau menghentikan langganan. Keterbukaan ini mengurangi kejutan, dan kejutan adalah sumber utama sengketa pembayaran." },
  { type: "p", text: "Kirim pemberitahuan pada saat yang penting: sebelum masa percobaan berakhir, sebelum perpanjangan tahunan, setelah pembayaran berhasil, dan ketika ada perubahan harga. Pelanggan yang tahu apa yang akan ditagih dan kapan jarang merasa dirugikan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf",
    alt: "Dua rekan kerja saling tos di meja rapat",
    caption: "Dalam model langganan, pelanggan yang bertahan dan merasa terbantu adalah hasil kerja seluruh tim.",
  },
  { type: "h2", text: "Ukuran yang perlu dipantau" },
  { type: "p", text: "Bisnis langganan memiliki bahasa ukurannya sendiri. Ukuran yang paling dasar adalah pendapatan berulang per bulan dan jumlah pelanggan aktif. Tetapi dua angka itu hanya menceritakan keadaan sekarang. Yang menentukan masa depan adalah pergerakannya: berapa yang masuk, berapa yang naik paket, berapa yang turun, dan berapa yang berhenti." },
  { type: "ul", items: [
    "Pendapatan berulang bulanan dan perubahannya menurut sumber",
    "Proporsi pelanggan yang berhenti per periode, dipisahkan antara sukarela dan karena pembayaran gagal",
    "Lama rata-rata pelanggan bertahan menurut bulan pendaftarannya",
    "Biaya mendapatkan satu pelanggan baru dan berapa lama biaya itu kembali",
    "Proporsi tagihan yang berhasil pada percobaan pertama",
    "Alasan pembatalan yang paling sering disebut",
  ] },
  { type: "p", text: "Pelajari pelanggan menurut kelompok pendaftarannya. Angka rata-rata menyembunyikan banyak hal; melihat berapa banyak pendaftar bulan tertentu yang masih aktif tiga, enam, dan dua belas bulan kemudian menunjukkan apakah perbaikan Anda benar-benar berpengaruh. Pelanggan yang berhenti pada bulan pertama biasanya menandakan janji yang tidak sesuai kenyataan." },
  { type: "h2", text: "Menjaga pelanggan tetap bertahan" },
  { type: "p", text: "Retensi ditentukan jauh sebelum pelanggan menekan tombol berhenti. Pelanggan yang sejak awal memakai produk dengan baik dan merasakan manfaatnya cenderung bertahan. Karena itu bulan pertama paling menentukan: bantu pelanggan baru memulai, pastikan kiriman pertama tiba dengan baik, dan tanyakan pengalamannya." },
  { type: "p", text: "Perhatikan tanda-tanda menurun: pemakaian yang berkurang, kiriman yang sering ditunda, atau keluhan yang tidak selesai. Menghubungi pelanggan pada saat itu lebih efektif daripada menawarkan diskon ketika ia sudah memutuskan pergi. Tindakan seperti ini hanya mungkin bila data pemakaian, tagihan, dan layanan pelanggan terhubung di satu tempat." },
  { type: "p", text: "Libatkan seluruh tim dalam hal ini, bukan hanya pemasaran. Gudang yang mengirim tepat waktu, keuangan yang menagih dengan benar, dan layanan pelanggan yang menjawab cepat sama-sama menentukan apakah pelanggan memperpanjang. Bagikan angka retensi dan alasan berhenti kepada semua bagian secara rutin, agar setiap orang melihat pengaruh pekerjaannya terhadap pendapatan berulang." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Memaksakan langganan pada produk yang tidak dibutuhkan secara berulang",
    "Menawarkan terlalu banyak paket dengan pembeda yang membingungkan",
    "Menghentikan langganan seketika saat satu pembayaran gagal",
    "Mempersulit pembatalan untuk menahan pelanggan",
    "Mencatat pembayaran di muka seluruhnya sebagai pendapatan bulan berjalan",
    "Hanya mengejar pelanggan baru tanpa memperhatikan yang berhenti",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Lihat data penjualan dan cari pelanggan yang membeli barang atau jasa yang sama secara berulang",
    "Rancang satu penawaran langganan sederhana untuk kelompok itu sebagai uji coba",
    "Tuliskan aturan tagihan: siklus, perubahan paket, pembayaran gagal, jeda, dan pembatalan",
    "Bahas dengan akuntan cara mencatat pendapatan diterima di muka dan perlakuan pajaknya",
    "Tetapkan ukuran yang dipantau sejak hari pertama, termasuk alasan pelanggan berhenti",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Model langganan memberi pendapatan yang lebih bisa diperkirakan dan hubungan pelanggan yang lebih panjang, tetapi menuntut disiplin di belakang layar. Tagihan harus tepat, pembayaran gagal harus ditangani dengan sabar, pembatalan harus mudah, dan pendapatan harus dicatat sesuai periodenya. Semua itu memerlukan sistem yang dirancang untuk siklus, bukan untuk transaksi tunggal." },
  { type: "p", text: "Mulailah dari kebutuhan pelanggan yang memang berulang, uji dengan penawaran sederhana, dan bangun sistemnya seiring bukti yang terkumpul. Bisnis yang menjalankannya dengan jujur akan menemukan bahwa pendapatan berulang adalah hasil dari pelanggan yang terus merasa terbantu." },
  {
    type: "cta",
    title: "Ingin menambahkan langganan dan tagihan berulang ke bisnis Anda?",
    text: "Tim AG·SORA membangun website, aplikasi, dan sistem tagihan berulang yang terhubung dengan penyedia pembayaran, pembukuan, dan halaman akun pelanggan. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/custom-software",
    label: "Konsultasi gratis",
  },
];
