import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Banyak pemilik bisnis baru tahu website atau aplikasinya bermasalah dari pelanggan. Pesan masuk bertanya mengapa halaman pembayaran tidak bisa dibuka, atau karyawan melapor bahwa sistem kasir lambat sejak pagi. Pada saat itu kerugian sudah berjalan: pesanan hilang, antrean memanjang, dan kepercayaan menipis. Pertanyaannya bukan apakah sistem akan pernah bermasalah, melainkan seberapa cepat Anda mengetahuinya dan seberapa siap Anda menanganinya." },
  { type: "p", text: "Monitoring adalah praktik mengamati kesehatan sistem secara terus-menerus agar masalah terdeteksi sebelum pelanggan mengeluh. Banyak orang mengira monitoring hanya urusan perusahaan besar dengan tim teknis penuh. Kenyataannya, bisnis kecil dan menengah pun bisa memasang pemantauan dasar dengan biaya wajar, dan manfaatnya sering lebih terasa karena tidak ada tim besar yang berjaga." },
  { type: "p", text: "Artikel ini membahas cara merancang pemantauan website dan aplikasi bisnis yang realistis. Kami membahas apa yang perlu dipantau, jenis pemeriksaan, peringatan yang tidak membuat lelah, halaman status, pencatatan kesalahan, penanganan insiden, dan kebiasaan yang menjaga sistem tetap sehat. Kami tidak memakai angka rekaan tentang persentase ketersediaan; yang kami tawarkan adalah prinsip dan daftar periksa yang bisa diterapkan pada sistem dengan berbagai skala." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Pantau dari sudut pandang pengguna: apakah alur penting seperti masuk, mencari, dan membayar benar-benar berjalan",
      "Mulai dengan beberapa pemeriksaan sederhana pada hal yang paling merugikan bila mati, bukan memantau segalanya",
      "Atur peringatan agar jarang tetapi bermakna, dengan penerima dan tindakan yang jelas",
      "Catat kesalahan dan jejak kejadian sehingga penyebab masalah bisa ditelusuri, bukan ditebak",
      "Siapkan prosedur insiden sederhana dan pelajari tiap kejadian agar tidak terulang",
    ],
  },
  { type: "h2", text: "Mengapa monitoring bukan kemewahan" },
  { type: "p", text: "Setiap sistem yang bergantung pada server, jaringan, layanan pihak ketiga, dan kode yang terus berubah pasti sesekali mengalami gangguan. Sertifikat keamanan kedaluwarsa, ruang penyimpanan penuh, penyedia pembayaran sedang bermasalah, atau pembaruan terbaru membawa kesalahan yang lolos dari pengujian. Semua itu normal. Yang tidak normal adalah menemukannya berjam-jam kemudian." },
  { type: "p", text: "Dampak gangguan sulit diukur dengan tepat karena tergantung jam kejadian, jenis bisnis, dan lamanya. Namun logikanya sederhana: setiap menit toko online tidak bisa menerima pesanan adalah penjualan yang berpotensi hilang, dan setiap menit aplikasi internal mati adalah waktu karyawan yang terbuang. Pemantauan memperpendek jeda antara kejadian dan penanganan, dan jeda itulah yang menentukan besar kecilnya kerugian." },
  { type: "p", text: "Manfaat lainnya kurang terlihat tetapi nyata. Data pemantauan menunjukkan pola: halaman yang melambat setiap akhir bulan, server yang kehabisan memori setiap beberapa hari, atau layanan pihak ketiga yang sering gagal. Pola seperti itu memungkinkan perbaikan permanen, bukan sekadar memadamkan api berulang kali." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31",
    alt: "Rak server dengan kabel jaringan yang tersusun rapat",
    caption: "Di balik setiap halaman yang terbuka ada server dan jaringan yang perlu diamati, bukan sekadar dipercaya.",
  },
  { type: "h2", text: "Apa yang sebenarnya perlu dipantau" },
  { type: "p", text: "Godaan terbesar adalah memantau semuanya sekaligus, lalu tenggelam dalam grafik dan peringatan yang tidak ada yang membaca. Mulailah dari pertanyaan sederhana: apa yang paling merugikan jika mati? Untuk toko online, jawabannya biasanya beranda, halaman produk, keranjang, dan pembayaran. Untuk aplikasi internal, jawabannya mungkin proses masuk, pencatatan transaksi, dan laporan harian." },
  { type: "p", text: "Dari situ, pantau pada beberapa lapisan. Lapisan pertama adalah ketersediaan: apakah layanan bisa diakses dan menjawab dengan benar. Lapisan kedua adalah kecepatan: seberapa cepat halaman dan proses penting selesai, karena sistem yang sangat lambat sama buruknya dengan yang mati. Lapisan ketiga adalah kesehatan infrastruktur: pemakaian prosesor, memori, ruang penyimpanan, dan koneksi basis data. Lapisan keempat adalah kesalahan aplikasi: pengecualian dan galat yang dialami pengguna nyata." },
  { type: "ol", items: [
    "Ketersediaan: halaman dan titik layanan utama merespons dengan status yang benar",
    "Kecepatan: waktu muat halaman dan waktu proses untuk alur penting",
    "Infrastruktur: prosesor, memori, ruang penyimpanan, dan koneksi basis data",
    "Kesalahan aplikasi: galat yang dialami pengguna dan tugas terjadwal yang gagal",
    "Ketergantungan: pembayaran, pengiriman email, dan layanan pihak ketiga lain yang dipakai sistem",
    "Keamanan dasar: masa berlaku sertifikat, domain, dan percobaan masuk yang mencurigakan",
  ] },
  { type: "p", text: "Pemantauan pihak ketiga sering terlupakan. Banyak insiden berasal dari layanan yang bukan milik Anda, seperti penyedia pembayaran, layanan peta, atau pengirim pesan. Anda tidak bisa memperbaikinya, tetapi bisa mendeteksi dan menyiapkan respons, misalnya menampilkan pesan yang jujur kepada pelanggan atau menawarkan metode pembayaran alternatif." },
  { type: "h2", text: "Pemeriksaan dari luar dan dari dalam" },
  { type: "p", text: "Ada dua cara memandang sistem. Pemeriksaan dari luar meniru pengguna: sebuah layanan memanggil halaman Anda dari berbagai lokasi secara berkala dan memastikan hasilnya benar. Keunggulannya adalah ia melihat apa yang dilihat pengguna, termasuk masalah jaringan, DNS, dan sertifikat yang tidak terlihat dari dalam server. Kelemahannya, ia tidak tahu penyebabnya." },
  { type: "p", text: "Pemeriksaan dari dalam mengamati keadaan sistem sendiri: beban server, antrean pekerjaan, ukuran basis data, dan log. Ia membantu menjelaskan mengapa sesuatu terjadi, bahkan memprediksi sebelum terjadi, misalnya ketika ruang penyimpanan terus menyusut. Kombinasi keduanya paling kuat: pemeriksaan luar memberi tahu bahwa ada yang salah, pemeriksaan dalam membantu menemukan sebabnya." },
  { type: "h3", text: "Pemeriksaan alur, bukan hanya halaman" },
  { type: "p", text: "Halaman beranda yang terbuka belum membuktikan bahwa toko bisa menjual. Sistem sering mati di bagian yang lebih dalam: pencarian tidak mengembalikan hasil, tombol tambah ke keranjang gagal, atau pembayaran menolak semua transaksi. Pemeriksaan alur, atau pemeriksaan sintetis, menjalankan skenario sederhana seperti masuk, mencari produk, dan menambahkannya ke keranjang, lalu memastikan setiap langkah berhasil. Untuk bagian yang melibatkan uang, gunakan mode uji dari penyedia pembayaran sehingga tidak ada transaksi nyata." },
  { type: "p", text: "Jalankan pemeriksaan alur pada selang yang masuk akal, misalnya beberapa menit sekali untuk alur terpenting dan lebih jarang untuk yang lain. Terlalu sering membebani sistem dan menghasilkan data yang tidak dibutuhkan, terlalu jarang membuat deteksi terlambat. Pastikan pemeriksaan tidak mengotori data nyata, misalnya dengan akun uji yang jelas ditandai." },
  { type: "h2", text: "Peringatan yang tidak membuat lelah" },
  { type: "p", text: "Peringatan adalah titik di mana pemantauan bertemu manusia, dan di sinilah banyak sistem gagal. Terlalu banyak peringatan membuat orang mengabaikannya, sehingga peringatan yang benar-benar penting terlewat. Prinsipnya sederhana: setiap peringatan harus layak membangunkan seseorang, dan harus memiliki tindakan yang jelas." },
  { type: "ul", items: [
    "Beri peringatan hanya untuk kondisi yang berdampak pada pengguna atau akan segera berdampak",
    "Tetapkan ambang yang masuk akal dan syarat durasi, misalnya gagal beberapa kali berturut-turut, agar gangguan sesaat tidak memicu alarm",
    "Bedakan tingkat keparahan: yang harus ditangani sekarang, yang cukup ditinjau besok pagi, dan yang hanya dicatat",
    "Kirim ke saluran yang benar-benar dibaca, dan tentukan siapa penerima utama serta penggantinya",
    "Sertakan konteks dalam pesan: apa yang gagal, sejak kapan, dan tautan ke panduan penanganan",
    "Tinjau peringatan secara berkala dan hapus atau perbaiki yang sering memicu tanpa tindakan",
  ] },
  { type: "p", text: "Siapkan juga mekanisme eskalasi. Jika penerima pertama tidak merespons dalam waktu tertentu, peringatan diteruskan ke orang berikutnya. Untuk tim kecil yang tidak berjaga sepanjang waktu, tentukan dengan jujur jam layanan yang bisa dijanjikan, dan sampaikan kepada pemangku kepentingan. Lebih baik janji realistis daripada jadwal jaga yang tidak pernah dijalani." },
  { type: "callout", title: "Peringatan yang baik bisa ditindaklanjuti", text: "Jika sebuah peringatan datang dan penerimanya bertanya apa yang harus dilakukan, peringatan itu belum selesai dirancang. Setiap peringatan perlu menunjuk pada langkah pertama yang jelas." },
  { type: "h2", text: "Mencatat kesalahan dan jejak kejadian" },
  { type: "p", text: "Mengetahui bahwa sesuatu rusak hanyalah separuh pekerjaan. Separuh lainnya adalah mengetahui mengapa. Untuk itu diperlukan catatan: log aplikasi yang merekam kejadian penting, dan pelacakan kesalahan yang mengumpulkan pengecualian beserta konteksnya, seperti halaman yang dibuka, versi aplikasi, dan langkah yang dilakukan pengguna sebelum galat." },
  { type: "p", text: "Catat dengan terstruktur dan konsisten. Log yang berupa baris teks acak sulit dicari, sedangkan log dengan bidang yang jelas, seperti waktu, tingkat keparahan, modul, dan nomor rujukan permintaan, memungkinkan penyaringan cepat. Nomor rujukan permintaan yang sama di setiap lapisan membantu menelusuri satu transaksi dari layar pengguna sampai basis data." },
  { type: "p", text: "Jaga privasi. Jangan mencatat kata sandi, nomor kartu, atau data pribadi yang tidak perlu dalam log, karena log sering dibaca banyak orang dan disimpan lama. Tetapkan masa penyimpanan log yang masuk akal, dan batasi siapa yang boleh mengaksesnya. Ketentuan perlindungan data pribadi yang berlaku saat ini patut diperiksa untuk memastikan praktik pencatatan Anda sesuai." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74",
    alt: "Layar menampilkan panel metrik dengan grafik garis kecil dan angka performa",
    caption: "Grafik berguna hanya jika seseorang tahu angka mana yang menandakan masalah dan apa yang dilakukan setelahnya.",
  },
  { type: "h2", text: "Memantau kecepatan dari sisi pengguna" },
  { type: "p", text: "Server yang sehat tidak menjamin pengalaman yang cepat. Pengguna di ponsel dengan jaringan lambat, gambar yang terlalu besar, atau skrip pihak ketiga yang berat dapat membuat halaman terasa menyiksa walau server tidak bermasalah. Karena itu, selain metrik server, perhatikan pengalaman nyata pengguna: seberapa cepat konten utama muncul, seberapa cepat halaman bisa digunakan, dan seberapa stabil tata letaknya." },
  { type: "p", text: "Kumpulkan data dari pengguna sungguhan jika memungkinkan, karena kondisi nyata sangat beragam. Kelompokkan menurut jenis perangkat, jaringan, dan halaman agar terlihat bagian mana yang bermasalah. Perubahan mendadak setelah pembaruan adalah petunjuk kuat bahwa sesuatu yang baru menyebabkan perlambatan, dan data ini memudahkan keputusan membatalkan perubahan." },
  { type: "h2", text: "Halaman status dan komunikasi saat gangguan" },
  { type: "p", text: "Saat gangguan terjadi, cara Anda berkomunikasi menentukan seberapa besar kepercayaan yang tersisa. Pelanggan lebih memaklumi sistem yang sedang diperbaiki dan diberi tahu terus-menerus daripada sistem yang diam tanpa penjelasan. Halaman status sederhana, yang dihosting terpisah dari sistem utama agar tetap bisa dibuka ketika sistem utama mati, menampilkan keadaan terkini dan riwayat gangguan." },
  { type: "p", text: "Tulis pembaruan dengan bahasa yang jujur dan tidak teknis berlebihan: apa yang terdampak, apa yang sedang dilakukan, dan kapan pembaruan berikutnya akan datang. Jangan menjanjikan waktu pemulihan yang tidak bisa Anda pastikan. Setelah pulih, sampaikan ringkasan singkat tentang apa yang terjadi dan apa yang diubah agar tidak berulang." },
  { type: "p", text: "Siapkan juga pesan sementara di aplikasi atau situs untuk bagian yang terganggu. Pelanggan yang melihat pesan jelas tentang pembayaran yang sedang bermasalah dan alternatif yang tersedia akan lebih sabar daripada yang mengalami kegagalan tanpa penjelasan. Latihan menulis pesan semacam ini sebelum diperlukan menghemat banyak waktu saat tekanan tinggi." },
  { type: "h2", text: "Menangani insiden dengan tenang" },
  { type: "p", text: "Saat sistem bermasalah, kepanikan adalah musuh. Prosedur insiden yang sederhana dan sudah disepakati membuat tim bergerak teratur. Intinya hanya beberapa hal: siapa yang memimpin penanganan, siapa yang berkomunikasi dengan pelanggan, bagaimana keputusan diambil, dan di mana catatan kejadian disimpan." },
  { type: "ol", items: [
    "Konfirmasi masalah dan nilai dampaknya: siapa dan apa yang terdampak",
    "Tunjuk satu orang yang memimpin dan satu orang yang berkomunikasi",
    "Pulihkan layanan lebih dulu, misalnya dengan membatalkan pembaruan terakhir, sebelum mencari akar masalah",
    "Catat kronologi: waktu, tindakan, dan hasilnya, selagi masih segar",
    "Sampaikan pembaruan berkala kepada pihak yang terdampak",
    "Setelah pulih, tinjau tanpa mencari kambing hitam dan tetapkan perbaikan konkret",
  ] },
  { type: "p", text: "Tinjauan setelah insiden adalah salah satu kebiasaan paling bernilai. Tujuannya bukan menyalahkan orang, melainkan memahami bagaimana sistem dan proses memungkinkan kesalahan terjadi. Hasilnya berupa daftar perbaikan yang spesifik, seperti menambah pemeriksaan yang terlewat, memperbaiki panduan, atau mengubah cara menerapkan pembaruan. Tanpa itu, insiden yang sama akan datang lagi." },
  { type: "h2", text: "Pembaruan dan pemeliharaan yang aman" },
  { type: "p", text: "Sebagian besar gangguan bukan datang dari luar, melainkan dari perubahan yang kita buat sendiri. Pembaruan kode, perubahan konfigurasi, dan migrasi basis data adalah penyebab yang sangat umum. Karena itu, pemantauan harus terhubung dengan proses penerapan: tandai di grafik kapan pembaruan dilakukan, sehingga lonjakan kesalahan bisa langsung dikaitkan dengan perubahan." },
  { type: "p", text: "Terapkan pembaruan secara bertahap bila memungkinkan, misalnya ke sebagian pengguna dulu lalu meluas jika sehat. Siapkan cara membatalkan yang cepat dan sudah dicoba. Hindari menerapkan perubahan besar pada saat tersibuk atau menjelang akhir pekan ketika tidak ada yang berjaga. Jadwalkan pemeliharaan di jam sepi dan umumkan sebelumnya." },
  { type: "p", text: "Kaitkan pula dengan strategi pencadangan. Pemantauan yang baik juga memeriksa bahwa pencadangan berjalan dan, yang lebih penting, bahwa hasilnya benar-benar bisa dipulihkan. Cadangan yang tidak pernah diuji adalah asumsi, bukan jaminan. Uji pemulihan secara berkala dan catat waktu yang dibutuhkan." },
  { type: "h2", text: "Memilih alat sesuai skala" },
  { type: "p", text: "Tidak ada satu paket alat yang cocok untuk semua. Untuk bisnis kecil, kombinasi sederhana sering cukup: layanan pemeriksaan ketersediaan eksternal, pelacakan kesalahan untuk aplikasi, dan metrik dasar server dari penyedia hosting. Seiring pertumbuhan, tambahkan pencatatan terpusat, pemantauan kinerja aplikasi, dan pemeriksaan alur yang lebih lengkap." },
  { type: "ul", items: [
    "Pilih alat yang tim Anda benar-benar sanggup menjalankan dan membaca, bukan yang fiturnya paling banyak",
    "Perhatikan biaya yang bisa membengkak seiring volume data, terutama untuk log dan metrik",
    "Pastikan peringatan bisa dikirim ke saluran yang dipakai tim sehari-hari",
    "Periksa di mana data pemantauan disimpan dan siapa yang bisa mengaksesnya",
    "Hindari ketergantungan tunggal: layanan pemantau sebaiknya tidak berjalan di infrastruktur yang sama dengan yang dipantau",
    "Dokumentasikan konfigurasi pemantauan agar tidak bergantung pada ingatan satu orang",
  ] },
  { type: "p", text: "Jika bisnis Anda memakai vendor untuk membangun dan merawat sistem, tanyakan apa saja yang dipantau, bagaimana peringatan dikirim, dan siapa yang merespons di luar jam kerja. Hal ini sebaiknya tertulis dalam kesepakatan pemeliharaan, termasuk waktu respons yang dijanjikan, bukan hanya diucapkan secara lisan." },
  { type: "h2", text: "Menentukan target yang realistis" },
  { type: "p", text: "Banyak bisnis ingin sistem yang tidak pernah mati, tetapi tuntutan itu mahal dan jarang diperlukan. Lebih berguna menentukan target yang sesuai dampak bisnis. Sistem kasir toko yang buka setiap hari mungkin membutuhkan ketersediaan tinggi dan cara kerja cadangan saat internet putus, sedangkan portal laporan internal mungkin bisa menoleransi jeda singkat di luar jam kerja." },
  { type: "p", text: "Rumuskan target dalam bahasa yang bisa dipahami semua pihak: berapa lama sistem boleh mati sebelum bisnis terganggu, dan berapa banyak data yang boleh hilang. Dua pertanyaan itu menentukan strategi pemantauan, pencadangan, dan arsitektur. Semakin ketat targetnya, semakin besar biaya dan kompleksitasnya, sehingga setiap peningkatan harus sepadan dengan nilai yang dilindungi." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Hanya memeriksa beranda sehingga kerusakan pada pembayaran atau pencarian tidak terdeteksi",
    "Mengirim terlalu banyak peringatan sehingga semuanya diabaikan",
    "Menyimpan halaman status di sistem yang sama dengan yang dipantau",
    "Mencatat data sensitif dalam log tanpa batas akses dan masa simpan",
    "Tidak pernah menguji pemulihan cadangan",
    "Melewatkan tinjauan setelah insiden sehingga akar masalah tidak pernah diperbaiki",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Daftar tiga sampai lima alur yang paling merugikan bila mati, misalnya masuk, pencarian, keranjang, dan pembayaran",
    "Pasang pemeriksaan ketersediaan dari luar untuk alur itu dan pantau masa berlaku sertifikat serta domain",
    "Pasang pelacakan kesalahan pada aplikasi dan tentukan siapa yang menerima peringatannya",
    "Tulis prosedur insiden satu halaman: siapa memimpin, siapa berkomunikasi, dan langkah pemulihan awal",
    "Jadwalkan uji pemulihan cadangan dan catat hasilnya",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Monitoring bukan tentang menghindari semua gangguan, melainkan tentang mengetahuinya lebih cepat, memahaminya lebih baik, dan memulihkannya dengan lebih tenang. Pemeriksaan dari sudut pandang pengguna, peringatan yang bermakna, pencatatan yang rapi, komunikasi yang jujur, dan kebiasaan belajar dari setiap insiden membuat sistem makin tangguh dari waktu ke waktu." },
  { type: "p", text: "Mulailah kecil dengan hal yang paling merugikan bila mati, lalu kembangkan seiring bisnis tumbuh. Dengan begitu Anda tidak lagi bergantung pada pelanggan untuk memberi tahu bahwa ada yang salah." },
  {
    type: "cta",
    title: "Ingin sistem yang dipantau dan dirawat dengan baik setelah diluncurkan?",
    text: "Tim AG·SORA membangun website dan aplikasi lengkap dengan pemantauan, pelacakan kesalahan, dan prosedur pemeliharaan yang jelas. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/custom-software",
    label: "Konsultasi gratis",
  },
];
