import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Membangun aplikasi mobile bisnis sering terasa seperti garis akhir: fitur selesai, pengujian lulus, aplikasi tayang di toko aplikasi. Padahal bagi pengguna, perjalanan baru dimulai pada saat itu. Beberapa menit pertama setelah aplikasi dibuka menentukan apakah seseorang akan kembali besok atau menghapusnya sebelum sempat merasakan manfaatnya." },
  { type: "p", text: "Fase awal itu disebut onboarding, yaitu proses memperkenalkan pengguna baru pada aplikasi hingga mereka mencapai momen \"oh, ini berguna\". Onboarding yang baik bukan sekadar rangkaian layar pengantar yang bisa digeser. Ia mencakup bagaimana pengguna mendaftar, apa yang diminta dari mereka, kapan izin akses diminta, dan seberapa cepat mereka berhasil melakukan sesuatu yang bernilai." },
  { type: "p", text: "Artikel ini membahas onboarding dari sudut pandang pemilik bisnis yang ingin aplikasinya benar-benar dipakai, bukan hanya diunduh. Kami tidak memakai angka rekaan tentang tingkat retensi; setiap aplikasi, audiens, dan industri berbeda. Yang kami tawarkan adalah prinsip dan cara mengukur yang bisa Anda terapkan pada data aplikasi Anda sendiri, serta kesalahan umum yang sebaiknya dihindari sejak tahap perancangan." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Tujuan onboarding adalah mengantar pengguna ke momen pertama yang bernilai secepat mungkin, bukan menjelaskan semua fitur",
      "Kurangi hambatan pendaftaran: minta data seperlunya, tawarkan masuk dengan akun yang sudah dimiliki, dan tunda yang bisa ditunda",
      "Minta izin akses, seperti notifikasi dan lokasi, pada saat pengguna paham manfaatnya, bukan di detik pertama",
      "Gunakan panduan kontekstual dan keadaan kosong yang membantu, bukan tutorial panjang yang dilewati",
      "Ukur tiap langkah dengan corong sederhana, lalu perbaiki satu hambatan terbesar dalam satu waktu",
    ],
  },
  { type: "h2", text: "Mengapa beberapa menit pertama begitu menentukan" },
  { type: "p", text: "Pengguna ponsel membuka dan meninggalkan aplikasi dengan cepat. Mereka punya banyak aplikasi lain yang bersaing merebut perhatian, dan kesabaran mereka terhadap aplikasi baru biasanya pendek. Jika dalam beberapa menit pertama mereka bingung, diminta terlalu banyak hal, atau tidak melihat manfaat jelas, tombol hapus hanya berjarak satu ketukan." },
  { type: "p", text: "Ada alasan psikologis di baliknya. Pengguna baru datang dengan satu harapan: aplikasi ini akan membantu saya menyelesaikan sesuatu. Setiap langkah yang tidak membawa mereka lebih dekat ke harapan itu terasa seperti hambatan. Pendaftaran panjang, layar pengantar yang menjelaskan hal-hal yang belum relevan, dan permintaan izin yang mendadak semuanya menunda manfaat yang dijanjikan." },
  { type: "p", text: "Bagi bisnis, onboarding yang buruk berarti biaya yang terbuang. Anda sudah membayar untuk pengembangan, promosi, dan mungkin iklan untuk mendatangkan pengguna. Jika sebagian besar dari mereka pergi pada menit pertama, setiap unduhan menjadi mahal. Memperbaiki onboarding sering kali lebih murah dan lebih berdampak daripada mendatangkan lebih banyak pengguna ke corong yang bocor." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
    alt: "Dua orang menunjuk layar laptop sambil berdiskusi",
    caption: "Merancang onboarding sebaiknya dimulai dengan berdiskusi tentang apa yang sebenarnya ingin dicapai pengguna baru, bukan tentang fitur apa yang ingin dipamerkan.",
  },
  { type: "h2", text: "Mulai dari momen pertama yang bernilai" },
  { type: "p", text: "Pertanyaan pertama dalam merancang onboarding bukanlah \"apa yang harus kami jelaskan?\", melainkan \"apa momen pertama saat pengguna merasakan manfaat nyata?\" Momen itu kadang disebut momen aha. Untuk aplikasi pemesanan, mungkin saat pengguna berhasil memesan layanan pertama. Untuk aplikasi kasir, saat transaksi pertama tercatat. Untuk aplikasi absensi, saat karyawan berhasil mencatat kehadiran pertamanya." },
  { type: "p", text: "Setelah momen itu teridentifikasi, rancang jalur tersingkat menuju ke sana. Setiap layar, isian, dan keputusan di antara pembukaan aplikasi dan momen itu perlu dipertanyakan: apakah ini benar-benar perlu sekarang? Jika tidak, tunda, sederhanakan, atau hapus. Hasil akhirnya biasanya jalur yang jauh lebih pendek daripada yang dibayangkan di awal." },
  { type: "p", text: "Libatkan pengguna sungguhan dalam menentukan momen ini. Amati beberapa orang yang belum pernah memakai aplikasi Anda mencoba mencapai tujuan tertentu tanpa dibantu. Tempat mereka ragu, salah ketuk, atau bertanya adalah petunjuk paling jujur tentang hambatan onboarding Anda. Pengamatan lima atau enam orang saja sudah sering membuka masalah yang tidak terlihat oleh tim pengembang yang terlalu akrab dengan aplikasinya." },
  { type: "h3", text: "Bedakan jenis pengguna" },
  { type: "p", text: "Tidak semua pengguna baru punya tujuan yang sama. Pemilik toko yang mendaftar di aplikasi manajemen berbeda kebutuhannya dengan karyawan yang diundang ke aplikasi yang sama. Jika aplikasi melayani beberapa peran, pertimbangkan jalur onboarding berbeda untuk tiap peran, atau satu pertanyaan awal singkat yang mengarahkan ke jalur yang tepat. Jalur yang relevan terasa lebih singkat bagi pengguna, meski jumlah langkahnya sama." },
  { type: "h2", text: "Merancang pendaftaran dengan hambatan sekecil mungkin" },
  { type: "p", text: "Pendaftaran adalah gerbang pertama, dan sering kali gerbang tersempit. Setiap kolom yang harus diisi meningkatkan kemungkinan orang menyerah. Prinsip dasarnya: minta hanya yang benar-benar dibutuhkan untuk memulai, dan kumpulkan sisanya nanti ketika ada alasan yang jelas." },
  {
    type: "ol",
    items: [
      "Tawarkan opsi masuk dengan akun yang sudah dimiliki pengguna, jika sesuai dengan audiens Anda dan kebijakan privasi Anda",
      "Untuk pendaftaran dengan nomor ponsel atau email, gunakan kode verifikasi sekali pakai agar pengguna tidak perlu mengarang dan mengingat kata sandi baru",
      "Tampilkan hanya kolom yang perlu, dengan label jelas dan jenis papan ketik yang sesuai, misalnya papan angka untuk nomor telepon",
      "Beri umpan balik langsung pada kesalahan isian, jangan menunggu pengguna menekan kirim",
      "Pertimbangkan membiarkan pengguna menjelajah sebagian aplikasi sebelum diminta mendaftar, jika sifat aplikasi memungkinkan",
    ],
  },
  { type: "p", text: "Alasan di balik setiap permintaan data harus bisa Anda jelaskan. Jika Anda meminta tanggal lahir, alamat, atau data lain, tampilkan secara singkat mengapa data itu dibutuhkan. Transparansi menumbuhkan kepercayaan, dan sebaiknya sejalan dengan kebijakan privasi serta ketentuan perlindungan data pribadi yang berlaku. Rujuklah ketentuan terbaru, jangan bergantung pada ringkasan yang mungkin sudah usang." },
  { type: "h3", text: "Pengalaman di perangkat kecil" },
  { type: "p", text: "Ingat bahwa pengguna sering mendaftar sambil berdiri, di keramaian, dengan satu tangan. Targetkan area ketuk yang cukup besar, jarak antar elemen yang nyaman, dan teks yang terbaca tanpa memicingkan mata. Pastikan papan ketik tidak menutupi kolom yang sedang diisi dan tombol lanjut tetap terlihat. Detail kecil seperti ini sering membedakan pendaftaran yang mulus dari yang menjengkelkan." },
  { type: "h2", text: "Layar pengantar: kapan membantu, kapan mengganggu" },
  { type: "p", text: "Banyak aplikasi membuka dengan tiga sampai lima layar yang bisa digeser, berisi ilustrasi dan kalimat promosi. Layar semacam ini punya tempat, tetapi sering disalahgunakan. Pengguna yang baru membuka aplikasi biasanya ingin segera mencoba, bukan membaca. Layar pengantar yang menjelaskan fitur yang belum mereka perlukan kebanyakan hanya dilewati tanpa dibaca." },
  { type: "p", text: "Layar pengantar paling berguna jika singkat, menjelaskan nilai utama dalam bahasa pengguna, dan selalu bisa dilewati. Satu sampai tiga layar yang menjawab pertanyaan \"apa yang bisa saya lakukan di sini dan mengapa penting bagi saya\" sudah cukup. Hindari jargon teknis dan janji yang terlalu umum." },
  { type: "p", text: "Alternatif yang sering lebih efektif adalah panduan kontekstual: petunjuk kecil yang muncul pada saat dan tempat yang relevan. Misalnya, ketika pengguna pertama kali membuka halaman laporan, muncul penjelasan singkat tentang cara membaca grafik. Petunjuk seperti ini dipelajari sambil melakukan, sehingga lebih melekat dan tidak memaksa pengguna menghafal sebelum mulai." },
  {
    type: "callout",
    title: "Prinsip sederhana",
    text: "Jelaskan sesuatu tepat sebelum pengguna membutuhkannya, bukan jauh sebelumnya. Informasi yang datang terlalu awal terlupakan, dan yang datang terlambat membuat pengguna tersesat.",
  },
  { type: "h2", text: "Meminta izin akses pada waktu yang tepat" },
  { type: "p", text: "Aplikasi sering memerlukan izin: mengirim notifikasi, mengakses lokasi, kamera, kontak, atau galeri foto. Cara dan waktu meminta izin sangat memengaruhi apakah pengguna setuju. Meminta semuanya di detik pertama, sebelum pengguna paham manfaatnya, hampir selalu berujung penolakan." },
  { type: "p", text: "Kebiasaan yang lebih baik adalah meminta izin tepat ketika fitur yang membutuhkannya akan dipakai. Aplikasi pengiriman bisa meminta izin lokasi saat pengguna hendak melihat kurir terdekat. Aplikasi yang memindai dokumen meminta izin kamera saat pengguna menekan tombol pindai. Sebelum dialog sistem muncul, tampilkan satu kalimat penjelasan tentang apa manfaatnya bagi pengguna. Dengan konteks seperti itu, kemungkinan disetujui jauh lebih besar." },
  { type: "p", text: "Perlu diingat bahwa pada banyak perangkat, jika pengguna menolak izin sistem, aplikasi tidak bisa meminta lagi dengan dialog yang sama; pengguna harus mengubahnya sendiri di pengaturan perangkat. Karena itu, kesempatan meminta izin perlu dipakai dengan bijak. Siapkan pula tampilan cadangan yang tetap berguna ketika izin ditolak, dengan penjelasan ramah tentang cara mengaktifkannya nanti jika pengguna berubah pikiran." },
  { type: "p", text: "Soal notifikasi, pertimbangan tambahan: pengguna cenderung mengizinkannya jika sudah merasakan nilai aplikasi dan paham jenis pesan yang akan datang. Topik ini terkait erat dengan retensi, dan kami bahas lebih dalam di artikel kami tentang notifikasi push dan retensi aplikasi mobile." },
  { type: "h2", text: "Keadaan kosong dan data awal" },
  { type: "p", text: "Salah satu tantangan onboarding yang sering terlupa adalah layar kosong. Aplikasi baru belum berisi data pengguna, sehingga daftar pesanan, riwayat transaksi, atau dasbor tampil kosong. Layar kosong yang hanya bertuliskan \"Belum ada data\" adalah peluang yang terbuang." },
  { type: "p", text: "Ubah keadaan kosong menjadi petunjuk langkah pertama. Tampilkan penjelasan singkat tentang apa yang akan muncul di sini dan tombol yang jelas untuk memulai, misalnya \"Tambah produk pertama Anda\". Untuk dasbor, pertimbangkan menampilkan contoh data yang jelas ditandai sebagai contoh, sehingga pengguna bisa membayangkan hasil akhirnya, lalu menghilangkannya begitu data nyata masuk." },
  { type: "p", text: "Jika aplikasi Anda membutuhkan banyak data awal supaya berguna, seperti daftar produk, pelanggan, atau karyawan, tawarkan cara memasukkannya dengan cepat. Impor dari spreadsheet, template siap pakai, atau bantuan dari tim Anda dapat memangkas hambatan besar. Aplikasi yang tidak berguna sebelum 200 baris data diketik tangan akan sering ditinggalkan sebelum sampai ke sana." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1531297484001-80022131f5a1",
    alt: "Laptop setengah tertutup memancarkan cahaya berwarna di ruangan gelap",
    caption: "Sebelum data pertama masuk, aplikasi terasa kosong; petunjuk langkah pertama yang jelas menjaga pengguna tetap melangkah.",
  },
  { type: "h2", text: "Membangun kebiasaan setelah momen pertama" },
  { type: "p", text: "Onboarding tidak berhenti saat pengguna mencapai momen aha pertama. Tantangan berikutnya adalah membuat mereka kembali. Banyak pengguna mencoba sekali, merasa cukup, lalu lupa. Beberapa pendekatan membantu mengubah percobaan pertama menjadi kebiasaan." },
  { type: "p", text: "Tunjukkan langkah berikutnya yang logis. Setelah pengguna menyelesaikan transaksi pertama, arahkan ke hal yang wajar dilakukan selanjutnya, misalnya melihat laporan atau mengundang rekan kerja. Gunakan daftar kemajuan sederhana yang memperlihatkan seberapa jauh pengguna sudah menyiapkan akunnya, tetapi hindari kesan menggurui atau memaksa. Rayakan pencapaian kecil dengan umpan balik yang sopan dan singkat." },
  { type: "p", text: "Kirim pesan lanjutan yang relevan dan tidak berlebihan, lewat notifikasi di dalam aplikasi, email, atau pesan lain yang sudah disetujui pengguna. Pesan seperti \"Anda belum menyelesaikan pengaturan toko, selesaikan dalam dua menit\" lebih berguna daripada promosi umum. Dan selalu beri kemudahan untuk mengatur atau menghentikan pesan tersebut." },
  { type: "h3", text: "Dukungan saat pengguna kebingungan" },
  { type: "p", text: "Sediakan jalan keluar yang mudah ketika pengguna tersangkut: pusat bantuan singkat, pertanyaan yang sering diajukan, atau tombol hubungi yang membuka percakapan dengan tim Anda. Pengguna yang tersangkut tanpa jalan keluar biasanya tidak mengirim keluhan; mereka hanya pergi. Dukungan yang terlihat dan mudah dijangkau mengurangi kehilangan diam-diam itu." },
  { type: "h2", text: "Mengukur onboarding dengan corong sederhana" },
  { type: "p", text: "Anda tidak bisa memperbaiki onboarding dengan menebak. Susun corong sederhana yang menghitung berapa pengguna yang melewati tiap langkah: membuka aplikasi, memulai pendaftaran, menyelesaikan pendaftaran, mencapai momen pertama yang bernilai, dan kembali pada hari-hari berikutnya. Bandingkan jumlah di antara tiap langkah untuk menemukan titik kebocoran terbesar." },
  { type: "p", text: "Beberapa pertanyaan membantu menafsirkan angka. Jika banyak orang membuka tetapi sedikit memulai pendaftaran, mungkin nilai aplikasi belum jelas di awal. Jika banyak memulai tetapi sedikit menyelesaikan, formulirnya mungkin terlalu panjang atau ada galat teknis. Jika banyak mendaftar tetapi sedikit mencapai momen pertama, jalur menuju nilai terlalu berliku. Jika banyak mencapai momen pertama tetapi tidak kembali, masalahnya ada pada kebiasaan dan retensi, bukan onboarding awal." },
  { type: "p", text: "Gunakan data kuantitatif bersama pengamatan kualitatif. Angka memberi tahu di mana pengguna pergi, sedangkan pengamatan dan wawancara singkat memberi tahu mengapa. Dan jangan lupa menjaga privasi: kumpulkan hanya data yang perlu, beri tahu pengguna dengan jelas, dan patuhi ketentuan yang berlaku." },
  { type: "h3", text: "Uji perubahan satu per satu" },
  { type: "p", text: "Ketika menemukan hambatan, ubah satu hal pada satu waktu dan bandingkan hasilnya. Jika Anda mengubah lima hal sekaligus, Anda tidak akan tahu mana yang berpengaruh. Untuk aplikasi dengan jumlah pengguna cukup, uji perbandingan dua versi dapat membantu. Untuk aplikasi yang masih kecil, perubahan bertahap dengan pengamatan cermat sudah memadai." },
  { type: "h2", text: "Kesalahan onboarding yang sering terjadi" },
  { type: "p", text: "Beberapa kesalahan muncul berulang pada banyak aplikasi. Meminta pendaftaran sebelum pengguna sempat melihat manfaat apa pun adalah salah satunya. Menumpuk terlalu banyak layar pengantar yang tidak bisa dilewati adalah yang lain. Meminta semua izin sekaligus di awal, memaksa pengguna mengisi profil lengkap sebelum bisa memakai aplikasi, dan membiarkan layar kosong tanpa petunjuk juga umum terjadi." },
  { type: "p", text: "Kesalahan lain yang sering terlewat adalah tidak memeriksa pengalaman pada kondisi nyata: koneksi lambat, perangkat lama, atau layar kecil. Aplikasi yang terasa mulus di perangkat pengembang bisa menyiksa di ponsel pengguna yang sebenarnya. Uji onboarding pada beberapa jenis perangkat dan kualitas jaringan, termasuk yang paling sederhana di antara pengguna Anda." },
  { type: "p", text: "Terakhir, banyak tim menganggap onboarding sebagai proyek sekali jadi. Padahal aplikasi berubah, fitur bertambah, dan audiens bergeser. Tinjau onboarding secara berkala dan perbarui ketika data menunjukkan hambatan baru." },
  { type: "h2", text: "Langkah praktis memperbaiki onboarding" },
  {
    type: "ol",
    items: [
      "Tentukan momen pertama yang bernilai bagi tiap jenis pengguna aplikasi Anda",
      "Pangkas langkah dan isian di antara pembukaan aplikasi dan momen itu, tunda yang tidak mendesak",
      "Sederhanakan pendaftaran dan gunakan verifikasi sekali pakai bila sesuai",
      "Pindahkan permintaan izin ke saat fitur terkait dipakai, disertai penjelasan manfaatnya",
      "Ganti layar kosong dengan petunjuk langkah pertama dan sediakan cara cepat mengisi data awal",
      "Pasang corong pengukuran sederhana dan perbaiki satu hambatan terbesar setiap kali",
    ],
  },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Onboarding adalah jembatan antara aplikasi yang sudah dibangun dan aplikasi yang benar-benar dipakai. Aplikasi dengan fitur lengkap tetapi onboarding buruk akan kalah oleh aplikasi sederhana yang membawa pengguna pada manfaat dalam hitungan menit. Kuncinya bukan menjelaskan lebih banyak, melainkan menghilangkan hambatan dan mengantar pengguna ke nilai secepat mungkin." },
  { type: "p", text: "Jika Anda sedang merencanakan aplikasi mobile untuk bisnis, pikirkan onboarding sejak tahap perancangan, bukan sebagai tambahan di akhir. Rancang bersama jalur pengguna, uji dengan orang sungguhan, ukur hasilnya, dan perbaiki terus. Dengan begitu investasi pengembangan Anda berubah menjadi pengguna aktif, bukan sekadar angka unduhan." },
  {
    type: "cta",
    title: "Merencanakan aplikasi mobile untuk bisnis Anda?",
    text: "Tim AG·SORA merancang aplikasi mobile dengan pengalaman pengguna yang matang, dari pendaftaran hingga momen pertama yang bernilai. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/mobile",
    label: "Konsultasi gratis",
  },
];
