import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Menjual dengan tempo pembayaran adalah hal lazim dalam bisnis antarperusahaan. Barang dikirim atau jasa diselesaikan hari ini, pembayaran diharapkan tiga puluh hari kemudian. Di antara dua titik itu ada pekerjaan yang sering diabaikan: membuat faktur yang benar, mengirimkannya tepat waktu kepada orang yang tepat, mengingatkan, dan mencocokkan pembayaran yang masuk." },
  { type: "p", text: "Pada banyak bisnis, pekerjaan ini dilakukan manual dari tabel hitung dan surel. Faktur terlambat dibuat karena menunggu surat jalan, terkirim ke alamat yang salah, atau tidak pernah ditindaklanjuti ketika jatuh tempo lewat. Uang yang seharusnya sudah masuk tertahan di tagihan yang tidak diurus, sementara bisnis tetap harus membayar gaji dan pemasok tepat waktu." },
  { type: "p", text: "Artikel ini membahas cara merapikan dan mengotomatiskan siklus dari pesanan sampai uang diterima: penerbitan faktur, pengiriman, pengingat, pencocokan pembayaran, dan penanganan sengketa. Kami tidak menjanjikan angka percepatan tertentu; yang kami tawarkan adalah urutan kerja yang masuk akal untuk bisnis kecil dan menengah." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Faktur yang benar dan tepat waktu adalah syarat pertama pembayaran yang tepat waktu",
      "Hubungkan faktur dengan pesanan dan pengiriman agar data tidak diketik ulang",
      "Otomatiskan pengiriman dan pengingat, tetapi biarkan manusia menangani kasus khusus",
      "Cocokkan pembayaran masuk secara otomatis dan tangani selisih sebagai pengecualian",
      "Ukur umur piutang secara rutin dan gunakan sebagai dasar tindakan, bukan sekadar laporan",
    ],
  },
  { type: "h2", text: "Mengapa penagihan sering terlambat" },
  { type: "p", text: "Penyebab paling umum bukan pelanggan yang enggan membayar, melainkan prosesnya sendiri. Faktur terlambat terbit karena bagian penjualan belum menyerahkan data, atau bagian gudang belum mengonfirmasi pengiriman. Setiap hari keterlambatan penerbitan hampir selalu menjadi keterlambatan pembayaran dengan jumlah hari yang sama." },
  { type: "p", text: "Penyebab lain adalah faktur yang salah: harga tidak sesuai kesepakatan, nomor pesanan pembelian pelanggan tidak tercantum, atau alamat penagihan keliru. Bagian keuangan pelanggan umumnya menolak atau menahan faktur yang tidak lengkap, dan penolakan itu baru diketahui berminggu-minggu kemudian bila tidak ada yang memantau." },
  { type: "p", text: "Terakhir, tidak ada yang bertanggung jawab atas tindak lanjut. Penagihan terasa kurang menyenangkan dan mudah ditunda, sementara bagian penjualan khawatir merusak hubungan. Tanpa jadwal dan pemilik yang jelas, tagihan jatuh tempo tidak ditindaklanjuti sampai kas mulai terasa ketat." },
  { type: "h2", text: "Faktur yang benar sejak pertama" },
  { type: "p", text: "Fondasinya adalah data yang mengalir tanpa diketik ulang. Faktur sebaiknya dihasilkan langsung dari pesanan dan pengiriman yang sudah tercatat, memakai harga yang disepakati dan syarat pembayaran dari data pelanggan. Semakin sedikit tangan yang menyentuh angka, semakin sedikit kesalahan yang perlu dikoreksi." },
  { type: "p", text: "Pahami apa yang dibutuhkan pelanggan agar faktur diterima tanpa hambatan: nomor pesanan pembelian mereka, nama pihak yang menerima, format dokumen, dan kanal pengiriman. Simpan kebutuhan khusus ini di catatan pelanggan sehingga setiap faktur otomatis memenuhinya, termasuk pelanggan besar yang mensyaratkan portal tertentu." },
  { type: "p", text: "Pastikan faktur memenuhi ketentuan perpajakan yang berlaku, termasuk format dan penomoran. Ketentuan ini dapat berubah, sehingga rujuk selalu aturan terbaru dari otoritas pajak dan konsultasikan dengan akuntan atau konsultan pajak Anda." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1554224155-6726b3ff858f",
    alt: "Tumpukan formulir, nota, dan kalkulator di atas meja",
    caption: "Faktur yang dibuat dari data pesanan dan pengiriman mengurangi kesalahan yang menunda pembayaran.",
  },
  { type: "h2", text: "Kapan faktur diterbitkan dan bagaimana dikirim" },
  { type: "p", text: "Tentukan pemicu penerbitan secara tegas: saat barang dikirim, saat barang diterima, saat pekerjaan selesai, atau berdasarkan tahapan pada proyek. Pemicu yang jelas menghilangkan perdebatan internal dan membuat faktur terbit pada hari yang sama dengan kejadiannya, bukan menunggu akhir bulan." },
  { type: "p", text: "Kirim faktur lewat kanal yang benar-benar dibaca. Surel dengan lampiran sering tenggelam; tautan langsung ke faktur dengan tombol pembayaran lebih jarang terlewat. Beberapa pelanggan menginginkan pengiriman lewat portal atau pertukaran dokumen elektronik. Catat preferensi ini dan biarkan sistem memilih kanal yang tepat." },
  { type: "p", text: "Setelah faktur terkirim, catat statusnya: terkirim, dibuka, diakui, atau ditolak. Banyak sistem menyediakan tanda terima baca. Informasi ini sederhana tetapi mengubah penagihan dari menebak menjadi mengetahui apakah faktur sudah sampai kepada orang yang berwenang." },
  { type: "h2", text: "Syarat pembayaran dan insentif" },
  { type: "p", text: "Syarat pembayaran adalah keputusan bisnis, bukan sekadar kebiasaan. Tempo yang panjang membantu pelanggan tetapi menekan kas Anda. Tinjau syarat standar secara berkala dan sesuaikan dengan profil risiko dan nilai pelanggan. Pelanggan baru atau berisiko dapat diminta uang muka atau tempo yang lebih pendek." },
  { type: "p", text: "Pertimbangkan insentif pembayaran lebih awal untuk pelanggan tertentu, misalnya potongan kecil bila dibayar dalam jangka waktu singkat. Hitung dengan cermat apakah biaya insentif lebih kecil daripada manfaat kas yang lebih cepat bagi bisnis Anda. Untuk sebagian bisnis ini menguntungkan, untuk yang lain tidak." },
  { type: "p", text: "Pertimbangkan juga biaya keterlambatan bila memang dicantumkan dalam kesepakatan. Terapkan secara konsisten dan komunikasikan sejak awal; menerapkannya mendadak pada pelanggan yang tidak pernah diberi tahu hanya merusak hubungan. Banyak bisnis memilih tidak menerapkannya, tetapi tetap menyebutkannya sebagai alasan untuk disiplin." },
  { type: "h2", text: "Pengingat yang sopan dan konsisten" },
  { type: "p", text: "Pengingat otomatis adalah salah satu manfaat otomasi yang paling terasa. Rancang urutannya: pemberitahuan ramah beberapa hari sebelum jatuh tempo, pengingat pada hari jatuh tempo, lalu pengingat setelah lewat tempo dengan nada yang makin tegas. Setiap pesan memuat rincian faktur dan cara membayar agar penerima tidak perlu bertanya." },
  { type: "ul", items: [
    "Sebelum jatuh tempo: pemberitahuan singkat berisi ringkasan dan tautan pembayaran",
    "Pada hari jatuh tempo: pengingat ramah bahwa pembayaran jatuh tempo hari ini",
    "Beberapa hari setelah lewat tempo: pengingat dengan permintaan konfirmasi jadwal pembayaran",
    "Setelah lewat tempo lebih lama: tindak lanjut oleh orang, melalui telepon atau pertemuan",
    "Pada tingkat lanjut: eskalasi ke pihak berwenang di perusahaan pelanggan atau pembahasan kebijakan kredit",
  ] },
  { type: "p", text: "Sisakan ruang bagi penilaian manusia. Pelanggan besar yang bayarnya selalu tertunda dua hari mungkin tidak perlu pengingat keras, sedangkan pelanggan baru dengan tagihan besar perlu perhatian lebih awal. Sistem yang baik memungkinkan pengecualian per pelanggan dan menghentikan pengingat otomatis ketika ada sengketa yang sedang diselesaikan." },
  { type: "h2", text: "Mencocokkan pembayaran yang masuk" },
  { type: "p", text: "Pembayaran yang masuk ke rekening perlu dicocokkan dengan faktur yang dibayarnya. Masalahnya, pelanggan sering membayar beberapa faktur sekaligus, membayar sebagian, atau memotong biaya tanpa penjelasan. Mencocokkan ini secara manual memakan waktu dan rawan salah." },
  { type: "p", text: "Banyak ERP mengimpor mutasi rekening dan mengusulkan pasangan antara pembayaran dan faktur berdasarkan nominal, nama pengirim, dan referensi. Cocokkan yang pasti secara otomatis, dan sisakan yang meragukan untuk ditinjau orang. Gunakan nomor faktur sebagai referensi pembayaran dan mintalah pelanggan mencantumkannya." },
  { type: "p", text: "Tangani selisih dengan aturan jelas: pembayaran kurang, pembayaran lebih, atau potongan. Selisih kecil dapat dibukukan sebagai penyesuaian dengan batas yang disetujui, sedangkan selisih besar perlu ditelusuri. Tanpa aturan, selisih ini menumpuk di akun sementara dan menyulitkan penutupan buku." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1553877522-43269d4ea984",
    alt: "Dokumen laporan keuangan dan kalkulator di atas meja kerja",
    caption: "Pencocokan pembayaran yang rapi membuat umur piutang yang dilaporkan benar-benar mencerminkan keadaan.",
  },
  { type: "h2", text: "Menangani sengketa tagihan" },
  { type: "p", text: "Tidak semua faktur yang tertunda adalah pelanggan yang menunda. Sebagian adalah sengketa: barang yang dikeluhkan, harga yang dipertanyakan, atau jumlah yang tidak cocok. Tandai faktur dalam sengketa agar tidak ikut diingatkan secara otomatis, dan catat apa yang dipersoalkan serta siapa yang menanganinya." },
  { type: "p", text: "Selesaikan sengketa dengan cepat karena nilai tertahannya bukan hanya satu faktur. Pelanggan yang sedang berselisih sering menahan pembayaran faktur lain. Catat penyebab setiap sengketa dan tinjau polanya: apakah sering berasal dari harga yang salah, pengiriman yang tidak lengkap, atau faktur yang terlambat? Perbaiki di hulu." },
  { type: "p", text: "Dokumentasikan setiap kesepakatan penyelesaian, termasuk nota kredit yang diterbitkan. Nota kredit yang tidak tercatat dengan baik membuat pelanggan merasa membayar dua kali atau membuat piutang tampak lebih besar daripada sebenarnya." },
  { type: "h2", text: "Memantau umur piutang dan risiko kredit" },
  { type: "p", text: "Laporan umur piutang mengelompokkan tagihan berdasarkan berapa lama telah beredar, misalnya belum jatuh tempo, terlambat satu bulan, atau lebih lama. Laporan ini adalah alat kerja, bukan sekadar arsip. Tinjau mingguan, tentukan tindakan untuk tiap kelompok, dan tetapkan orang yang bertanggung jawab." },
  { type: "p", text: "Gunakan data historis untuk menilai risiko pelanggan. Pelanggan yang selalu terlambat berat perlu batas kredit lebih rendah atau syarat lebih ketat. Sebaliknya, pelanggan yang konsisten tepat waktu layak mendapat perlakuan lebih longgar. Batas kredit sebaiknya terhubung dengan pesanan sehingga sistem memperingatkan sebelum pesanan baru disetujui untuk pelanggan yang menunggak." },
  { type: "p", text: "Perhatikan konsentrasi risiko. Bila sebagian besar piutang berasal dari satu atau dua pelanggan, kegagalan bayar satu di antaranya berdampak besar. Pantau proporsi ini dan kembangkan basis pelanggan atau jaminan sesuai kebutuhan." },
  { type: "callout", title: "Penagihan adalah bagian dari hubungan pelanggan", text: "Pengingat yang sopan, jelas, dan konsisten justru menunjukkan profesionalisme. Pelanggan yang baik umumnya menghargai tagihan yang akurat dan mudah dibayar. Yang merusak hubungan adalah faktur yang salah, pengingat yang tiba-tiba keras, dan tidak adanya jawaban ketika mereka bertanya." },
  { type: "h2", text: "Dampak pada arus kas dan perencanaan" },
  { type: "p", text: "Ketika data faktur, jatuh tempo, dan pembayaran terhubung, Anda dapat memprakirakan kas masuk dengan lebih baik. Bukan sekadar berapa piutang yang ada, tetapi kapan kira-kira masing-masing akan dibayar berdasarkan kebiasaan tiap pelanggan. Perkiraan ini membantu memutuskan pembayaran kepada pemasok dan kebutuhan pendanaan jangka pendek." },
  { type: "p", text: "Gunakan juga untuk melihat dampak keputusan penjualan. Diskon besar dengan tempo panjang mungkin tampak menguntungkan di laporan laba rugi, tetapi menekan kas. Dengan data umur piutang, Anda dapat menilai nilai sebenarnya dari penjualan kepada pelanggan tertentu." },
  { type: "p", text: "Lakukan peninjauan bulanan atas penghapusan piutang yang tidak tertagih dengan persetujuan yang tercatat. Piutang lama yang sebenarnya sudah tidak mungkin tertagih membuat laporan tampak sehat padahal tidak. Perlakuan akuntansi dan pajaknya sebaiknya dikonsultasikan dengan akuntan Anda." },
  { type: "h2", text: "Penagihan bertahap dan penagihan berulang" },
  { type: "p", text: "Tidak semua penjualan diselesaikan dengan satu faktur. Proyek sering ditagih bertahap berdasarkan tonggak pekerjaan, sedangkan layanan berlangganan ditagih berulang setiap periode. Keduanya perlu jadwal dan aturan yang tertulis di sistem agar tidak ada tahap yang lupa ditagih." },
  { type: "p", text: "Untuk tagihan bertahap, hubungkan setiap tahap dengan bukti penyelesaian, misalnya berita acara atau persetujuan pelanggan. Faktur yang disertai bukti jauh lebih sulit ditolak, dan proses persetujuan di pihak pelanggan berjalan lebih cepat." },
  { type: "p", text: "Untuk tagihan berulang, otomatiskan penerbitan sesuai jadwal dan perhatikan perubahan: penambahan layanan di tengah periode, perubahan harga, atau penghentian. Tinjau secara berkala daftar tagihan berulang agar tidak ada pelanggan yang ditagih untuk layanan yang sudah berhenti, atau sebaliknya, layanan yang berjalan tanpa ditagih." },
  { type: "h2", text: "Portal pelanggan untuk faktur dan pembayaran" },
  { type: "p", text: "Portal sederhana tempat pelanggan melihat seluruh faktur, mengunduh salinan, dan membayar langsung akan mengurangi banyak pertanyaan rutin. Pelanggan tidak perlu mencari surel lama atau meminta salinan ulang, dan bagian keuangan Anda terbebas dari pekerjaan mengirim ulang dokumen." },
  { type: "p", text: "Sediakan beberapa cara membayar yang umum bagi pelanggan Anda, seperti transfer bank dengan nomor rekening virtual, kartu, atau dompet digital, sehingga hambatan membayar rendah. Pembayaran lewat jalur yang terhubung ke sistem biasanya otomatis tercocokkan, mengurangi kerja manual di sisi Anda." },
  { type: "p", text: "Pastikan portal aman: akses per pelanggan, hak akses yang jelas, dan catatan aktivitas. Faktur memuat informasi sensitif seperti harga dan volume pembelian yang tidak boleh terlihat oleh pelanggan lain." },
  { type: "h2", text: "Kontrol internal dan pembagian tugas" },
  { type: "p", text: "Otomasi tidak menghapus kebutuhan akan kontrol. Orang yang menerbitkan faktur sebaiknya bukan orang yang mencocokkan pembayaran atau menyetujui pembatalan dan nota kredit. Pemisahan ini mengurangi peluang kesalahan maupun penyalahgunaan, misalnya pembayaran yang dialihkan atau faktur yang dibatalkan tanpa sepengetahuan siapa pun." },
  { type: "p", text: "Wajibkan persetujuan untuk pembatalan faktur, nota kredit di atas batas tertentu, dan penghapusan piutang, lengkap dengan alasan yang tercatat. Tinjau secara berkala daftar pembatalan dan penyesuaian untuk melihat pola yang tidak wajar." },
  { type: "p", text: "Pastikan penomoran faktur berurutan dan tidak dapat diubah secara diam-diam. Penomoran yang rapi mempermudah pemeriksaan, memenuhi ketentuan perpajakan, dan menjadi pertahanan pertama bila ada pemeriksaan atau perselisihan di kemudian hari." },
  { type: "h2", text: "Ritme kerja mingguan yang sederhana" },
  { type: "p", text: "Sistem hanya sebaik kebiasaan yang menjalankannya. Tetapkan pertemuan singkat mingguan antara bagian keuangan dan penjualan untuk meninjau tagihan lewat tempo, sengketa yang terbuka, dan pelanggan yang perlu dihubungi langsung. Lima belas menit yang teratur biasanya lebih efektif daripada rapat besar yang jarang." },
  { type: "p", text: "Libatkan bagian penjualan karena merekalah yang memegang hubungan. Penagihan yang disampaikan oleh orang yang dikenal pelanggan sering lebih cepat berhasil, terutama untuk hal yang perlu pembicaraan. Beri mereka data yang jelas agar pembicaraannya konkret, bukan sekadar menanyakan kabar pembayaran." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menunggu akhir bulan untuk menerbitkan faktur yang seharusnya terbit saat kejadian",
    "Mengetik ulang data pesanan ke faktur sehingga rentan salah",
    "Mengirim faktur tanpa mengetahui apakah sudah diterima orang yang berwenang",
    "Mengirim pengingat otomatis untuk faktur yang sedang disengketakan",
    "Membiarkan selisih pembayaran menumpuk tanpa aturan penyelesaian",
    "Menganggap laporan umur piutang sebagai arsip, bukan daftar tindakan",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Hitung berapa hari rata-rata antara pengiriman atau penyelesaian pekerjaan dan faktur terbit",
    "Daftar kebutuhan khusus faktur dari lima pelanggan terbesar dan simpan di catatan pelanggan",
    "Susun jadwal pengingat tertulis dan tentukan siapa yang menjalankannya",
    "Tinjau laporan umur piutang dan tentukan tindakan untuk tiap tagihan yang lewat tempo",
    "Tetapkan aturan penanganan selisih pembayaran kecil dan batas persetujuannya",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Penagihan yang rapi bukan soal menekan pelanggan, melainkan soal memastikan setiap pekerjaan yang sudah Anda selesaikan berubah menjadi uang pada waktunya. Faktur yang benar, pengiriman yang jelas, pengingat yang konsisten, dan pencocokan yang teliti adalah rangkaian kebiasaan yang bersama-sama menjaga kas bisnis." },
  { type: "p", text: "Otomasi membantu menjalankan kebiasaan itu setiap hari tanpa bergantung pada ingatan orang. Mulailah dari bagian yang paling bermasalah, ukur umur piutang secara rutin, dan perbaiki bertahap. Hasilnya adalah kas yang lebih dapat diprediksi dan hubungan pelanggan yang lebih profesional." },
  {
    type: "cta",
    title: "Piutang sering tertahan karena faktur dan penagihan manual?",
    text: "Tim AG·SORA menerapkan ERP yang menghubungkan pesanan, pengiriman, faktur, pengingat, dan pencocokan pembayaran dalam satu alur. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/erp",
    label: "Konsultasi gratis",
  },
];
