import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Kata sandi adalah bagian dari aplikasi yang paling dibenci semua orang. Pelanggan lupa kata sandinya dan meninggalkan keranjang belanja. Karyawan menuliskannya di kertas yang ditempel di monitor. Tim layanan pelanggan menghabiskan waktu mengatur ulang akun. Dan ketika terjadi kebocoran data di tempat lain, kata sandi yang sama yang dipakai di banyak layanan membuka pintu ke aplikasi Anda juga." },
  { type: "p", text: "Selama bertahun-tahun jawaban yang ditawarkan adalah menambah aturan: kata sandi harus lebih panjang, memakai simbol, diganti berkala, lalu ditambah kode lewat SMS. Setiap tambahan membuat masuk ke aplikasi sedikit lebih aman dan jauh lebih merepotkan. Sekarang ada pendekatan yang menjanjikan keduanya sekaligus: lebih aman dan lebih mudah. Namanya passkey." },
  { type: "p", text: "Artikel ini menjelaskan passkey dan cara masuk tanpa kata sandi dari sudut pandang pemilik bisnis. Kami membahas cara kerjanya secara sederhana, manfaat dan batasannya, pilihan lain seperti tautan ajaib dan kode sekali pakai, pemulihan akun, serta cara menerapkannya bertahap di website dan aplikasi mobile. Dukungan perangkat dan peramban terus berkembang, jadi periksa keadaan terkini bersama pengembang Anda sebelum memutuskan." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Kata sandi lemah bukan karena pengguna malas, melainkan karena rancangannya menuntut hal yang sulit dilakukan manusia",
      "Passkey memakai pasangan kunci yang tersimpan di perangkat pengguna dan dibuka dengan sidik jari, wajah, atau PIN perangkat",
      "Passkey tahan terhadap situs tiruan karena terikat pada alamat situs yang asli",
      "Terapkan bertahap: tawarkan sebagai pilihan dulu, jangan langsung menghapus cara lama",
      "Pemulihan akun adalah bagian tersulit dan harus dirancang sama serius dengan cara masuknya",
    ],
  },
  { type: "h2", text: "Mengapa kata sandi menjadi masalah bisnis" },
  { type: "p", text: "Kata sandi menuntut manusia melakukan sesuatu yang tidak wajar: mengingat puluhan rangkaian huruf acak yang berbeda untuk setiap layanan. Karena hampir tidak ada yang sanggup, orang memakai kata sandi yang mudah ditebak atau memakai satu kata sandi untuk semuanya. Itu bukan kelalaian pribadi, melainkan akibat yang bisa diperkirakan dari rancangannya." },
  { type: "p", text: "Bagi bisnis, akibatnya muncul di dua tempat. Yang pertama adalah keamanan. Penyerang mengambil daftar kata sandi yang bocor dari satu layanan dan mencobanya secara otomatis di layanan lain. Yang kedua adalah penjualan dan biaya layanan. Setiap pelanggan yang gagal masuk adalah transaksi yang mungkin batal, dan setiap permintaan atur ulang kata sandi adalah beban bagi tim dukungan." },
  { type: "p", text: "Ancaman yang paling sulit dilawan dengan kata sandi adalah penipuan lewat situs tiruan. Pengguna menerima pesan yang tampak resmi, mengeklik tautan, lalu memasukkan kata sandinya di halaman yang meniru aplikasi Anda. Kata sandi yang paling panjang sekalipun tidak menolong, karena pengguna sendiri yang menyerahkannya." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7",
    alt: "Gembok merah di atas keyboard komputer hitam",
    caption: "Selama pintu masuk bergantung pada rahasia yang harus diingat manusia, pintu itu akan tetap menjadi titik lemah.",
  },
  { type: "h2", text: "Apa itu passkey dalam bahasa sederhana" },
  { type: "p", text: "Passkey menggantikan rahasia yang diingat dengan sepasang kunci digital. Ketika pengguna mendaftar, perangkatnya membuat dua kunci yang berpasangan. Kunci pribadi tetap tersimpan di perangkat dan tidak pernah dikirim ke mana pun. Kunci publik dikirim ke server aplikasi Anda. Kunci publik tidak berbahaya bila bocor, karena tidak bisa dipakai untuk masuk." },
  { type: "p", text: "Ketika pengguna ingin masuk, server mengirim tantangan acak. Perangkat menandatangani tantangan itu dengan kunci pribadi setelah pengguna membuka kunci perangkatnya dengan sidik jari, pengenalan wajah, atau PIN. Server memeriksa tanda tangan dengan kunci publik. Bagi pengguna, seluruh proses terasa seperti membuka kunci ponsel." },
  { type: "p", text: "Penting dipahami bahwa sidik jari atau wajah tidak pernah dikirim ke server Anda. Data biometrik hanya dipakai di perangkat untuk membuka kunci pribadi. Aplikasi Anda tidak menyimpan dan tidak melihatnya. Ini sering menjadi kekhawatiran pengguna, dan perlu dijelaskan dengan kalimat yang sederhana di layar pendaftaran." },
  { type: "h2", text: "Mengapa passkey lebih aman" },
  { type: "p", text: "Tidak ada rahasia bersama yang tersimpan di server. Jika basis data aplikasi Anda bocor, penyerang hanya mendapat kunci publik yang tidak berguna untuk masuk. Tidak ada daftar kata sandi untuk dipecahkan dan dicoba di tempat lain. Akibat dari satu kebocoran menjadi jauh lebih terbatas." },
  { type: "p", text: "Passkey juga terikat pada alamat situs tempat ia dibuat. Perangkat hanya mau memakainya di alamat yang asli. Situs tiruan dengan alamat mirip tidak akan ditawari passkey tersebut, sehingga pengguna tidak bisa tertipu menyerahkannya. Inilah perbedaan terbesar dibanding kata sandi dan kode sekali pakai, yang keduanya bisa diketik di halaman palsu." },
  { type: "p", text: "Selain itu passkey tidak bisa ditebak, tidak bisa dipakai ulang di layanan lain, dan memerlukan perangkat pengguna beserta cara membuka kuncinya. Dengan kata lain, ia sudah menggabungkan dua faktor dalam satu langkah: sesuatu yang dimiliki dan sesuatu yang melekat pada atau diketahui pengguna." },
  { type: "callout", title: "Lebih aman dan lebih mudah sekaligus", text: "Kebanyakan langkah keamanan menambah gesekan. Passkey termasuk sedikit perbaikan yang mengurangi gesekan sambil menaikkan keamanan, sehingga alasan menolaknya lebih sedikit, baik dari pengguna maupun dari tim penjualan." },
  { type: "h2", text: "Di mana passkey disimpan" },
  { type: "p", text: "Ada dua bentuk umum. Yang pertama adalah passkey yang disinkronkan lewat pengelola kata sandi atau akun ekosistem perangkat, sehingga tersedia di ponsel, tablet, dan komputer milik pengguna yang sama. Bentuk ini paling nyaman bagi pelanggan umum, karena passkey tidak hilang ketika ponsel diganti." },
  { type: "p", text: "Yang kedua adalah passkey yang terikat pada satu perangkat, misalnya kunci keamanan fisik. Bentuk ini tidak bisa disalin dan cocok untuk akun yang berisiko tinggi, seperti administrator sistem dan bagian keuangan. Kekurangannya, kehilangan perangkat berarti kehilangan akses bila tidak ada cadangan." },
  { type: "p", text: "Pengguna juga bisa masuk di perangkat lain dengan memindai kode dari ponselnya, tanpa passkey ikut berpindah. Alur ini berguna untuk komputer bersama. Sebagai pemilik aplikasi, Anda tidak mengatur tempat penyimpanan passkey pelanggan, tetapi Anda dapat menetapkan kebijakan yang lebih ketat untuk akun karyawan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1563986768609-322da13575f3",
    alt: "Seseorang memegang ponsel di depan laptop yang membuka aplikasi serupa",
    caption: "Ponsel pengguna dapat menjadi kunci untuk masuk di perangkat lain tanpa mengetik rahasia apa pun.",
  },
  { type: "h2", text: "Batasan yang perlu diketahui" },
  { type: "p", text: "Passkey bukan sihir. Tidak semua pengguna memakai perangkat dan peramban yang mendukungnya, dan sebagian memakai ponsel lama. Sebagian lagi belum mengenal istilahnya dan ragu ketika ditawari. Karena itu passkey belum bisa menjadi satu-satunya cara masuk untuk aplikasi yang melayani masyarakat luas." },
  { type: "p", text: "Perangkat yang dipakai bersama juga menjadi tantangan. Di toko, satu tablet kasir bisa dipakai bergantian oleh beberapa karyawan. Passkey yang terikat pada kunci layar perangkat tidak membedakan siapa yang sedang memegangnya. Untuk keadaan ini diperlukan rancangan lain, seperti PIN per karyawan di atas sesi perangkat yang sudah terdaftar, atau kunci keamanan perorangan." },
  { type: "p", text: "Terakhir, passkey melindungi pintu masuk, bukan seluruh rumah. Sesi yang sudah terbuka masih bisa dicuri dari perangkat yang terinfeksi, dan karyawan yang berwenang masih bisa menyalahgunakan aksesnya. Pengaturan hak akses, pencatatan aktivitas, dan batas waktu sesi tetap diperlukan." },
  { type: "h2", text: "Pilihan lain selain passkey" },
  { type: "p", text: "Masuk tanpa kata sandi tidak hanya berarti passkey. Ada beberapa cara lain yang lebih sederhana dibangun dan sudah dikenal pengguna, masing-masing dengan kelebihan dan kelemahannya." },
  { type: "ul", items: [
    "Tautan ajaib lewat email: mudah dipakai, tetapi bergantung pada keamanan dan kecepatan kotak masuk",
    "Kode sekali pakai lewat SMS atau pesan instan: akrab bagi pengguna, tetapi bisa diketik di situs tiruan dan bergantung pada jaringan seluler",
    "Kode dari aplikasi autentikator: tidak bergantung pada sinyal, tetapi memerlukan pemasangan aplikasi tambahan",
    "Masuk dengan akun pihak ketiga: cepat, tetapi menjadikan Anda bergantung pada penyedia akun tersebut",
    "Kunci keamanan fisik: sangat kuat, tetapi memerlukan pembelian dan pembagian perangkat",
  ] },
  { type: "p", text: "Banyak aplikasi menggabungkan beberapa cara. Pelanggan umum boleh memilih antara passkey, kode sekali pakai, dan akun pihak ketiga. Karyawan dengan akses penting diwajibkan memakai cara yang tahan terhadap situs tiruan. Yang penting, cara terlemah yang Anda izinkan menentukan kekuatan sebenarnya dari sebuah akun." },
  { type: "h2", text: "Pemulihan akun: bagian yang paling sulit" },
  { type: "p", text: "Setiap sistem masuk pada akhirnya dinilai dari apa yang terjadi ketika pengguna kehilangan aksesnya. Ponsel hilang, rusak, atau diganti tanpa sinkronisasi. Jika jalur pemulihan terlalu sulit, pelanggan yang sah terkunci di luar. Jika terlalu mudah, penyerang memakai jalur pemulihan sebagai pintu belakang, dan seluruh keamanan passkey menjadi sia-sia." },
  { type: "p", text: "Dorong pengguna mendaftarkan lebih dari satu cara masuk sejak awal, misalnya passkey di dua perangkat atau passkey ditambah alamat email terverifikasi. Untuk akun bernilai tinggi, pemulihan sebaiknya melibatkan pemeriksaan tambahan dan jeda waktu, disertai pemberitahuan ke semua kontak terdaftar agar pemilik asli tahu bila ada upaya yang bukan darinya." },
  { type: "p", text: "Tim layanan pelanggan perlu prosedur tertulis untuk permintaan pemulihan. Penipu sering menelepon dengan cerita yang meyakinkan dan mendesak. Prosedur yang jelas, tidak bergantung pada perasaan petugas, dan tercatat setiap langkahnya melindungi pelanggan sekaligus melindungi petugas dari tekanan." },
  { type: "h2", text: "Menerapkan bertahap pada pelanggan" },
  { type: "p", text: "Jangan menghapus kata sandi dalam semalam. Peralihan yang berhasil biasanya dilakukan bertahap dan menempatkan passkey sebagai tawaran, bukan paksaan. Dengan begitu pengguna yang perangkatnya belum mendukung tetap bisa masuk, dan Anda bisa mengamati kendala sebelum melangkah lebih jauh." },
  { type: "ol", items: [
    "Tambahkan passkey sebagai pilihan di pengaturan akun dan uji dengan kelompok kecil",
    "Tawarkan pembuatan passkey tepat setelah pengguna berhasil masuk dengan cara lama",
    "Jadikan passkey pilihan pertama di layar masuk bagi yang sudah memilikinya",
    "Tawarkan passkey sebagai cara utama untuk pendaftar baru",
    "Tinjau data pemakaian dan kendala sebelum memutuskan nasib kata sandi",
  ] },
  { type: "p", text: "Perhatikan kata-kata di layar. Istilah passkey belum akrab bagi banyak orang. Kalimat seperti masuk dengan sidik jari atau wajah, tanpa kata sandi lebih mudah dipahami daripada istilah teknis. Jelaskan dalam satu atau dua kalimat bahwa data biometrik tetap berada di perangkat." },
  { type: "h2", text: "Menerapkan pada karyawan dan sistem internal" },
  { type: "p", text: "Sistem internal seperti ERP, panel admin toko, dan dasbor keuangan menyimpan data yang jauh lebih peka daripada akun pelanggan. Di sinilah cara masuk yang kuat paling layak diwajibkan. Mulailah dari peran berisiko tertinggi: administrator, keuangan, dan siapa pun yang dapat mengubah harga, mengembalikan dana, atau mengekspor data pelanggan." },
  { type: "p", text: "Jika perusahaan memakai banyak aplikasi, pertimbangkan masuk tunggal lewat satu penyedia identitas. Karyawan masuk sekali dengan cara yang kuat, lalu mendapat akses ke aplikasi sesuai perannya. Ketika karyawan keluar, akses ke semua aplikasi dicabut dari satu tempat. Pendekatan ini mengurangi akun yatim yang terlupa dan masih aktif." },
  { type: "p", text: "Siapkan pula proses untuk karyawan baru, karyawan yang berganti perangkat, dan perangkat yang hilang. Prosedur yang jelas mencegah jalan pintas berbahaya, seperti berbagi akun antarkaryawan ketika seseorang tidak bisa masuk." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1592744254966-58c65cfd2e69",
    alt: "Kunci kombinasi berwarna perak dan hitam",
    caption: "Cara masuk yang kuat paling layak diwajibkan pada akun yang memegang data dan uang perusahaan.",
  },
  { type: "h2", text: "Pertimbangan teknis untuk dibahas dengan pengembang" },
  { type: "p", text: "Passkey dibangun di atas standar terbuka yang didukung peramban dan sistem operasi utama, sehingga Anda tidak terikat pada satu vendor. Meski begitu, penerapannya menyangkut banyak rincian yang mudah keliru. Menggunakan pustaka atau layanan identitas yang sudah teruji biasanya lebih aman daripada menulis semuanya sendiri." },
  { type: "ul", items: [
    "Apakah website dan aplikasi mobile memakai akun dan passkey yang sama",
    "Bagaimana passkey didaftarkan, diberi nama, dan dihapus oleh pengguna di pengaturan akun",
    "Bagaimana sesi dikelola: masa berlaku, keluar dari semua perangkat, dan pemeriksaan ulang untuk tindakan peka",
    "Apa saja yang dicatat: pendaftaran, upaya masuk yang gagal, dan perubahan cara pemulihan",
    "Bagaimana perilaku pada peramban atau perangkat yang belum mendukung",
    "Bagaimana perubahan domain atau penggabungan aplikasi kelak memengaruhi passkey yang sudah ada",
  ] },
  { type: "p", text: "Butir terakhir patut digarisbawahi. Karena passkey terikat pada alamat situs, keputusan tentang domain sebaiknya matang sebelum passkey diluncurkan. Memindahkan aplikasi ke alamat lain di kemudian hari dapat membuat pengguna harus mendaftar ulang." },
  { type: "h2", text: "Mengukur keberhasilan" },
  { type: "p", text: "Ukur dampaknya pada keamanan dan pada kemudahan. Dari sisi kemudahan, perhatikan proporsi upaya masuk yang berhasil, waktu yang diperlukan untuk masuk, dan jumlah permintaan atur ulang kata sandi ke layanan pelanggan. Dari sisi keamanan, perhatikan jumlah akun yang diambil alih dan upaya masuk mencurigakan." },
  { type: "p", text: "Pantau pula berapa banyak pengguna yang mendaftarkan passkey dan berapa yang benar-benar memakainya. Bila banyak yang mendaftar tetapi tetap masuk dengan kata sandi, mungkin tata letak layar masuk belum menonjolkan pilihan itu. Angka pemakaian menunjukkan di mana rancangan perlu diperbaiki." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menghapus kata sandi sekaligus tanpa masa peralihan",
    "Membuat jalur pemulihan yang lebih lemah daripada cara masuknya",
    "Memakai istilah teknis di layar tanpa penjelasan sederhana",
    "Mewajibkan cara masuk kuat pada pelanggan tetapi tidak pada admin",
    "Membiarkan karyawan berbagi satu akun karena sulit masuk",
    "Menganggap passkey menggantikan pengaturan hak akses dan pencatatan aktivitas",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Minta data jumlah permintaan atur ulang kata sandi dan upaya masuk gagal dari tim Anda",
    "Daftar akun internal yang memiliki akses paling peka dan periksa cara masuknya",
    "Wajibkan verifikasi dua langkah pada akun admin yang belum memakainya",
    "Bahas dengan pengembang kesiapan aplikasi Anda untuk passkey dan pilihan pustakanya",
    "Tulis prosedur pemulihan akun untuk tim layanan pelanggan",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Masuk tanpa kata sandi adalah salah satu perkembangan teknologi yang manfaatnya langsung terasa oleh pengguna biasa. Passkey membuat masuk ke aplikasi sesederhana membuka kunci ponsel, sambil menutup celah yang selama ini paling sering dimanfaatkan penipu. Bagi bisnis, itu berarti lebih sedikit akun yang dibobol, lebih sedikit pelanggan yang menyerah di layar masuk, dan lebih ringan beban layanan pelanggan." },
  { type: "p", text: "Kuncinya adalah penerapan bertahap dan pemulihan akun yang dirancang serius. Mulailah dari akun internal yang paling peka, tawarkan kepada pelanggan sebagai pilihan, dan biarkan data pemakaian menuntun langkah berikutnya." },
  {
    type: "cta",
    title: "Ingin website atau aplikasi dengan cara masuk yang aman dan tidak merepotkan?",
    text: "Tim AG·SORA membangun website dan aplikasi mobile dengan passkey, verifikasi berlapis, hak akses per peran, dan alur pemulihan akun yang dirancang dengan hati-hati. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/custom-software",
    label: "Konsultasi gratis",
  },
];
