import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Hampir setiap website dan aplikasi bisnis mengumpulkan data pribadi, sering tanpa disadari pemiliknya. Formulir kontak menyimpan nama dan nomor telepon, toko online menyimpan alamat dan riwayat pesanan, aplikasi menyimpan identitas perangkat dan lokasi, dan alat analitik mencatat perilaku pengunjung. Semua itu adalah data pribadi, dan mengelolanya bukan lagi sekadar urusan teknis, melainkan tanggung jawab hukum dan kepercayaan." },
  { type: "p", text: "Di Indonesia, ketentuan tentang pelindungan data pribadi kini diatur dalam undang-undang tersendiri beserta aturan turunannya. Bagi pemilik bisnis, pertanyaan praktisnya bukan menghafal pasal, melainkan memahami prinsip-prinsipnya dan menerjemahkannya menjadi kebiasaan kerja: apa yang dikumpulkan, untuk apa, disimpan di mana, siapa yang boleh mengakses, dan apa yang dilakukan ketika terjadi masalah. Bisnis yang membangun kebiasaan ini lebih siap menghadapi aturan yang berkembang dan lebih dipercaya pelanggan." },
  { type: "p", text: "Artikel ini membahas langkah-langkah praktis untuk mengelola data pribadi pada website dan aplikasi. Kami membahas pemetaan data, dasar pengumpulan dan persetujuan, pemberitahuan privasi, hak pemilik data, pengamanan, pihak ketiga, masa simpan, penanganan kebocoran, dan kebiasaan tata kelola. Perhatikan bahwa artikel ini bersifat edukatif dan bukan nasihat hukum. Aturan dapat berubah dan penerapannya bergantung pada jenis bisnis Anda, sehingga rujuklah sumber resmi terkini dan konsultasikan kepada penasihat hukum untuk kasus Anda. Kami sengaja tidak mengutip angka atau tenggat tertentu yang mungkin sudah berubah." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Mulai dengan memetakan data pribadi apa yang Anda kumpulkan, dari mana, untuk apa, dan ke mana mengalirnya",
      "Kumpulkan hanya yang diperlukan dan pastikan ada dasar yang sah, termasuk persetujuan bila diperlukan",
      "Sampaikan pemberitahuan privasi yang jelas dan sediakan cara bagi pemilik data untuk menggunakan haknya",
      "Amankan data dengan kontrol teknis dan organisasi, dan atur pihak ketiga lewat perjanjian tertulis",
      "Siapkan rencana penanganan kebocoran dan tetapkan penanggung jawab pelindungan data di perusahaan",
    ],
  },
  { type: "h2", text: "Mengapa bisnis perlu peduli sekarang" },
  { type: "p", text: "Ada tiga alasan yang saling menguatkan. Pertama, kewajiban hukum. Pengendali data pribadi memiliki kewajiban tertentu, dan pelanggaran dapat berujung pada sanksi administratif maupun konsekuensi lain sesuai ketentuan. Kedua, kepercayaan pelanggan. Pelanggan semakin sadar bahwa data mereka berharga, dan bisnis yang ceroboh akan kehilangan kepercayaan dengan cepat, terutama bila terjadi kebocoran. Ketiga, ketahanan bisnis. Data yang berantakan, tersebar, dan tidak diketahui keberadaannya adalah risiko operasional: sulit diamankan, sulit dihapus, dan sulit dipertanggungjawabkan." },
  { type: "p", text: "Bisnis kecil sering mengira aturan ini hanya untuk perusahaan besar. Padahal prinsip dasarnya berlaku bagi siapa pun yang memproses data pribadi, dan ukuran bisnis biasanya hanya memengaruhi seberapa formal tata kelola yang diperlukan, bukan ada tidaknya tanggung jawab. Pendekatan yang bijak adalah menerapkan langkah yang proporsional dengan risiko dan skala Anda, lalu meningkatkannya seiring pertumbuhan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85",
    alt: "Tangan menandatangani dokumen di atas meja",
    caption: "Pelindungan data pribadi berawal dari kesadaran bahwa setiap data yang dikumpulkan membawa tanggung jawab.",
  },
  { type: "h2", text: "Langkah pertama: memetakan data yang Anda miliki" },
  { type: "p", text: "Anda tidak bisa melindungi apa yang tidak Anda ketahui. Langkah pertama adalah menyusun inventaris data pribadi: apa saja yang dikumpulkan, dari siapa, lewat mana, disimpan di mana, dipakai untuk apa, dibagikan kepada siapa, dan berapa lama disimpan. Lakukan untuk seluruh titik sentuh, termasuk yang sering terlupa seperti formulir lama, berkas ekspor, cadangan, dan alat pihak ketiga yang dipasang tim pemasaran." },
  { type: "ul", items: [
    "Data yang dikumpulkan lewat formulir, pendaftaran, pembelian, dan pesan layanan pelanggan",
    "Data teknis dari perangkat dan peramban: alamat jaringan, identitas perangkat, dan cookie",
    "Data lokasi, kontak, foto, atau mikrofon yang diminta aplikasi seluler",
    "Data dari analitik, iklan, dan alat pelacakan perilaku",
    "Data karyawan, pelamar kerja, dan mitra bisnis",
    "Salinan data di cadangan, berkas lokal, lembar kerja, dan kotak masuk surel",
  ] },
  { type: "p", text: "Untuk tiap kategori, catat juga sensitivitasnya. Data tertentu, seperti data kesehatan, biometrik, keuangan pribadi, atau data anak, umumnya memerlukan perlindungan lebih ketat menurut ketentuan. Tandai data semacam itu agar mendapat perlakuan khusus. Hasil pemetaan ini menjadi dasar untuk semua langkah berikutnya, dan layak diperbarui setiap kali Anda menambah fitur atau alat baru." },
  { type: "h2", text: "Kumpulkan seperlunya dan pastikan dasar yang sah" },
  { type: "p", text: "Prinsip yang paling berguna adalah minimalisasi: kumpulkan hanya data yang benar-benar diperlukan untuk tujuan yang jelas. Formulir yang meminta tanggal lahir, alamat lengkap, dan pekerjaan padahal hanya perlu surel untuk mengirim buletin adalah contoh pengumpulan berlebihan. Setiap kolom tambahan menambah risiko dan beban tanpa menambah nilai." },
  { type: "p", text: "Setiap pemrosesan data pribadi membutuhkan dasar yang sah menurut ketentuan. Persetujuan pemilik data adalah salah satunya, tetapi bukan satu-satunya. Ada dasar lain, seperti pelaksanaan perjanjian dengan pemilik data atau pemenuhan kewajiban hukum. Pahami dasar mana yang berlaku untuk tiap aktivitas Anda. Misalnya, memproses alamat untuk mengirim pesanan didasarkan pada perjanjian jual beli, sedangkan mengirim promosi biasanya memerlukan persetujuan tersendiri." },
  { type: "ul", items: [
    "Tentukan tujuan tiap jenis data sebelum mengumpulkannya dan jangan memakainya untuk tujuan lain tanpa dasar yang sesuai",
    "Hindari kolom wajib yang tidak diperlukan; jadikan opsional bila sekadar tambahan",
    "Bila memakai persetujuan, buat sukarela, spesifik, dan mudah dicabut",
    "Jangan menggabungkan persetujuan untuk banyak hal dalam satu kotak centang",
    "Jangan mengatur kotak persetujuan agar sudah terpilih sebelumnya",
    "Catat kapan, bagaimana, dan untuk apa persetujuan diberikan",
  ] },
  { type: "h2", text: "Pemberitahuan privasi yang bisa dipahami" },
  { type: "p", text: "Pemilik data berhak mengetahui bagaimana datanya diperlakukan. Pemberitahuan privasi, sering disebut kebijakan privasi, adalah cara memenuhinya. Banyak kebijakan privasi justru gagal karena ditulis seperti dokumen hukum yang panjang dan tidak terbaca, atau disalin dari situs lain tanpa disesuaikan dengan praktik sebenarnya. Kebijakan yang tidak sesuai kenyataan lebih berbahaya daripada tidak ada, karena menjadi bukti ketidakjujuran." },
  { type: "ul", items: [
    "Siapa Anda dan bagaimana menghubungi Anda terkait data pribadi",
    "Data apa yang dikumpulkan dan dari mana",
    "Untuk apa data digunakan dan atas dasar apa",
    "Kepada siapa data dibagikan, termasuk kategori penyedia layanan",
    "Berapa lama data disimpan atau kriteria untuk menentukannya",
    "Hak pemilik data dan cara menggunakannya",
    "Apakah data dikirim ke luar negeri dan perlindungan yang diterapkan",
  ] },
  { type: "p", text: "Gunakan bahasa sederhana, susun dengan judul yang jelas, dan tampilkan pada saat relevan, misalnya ringkasan singkat di dekat formulir dengan tautan ke versi lengkap. Perbarui setiap kali praktik berubah dan simpan versi lamanya. Bila Anda melayani pengguna dalam beberapa bahasa, sediakan pemberitahuan dalam bahasa yang sama dengan antarmukanya agar benar-benar dapat dipahami." },
  { type: "callout", title: "Kebijakan harus mencerminkan praktik", text: "Sebelum menerbitkan kebijakan privasi, periksa bersama tim teknis apa yang sebenarnya dilakukan sistem. Kebijakan yang indah tetapi tidak sesuai praktik menciptakan risiko, bukan perlindungan." },
  { type: "h2", text: "Cookie, pelacak, dan analitik" },
  { type: "p", text: "Banyak website memasang cookie dan pelacak untuk analitik, iklan, dan fungsi lain. Sebagian diperlukan agar situs berfungsi, sedangkan sebagian lain untuk analitik atau pemasaran yang umumnya memerlukan perhatian lebih terhadap persetujuan. Periksa seluruh pelacak yang aktif di situs Anda, termasuk yang dipasang lewat alat pihak ketiga, lalu kelompokkan menurut tujuannya." },
  { type: "ul", items: [
    "Daftar semua cookie dan pelacak aktif dan tentukan tujuannya masing-masing",
    "Pisahkan yang benar-benar diperlukan agar situs berfungsi dari yang bersifat analitik atau iklan",
    "Tampilkan pemberitahuan dan pilihan yang jelas, dengan menolak semudah menerima",
    "Jangan menjalankan pelacak yang memerlukan persetujuan sebelum persetujuan diberikan",
    "Sediakan cara mengubah pilihan kapan saja",
    "Tinjau berkala karena alat baru sering ditambahkan tanpa disadari",
  ] },
  { type: "p", text: "Pilihan teknis yang menghormati privasi, seperti analitik yang tidak memakai pengenal perorangan atau data teragregasi, sering tersedia dan cukup untuk banyak kebutuhan bisnis. Pertimbangkan pendekatan itu sebelum mengaktifkan pelacakan yang lebih invasif." },
  { type: "h2", text: "Hak pemilik data dan cara melayaninya" },
  { type: "p", text: "Ketentuan pelindungan data pribadi memberi pemilik data hak-hak tertentu atas datanya, seperti meminta informasi tentang pemrosesan, mengakses, memperbaiki, menghapus, atau membatasi pemrosesan, serta menarik persetujuan. Rincian dan batas waktu pemenuhannya diatur dalam ketentuan yang berlaku, sehingga perlu diperiksa dari sumber resmi terkini." },
  { type: "p", text: "Tantangan praktisnya: jika data tersebar di banyak sistem, memenuhi permintaan seperti hapus data saya menjadi sangat sulit. Inilah alasan pemetaan data penting. Sediakan saluran yang jelas untuk menerima permintaan, misalnya alamat surel khusus atau formulir, tetapkan siapa yang menanganinya, verifikasi identitas peminta agar data tidak diberikan kepada orang yang salah, dan catat tiap permintaan beserta penyelesaiannya." },
  { type: "ol", items: [
    "Terima permintaan lewat saluran yang disebutkan dalam pemberitahuan privasi",
    "Verifikasi identitas peminta dengan cara yang proporsional dan tidak berlebihan",
    "Cari data peminta di seluruh sistem yang tercatat dalam inventaris, termasuk cadangan dan pihak ketiga",
    "Penuhi, tolak sebagian, atau jelaskan batasannya sesuai ketentuan, dengan alasan tertulis",
    "Beri tahu peminta hasilnya dalam jangka waktu yang ditetapkan ketentuan",
    "Arsipkan catatan permintaan dan tindakannya sebagai bukti kepatuhan",
  ] },
  { type: "p", text: "Dari sisi pengembangan, rancang sistem agar kemampuan ini mudah dipenuhi: data pelanggan terpusat dan terhubung dengan identitas yang konsisten, ada fungsi untuk mengekspor dan menghapus atau menganonimkan data seseorang, dan data di cadangan memiliki masa simpan yang jelas. Membangunnya sejak awal jauh lebih murah daripada menambalnya saat permintaan pertama datang." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b",
    alt: "Layar laptop menampilkan baris-baris kode program di ruangan gelap",
    caption: "Privasi yang baik dirancang dalam kode: pengumpulan seperlunya, akses terbatas, dan kemampuan menghapus data.",
  },
  { type: "h2", text: "Mengamankan data pribadi" },
  { type: "p", text: "Pelindungan data pribadi tidak terpisah dari keamanan. Pengendali data wajib menjaga keamanan data yang diprosesnya dengan langkah teknis dan organisasi yang sesuai risiko. Ukuran kecukupannya bergantung pada sensitivitas data dan potensi dampak bila bocor, sehingga data yang lebih sensitif memerlukan pengamanan lebih kuat." },
  { type: "ul", items: [
    "Enkripsi data saat dikirim dan, untuk data sensitif, saat disimpan",
    "Pembatasan akses berdasarkan peran, dengan prinsip hak akses seminimal mungkin",
    "Autentikasi berlapis untuk akun administratif dan akses ke data pelanggan",
    "Pencatatan akses dan perubahan pada data sensitif agar dapat ditelusuri",
    "Pembaruan keamanan rutin untuk server, aplikasi, dan pustaka yang dipakai",
    "Cadangan terenkripsi yang diuji pemulihannya, dengan akses terbatas",
    "Pemisahan lingkungan pengujian dan produksi, serta tidak memakai data pelanggan nyata untuk uji coba tanpa perlindungan",
    "Pelatihan karyawan tentang penanganan data, surel penipuan, dan perangkat kerja",
  ] },
  { type: "p", text: "Aspek organisasi sama pentingnya dengan teknis. Banyak kebocoran terjadi bukan karena peretasan canggih, melainkan karena kelalaian: berkas berisi data pelanggan terkirim ke orang yang salah, laptop hilang tanpa enkripsi, atau mantan karyawan yang aksesnya tidak dicabut. Tetapkan aturan sederhana dan latih tim untuk mematuhinya, termasuk prosedur saat karyawan masuk, berpindah tugas, dan keluar." },
  { type: "h2", text: "Pihak ketiga dan penyedia layanan" },
  { type: "p", text: "Hampir tak ada bisnis yang mengelola data sepenuhnya sendiri. Penyedia hosting, layanan surel, alat analitik, sistem pembayaran, penyedia dukungan pelanggan, dan pengembang eksternal semuanya bisa menyentuh data pribadi. Ketika Anda menyerahkan data kepada mereka, tanggung jawab Anda tidak otomatis hilang, sehingga pemilihan dan pengaturan hubungan dengan mereka sangat penting." },
  { type: "ul", items: [
    "Daftar semua penyedia yang memproses data pribadi atas nama Anda",
    "Periksa praktik keamanan dan kebijakan privasi mereka sebelum memakai, dan minta bukti bila perlu",
    "Atur dalam perjanjian tertulis apa yang boleh mereka lakukan dengan data, kewajiban pengamanan, dan pemberitahuan bila terjadi kebocoran",
    "Pastikan data hanya dipakai sesuai instruksi Anda dan bukan untuk tujuan mereka sendiri",
    "Ketahui lokasi penyimpanan data dan periksa ketentuan bila data dikirim ke luar negeri",
    "Siapkan rencana pengembalian atau penghapusan data bila kerja sama berakhir",
    "Tinjau daftar penyedia secara berkala dan hentikan yang sudah tidak diperlukan",
  ] },
  { type: "p", text: "Hal yang sama berlaku bagi vendor pengembang perangkat lunak. Saat sistem dikembangkan atau dipelihara pihak luar, tentukan siapa yang boleh mengakses data nyata, bagaimana akses diberikan dan dicabut, dan apa yang dilakukan dengan salinan data setelah proyek selesai. Hal ini sebaiknya tertuang dalam kontrak, bukan hanya kesepahaman lisan." },
  { type: "h2", text: "Masa simpan dan penghapusan data" },
  { type: "p", text: "Data pribadi tidak boleh disimpan selamanya tanpa alasan. Setelah tujuan pemrosesan tercapai dan tidak ada kewajiban hukum atau kepentingan sah untuk menyimpannya, data seharusnya dihapus atau dianonimkan. Menumpuk data yang tidak lagi dipakai hanya memperbesar risiko dan dampak bila terjadi kebocoran." },
  { type: "ol", items: [
    "Tetapkan masa simpan untuk tiap kategori data berdasarkan tujuan dan kewajiban hukum yang berlaku, bukan sekadar kebiasaan",
    "Terapkan penghapusan atau anonimisasi otomatis bila memungkinkan",
    "Pastikan data di cadangan, log, dan salinan lain ikut tercakup dalam kebijakan",
    "Catat pengecualian dan alasannya, misalnya data yang harus disimpan untuk kewajiban perpajakan atau pembukuan",
    "Tinjau kebijakan secara berkala dan sesuaikan dengan perubahan aturan",
  ] },
  { type: "p", text: "Perhatikan perbedaan antara penghapusan dan penyembunyian. Data yang hanya ditandai sebagai terhapus tetapi tetap ada di basis data masih merupakan data pribadi yang disimpan. Rancang proses penghapusan yang sungguh-sungguh menghapus atau menganonimkan, dan uji bahwa hasilnya benar." },
  { type: "h2", text: "Bersiap menghadapi kebocoran data" },
  { type: "p", text: "Seberapa baik pun pengamanan, insiden tetap mungkin terjadi. Perbedaan antara insiden yang terkendali dan bencana sering terletak pada kesiapan. Ketentuan mengenai kewajiban pemberitahuan atas kegagalan pelindungan data pribadi, termasuk siapa yang harus diberi tahu dan dalam jangka waktu berapa, diatur dalam aturan yang berlaku, sehingga rencana Anda harus mengacu pada ketentuan terkini dan nasihat hukum." },
  { type: "ol", items: [
    "Tetapkan tim dan penanggung jawab penanganan insiden beserta cara menghubungi mereka di luar jam kerja",
    "Siapkan langkah awal: mengisolasi sistem terdampak, mengganti kredensial, dan menyimpan bukti",
    "Nilai cakupan: data apa, milik siapa, dan potensi dampaknya bagi pemilik data",
    "Tentukan siapa yang harus diberi tahu, termasuk pihak berwenang dan pemilik data, serta isi dan waktunya sesuai ketentuan",
    "Siapkan templat pemberitahuan yang jelas, jujur, dan menyertakan langkah yang dapat diambil pemilik data",
    "Setelah pulih, tinjau penyebab, perbaiki celah, dan dokumentasikan pelajaran",
  ] },
  { type: "p", text: "Latih rencana ini melalui simulasi singkat, misalnya tanyakan pada tim apa yang akan dilakukan jika esok pagi ditemukan basis data pelanggan bocor. Latihan semacam ini cepat menyingkap celah: tidak ada yang tahu siapa yang harus dihubungi, tidak ada cadangan yang bersih, atau tidak ada log yang cukup untuk menilai cakupan." },
  { type: "h2", text: "Tata kelola: menjadikannya kebiasaan, bukan proyek sekali jadi" },
  { type: "p", text: "Pelindungan data pribadi bukan proyek yang selesai, melainkan kebiasaan yang berlanjut. Tetapkan siapa yang bertanggung jawab di perusahaan, baik seorang pejabat atau petugas pelindungan data bila ketentuan mewajibkannya, maupun penanggung jawab internal pada bisnis yang lebih kecil. Periksa ketentuan terkini untuk mengetahui apakah jenis dan skala pemrosesan Anda mensyaratkan penunjukan petugas khusus." },
  { type: "ul", items: [
    "Perbarui inventaris data setiap kali ada fitur, alat, atau penyedia baru",
    "Lakukan penilaian dampak untuk pemrosesan berisiko tinggi sebelum memulainya, bila diwajibkan atau layak dilakukan",
    "Libatkan pertimbangan privasi sejak perancangan fitur, bukan setelah selesai dibangun",
    "Latih karyawan baru dan segarkan pelatihan secara berkala",
    "Dokumentasikan kebijakan, keputusan, dan bukti kepatuhan agar dapat ditunjukkan bila diminta",
    "Pantau perkembangan peraturan dan perbarui praktik sesuai perubahan",
  ] },
  { type: "p", text: "Dokumentasi memiliki dua fungsi: membantu tim bekerja konsisten dan menjadi bukti itikad baik ketika ada pemeriksaan atau keluhan. Tidak perlu tebal; catatan singkat yang akurat dan terawat lebih berguna daripada dokumen besar yang tidak pernah dibuka." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menyalin kebijakan privasi dari situs lain tanpa menyesuaikan dengan praktik nyata",
    "Mengumpulkan data jauh lebih banyak daripada yang dibutuhkan untuk tujuan yang jelas",
    "Memasang alat pelacak pihak ketiga tanpa memeriksa data apa yang mereka kirim",
    "Menggunakan data pelanggan nyata di lingkungan pengujian tanpa perlindungan",
    "Tidak memiliki cara menerima dan menjawab permintaan pemilik data",
    "Tidak memiliki rencana kebocoran sampai kebocoran benar-benar terjadi",
    "Menganggap pelindungan data sebagai urusan satu kali yang dapat diselesaikan dengan satu dokumen",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Susun inventaris sederhana: data pribadi apa yang dikumpulkan website, aplikasi, dan alat pihak ketiga Anda",
    "Periksa formulir dan hapus kolom yang tidak diperlukan",
    "Bandingkan kebijakan privasi dengan praktik nyata dan perbaiki ketidaksesuaiannya",
    "Daftar semua penyedia yang menyentuh data pribadi dan periksa perjanjian dengan mereka",
    "Tunjuk penanggung jawab pelindungan data dan jadwalkan simulasi penanganan kebocoran",
    "Konsultasikan dengan penasihat hukum dan rujuk sumber resmi terkini untuk kewajiban spesifik bisnis Anda",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Mengelola data pribadi dengan baik bukan hanya soal menghindari sanksi, melainkan bagian dari membangun bisnis yang dipercaya. Pemetaan data, pengumpulan seperlunya, dasar yang sah, pemberitahuan yang jujur, pengamanan yang layak, pengaturan pihak ketiga, masa simpan yang jelas, dan kesiapan menghadapi insiden membuat bisnis Anda lebih tangguh dan pelanggan lebih tenang." },
  { type: "p", text: "Mulailah dari langkah yang paling sederhana dan paling berdampak, lalu bangun kebiasaan tata kelola yang konsisten. Karena aturan terus berkembang, jadikan peninjauan berkala dan konsultasi dengan penasihat hukum sebagai bagian dari rutinitas Anda." },
  {
    type: "cta",
    title: "Ingin website atau aplikasi yang dirancang dengan memperhatikan privasi dan keamanan data?",
    text: "Tim AG·SORA membangun website dan aplikasi dengan pengumpulan data seperlunya, kontrol akses yang ketat, dan fitur yang memudahkan Anda memenuhi permintaan pemilik data. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/custom-software",
    label: "Konsultasi gratis",
  },
];
