import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Pengunjung yang mengetik sesuatu di kotak pencarian toko online sedang memberi tahu Anda dengan kata-katanya sendiri apa yang ingin ia beli. Tidak ada sinyal niat yang lebih jelas daripada itu. Namun di banyak toko, kotak pencarian justru menjadi bagian yang paling jarang diperhatikan: dipasang sekali saat toko dibangun, lalu dibiarkan bertahun-tahun tanpa pernah diperiksa hasilnya." },
  { type: "p", text: "Akibatnya mudah ditebak. Pembeli mengetik nama barang dengan ejaan yang sedikit berbeda dan mendapat halaman kosong. Pembeli lain memilih kategori lalu harus menggulir ratusan produk karena tidak ada filter ukuran atau harga. Mereka tidak mengeluh; mereka menutup tab dan mencari di tempat lain. Toko kehilangan penjualan dari orang yang sebenarnya sudah siap membeli, padahal barangnya tersedia di gudang." },
  { type: "p", text: "Artikel ini membahas cara merancang pencarian dan filter produk yang membantu pembeli menemukan barang dengan cepat, baik di website maupun di aplikasi mobile. Kami membahas data yang menjadi dasarnya, toleransi salah ketik, sinonim, saran otomatis, filter, pengurutan, halaman tanpa hasil, dan cara membaca data pencarian. Kami tidak memakai angka rekaan; yang kami tawarkan adalah prinsip dan langkah yang bisa diperiksa sendiri di toko Anda." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Pencarian yang baik bergantung pada data produk yang rapi: nama, atribut, kategori, dan stok",
      "Tangani salah ketik, sinonim, dan istilah sehari-hari agar pembeli tidak menemui halaman kosong",
      "Sediakan filter yang sesuai dengan cara orang memilih barang di kategori tersebut",
      "Rancang halaman tanpa hasil sebagai jalan keluar, bukan jalan buntu",
      "Baca kata kunci yang diketik pembeli secara rutin dan jadikan dasar perbaikan katalog",
    ],
  },
  { type: "h2", text: "Mengapa pencarian layak mendapat perhatian khusus" },
  { type: "p", text: "Pengunjung toko online umumnya terbagi dua. Sebagian datang untuk melihat-lihat dan menelusuri kategori. Sebagian lagi sudah tahu apa yang dicari dan langsung menuju kotak pencarian. Kelompok kedua ini biasanya paling dekat dengan keputusan membeli, karena mereka datang dengan kebutuhan yang sudah jelas dan hanya ingin memastikan barangnya ada, cocok, dan harganya masuk akal." },
  { type: "p", text: "Semakin besar katalog, semakin penting pencarian. Toko dengan tiga puluh produk bisa mengandalkan menu dan halaman kategori. Toko dengan tiga ribu produk tidak bisa. Tanpa pencarian dan filter yang layak, menambah produk justru membuat toko terasa lebih sulit dipakai, karena setiap barang baru memperpanjang daftar yang harus digulir pembeli." },
  { type: "p", text: "Pencarian juga merupakan sumber riset pasar yang gratis. Setiap kata yang diketik adalah permintaan nyata, termasuk untuk barang yang belum Anda jual. Toko yang mencatat dan membaca data ini tahu produk apa yang dicari tetapi tidak tersedia, istilah apa yang dipakai pelanggan, dan kategori mana yang paling membingungkan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1586880244406-556ebe35f282",
    alt: "Laptop menampilkan halaman beranda platform toko online",
    caption: "Kotak pencarian sering menjadi tempat pertama yang dituju pembeli yang sudah tahu apa yang dicari.",
  },
  { type: "h2", text: "Pencarian yang baik dimulai dari data produk" },
  { type: "p", text: "Mesin pencari hanya bisa menemukan apa yang tertulis. Jika nama produk Anda hanya berisi kode internal, atau warna dan ukuran tersimpan di dalam foto dan bukan di kolom data, tidak ada teknologi yang bisa menolong. Karena itu pekerjaan memperbaiki pencarian hampir selalu dimulai dari merapikan katalog, bukan dari mengganti mesin pencarinya." },
  { type: "p", text: "Pastikan setiap produk memiliki nama yang deskriptif, kategori yang benar, dan atribut yang terisi dalam kolom terpisah: merek, ukuran, warna, bahan, kapasitas, kompatibilitas, atau apa pun yang relevan untuk jenis barang tersebut. Atribut inilah yang nantinya menjadi filter. Atribut yang ditulis bebas, misalnya biru tua di satu produk dan navy di produk lain, menghasilkan filter yang berantakan." },
  { type: "p", text: "Tentukan pula kolom mana yang ikut dicari dan seberapa besar bobotnya. Kecocokan pada nama produk biasanya lebih penting daripada kecocokan pada deskripsi panjang. Kode barang dan nomor model perlu bisa dicari secara persis, karena pembeli bisnis dan teknisi sering mencari dengan nomor tersebut. Keputusan sederhana ini sangat memengaruhi urutan hasil yang muncul." },
  { type: "h2", text: "Toleransi salah ketik dan variasi penulisan" },
  { type: "p", text: "Orang mengetik dengan cepat, di layar ponsel yang kecil, sering sambil melakukan hal lain. Salah ketik satu huruf, spasi yang hilang, atau tanda hubung yang berbeda adalah hal biasa. Pencarian yang menuntut ejaan sempurna akan menolak sebagian pembeli tanpa alasan yang mereka pahami. Mereka hanya melihat tulisan produk tidak ditemukan dan menyimpulkan toko Anda tidak menjualnya." },
  { type: "p", text: "Sebagian besar mesin pencari modern menyediakan pencocokan yang toleran terhadap selisih beberapa huruf. Aktifkan fitur itu, tetapi atur dengan hati-hati. Toleransi yang terlalu longgar pada kata pendek menghasilkan hasil yang tidak nyambung, sedangkan pada kode barang toleransi justru berbahaya karena dua kode yang mirip bisa merujuk barang yang sama sekali berbeda." },
  { type: "p", text: "Perhatikan pula variasi penulisan yang umum: kata yang disambung atau dipisah, angka yang ditulis dengan huruf, satuan yang disingkat, serta campuran bahasa Indonesia dan Inggris. Pembeli bisa menulis kaos atau kaus, charger atau pengisi daya, 1 liter atau 1000 ml. Semua bentuk itu sebaiknya mengarah ke hasil yang sama." },
  { type: "h2", text: "Sinonim dan bahasa pelanggan" },
  { type: "p", text: "Bahasa yang dipakai tim Anda untuk menamai produk sering berbeda dari bahasa pelanggan. Tim memakai istilah pemasok atau istilah teknis, sementara pelanggan memakai istilah sehari-hari, nama merek yang sudah menjadi sebutan umum, atau bahkan istilah daerah. Kamus sinonim menjembatani keduanya, sehingga pencarian dengan istilah pelanggan tetap menemukan produk dengan nama resmi." },
  { type: "p", text: "Kamus ini tidak perlu disusun dengan menebak. Sumber terbaiknya adalah daftar kata kunci yang tidak menghasilkan apa pun. Tinjau daftar itu secara berkala, lalu putuskan satu per satu: apakah kata tersebut sinonim dari produk yang sudah ada, salah ketik yang perlu ditangani, atau permintaan untuk barang yang memang belum dijual." },
  { type: "callout", title: "Katalog mengikuti pelanggan, bukan sebaliknya", text: "Bila banyak pembeli mencari dengan suatu istilah, pertimbangkan untuk memasukkan istilah itu ke nama atau deskripsi produk. Selain membantu pencarian di dalam toko, langkah ini juga membantu produk Anda ditemukan lewat mesin pencari umum." },
  { type: "h2", text: "Saran otomatis saat mengetik" },
  { type: "p", text: "Saran yang muncul ketika pembeli baru mengetik beberapa huruf mempercepat pencarian dan mengurangi salah ketik. Pembeli tinggal memilih saran yang cocok tanpa menyelesaikan ketikannya. Di ponsel, tempat mengetik terasa paling merepotkan, fitur ini sangat terasa manfaatnya." },
  { type: "p", text: "Saran yang baik menampilkan campuran yang bermanfaat: kata kunci populer, kategori yang relevan, dan beberapa produk langsung lengkap dengan gambar kecil serta harga. Batasi jumlahnya agar tidak menutupi layar. Pastikan saran hanya mengarah ke hasil yang benar-benar ada; saran yang berujung halaman kosong lebih mengecewakan daripada tidak ada saran sama sekali." },
  { type: "p", text: "Perhatikan kecepatan. Saran yang baru muncul satu detik setelah pembeli selesai mengetik tidak berguna. Fitur ini menuntut respons yang hampir seketika, sehingga perlu dirancang dengan indeks pencarian yang ringan, bukan dengan menanyai basis data utama pada setiap ketukan tombol." },
  { type: "h2", text: "Filter yang sesuai dengan cara orang memilih" },
  { type: "p", text: "Filter membantu pembeli mempersempit ratusan produk menjadi belasan yang relevan. Kuncinya adalah menyediakan filter yang sesuai dengan cara orang memilih barang di kategori itu. Untuk pakaian, orang memilih berdasarkan ukuran, warna, dan model. Untuk elektronik, berdasarkan merek, kapasitas, dan fitur. Untuk suku cadang, berdasarkan kecocokan dengan tipe mesin. Satu set filter yang sama untuk semua kategori hampir pasti keliru." },
  { type: "ul", items: [
    "Tampilkan filter yang paling sering dipakai di urutan teratas, misalnya harga, ukuran, dan merek",
    "Tunjukkan jumlah produk pada setiap pilihan agar pembeli tahu apa yang akan didapat",
    "Sembunyikan atau redupkan pilihan yang hasilnya nol supaya pembeli tidak terjebak",
    "Izinkan memilih beberapa nilai sekaligus dalam satu filter, misalnya dua warna",
    "Tampilkan filter yang sedang aktif dengan jelas dan sediakan cara mudah untuk menghapusnya",
    "Sediakan pilihan hanya yang tersedia agar barang habis tidak memenuhi hasil",
  ] },
  { type: "p", text: "Di layar ponsel, filter memerlukan rancangan tersendiri. Panel samping yang nyaman di layar lebar tidak muat di layar kecil. Pola yang umum dipakai adalah tombol filter yang membuka panel penuh, dengan tombol terapkan yang selalu terlihat dan menunjukkan jumlah hasil. Pembeli harus dapat mengubah filter tanpa kehilangan posisi dan tanpa menunggu halaman dimuat ulang seluruhnya." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1563013544-824ae1b704d3",
    alt: "Seseorang memegang kartu pembayaran sambil berbelanja di laptop",
    caption: "Semakin cepat pembeli menemukan barang yang cocok, semakin dekat ia dengan langkah pembayaran.",
  },
  { type: "h2", text: "Urutan hasil: relevansi dan kepentingan bisnis" },
  { type: "p", text: "Menemukan produk yang cocok baru setengah pekerjaan; urutan penampilannya sama pentingnya. Kebanyakan pembeli hanya melihat beberapa hasil pertama. Urutan bawaan sebaiknya mengutamakan relevansi dengan kata yang diketik, lalu dipertajam dengan sinyal lain seperti ketersediaan stok, popularitas, dan penilaian pembeli." },
  { type: "p", text: "Barang yang stoknya habis sebaiknya turun ke bagian bawah, bukan memenuhi baris pertama. Anda juga boleh memberi sedikit dorongan pada produk tertentu, misalnya barang baru atau barang dengan margin lebih baik, tetapi lakukan secukupnya. Jika dorongan bisnis mengalahkan relevansi, pembeli merasa hasil pencarian tidak nyambung dan berhenti mempercayainya." },
  { type: "p", text: "Selain urutan bawaan, sediakan pilihan pengurutan yang jelas: harga terendah, harga tertinggi, terbaru, dan terlaris. Ingat pilihan pembeli selama ia masih menelusuri kategori yang sama. Hal kecil seperti ini membuat toko terasa menghargai waktu pembeli." },
  { type: "h2", text: "Halaman tanpa hasil bukan jalan buntu" },
  { type: "p", text: "Seberapa pun baiknya pencarian, akan selalu ada kata kunci yang tidak menghasilkan apa pun. Yang membedakan toko yang baik adalah apa yang terjadi setelahnya. Halaman kosong dengan satu kalimat produk tidak ditemukan mengusir pembeli. Halaman yang menawarkan jalan lain memberi kesempatan kedua." },
  { type: "ul", items: [
    "Tawarkan ejaan alternatif atau kata kunci yang mirip bila ada",
    "Tampilkan kategori yang paling dekat dengan kata yang dicari",
    "Tampilkan produk terlaris atau produk yang baru dilihat sebagai titik lanjut",
    "Sediakan jalur cepat untuk bertanya, misalnya tombol obrolan atau WhatsApp",
    "Untuk barang yang belum dijual, tawarkan pemberitahuan bila kelak tersedia",
  ] },
  { type: "p", text: "Catat setiap pencarian tanpa hasil. Daftar ini adalah salah satu laporan paling berharga di toko online, karena langsung menunjukkan kebutuhan yang belum terpenuhi. Sebagian bisa diselesaikan dengan sinonim, sebagian dengan memperbaiki nama produk, dan sebagian lagi menjadi bahan pertimbangan untuk menambah jenis barang." },
  { type: "h2", text: "Pencarian di aplikasi mobile" },
  { type: "p", text: "Di aplikasi mobile, pencarian biasanya menjadi cara utama menjelajah karena ruang untuk menu sangat terbatas. Tempatkan kotak pencarian di posisi yang mudah dijangkau ibu jari dan selalu terlihat di halaman utama. Simpan riwayat pencarian terakhir di perangkat agar pembeli bisa mengulanginya dengan satu ketukan." },
  { type: "p", text: "Manfaatkan kemampuan perangkat bila sesuai dengan jenis barang Anda. Pemindaian kode batang membantu pembeli yang ingin memesan ulang barang yang sudah ada di tangan. Pencarian dengan suara membantu pengguna yang sedang tidak leluasa mengetik. Pencarian dengan foto bisa berguna untuk produk yang sulit dijelaskan dengan kata, walau memerlukan pengujian serius sebelum diandalkan." },
  { type: "p", text: "Perhatikan juga kondisi jaringan. Pengguna ponsel sering berada di sinyal yang lemah. Tampilkan hasil secara bertahap, simpan hasil terakhir agar tombol kembali terasa instan, dan beri tanda yang jelas ketika pencarian sedang berjalan. Layar yang diam tanpa keterangan membuat pengguna mengira aplikasi macet." },
  { type: "h2", text: "Pencarian cerdas dan rekomendasi: apa yang realistis" },
  { type: "p", text: "Perkembangan teknologi beberapa tahun terakhir membuat pencarian yang memahami makna, bukan sekadar mencocokkan kata, semakin terjangkau. Dengan pendekatan ini, pencarian seperti hadiah untuk ayah yang suka memancing bisa mengarah ke produk yang relevan walau tidak ada kata yang sama persis di nama produk." },
  { type: "p", text: "Kemampuan ini menarik, tetapi bukan pengganti dasar yang rapi. Pencarian berbasis makna tetap bergantung pada deskripsi dan atribut yang lengkap. Ia juga bisa keliru dengan cara yang sulit ditebak, misalnya menampilkan barang yang mirip secara tema tetapi salah ukuran atau tidak kompatibel. Untuk pencarian kode barang dan nama spesifik, pencocokan kata biasa sering tetap lebih tepat." },
  { type: "p", text: "Pendekatan yang masuk akal adalah menggabungkan keduanya dan mengujinya dengan kata kunci nyata dari toko Anda sebelum dipakai luas. Mulailah dari kasus yang paling terasa manfaatnya, seperti menyelamatkan pencarian yang sebelumnya tanpa hasil, lalu perluas bila terbukti membantu. Hal yang sama berlaku untuk rekomendasi produk serupa di halaman hasil." },
  { type: "h2", text: "Kecepatan dan pilihan teknis" },
  { type: "p", text: "Pencarian yang lambat terasa seperti toko yang pelayannya lama menjawab. Untuk katalog kecil, fitur pencarian bawaan platform atau basis data sering sudah cukup. Ketika katalog membesar dan kebutuhan seperti toleransi salah ketik, sinonim, dan filter berjumlah banyak mulai muncul, mesin pencari khusus yang menyimpan indeks tersendiri menjadi pilihan yang lebih sehat." },
  { type: "p", text: "Ada dua jalur umum: memakai layanan pencarian yang dikelola pihak lain dengan biaya berlangganan, atau menjalankan mesin pencari sendiri di server Anda. Layanan terkelola lebih cepat dipasang dan tidak membebani tim, tetapi biayanya tumbuh seiring jumlah produk dan pencarian. Menjalankan sendiri memberi kendali penuh, tetapi menuntut orang yang merawatnya." },
  { type: "p", text: "Apa pun pilihannya, pastikan indeks pencarian selalu selaras dengan data toko. Perubahan harga, stok, dan produk baru harus sampai ke indeks dalam waktu singkat. Hasil pencarian yang menampilkan harga lama atau barang yang sudah habis menimbulkan kekecewaan tepat di saat pembeli siap membeli." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43",
    alt: "Layar menampilkan grafik klik dan tayangan dengan garis biru berfluktuasi",
    caption: "Data pencarian menunjukkan apa yang dicari pembeli dan seberapa sering mereka menemukannya.",
  },
  { type: "h2", text: "Mengukur dan memperbaiki secara rutin" },
  { type: "p", text: "Pencarian bukan fitur yang selesai sekali pasang. Katalog berubah, musim berganti, dan istilah yang dipakai pelanggan ikut bergeser. Tetapkan beberapa ukuran sederhana dan tinjau secara berkala: kata kunci yang paling sering diketik, proporsi pencarian tanpa hasil, proporsi pencarian yang diikuti klik pada produk, dan proporsi yang berakhir dengan pembelian." },
  { type: "ol", items: [
    "Ambil daftar kata kunci terbanyak dan coba sendiri satu per satu di ponsel",
    "Periksa apakah hasil teratas memang barang yang paling masuk akal untuk kata itu",
    "Tinjau daftar pencarian tanpa hasil dan kelompokkan menurut sebabnya",
    "Tambahkan sinonim, perbaiki nama produk, atau catat sebagai peluang barang baru",
    "Ulangi setelah perubahan untuk memastikan perbaikannya benar-benar terasa",
  ] },
  { type: "p", text: "Kebiasaan ini tidak memerlukan alat mahal. Yang diperlukan adalah seseorang yang ditunjuk sebagai pemilik pencarian dan jadwal tinjauan yang tetap, misalnya sebulan sekali. Toko yang melakukannya dengan disiplin hampir selalu menemukan perbaikan mudah yang selama ini tidak terlihat." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menyembunyikan kotak pencarian di balik ikon kecil yang sulit ditemukan",
    "Menuntut ejaan persis sehingga salah ketik kecil berujung halaman kosong",
    "Menyediakan filter yang sama untuk semua kategori tanpa melihat jenis barangnya",
    "Menampilkan barang habis di urutan teratas hasil pencarian",
    "Membiarkan indeks pencarian tertinggal dari perubahan harga dan stok",
    "Tidak pernah mencatat dan membaca kata kunci yang diketik pembeli",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Coba sepuluh kata kunci yang biasa dipakai pelanggan Anda, termasuk versi salah ketiknya, dan catat hasilnya",
    "Aktifkan pencatatan kata kunci pencarian dan pencarian tanpa hasil bila belum ada",
    "Rapikan atribut pada satu kategori terpenting agar bisa dijadikan filter yang bersih",
    "Susun daftar sinonim awal dari istilah yang sering dipakai pelanggan di obrolan dan ulasan",
    "Perbaiki halaman tanpa hasil dengan saran kategori, produk terlaris, dan tombol bertanya",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Pencarian dan filter adalah pelayan toko Anda di dunia digital. Ketika keduanya bekerja baik, pembeli merasa dipahami: ia mengetik dengan bahasanya sendiri, mendapat jawaban yang nyambung, dan menemukan barang yang cocok dalam beberapa ketukan. Ketika keduanya buruk, katalog selengkap apa pun terasa kosong." },
  { type: "p", text: "Mulailah dari data produk yang rapi, tangani salah ketik dan sinonim, sediakan filter yang sesuai kategori, dan baca data pencarian secara rutin. Perbaikan kecil yang dilakukan terus-menerus di bagian ini termasuk investasi yang paling langsung terasa pada penjualan toko online." },
  {
    type: "cta",
    title: "Ingin toko online dengan pencarian dan filter yang benar-benar membantu pembeli?",
    text: "Tim AG·SORA membangun toko online dan aplikasi belanja dengan katalog terstruktur, pencarian yang toleran salah ketik, filter per kategori, dan laporan kata kunci. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
