import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Setiap toko online yang mulai ramai cepat atau lambat bertemu dengan penipuan. Bentuknya beragam: pembeli yang memakai kartu curian, pesanan palsu untuk menguji kartu, pengembalian dana yang disalahgunakan, akun yang diambil alih, hingga pesan yang menyamar sebagai toko Anda untuk meminta pelanggan mentransfer uang. Sebagian besar tidak terlihat sampai kerugiannya muncul di laporan." },
  { type: "p", text: "Banyak pemilik toko menganggap keamanan pembayaran sepenuhnya urusan penyedia pembayaran. Sebagian memang benar: data kartu yang sensitif sebaiknya tidak pernah menyentuh server Anda. Namun keputusan menerima atau menolak sebuah pesanan, cara menangani sengketa, dan pengamanan akun pelanggan tetap berada di tangan Anda." },
  { type: "p", text: "Artikel ini membahas jenis penipuan yang lazim di toko online, sinyal yang patut diwaspadai, lapisan pertahanan yang masuk akal untuk bisnis kecil dan menengah, serta cara menangani sengketa pembayaran. Kami tidak menyebut angka kerugian rekaan; fokusnya adalah cara berpikir dan kebiasaan kerja yang bisa diterapkan." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Jangan menyimpan data kartu sendiri; gunakan penyedia pembayaran yang menangani data sensitif",
      "Kenali pola pesanan mencurigakan dan tetapkan aturan tinjauan yang jelas",
      "Amankan akun pelanggan dan akun staf dengan autentikasi berlapis",
      "Siapkan bukti yang rapi agar sengketa pembayaran bisa dijawab dengan cepat",
      "Seimbangkan keamanan dan kenyamanan: pemeriksaan yang berlebihan juga membuat pembeli jujur pergi",
    ],
  },
  { type: "h2", text: "Jenis penipuan yang paling sering dihadapi toko online" },
  { type: "p", text: "Yang paling dikenal adalah penggunaan kartu atau akun pembayaran curian. Pelaku memesan barang yang mudah dijual kembali, lalu pemilik kartu yang sebenarnya mengajukan sengketa. Toko kehilangan barang, ongkos kirim, dan sering kali dikenai biaya sengketa, padahal pembayarannya sempat tampak berhasil." },
  { type: "p", text: "Jenis lain adalah pengujian kartu. Pelaku memakai toko Anda untuk mencoba ratusan nomor kartu dengan nilai transaksi kecil guna mencari yang masih aktif. Kerugiannya bukan barang, melainkan biaya pemrosesan, reputasi di mata penyedia pembayaran, dan potensi pemblokiran akun penjual." },
  { type: "p", text: "Ada pula penipuan yang berasal dari pembeli sungguhan: mengaku barang tidak sampai padahal diterima, mengembalikan barang yang berbeda dari yang dikirim, atau menyalahgunakan kebijakan retur. Dan di sisi sebaliknya, ada penipuan yang menyasar pelanggan Anda, seperti halaman palsu yang meniru toko atau pesan yang meminta transfer ke rekening lain." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1563013544-824ae1b704d3",
    alt: "Seseorang memegang kartu pembayaran sambil berbelanja di laptop",
    caption: "Pembayaran online yang tampak berhasil belum tentu final; sengketa dapat muncul beberapa minggu kemudian.",
  },
  { type: "h2", text: "Lapisan pertama: jangan memegang data kartu" },
  { type: "p", text: "Cara paling efektif mengurangi risiko adalah tidak menyimpan data kartu sama sekali. Gunakan penyedia pembayaran yang menampilkan formulir pembayaran mereka sendiri atau menyematkannya dengan aman, sehingga nomor kartu langsung dikirim ke penyedia tanpa melewati server Anda. Dengan begitu, beban pengamanan data sensitif terutama berada pada pihak yang memang berkompetensi." },
  { type: "p", text: "Pelajari persyaratan keamanan data kartu yang berlaku bagi pedagang dan bagaimana penyedia Anda membantu memenuhinya. Rincian aturan bisa berubah, sehingga rujuk selalu dokumen terbaru dari penyedia pembayaran Anda, bukan ingatan atau artikel lama." },
  { type: "p", text: "Selain itu, pastikan seluruh halaman toko dilayani lewat koneksi terenkripsi, pustaka dan plugin selalu diperbarui, dan skrip pihak ketiga di halaman checkout dibatasi seminimal mungkin. Skrip yang disusupi di halaman pembayaran adalah salah satu cara data pelanggan dicuri tanpa membobol server." },
  { type: "h2", text: "Sinyal pesanan yang patut diperiksa" },
  { type: "p", text: "Tidak ada satu sinyal yang pasti menunjukkan penipuan; yang bermanfaat adalah kombinasinya. Perhatikan ketidakcocokan antara alamat penagihan dan pengiriman, pesanan bernilai besar dari akun yang baru dibuat, banyak pesanan dari perangkat atau alamat jaringan yang sama dengan identitas berbeda, serta permintaan pengiriman kilat untuk barang bernilai tinggi." },
  { type: "ul", items: [
    "Akun baru langsung memesan barang bernilai tinggi dalam jumlah besar",
    "Banyak percobaan pembayaran gagal beruntun sebelum akhirnya berhasil",
    "Alamat surel yang tampak acak atau memakai layanan sementara",
    "Alamat pengiriman ke penerus barang atau lokasi yang sama untuk banyak pesanan berbeda",
    "Permintaan mengubah alamat pengiriman setelah pembayaran diterima",
    "Pesanan yang masuk dalam rentetan cepat dengan nilai kecil dan sama",
  ] },
  { type: "p", text: "Sinyal-sinyal ini sebaiknya memicu tinjauan manual, bukan penolakan otomatis. Banyak pembeli jujur kebetulan memenuhi satu atau dua sinyal, misalnya orang yang mengirim hadiah ke alamat lain. Telepon atau pesan singkat untuk memastikan pesanan sering kali cukup menyaring yang mencurigakan." },
  { type: "h2", text: "Aturan tinjauan yang sederhana tetapi konsisten" },
  { type: "p", text: "Bisnis kecil tidak perlu sistem deteksi yang rumit untuk memulai. Cukup tulis beberapa aturan: pesanan di atas nilai tertentu dari akun baru ditahan untuk diperiksa, pesanan dengan alamat berbeda dan barang bernilai tinggi dikonfirmasi, dan pesanan yang melewati ambang percobaan pembayaran gagal ditandai. Aturan tertulis membuat keputusan konsisten dan mudah dilatihkan kepada staf." },
  { type: "p", text: "Pantau dampak aturan Anda. Catat berapa pesanan yang ditahan, berapa yang ternyata sah, dan berapa yang terbukti bermasalah. Bila banyak pesanan sah tertahan, aturan terlalu ketat dan merugikan penjualan. Bila banyak penipuan lolos, aturan terlalu longgar. Sesuaikan secara berkala berdasarkan catatan, bukan perasaan." },
  { type: "p", text: "Banyak penyedia pembayaran dan platform toko menyediakan skor risiko dan alat pemeriksaan tambahan. Manfaatkan, tetapi pahami cara kerjanya dan tetap tinjau hasilnya. Alat otomatis adalah penyaring awal yang membantu, bukan pengganti penilaian manusia untuk kasus yang batas." },
  { type: "callout", title: "Keamanan yang membuat pembeli jujur pergi bukan keamanan yang baik", text: "Setiap langkah verifikasi tambahan adalah gesekan bagi pembeli yang sah. Terapkan pemeriksaan yang lebih ketat hanya pada pesanan berisiko, dan biarkan sebagian besar pembeli menyelesaikan checkout dengan mulus." },
  { type: "h2", text: "Mengamankan akun pelanggan dan akun staf" },
  { type: "p", text: "Pengambilalihan akun terjadi ketika pelaku masuk memakai kata sandi yang bocor dari layanan lain. Mereka kemudian memakai metode pembayaran tersimpan atau poin loyalitas pelanggan. Dorong pelanggan memakai kata sandi unik, sediakan verifikasi dua langkah atau passkey, dan batasi percobaan masuk yang gagal." },
  { type: "p", text: "Akun staf perlu perlindungan yang lebih kuat lagi, karena akses ke panel admin berarti akses ke data seluruh pelanggan, pengubahan harga, dan pengembalian dana. Wajibkan verifikasi dua langkah, berikan hak akses sesuai kebutuhan, dan cabut akses segera ketika staf berhenti atau berpindah tugas." },
  { type: "p", text: "Aktifkan pemberitahuan untuk kejadian sensitif: login dari perangkat baru, perubahan alamat surel, perubahan metode pembayaran, dan pengembalian dana bernilai besar. Pemberitahuan memberi pelanggan dan tim kesempatan menghentikan penyalahgunaan sebelum merugikan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7",
    alt: "Gembok merah di atas keyboard komputer hitam",
    caption: "Akun staf dengan akses luas perlu perlindungan paling kuat.",
  },
  { type: "h2", text: "Mencegah penyalahgunaan pengembalian dana dan retur" },
  { type: "p", text: "Kebijakan retur yang ramah pelanggan adalah keunggulan, tetapi juga celah. Beberapa pelaku memanfaatkan retur untuk mengembalikan barang palsu, barang bekas, atau kotak kosong. Periksa barang yang dikembalikan sebelum dana dikembalikan, dan catat kondisinya dengan foto." },
  { type: "p", text: "Pola berulang perlu diperhatikan: akun yang sering meretur, pembeli yang selalu mengaku barang tidak sampai, atau pengembalian dana yang mengarah ke rekening berbeda dari pembayaran awal. Kembalikan dana ke metode pembayaran asal sebagai aturan dasar, dan batasi pengecualian pada persetujuan yang tercatat." },
  { type: "p", text: "Pisahkan wewenang. Orang yang menerima retur sebaiknya bukan satu-satunya yang menyetujui pengembalian dana bernilai besar. Pemisahan ini sama prinsipnya dengan pemisahan tugas dalam pembelian dan melindungi Anda dari kesalahan maupun penyalahgunaan di dalam." },
  { type: "h2", text: "Menghadapi sengketa pembayaran" },
  { type: "p", text: "Ketika pemilik kartu mengajukan sengketa, penyedia pembayaran biasanya memberi Anda waktu terbatas untuk menyerahkan bukti. Siapkan bukti sejak awal: rincian pesanan, alamat pengiriman, nomor resi dan bukti penerimaan, korespondensi dengan pembeli, serta kebijakan toko yang ditampilkan saat checkout. Bukti yang tersimpan rapi membuat Anda bisa menjawab dalam hitungan menit." },
  { type: "p", text: "Tinjau penyebab setiap sengketa. Apakah karena penipuan, barang tidak sesuai, deskripsi yang menyesatkan, atau pembeli tidak mengenali nama yang muncul di tagihan kartu? Nama usaha yang tidak jelas di tagihan adalah penyebab sengketa yang bisa dicegah dengan memastikan nama yang tampil sesuai dengan nama toko yang dikenal pelanggan." },
  { type: "p", text: "Pantau rasio sengketa Anda dari waktu ke waktu. Penyedia pembayaran umumnya memiliki ambang yang bila terlampaui dapat berujung pada pembatasan akun. Mengetahui angka ini sejak dini memberi Anda waktu untuk memperbaiki penyebab sebelum akun terdampak." },
  { type: "h2", text: "Melindungi pelanggan dari penipuan yang mengatasnamakan toko" },
  { type: "p", text: "Penipu sering meniru toko yang dikenal: akun media sosial palsu, nomor percakapan yang menyerupai, atau situs tiruan dengan alamat yang nyaris sama. Korbannya pelanggan Anda, tetapi reputasi yang rusak adalah milik Anda. Komunikasikan dengan jelas kanal resmi toko dan hanya satu rekening atau metode pembayaran resmi." },
  { type: "p", text: "Sampaikan secara terbuka bahwa toko tidak pernah meminta kata sandi, kode verifikasi, atau transfer di luar halaman checkout resmi. Peringatan singkat di surel konfirmasi dan di halaman bantuan sering menyelamatkan pelanggan dari jebakan yang sudah umum." },
  { type: "p", text: "Pantau penggunaan nama dan logo Anda secara berkala dan laporkan akun atau situs tiruan kepada platform terkait. Tindakan cepat membatasi jumlah korban dan menunjukkan kepada pelanggan bahwa Anda serius menjaga mereka." },
  { type: "h2", text: "Bayar di tempat dan metode pembayaran lokal" },
  { type: "p", text: "Di pasar seperti Indonesia, banyak pembeli memilih bayar di tempat, transfer bank, dompet digital, atau QRIS. Setiap metode memiliki profil risiko berbeda. Bayar di tempat hampir tidak punya risiko kartu curian, tetapi membuka risiko pesanan main-main yang ditolak di depan pintu dan ongkos kirim yang terbuang." },
  { type: "p", text: "Untuk bayar di tempat, pertimbangkan konfirmasi singkat lewat pesan sebelum pengiriman, batas nilai pesanan, atau uang muka untuk barang bernilai tinggi. Catat pembeli yang berulang kali menolak paket sehingga pesanan berikutnya dari mereka dapat diperlakukan berbeda. Aturannya harus jelas dan disampaikan di halaman checkout agar adil." },
  { type: "p", text: "Pada transfer bank dan dompet digital, risiko utamanya adalah bukti transfer palsu dan konfirmasi yang dipalsukan. Jangan mengandalkan tangkapan layar; konfirmasi pembayaran lewat notifikasi resmi penyedia atau rekonsiliasi rekening. Sistem yang memverifikasi pembayaran secara otomatis menutup celah ini sekaligus mempercepat proses pesanan." },
  { type: "h2", text: "Memantau, mencatat, dan belajar dari kejadian" },
  { type: "p", text: "Keamanan yang baik membutuhkan jejak. Pastikan sistem mencatat siapa mengubah apa dan kapan: perubahan harga, pengembalian dana, perubahan alamat, serta akses ke data pelanggan. Catatan ini sangat berharga ketika perlu menyelidiki kejadian, dan sekadar keberadaannya sudah menekan godaan penyalahgunaan di dalam organisasi." },
  { type: "p", text: "Buat dasbor sederhana yang memantau beberapa angka: jumlah pembayaran gagal per hari, jumlah pesanan yang ditahan, jumlah sengketa, dan nilai pengembalian dana. Lonjakan mendadak pada salah satunya adalah sinyal untuk diperiksa, sering kali sebelum ada pelanggan yang mengeluh." },
  { type: "p", text: "Setelah setiap kejadian serius, lakukan tinjauan singkat tanpa mencari kambing hitam. Apa yang terjadi, mengapa lolos, dan aturan apa yang perlu ditambah? Tinjauan semacam ini mengubah setiap kerugian menjadi perbaikan yang membuat toko lebih kuat." },
  { type: "h2", text: "Privasi dan kewajiban terhadap data pelanggan" },
  { type: "p", text: "Pencegahan penipuan sering melibatkan pengumpulan data tambahan seperti alamat jaringan, informasi perangkat, dan riwayat pesanan. Kumpulkan seperlunya, beri tahu pelanggan melalui kebijakan privasi yang jelas, dan simpan selama diperlukan saja. Pengumpulan data yang berlebihan membuat Anda menanggung risiko yang tidak perlu." },
  { type: "p", text: "Siapkan rencana bila terjadi kebocoran data: siapa yang dihubungi, bagaimana pelanggan diberi tahu, dan langkah apa yang segera diambil. Rincian kewajiban hukum dapat berbeda dan berubah, sehingga konsultasikan dengan penasihat hukum dan rujuk aturan perlindungan data pribadi yang berlaku saat ini." },
  { type: "p", text: "Latih seluruh tim, termasuk staf layanan pelanggan, untuk mengenali upaya rekayasa sosial. Banyak pengambilalihan akun terjadi bukan karena peretasan canggih, melainkan karena penipu berhasil meyakinkan staf untuk mengubah alamat surel atau mengirimkan akses." },
  { type: "h2", text: "Memanfaatkan verifikasi tambahan dari penyedia pembayaran" },
  { type: "p", text: "Banyak penyedia pembayaran menawarkan verifikasi tambahan untuk transaksi kartu, seperti tantangan autentikasi oleh bank penerbit. Ketika verifikasi ini berhasil, tanggung jawab atas sengketa akibat kartu curian umumnya bergeser dari pedagang ke penerbit kartu, dengan syarat dan pengecualian yang berbeda tiap penyedia. Pelajari ketentuan penyedia Anda dengan teliti." },
  { type: "p", text: "Verifikasi tambahan juga menambah langkah bagi pembeli, sehingga sebagian pembeli membatalkan transaksi. Karena itu, banyak toko menerapkannya secara selektif: otomatis untuk transaksi berisiko atau bernilai tinggi, dan lebih ringan untuk pembeli lama yang sudah dikenal. Sesuaikan dengan profil pelanggan Anda." },
  { type: "p", text: "Uji alur pembayaran Anda dari sisi pembeli secara berkala, termasuk di ponsel dan jaringan yang lambat. Alur verifikasi yang membingungkan atau gagal di perangkat tertentu menyebabkan kehilangan penjualan yang tidak pernah muncul sebagai laporan kerugian." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menyimpan data kartu sendiri atau mengirimnya lewat surel dan percakapan",
    "Menolak otomatis semua pesanan yang tampak aneh tanpa tinjauan manual",
    "Memberi semua staf hak akses admin penuh tanpa verifikasi dua langkah",
    "Tidak menyimpan bukti pengiriman dan korespondensi untuk keperluan sengketa",
    "Membiarkan nama tagihan kartu berbeda dari nama toko yang dikenal pelanggan",
    "Menganggap keamanan selesai setelah satu kali pengaturan awal",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Pastikan tidak ada data kartu yang tersimpan atau lewat di sistem dan surel Anda",
    "Tulis lima aturan tinjauan pesanan beserta siapa yang memeriksa dan batas waktunya",
    "Aktifkan verifikasi dua langkah untuk semua akun admin dan tinjau daftar hak akses",
    "Susun daftar bukti standar yang selalu disimpan untuk setiap pesanan",
    "Periksa nama yang tampil di tagihan kartu dan kanal resmi toko yang Anda umumkan",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Penipuan tidak bisa dihapus sepenuhnya, tetapi dampaknya bisa dikendalikan. Kombinasi pembayaran yang ditangani penyedia terpercaya, aturan tinjauan yang konsisten, akun yang terlindungi, dan bukti yang tersimpan rapi membuat toko Anda jauh lebih sulit menjadi sasaran empuk." },
  { type: "p", text: "Ingat bahwa tujuannya adalah menjaga penjualan yang sah sekaligus menutup celah penyalahgunaan. Keamanan yang baik terasa nyaris tak terlihat oleh pembeli jujur, dan baru terasa oleh mereka yang berniat curang." },
  {
    type: "cta",
    title: "Ingin toko online Anda lebih aman dari penipuan pembayaran?",
    text: "Tim AG·SORA membangun toko online dengan integrasi pembayaran yang aman, aturan tinjauan pesanan, dan kontrol akses yang rapi. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
