import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Cara orang mencari informasi sedang berubah. Dulu seseorang mengetik beberapa kata di mesin pencari, mendapat daftar tautan, lalu membuka beberapa di antaranya. Sekarang semakin banyak orang yang bertanya dengan kalimat lengkap kepada asisten berbasis kecerdasan buatan, atau mendapat ringkasan jawaban di bagian paling atas halaman hasil pencarian, dan sering merasa cukup tanpa mengeklik apa pun." },
  { type: "p", text: "Bagi pemilik bisnis, perubahan ini menimbulkan pertanyaan yang wajar. Apakah website masih penting bila jawaban sudah diberikan sebelum orang sampai ke situs? Apakah upaya SEO yang sudah dilakukan menjadi sia-sia? Apakah ada cara baru yang harus dipelajari? Di tengah banyaknya klaim yang berlebihan, sulit membedakan mana yang benar-benar perlu ditanggapi." },
  { type: "p", text: "Artikel ini mencoba menjawab dengan tenang. Kami membahas apa yang sebenarnya berubah, apa yang tetap sama, jenis konten yang paling terdampak, serta langkah praktis agar bisnis Anda tetap ditemukan dan dipercaya. Bidang ini bergerak cepat dan tidak ada yang bisa memastikan arahnya, jadi kami tidak memakai angka rekaan dan tidak menjanjikan trik. Yang kami tawarkan adalah prinsip yang masuk akal apa pun bentuk pencarian kelak." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Pencarian berbasis AI merangkum jawaban dari banyak sumber, sehingga sebagian pertanyaan sederhana tidak lagi berujung pada kunjungan ke situs",
      "Dasar yang baik tetap sama: konten yang membantu, situs yang bisa dibaca mesin, dan reputasi yang nyata",
      "Konten yang berisi pengalaman dan data milik sendiri lebih sulit digantikan oleh ringkasan",
      "Informasi bisnis harus konsisten di website, profil bisnis, dan tempat lain yang menyebut Anda",
      "Ukur dengan prospek dan penjualan, bukan hanya jumlah kunjungan",
    ],
  },
  { type: "h2", text: "Apa yang sebenarnya berubah" },
  { type: "p", text: "Perubahan pertama adalah bentuk jawaban. Mesin pencari dan asisten AI kini mampu menyusun jawaban langsung dengan merangkum beberapa sumber, kadang disertai tautan ke sumbernya. Untuk pertanyaan sederhana, seperti definisi suatu istilah atau langkah umum melakukan sesuatu, pengguna mendapat yang ia perlukan tanpa membuka situs mana pun." },
  { type: "p", text: "Perubahan kedua adalah bentuk pertanyaan. Orang bertanya lebih panjang dan lebih spesifik, seperti berbicara kepada seseorang. Alih-alih mengetik sistem kasir restoran, mereka bertanya sistem kasir apa yang cocok untuk kedai kopi dengan dua cabang yang ingin stoknya tersambung. Pertanyaan lanjutan pun diajukan dalam percakapan yang sama." },
  { type: "p", text: "Perubahan ketiga adalah tempat pencarian terjadi. Orang mencari bukan hanya di mesin pencari, tetapi juga di aplikasi asisten, media sosial, marketplace, peta, dan platform video. Perjalanan menuju keputusan membeli tersebar di banyak tempat, dan website Anda menjadi salah satu perhentian, bukan satu-satunya." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5",
    alt: "Meja kerja dengan monitor dan laptop yang menampilkan halaman website, lampu meja, dan tanaman",
    caption: "Website tetap menjadi tempat bisnis menjelaskan dirinya dengan kata-katanya sendiri.",
  },
  { type: "h2", text: "Apa yang tidak berubah" },
  { type: "p", text: "Di balik perubahan bentuk itu, ada hal-hal yang tetap. Orang masih memiliki pertanyaan dan masih mencari pihak yang bisa dipercaya untuk menjawabnya. Sistem pencarian apa pun, lama atau baru, tetap memerlukan sumber yang jelas, akurat, dan dapat diandalkan. Ringkasan AI tidak muncul dari udara; ia disusun dari halaman-halaman yang ditulis manusia dan bisnis." },
  { type: "p", text: "Keputusan penting juga jarang diambil hanya dari ringkasan. Seseorang yang akan mengeluarkan dana besar untuk sistem, aplikasi, atau jasa profesional ingin melihat sendiri siapa penyedianya, apa saja yang pernah dikerjakan, bagaimana cara kerjanya, dan bagaimana menghubunginya. Untuk tahap itu, website bisnis masih menjadi tujuan." },
  { type: "p", text: "Karena itu sebagian besar pekerjaan SEO yang baik tetap relevan. Situs yang cepat, struktur yang rapi, konten yang menjawab pertanyaan nyata, dan reputasi yang dibangun dengan jujur bermanfaat bagi pencarian biasa maupun pencarian berbasis AI. Yang kehilangan nilai adalah jalan pintas: halaman tipis yang dibuat hanya untuk menangkap kata kunci." },
  { type: "h2", text: "Kunjungan berkurang, niat bertambah jelas" },
  { type: "p", text: "Banyak pemilik situs khawatir kunjungan akan turun karena pengguna mendapat jawaban tanpa mengeklik. Untuk jenis konten tertentu, kekhawatiran itu masuk akal. Halaman yang hanya menjawab pertanyaan umum dengan cara yang sama seperti ribuan halaman lain paling mudah digantikan oleh ringkasan." },
  { type: "p", text: "Namun kunjungan yang hilang itu sering kali memang bukan calon pelanggan. Orang yang hanya ingin tahu arti suatu istilah jarang berubah menjadi pembeli. Sebaliknya, orang yang tetap mengeklik setelah membaca ringkasan biasanya memiliki kebutuhan yang lebih dalam: ia ingin rincian, bukti, harga, atau ingin berbicara dengan seseorang." },
  { type: "p", text: "Artinya, ukuran keberhasilan perlu bergeser. Jumlah kunjungan saja makin kurang bermakna. Yang lebih penting adalah berapa banyak pengunjung yang menghubungi, meminta penawaran, mendaftar, atau membeli. Situs dengan kunjungan lebih sedikit tetapi lebih tepat sasaran bisa menghasilkan lebih banyak bisnis daripada sebelumnya." },
  { type: "callout", title: "Jangan panik, jangan pula mengabaikan", text: "Dua tanggapan yang sama kelirunya adalah membuang seluruh upaya SEO karena dianggap usang, dan berpura-pura tidak ada yang berubah. Sikap yang lebih berguna adalah memperkuat dasar yang berlaku di semua bentuk pencarian, lalu mengamati data Anda sendiri dari bulan ke bulan." },
  { type: "h2", text: "Konten yang sulit digantikan ringkasan" },
  { type: "p", text: "Sistem AI sangat baik dalam merangkum pengetahuan umum yang sudah banyak ditulis. Ia jauh lebih lemah dalam hal yang hanya dimiliki bisnis Anda: pengalaman langsung, data sendiri, sudut pandang, dan rincian tentang penawaran Anda. Di situlah konten yang layak dibuat." },
  { type: "ul", items: [
    "Penjelasan rinci tentang layanan, proses kerja, dan apa yang termasuk serta tidak termasuk",
    "Panduan yang lahir dari pengalaman mengerjakan pekerjaan nyata, lengkap dengan pertimbangan dan batasannya",
    "Perbandingan pilihan yang jujur, termasuk kapan penawaran Anda bukan pilihan yang tepat",
    "Jawaban atas pertanyaan yang benar-benar diajukan pelanggan kepada tim penjualan dan dukungan",
    "Informasi praktis yang terus diperbarui: harga, ketersediaan, wilayah layanan, jam operasional",
    "Pendapat yang beralasan tentang perkembangan di bidang Anda",
  ] },
  { type: "p", text: "Sumber gagasan terbaik ada di dalam bisnis Anda sendiri. Catat pertanyaan yang muncul di obrolan, telepon, dan rapat penjualan. Pertanyaan itu panjang, spesifik, dan memakai bahasa pelanggan, persis seperti pertanyaan yang kini diajukan orang kepada asisten AI. Halaman yang menjawabnya dengan jelas berguna bagi manusia maupun mesin." },
  { type: "h2", text: "Menulis agar mudah dipahami manusia dan mesin" },
  { type: "p", text: "Cara menulis yang baik bagi pembaca ternyata juga baik bagi sistem yang merangkum. Jawab pertanyaan secara langsung di awal bagian, lalu jelaskan rinciannya. Gunakan judul bagian yang menggambarkan isinya. Pakai kalimat lengkap yang tetap bermakna bila dikutip terpisah dari paragraf di sekitarnya." },
  { type: "p", text: "Sebutkan hal secara eksplisit. Tulis nama bisnis, jenis layanan, dan wilayah yang dilayani dengan jelas, jangan hanya menyiratkannya. Hindari kalimat pemasaran yang kabur seperti solusi terbaik untuk semua kebutuhan; kalimat seperti itu tidak memberi informasi kepada siapa pun. Pernyataan yang konkret dan dapat diperiksa lebih mungkin dipercaya dan dirujuk." },
  { type: "p", text: "Tunjukkan siapa yang menulis dan kapan diperbarui. Halaman yang mencantumkan penulis dengan keahlian relevan, tanggal pembaruan, dan sumber untuk klaim penting memberi tanda bahwa isinya dirawat. Untuk topik yang menyangkut uang, kesehatan, atau hukum, kehati-hatian seperti ini makin penting." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    alt: "Layar laptop menampilkan kode program berwarna di editor",
    caption: "Struktur teknis yang rapi membantu mesin memahami isi halaman tanpa harus menebak.",
  },
  { type: "h2", text: "Dasar teknis yang membuat situs bisa dibaca" },
  { type: "p", text: "Konten yang baik tidak berguna bila tidak bisa dibaca mesin. Pastikan isi penting tersedia sebagai teks di halaman, bukan hanya di dalam gambar atau baru muncul setelah skrip berjalan lama. Situs yang dibangun dengan kerangka modern sebaiknya menyajikan isi yang sudah jadi dari server agar perayap apa pun dapat membacanya." },
  { type: "ul", items: [
    "Struktur judul yang berurutan dan mencerminkan susunan isi",
    "Data terstruktur untuk jenis halaman yang relevan: organisasi, layanan, produk, artikel, tanya jawab",
    "Peta situs yang lengkap dan diperbarui ketika ada halaman baru",
    "Tautan internal yang menghubungkan halaman terkait secara masuk akal",
    "Kecepatan muat yang baik, terutama di ponsel",
    "Penanda bahasa yang benar untuk situs multibahasa",
  ] },
  { type: "p", text: "Data terstruktur patut mendapat perhatian khusus. Ia menyatakan secara eksplisit kepada mesin bahwa suatu halaman berbicara tentang layanan tertentu, dengan nama, deskripsi, dan penyedia tertentu. Informasi yang dinyatakan dengan jelas lebih kecil kemungkinannya disalahpahami ketika dirangkum." },
  { type: "h2", text: "Mengatur akses perayap AI" },
  { type: "p", text: "Sejumlah penyedia sistem AI menjalankan perayap sendiri, dan sebagian menyediakan cara bagi pemilik situs untuk mengizinkan atau menolak aksesnya lewat berkas pengaturan perayap. Ini keputusan bisnis, bukan sekadar urusan teknis. Mengizinkan berarti isi Anda dapat dipakai untuk menjawab pertanyaan; menolak berarti Anda mungkin tidak muncul di jawaban tersebut." },
  { type: "p", text: "Bagi kebanyakan bisnis yang ingin ditemukan calon pelanggan, tampil dalam jawaban lebih menguntungkan daripada tidak tampil. Bagi penerbit yang menjual kontennya, pertimbangannya berbeda. Daftar perayap dan cara kerjanya terus berubah, jadi tinjau pengaturan ini secara berkala bersama pengembang dan rujuk dokumentasi resmi masing-masing penyedia." },
  { type: "p", text: "Apa pun pilihannya, jangan menaruh informasi rahasia di halaman publik dengan harapan tidak ditemukan. Harga khusus, dokumen internal, dan data pelanggan harus dilindungi dengan pembatasan akses yang sebenarnya, bukan dengan pengaturan perayap yang bersifat permintaan." },
  { type: "h2", text: "Reputasi di luar website" },
  { type: "p", text: "Sistem AI menyusun gambaran tentang sebuah bisnis dari banyak tempat, bukan hanya dari situs bisnis itu sendiri. Profil bisnis di peta, ulasan pelanggan, direktori industri, pemberitaan, dan pembahasan di forum ikut membentuknya. Bila tempat-tempat itu menyebut Anda dengan cara yang konsisten dan positif, gambaran yang muncul pun lebih kuat." },
  { type: "p", text: "Pastikan informasi dasar sama di semua tempat: nama bisnis, alamat, nomor telepon, jam buka, jenis layanan, dan wilayah yang dilayani. Ketidakcocokan kecil, seperti alamat lama di satu direktori, menimbulkan keraguan pada manusia dan mesin. Luangkan waktu untuk memeriksa dan memperbaikinya." },
  { type: "p", text: "Ulasan yang asli makin berharga. Minta pelanggan yang puas menulis ulasan di tempat yang relevan, dan tanggapi ulasan buruk dengan tenang serta bermanfaat. Jangan membuat ulasan palsu; selain melanggar ketentuan platform dan dapat melanggar hukum, pola seperti itu makin mudah dikenali." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1694928850410-b209896782a2",
    alt: "Pin Google Maps di atas selembar kertas",
    caption: "Informasi bisnis yang konsisten di peta dan direktori ikut membentuk jawaban tentang bisnis Anda.",
  },
  { type: "h2", text: "Memakai AI untuk membuat konten: manfaat dan risikonya" },
  { type: "p", text: "Alat AI bisa membantu pekerjaan konten: menyusun kerangka, merapikan bahasa, menerjemahkan, dan memeriksa kelengkapan. Dipakai dengan cara itu, ia menghemat waktu. Risikonya muncul ketika alat tersebut dipakai untuk menghasilkan halaman dalam jumlah besar tanpa pengetahuan baru di dalamnya." },
  { type: "p", text: "Halaman yang dihasilkan otomatis dari pengetahuan umum tidak menambah apa pun yang belum dimiliki sistem AI itu sendiri. Ia tidak punya alasan untuk dirujuk. Lebih buruk lagi, alat AI dapat menulis hal yang terdengar meyakinkan tetapi keliru, termasuk angka dan kutipan yang tidak pernah ada. Menerbitkannya tanpa pemeriksaan merusak kepercayaan pada bisnis Anda." },
  { type: "p", text: "Aturan yang sederhana: manusia yang memahami bidangnya menentukan isi dan bertanggung jawab atas kebenarannya, sedangkan alat membantu penyusunannya. Setiap klaim diperiksa, setiap contoh berasal dari pengalaman nyata, dan setiap halaman memiliki alasan untuk ada selain mengisi kata kunci." },
  { type: "h2", text: "Toko online dan pencarian produk" },
  { type: "p", text: "Bagi toko online, perubahan ini terasa pada cara orang menemukan produk. Asisten belanja dapat membandingkan barang dari berbagai toko berdasarkan spesifikasi, harga, ketersediaan, dan ulasan. Produk dengan data yang lengkap dan terstruktur lebih mudah dipahami dan dibandingkan daripada produk yang hanya berisi foto dan satu kalimat." },
  { type: "p", text: "Lengkapi setiap produk dengan nama yang deskriptif, atribut yang terisi, deskripsi yang menjawab pertanyaan pembeli, harga dan stok yang selalu terbaru, serta kebijakan pengiriman dan retur yang jelas. Data produk terstruktur dan umpan produk yang rapi membuat informasi itu dapat dibaca oleh berbagai sistem, bukan hanya oleh pengunjung situs." },
  { type: "p", text: "Pekerjaan ini sama dengan yang membuat pencarian di dalam toko Anda berjalan baik. Katalog yang rapi adalah investasi yang hasilnya dirasakan di banyak tempat sekaligus." },
  { type: "h2", text: "Mengukur dengan cara yang lebih bermakna" },
  { type: "p", text: "Alat ukur untuk pencarian berbasis AI masih berkembang dan belum selengkap alat untuk pencarian biasa. Sebagian kunjungan dari asisten AI terlihat di laporan sumber kunjungan, sebagian tidak. Karena itu jangan bergantung pada satu angka." },
  { type: "ul", items: [
    "Jumlah prospek, permintaan penawaran, dan penjualan dari kunjungan organik",
    "Pencarian yang menyebut nama merek Anda, sebagai tanda orang mengenal bisnis Anda",
    "Halaman yang menjadi pintu masuk dan apa yang dilakukan pengunjung sesudahnya",
    "Jawaban pelanggan baru ketika ditanya dari mana mereka mengetahui bisnis Anda",
    "Pemeriksaan berkala: tanyakan kepada beberapa asisten AI tentang bidang dan bisnis Anda, lalu catat jawabannya",
  ] },
  { type: "p", text: "Butir terakhir sederhana tetapi berguna. Dengan sesekali mengajukan pertanyaan yang biasa diajukan calon pelanggan, Anda melihat apakah bisnis Anda disebut, apakah informasinya benar, dan sumber apa yang dirujuk. Informasi yang keliru biasanya dapat ditelusuri ke halaman lama atau profil yang tidak diperbarui." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menghentikan seluruh upaya SEO karena menganggapnya sudah mati",
    "Menerbitkan halaman buatan AI dalam jumlah besar tanpa pemeriksaan dan tanpa isi baru",
    "Mengejar trik yang menjanjikan tampil di jawaban AI dengan cara instan",
    "Membiarkan informasi bisnis berbeda-beda di berbagai tempat",
    "Menyimpan isi penting hanya dalam gambar atau berkas yang sulit dibaca mesin",
    "Menilai keberhasilan hanya dari jumlah kunjungan",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Kumpulkan dua puluh pertanyaan yang paling sering diajukan pelanggan kepada tim Anda",
    "Periksa apakah website Anda menjawab pertanyaan itu dengan jelas, lalu catat yang belum",
    "Samakan nama, alamat, nomor telepon, dan jam buka di website, profil bisnis, dan direktori",
    "Minta pengembang memeriksa data terstruktur, peta situs, dan keterbacaan isi oleh perayap",
    "Tanyakan kepada beberapa asisten AI tentang bisnis Anda dan catat apa yang benar serta yang keliru",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Pencarian berbasis AI mengubah bentuk jawaban dan jalan yang ditempuh orang menuju sebuah bisnis, tetapi tidak mengubah apa yang dicari orang: jawaban yang benar dari pihak yang bisa dipercaya. Bisnis yang memiliki website yang jelas, konten yang lahir dari pengalaman nyata, data yang rapi, dan reputasi yang konsisten berada pada posisi yang baik dalam bentuk pencarian apa pun." },
  { type: "p", text: "Tidak perlu mengejar setiap istilah baru. Perkuat dasarnya, amati data Anda sendiri, dan sesuaikan langkah seiring keadaan menjadi lebih jelas. Di tengah banyaknya konten yang dibuat serba otomatis, kejelasan dan kejujuran justru menjadi pembeda yang makin langka." },
  {
    type: "cta",
    title: "Ingin website yang siap untuk pencarian biasa maupun pencarian berbasis AI?",
    text: "Tim AG·SORA membangun website dengan struktur yang rapi, data terstruktur, performa cepat, dan konten yang menjawab pertanyaan pelanggan Anda. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
