import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Banyak pemilik toko online menghabiskan energi untuk iklan, foto produk, dan deskripsi yang menarik, lalu memperlakukan pengiriman sebagai urusan belakang yang \"pokoknya sampai\". Padahal bagi pelanggan, pengiriman adalah bagian dari produk itu sendiri. Barang yang bagus tetapi tiba terlambat, rusak, atau tanpa kabar akan meninggalkan kesan buruk yang lebih kuat daripada kesan baik dari halaman produk yang rapi." },
  { type: "p", text: "Pengiriman juga langsung menyentuh uang. Ongkos kirim yang salah hitung menggerus margin atau membuat pelanggan membatalkan pesanan di langkah terakhir. Pengemasan yang asal menambah barang rusak dan klaim. Pelacakan yang tidak jelas membuat tim layanan pelanggan kebanjiran pertanyaan yang sama berulang kali, \"Paket saya di mana?\". Semua itu bisa ditata, dan penataannya tidak harus mahal." },
  { type: "p", text: "Artikel ini membahas logistik toko online dari sudut pandang pemilik bisnis, bukan ahli rantai pasok. Kita mulai dari cara memilih kurir dan menyusun tarif, lalu pengemasan, pelacakan, pengiriman dari banyak titik, hingga retur dan cara mengukur apakah semuanya berjalan baik. Kami sengaja tidak memakai angka rekaan tentang tarif atau persentase keterlambatan, karena tarif kurir berubah dan berbeda di tiap wilayah. Yang kami tawarkan adalah cara berpikir dan daftar periksa yang bisa Anda terapkan pada data toko Anda sendiri." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Anggap pengiriman sebagai bagian dari produk: kecepatan, keamanan barang, dan kejelasan informasi sama pentingnya dengan kualitas barang",
      "Pilih kurir berdasarkan jangkauan wilayah pelanggan Anda, bukan hanya harga termurah, dan siapkan setidaknya satu cadangan",
      "Tampilkan ongkir seakurat mungkin sebelum pembayaran agar tidak ada kejutan yang membuat pesanan batal",
      "Standarkan pengemasan dan catat setiap paket dengan nomor resi yang bisa dilacak pelanggan",
      "Rancang alur retur dan penukaran sejak awal, lalu ukur waktu kirim, tingkat kerusakan, dan keluhan untuk terus memperbaiki",
    ],
  },
  { type: "h2", text: "Mengapa pengiriman menentukan pembelian ulang" },
  { type: "p", text: "Pelanggan jarang menilai toko online hanya dari momen klik beli. Penilaian sebenarnya terbentuk saat paket tiba. Jika paket datang sesuai janji, terbungkus rapi, dan isinya sesuai pesanan, pelanggan merasa keputusan membelinya tepat. Jika sebaliknya, ia akan ragu pada pembelian berikutnya, apa pun kualitas barangnya." },
  { type: "p", text: "Ada tiga hal yang paling sering dirasakan pelanggan. Pertama, kecepatan dan ketepatan janji. Pelanggan lebih mudah memaafkan estimasi tiga hari yang ditepati daripada estimasi satu hari yang meleset. Kedua, kondisi barang: kemasan penyok, produk pecah, atau bagian yang hilang. Ketiga, komunikasi: apakah ia tahu kapan barang dikirim, di mana posisinya, dan siapa yang bisa dihubungi jika ada masalah." },
  { type: "p", text: "Bagi bisnis, tiga hal itu berujung pada biaya yang nyata. Klaim barang rusak, kiriman ulang, dan waktu tim menjawab pertanyaan pelacakan semuanya memakan uang dan jam kerja. Memperbaiki hulu masalah, yaitu cara Anda memilih kurir, mengemas, dan memberi informasi, hampir selalu lebih murah daripada terus menambal akibatnya." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55",
    alt: "Dua orang menyerahkan sebuah paket kardus yang sudah dilakban",
    caption: "Momen paket berpindah tangan adalah saat pelanggan menilai seluruh pengalaman belanja, bukan hanya produknya.",
  },
  { type: "h2", text: "Memahami alur pengiriman dari awal sampai akhir" },
  { type: "p", text: "Sebelum membandingkan kurir, gambarkan dulu seluruh alur pengiriman di toko Anda. Alur yang jelas membuat Anda tahu di titik mana waktu dan biaya paling banyak terbuang. Secara umum, alurnya terdiri dari beberapa tahap yang saling terhubung." },
  {
    type: "ol",
    items: [
      "Pesanan masuk dan dibayar, lalu sistem menandainya siap diproses",
      "Petugas gudang mengambil barang sesuai pesanan, memeriksa jumlah dan kondisi",
      "Barang dikemas, ditimbang, dan diberi label alamat serta nomor resi",
      "Kurir menjemput atau paket diantar ke titik pengumpulan",
      "Paket dalam perjalanan dan statusnya diperbarui oleh kurir",
      "Paket diterima pelanggan, lalu status pesanan diselesaikan",
      "Jika ada masalah, alur retur atau klaim dijalankan",
    ],
  },
  { type: "p", text: "Setiap tahap punya penyebab keterlambatan sendiri. Pesanan bisa menumpuk di tahap pengambilan karena tata letak gudang yang membingungkan. Pengemasan bisa lambat karena bahan kemasan tidak tersedia. Pembaruan status bisa terlambat karena resi dimasukkan manual dan terlupa. Dengan memetakan alur ini, Anda bisa memberi nama pada masalahnya dan memperbaikinya satu per satu." },
  { type: "h3", text: "Cut-off time dan janji pengiriman" },
  { type: "p", text: "Tetapkan jam batas pesanan, yaitu waktu terakhir pesanan masih bisa diproses dan dikirim pada hari yang sama. Informasikan jam itu dengan jelas di halaman produk atau keranjang. Pelanggan yang tahu bahwa pesanan setelah pukul tertentu baru dikirim besok tidak akan kecewa, sedangkan pelanggan yang menduga barangnya berangkat hari ini lalu menunggu dua hari akan merasa dibohongi." },
  { type: "p", text: "Janji pengiriman sebaiknya konservatif. Hitung waktu proses internal ditambah estimasi kurir ditambah sedikit ruang cadangan. Lebih baik pelanggan menerima barang lebih cepat dari janji daripada sebaliknya." },
  { type: "h2", text: "Memilih kurir dan layanan yang tepat" },
  { type: "p", text: "Memilih kurir bukan sekadar membandingkan tarif. Pertanyaan pertama adalah ke mana pelanggan Anda berada. Kurir yang kuat di kota besar belum tentu andal untuk daerah terpencil, dan sebaliknya. Lihat sebaran alamat pelanggan di data pesanan Anda, lalu pilih kurir yang jangkauannya cocok dengan sebaran itu." },
  { type: "p", text: "Pertimbangan kedua adalah jenis barang. Barang kecil dan ringan cocok dengan layanan reguler, sedangkan barang besar, berat, mudah pecah, atau butuh pendinginan membutuhkan layanan khusus. Beberapa kurir menawarkan layanan kargo untuk barang berat dengan perhitungan berbeda, dan sebagian menyediakan layanan di hari yang sama untuk dalam kota." },
  { type: "p", text: "Pertimbangan ketiga adalah keandalan operasional: seberapa konsisten kurir menjemput paket, seberapa cepat status diperbarui, dan seberapa responsif layanan pelanggannya saat ada kehilangan atau kerusakan. Informasi ini paling jujur datang dari pengalaman Anda sendiri. Uji beberapa kurir dengan jumlah paket kecil pada rute yang sama, lalu bandingkan hasilnya." },
  { type: "h3", text: "Mengapa perlu kurir cadangan" },
  { type: "p", text: "Mengandalkan satu kurir membuat toko Anda rentan. Saat kurir itu mengalami gangguan, misalnya lonjakan musim belanja atau kendala di suatu wilayah, seluruh pengiriman ikut tersendat. Siapkan minimal satu kurir cadangan yang sudah pernah Anda coba dan akunnya sudah aktif. Dengan begitu Anda bisa memindahkan sebagian pengiriman tanpa harus mendaftar dan belajar dari nol di tengah krisis." },
  {
    type: "callout",
    title: "Catatan praktis",
    text: "Simpan catatan sederhana tentang performa tiap kurir per wilayah: jumlah paket, waktu tiba, dan jumlah masalah. Setelah beberapa bulan, catatan ini menjadi dasar negosiasi tarif dan keputusan kurir mana yang dipakai ke mana.",
  },
  { type: "h2", text: "Menghitung dan menampilkan ongkos kirim" },
  { type: "p", text: "Ongkos kirim adalah salah satu penyebab terbesar pelanggan membatalkan pesanan di langkah akhir, terutama jika angkanya baru muncul setelah mereka mengisi data. Prinsipnya sederhana: tampilkan biaya seawal dan seakurat mungkin." },
  { type: "p", text: "Ada beberapa pendekatan yang umum dipakai. Tarif datar berlaku sama untuk semua pesanan atau per wilayah, mudah dipahami tetapi bisa merugikan Anda pada pesanan berat. Tarif berdasarkan berat dan tujuan, yang diambil langsung dari kurir, paling akurat tetapi butuh integrasi. Gratis ongkir dengan syarat minimum belanja bisa mendorong keranjang yang lebih besar, tetapi hanya jika biayanya sudah dihitung ke dalam harga atau margin. Setiap pendekatan punya risiko, jadi pilih yang cocok dengan jenis barang dan margin Anda." },
  { type: "h3", text: "Berat volumetrik dan kemasan" },
  { type: "p", text: "Banyak kurir menghitung biaya berdasarkan yang lebih besar antara berat sebenarnya dan berat volumetrik, yaitu ukuran kemasan yang dikonversi ke berat. Barang ringan yang dikemas dalam kardus besar bisa terhitung mahal. Karena itu, ukuran kemasan yang pas sama pentingnya dengan berat barang. Menyediakan beberapa ukuran kemasan standar membantu menjaga ongkir tetap wajar sekaligus melindungi barang dengan baik." },
  { type: "h3", text: "Subsidi ongkir dan gratis ongkir" },
  { type: "p", text: "Gratis ongkir adalah alat pemasaran yang kuat, tetapi ongkir tidak benar-benar gratis; seseorang tetap membayarnya. Pastikan Anda tahu persis dari mana biaya itu ditutup: dari margin, dari harga yang sedikit lebih tinggi, atau dari syarat belanja minimum. Hitung dengan data pesanan Anda sendiri sebelum meluncurkannya, dan tinjau ulang secara berkala karena tarif kurir bisa berubah." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3",
    alt: "Pemandangan udara pelabuhan peti kemas dengan derek dan tumpukan kontainer",
    caption: "Di balik satu paket kecil ada jaringan logistik besar; memahami alurnya membantu Anda memilih layanan yang tepat.",
  },
  { type: "h2", text: "Pengemasan yang melindungi barang dan reputasi" },
  { type: "p", text: "Kemasan adalah garis pertahanan pertama terhadap kerusakan, sekaligus kesan pertama yang dipegang pelanggan. Pengemasan yang baik tidak harus mewah, tetapi harus konsisten. Tentukan standar per jenis produk, misalnya barang pecah belah memakai bantalan dan kardus berlapis, pakaian memakai kantong kedap air, dan produk cair memakai penutup tambahan." },
  { type: "p", text: "Beberapa kebiasaan membantu menjaga kualitas. Gunakan ukuran kemasan yang sesuai agar barang tidak bergeser di dalam kotak. Isi ruang kosong dengan bahan pengisi. Letakkan label alamat yang jelas dan tahan air, dan simpan salinan nota di dalam paket. Bagi barang berharga atau rapuh, foto kondisi barang sebelum dikemas dapat membantu jika terjadi klaim." },
  { type: "p", text: "Pengemasan juga bisa menjadi kesempatan membangun merek: sebuah kartu terima kasih, petunjuk perawatan produk, atau kode untuk pembelian berikutnya. Tetapi jangan mengorbankan perlindungan demi tampilan. Kemasan yang cantik namun membuat barang rusak tetaplah kemasan yang gagal." },
  { type: "h3", text: "Standar operasional untuk bagian pengemasan" },
  { type: "p", text: "Tuliskan prosedur pengemasan singkat dan tempelkan di meja kerja. Prosedur itu mencakup urutan langkah, bahan yang dipakai untuk tiap jenis produk, dan pemeriksaan akhir sebelum paket ditutup, yaitu memastikan isi sesuai nota dan alamat terbaca jelas. Dengan prosedur tertulis, siapa pun yang bertugas, termasuk karyawan baru, menghasilkan kemasan dengan kualitas yang sama." },
  { type: "h2", text: "Pelacakan paket dan komunikasi ke pelanggan" },
  { type: "p", text: "Sebagian besar pertanyaan layanan pelanggan di toko online adalah soal keberadaan paket. Anda bisa mengurangi pertanyaan itu secara drastis hanya dengan memberi informasi proaktif. Begitu paket dikirim, kirimkan nomor resi dan tautan pelacakan ke pelanggan lewat email atau pesan. Saat status berubah, misalnya paket sedang diantar atau gagal diantar, beri kabar singkat." },
  { type: "p", text: "Pesan yang baik pendek dan jelas: apa yang terjadi, apa yang diharapkan berikutnya, dan ke mana pelanggan bisa bertanya. Hindari istilah teknis kurir yang membingungkan. Jika terjadi keterlambatan yang jelas di luar kendali, seperti gangguan cuaca atau lonjakan paket, sampaikan lebih awal dan jujur. Pelanggan biasanya bisa memahami kendala yang dijelaskan, tetapi kesal pada keheningan." },
  { type: "h3", text: "Halaman status pesanan" },
  { type: "p", text: "Sediakan satu halaman tempat pelanggan bisa memasukkan nomor pesanan dan melihat statusnya tanpa harus menghubungi Anda. Halaman sederhana yang menampilkan tahap pesanan, nomor resi, dan tautan ke kurir sudah sangat membantu. Untuk toko dengan sistem yang terintegrasi, status ini dapat diperbarui otomatis dari data kurir, sehingga tim tidak perlu menyalin informasi secara manual." },
  {
    type: "callout",
    title: "Integrasi menghemat jam kerja",
    text: "Jika resi dan status masih diketik tangan, risiko salah ketik dan keterlambatan pembaruan selalu ada. Menghubungkan sistem toko dengan layanan kurir membuat resi tercatat otomatis dan status mengalir ke pelanggan tanpa campur tangan manual.",
  },
  { type: "h2", text: "Mengelola stok dan pengiriman dari banyak titik" },
  { type: "p", text: "Ketika bisnis berkembang, barang sering tersimpan di lebih dari satu tempat: gudang pusat, toko fisik, atau gudang mitra. Mengirim dari titik yang paling dekat dengan pelanggan memangkas waktu dan ongkir, tetapi menambah kerumitan. Anda perlu tahu stok di tiap lokasi secara akurat, aturan titik mana yang dipakai lebih dulu, dan cara menangani pesanan yang isinya tersebar di dua lokasi." },
  { type: "p", text: "Tanpa sistem yang menyatukan stok, kesalahan mudah terjadi: barang terjual padahal sudah habis di lokasi yang dituju, atau pesanan dikirim dari gudang yang jauh padahal stok tersedia di gudang yang dekat. Karena itu, pengiriman dari banyak titik hampir selalu membutuhkan sistem inventori terpusat yang memperbarui stok secara langsung setiap ada pesanan, pengiriman, atau retur." },
  { type: "p", text: "Untuk toko yang juga berjualan di marketplace, tantangannya bertambah karena stok yang sama dipakai di beberapa saluran. Menyinkronkan stok antar saluran mencegah penjualan ganda. Topik ini dibahas lebih rinci di artikel kami tentang menyatukan stok toko fisik dan marketplace." },
  { type: "h3", text: "Pre-order dan barang yang dibuat sesuai pesanan" },
  { type: "p", text: "Tidak semua barang tersedia di gudang saat dipesan. Untuk pre-order atau barang yang dibuat setelah pesanan masuk, komunikasikan estimasi waktu produksi secara terpisah dari estimasi pengiriman. Pelanggan perlu tahu dua hal itu: kapan barang selesai dibuat dan berapa lama pengirimannya. Mencampur keduanya dalam satu angka sering memicu kesalahpahaman." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2",
    alt: "Ponsel yang menampilkan aplikasi belanja online di atas meja",
    caption: "Pelanggan terbiasa memantau pesanan dari ponsel; informasi status yang jelas menghemat banyak pertanyaan ke tim Anda.",
  },
  { type: "h2", text: "Retur, penukaran, dan klaim" },
  { type: "p", text: "Cepat atau lambat, setiap toko online menghadapi retur. Barang tidak sesuai, ukuran salah, rusak saat perjalanan, atau pelanggan berubah pikiran. Cara Anda menangani momen ini sering lebih menentukan kepercayaan pelanggan daripada transaksi yang mulus. Pelanggan yang masalahnya diselesaikan dengan mudah sering kali justru menjadi pelanggan setia." },
  { type: "p", text: "Rancang kebijakan retur yang jelas dan tertulis. Kebijakan itu menjawab beberapa pertanyaan: dalam berapa hari retur diterima, kondisi barang seperti apa yang bisa dikembalikan, siapa yang menanggung ongkir retur, dan bagaimana pengembalian dana atau penukaran dilakukan. Tampilkan kebijakan ini di tempat yang mudah ditemukan, bukan disembunyikan di halaman paling bawah. Kebijakan yang transparan justru meningkatkan keberanian pelanggan untuk membeli." },
  { type: "p", text: "Proses internalnya juga perlu rapi. Catat alasan setiap retur, periksa kondisi barang saat tiba, dan putuskan apakah barang bisa dijual kembali, diperbaiki, atau dimusnahkan. Perbarui stok sesuai keputusan itu. Data alasan retur sangat berharga: jika banyak retur karena ukuran, mungkin panduan ukuran perlu diperbaiki; jika banyak karena rusak, mungkin kemasan atau kurir perlu diganti." },
  { type: "h3", text: "Menangani paket hilang dan rusak" },
  { type: "p", text: "Siapkan alur klaim ke kurir sebelum masalah terjadi. Ketahui batas waktu pengajuan klaim, dokumen yang dibutuhkan, dan apakah asuransi pengiriman layak diambil untuk barang bernilai tinggi. Foto kondisi barang saat dikemas dan bukti serah terima ke kurir akan sangat membantu. Di sisi pelanggan, jangan menunggu klaim selesai untuk mengganti barang pada kasus yang jelas; kecepatan Anda merespons lebih penting bagi pelanggan daripada urusan administrasi di belakang layar." },
  { type: "h2", text: "Mengukur kinerja logistik" },
  { type: "p", text: "Anda tidak bisa memperbaiki yang tidak diukur. Beberapa indikator sederhana sudah cukup untuk memberi gambaran sehat tidaknya logistik toko Anda. Waktu proses internal mengukur selisih antara pesanan dibayar dan paket diserahkan ke kurir. Waktu tiba mengukur lama perjalanan dari serah terima hingga diterima pelanggan. Tingkat barang rusak atau hilang menunjukkan kualitas pengemasan dan kurir. Jumlah pertanyaan soal status paket menunjukkan seberapa baik komunikasi Anda. Tingkat retur dan alasannya menunjukkan kecocokan produk dan deskripsi." },
  { type: "p", text: "Tinjau angka-angka ini secara rutin, misalnya sebulan sekali, dan bandingkan per kurir serta per wilayah. Pola yang muncul akan memberi petunjuk tindakan: mengganti kurir di suatu wilayah, menambah bahan pengemas, atau mempercepat proses di gudang. Fokus pada satu perbaikan dalam satu waktu agar efeknya jelas terlihat." },
  { type: "h3", text: "Peran sistem dalam menjaga data tetap rapi" },
  { type: "p", text: "Jika pesanan, stok, resi, dan retur tercatat di tempat berbeda, menyusun laporan di atas menjadi pekerjaan manual yang melelahkan. Sistem toko yang terhubung dengan inventori dan kurir menyatukan semua data itu dalam satu alur. Anda bisa melihat pesanan yang menunggu terlalu lama, paket yang belum diperbarui statusnya, dan wilayah dengan keterlambatan berulang tanpa membuka banyak berkas." },
  { type: "h2", text: "Langkah praktis memperbaiki logistik bulan ini" },
  { type: "p", text: "Anda tidak perlu merombak semuanya sekaligus. Berikut urutan perbaikan yang realistis untuk toko yang baru mulai merapikan logistik." },
  {
    type: "ol",
    items: [
      "Petakan alur pengiriman toko Anda dari pesanan masuk sampai paket diterima, lalu tandai tahap yang paling sering bermasalah",
      "Lihat sebaran alamat pelanggan dan uji dua atau tiga kurir pada rute yang sama dengan jumlah paket kecil",
      "Tetapkan ukuran kemasan standar dan tulis prosedur pengemasan singkat untuk tiap jenis produk",
      "Kirim nomor resi dan tautan pelacakan secara otomatis kepada pelanggan begitu paket berangkat",
      "Tulis kebijakan retur yang jelas dan tampilkan di halaman yang mudah dilihat",
      "Catat waktu proses, waktu tiba, kerusakan, dan keluhan, lalu tinjau setiap bulan",
    ],
  },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Pengiriman bukan beban tambahan di ujung proses penjualan; ia adalah bagian dari janji yang Anda buat kepada pelanggan. Toko yang mengelola pengiriman dengan baik mendapat keuntungan ganda: pelanggan lebih puas dan biaya tersembunyi, mulai dari klaim, kiriman ulang, hingga waktu menjawab pertanyaan, menyusut. Mulailah dari yang paling sederhana, yaitu memahami alur Anda, memilih kurir yang tepat, mengemas dengan standar yang konsisten, dan memberi kabar proaktif. Setelah dasar itu kokoh, otomatisasi dan integrasi sistem akan melipatgandakan hasilnya." },
  { type: "p", text: "Jika toko Anda sudah tumbuh dan pengelolaan pesanan, stok, serta pengiriman mulai terasa berantakan, mungkin sudah saatnya memiliki sistem yang menyatukan semuanya." },
  {
    type: "cta",
    title: "Ingin pengiriman toko online yang rapi dan terhubung?",
    text: "Tim AG·SORA membangun toko online dan sistem operasional yang terintegrasi dengan stok, kurir, dan pembayaran Anda. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
