import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Media sosial telah menjadi tempat orang menemukan barang, bertanya, membandingkan, bahkan membeli. Penjual kecil memajang foto di akun mereka dan menerima pesanan lewat pesan langsung, sedangkan penjual yang lebih besar menggelar siaran langsung untuk memperagakan produk dan menjawab pertanyaan secara real-time. Semua ini membuka pintu penjualan yang dulu hanya bisa dicapai dengan toko fisik atau iklan mahal." },
  { type: "p", text: "Namun penjualan lewat media sosial membawa masalah yang tidak terlihat di awal. Pesanan datang dalam bentuk pesan yang berantakan, stok tidak sinkron dengan toko lain, data pelanggan tersebar di banyak aplikasi, dan satu kali siaran langsung yang ramai bisa membuat tim kewalahan. Banyak penjual akhirnya sibuk membalas pesan tetapi tidak tahu berapa penjualan sebenarnya, siapa pelanggan setia, dan barang apa yang sebenarnya menguntungkan." },
  { type: "p", text: "Artikel ini membahas cara menjual lewat media sosial dan siaran langsung dengan cara yang bisa tumbuh. Kami membahas peran tiap saluran, menghubungkannya dengan toko sendiri, persiapan siaran langsung, pengelolaan pesanan dan stok, pembayaran, pelayanan pelanggan, pengukuran, dan risiko yang perlu dijaga. Kami tidak memakai angka rekaan tentang tingkat konversi; yang kami tawarkan adalah prinsip dan daftar periksa yang bisa diterapkan pada bisnis berbagai ukuran." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Media sosial adalah tempat menarik perhatian dan membangun percakapan; toko dan sistem Anda sendiri adalah tempat mencatat dan mengelola penjualan",
      "Arahkan pesanan dari semua saluran ke satu alur pencatatan agar stok, pembayaran, dan pengiriman tidak terpecah",
      "Siapkan siaran langsung seperti acara: produk, stok, harga, alur pesan, dan tim pendukung",
      "Jelaskan cara membayar dan konfirmasi pesanan dengan tegas untuk mengurangi pesanan fiktif dan salah paham",
      "Kumpulkan data pelanggan dengan izin yang jelas dan ukur hasil per saluran dengan jujur",
    ],
  },
  { type: "h2", text: "Peran media sosial dalam perjalanan pelanggan" },
  { type: "p", text: "Pelanggan jarang membeli pada kontak pertama. Mereka melihat produk di umpan, membuka profil, membaca komentar, bertanya lewat pesan, membandingkan dengan penjual lain, lalu memutuskan. Media sosial unggul di tahap awal: menarik perhatian, memperlihatkan produk dalam konteks nyata, dan membangun kedekatan lewat percakapan. Kedekatan itu penting karena banyak pembeli lebih percaya pada penjual yang terlihat nyata dan responsif." },
  { type: "p", text: "Media sosial lemah di tahap pencatatan. Platform dirancang untuk percakapan dan hiburan, bukan untuk menghitung stok, melacak pesanan, atau menghasilkan laporan keuangan. Penjual yang mengandalkan pesan langsung sebagai satu-satunya sistem akhirnya menyimpan pesanan di kepala atau di tangkapan layar, dan itu tidak bisa tumbuh." },
  { type: "p", text: "Pandangan yang sehat adalah memisahkan fungsi. Media sosial berfungsi sebagai etalase dan ruang percakapan. Toko sendiri, baik berupa website, aplikasi, atau sistem pemesanan sederhana, berfungsi sebagai tempat pesanan dicatat dan diproses. Tugas Anda adalah membuat jembatan yang mulus antara keduanya sehingga calon pembeli berpindah dari tertarik menjadi memesan tanpa hambatan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7",
    alt: "Ikon aplikasi media sosial dan desain dalam bentuk kubus tiga dimensi di latar gelap",
    caption: "Media sosial menarik perhatian dan percakapan; pencatatan penjualan tetap perlu rumah yang rapi.",
  },
  { type: "h2", text: "Menghubungkan media sosial dengan toko Anda sendiri" },
  { type: "p", text: "Mengandalkan satu platform untuk seluruh bisnis adalah risiko. Algoritma berubah, akun bisa dibatasi, dan jangkauan bisa turun tanpa peringatan. Toko sendiri memberi Anda kendali atas data pelanggan, tampilan, dan alur pembelian. Karena itu, anggap media sosial sebagai pintu masuk, bukan satu-satunya rumah." },
  { type: "p", text: "Beberapa cara menghubungkan keduanya. Letakkan tautan ke toko atau katalog di profil dan dalam setiap unggahan yang relevan. Gunakan tautan khusus per kampanye agar Anda tahu unggahan mana yang menghasilkan kunjungan. Sediakan halaman pesan sederhana yang menerima nomor pesanan atau kode produk agar pembeli yang sudah tertarik bisa memesan tanpa menjelaskan ulang. Bila memakai fitur belanja bawaan platform, tetap catat pesanannya di sistem Anda." },
  { type: "ul", items: [
    "Satu katalog produk yang dipakai di toko, di media sosial, dan di siaran langsung agar nama, harga, dan kode barang seragam",
    "Formulir pemesanan atau keranjang yang mencatat pesanan langsung ke sistem, bukan ke pesan pribadi",
    "Tautan terlacak untuk tiap kampanye dan tiap saluran",
    "Alur konfirmasi otomatis yang mengirim rincian pesanan dan instruksi pembayaran",
    "Pencatatan sumber pesanan agar laporan bisa menunjukkan saluran yang paling efektif",
  ] },
  { type: "p", text: "Jika toko sendiri belum ada, mulailah sederhana. Katalog yang rapi dan formulir pemesanan sudah menghilangkan sebagian besar kekacauan pesan langsung. Seiring pertumbuhan, barulah pertimbangkan toko online penuh yang terhubung dengan stok, pembayaran, dan pengiriman." },
  { type: "h2", text: "Satu alur untuk semua pesanan" },
  { type: "p", text: "Penjual yang berjualan di toko fisik, website, media sosial, dan marketplace sekaligus sering memiliki empat pencatatan berbeda. Stok yang terjual di satu tempat tidak berkurang di tempat lain, sehingga barang terakhir bisa terjual dua kali dan pelanggan kecewa. Solusinya adalah satu alur pencatatan pesanan yang menjadi tujuan semua saluran." },
  { type: "p", text: "Dalam praktik, artinya setiap pesanan, dari mana pun asalnya, masuk ke daftar pesanan yang sama dengan status yang sama: baru, menunggu pembayaran, dibayar, dikemas, dikirim, dan selesai. Stok berkurang dari satu sumber yang sama. Bila Anda memakai sistem kasir atau ERP, hubungkan pesanan dari media sosial ke sistem itu. Jika belum, setidaknya gunakan satu lembar kerja bersama yang diisi disiplin, dengan kode barang yang seragam." },
  { type: "p", text: "Tetapkan siapa yang boleh memasukkan pesanan dan bagaimana. Pesanan yang dimasukkan manual dari pesan langsung rawan salah ketik pada alamat, jumlah, atau varian. Lebih baik pelanggan mengisi sendiri formulir yang menyimpan datanya langsung, sehingga tim hanya memverifikasi, bukan mengetik ulang." },
  { type: "h2", text: "Persiapan siaran langsung" },
  { type: "p", text: "Siaran langsung menjual sambil menghibur. Penonton melihat produk dipakai, mengajukan pertanyaan, dan merasakan urgensi karena stok terbatas atau harga khusus selama siaran. Karena semua terjadi serentak dan cepat, persiapannya menentukan hasilnya. Siaran yang kacau karena stok salah, harga tidak jelas, atau pesanan menumpuk tanpa penanganan bisa merusak reputasi dalam satu malam." },
  { type: "ol", items: [
    "Tentukan tujuan siaran: memperkenalkan produk baru, menghabiskan stok tertentu, atau menjawab pertanyaan pelanggan",
    "Pilih dan uji produk yang akan dibahas, pastikan stok dan harga sudah final sebelum siaran dimulai",
    "Siapkan daftar produk berisi kode, harga, varian, dan poin penting untuk disampaikan",
    "Tentukan alur pemesanan yang sederhana dan sampaikan berulang selama siaran",
    "Tunjuk pembawa acara, orang yang memantau komentar dan pesanan, dan orang yang memeriksa stok",
    "Uji sinyal internet, pencahayaan, suara, dan perangkat cadangan sebelum tayang",
    "Siapkan pesan otomatis untuk menyambut pesanan dan menjelaskan langkah berikutnya",
  ] },
  { type: "p", text: "Pembagian peran sangat membantu. Pembawa acara fokus berbicara dan memperagakan, sementara rekan lain membaca komentar, menjawab pertanyaan teknis, mencatat pesanan, dan memperbarui stok. Satu orang yang melakukan semuanya hampir pasti akan kewalahan ketika penonton ramai." },
  { type: "p", text: "Tentukan batas kuota pesanan per produk berdasarkan stok nyata, dan segera umumkan ketika stok habis. Menjual melebihi stok demi terlihat laku adalah kesalahan mahal: pelanggan yang membayar lalu dibatalkan akan kecewa lebih dalam daripada yang tidak sempat memesan." },
  { type: "h3", text: "Setelah siaran selesai" },
  { type: "p", text: "Pekerjaan sesungguhnya sering dimulai setelah siaran berakhir. Rekapitulasi semua pesanan, cocokkan dengan stok, kirim konfirmasi dan instruksi pembayaran, lalu jadwalkan pengemasan. Catat apa yang berjalan baik dan apa yang kacau agar siaran berikutnya lebih mulus. Simpan rekaman siaran bila perlu, karena sering menjadi bahan konten dan bukti saat ada sengketa tentang apa yang dijanjikan." },
  { type: "h2", text: "Mengelola stok dan harga di banyak saluran" },
  { type: "p", text: "Stok adalah sumber masalah terbesar penjualan multisaluran. Bila stok dihitung terpisah di tiap saluran, selisih tak terhindarkan. Pilih satu sumber kebenaran stok dan perbarui dari sana. Untuk barang yang sangat laris, pertimbangkan menyisihkan sebagian stok untuk tiap saluran atau menambahkan penyangga agar tidak terjual berlebih." },
  { type: "p", text: "Harga juga perlu konsisten. Harga khusus siaran langsung wajar, tetapi harus jelas kapan berlaku dan kapan berakhir. Pelanggan yang menemukan harga lebih murah di saluran lain sehari kemudian akan merasa dirugikan. Tuliskan aturan harga per saluran dan pastikan tim menyampaikannya dengan sama." },
  { type: "callout", title: "Satu stok, banyak etalase", text: "Etalase boleh banyak, tetapi stok dan catatan pesanan sebaiknya hanya satu. Begitu stok dihitung di lebih dari satu tempat, selisih hanya soal waktu." },
  { type: "h2", text: "Pembayaran dan konfirmasi pesanan" },
  { type: "p", text: "Pesanan lewat pesan atau siaran sering terhenti pada tahap pembayaran: pembeli bilang mau, tetapi tidak kunjung membayar, atau memesan lalu menghilang. Cara mengurangi masalah ini adalah membuat langkah pembayaran sejelas dan semudah mungkin, dengan batas waktu yang disampaikan di awal. Tautan pembayaran yang dikirim otomatis dan memuat nominal pasti jauh lebih baik daripada instruksi manual yang rawan salah." },
  { type: "p", text: "Tawarkan metode yang umum dipakai pelanggan Anda, seperti transfer bank, dompet digital, atau kode QR. Pembayaran yang terhubung ke sistem membuat status pesanan berubah otomatis begitu dana masuk, sehingga tim tidak perlu memeriksa mutasi rekening satu per satu. Hindari menerima bukti pembayaran hanya lewat tangkapan layar tanpa verifikasi, karena bukti palsu bukan hal yang mustahil." },
  { type: "p", text: "Konfirmasi pesanan sebaiknya memuat rincian barang, jumlah, harga, ongkos kirim, alamat, perkiraan waktu proses, dan kebijakan pengembalian. Rincian tertulis mencegah salah paham dan menjadi rujukan bila terjadi perbedaan. Untuk pelanggan yang meminta barang dikirim ke tempat yang tidak biasa atau bernilai tinggi, lakukan konfirmasi tambahan sebelum mengirim." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c",
    alt: "Ponsel pintar menampilkan layar utama dengan berbagai ikon aplikasi komunikasi",
    caption: "Pesan masuk dari banyak aplikasi; tanpa satu alur pencatatan, pesanan mudah tercecer.",
  },
  { type: "h2", text: "Layanan pelanggan lewat pesan" },
  { type: "p", text: "Pelanggan media sosial terbiasa dengan balasan cepat. Menunda berjam-jam sering berarti kehilangan pembeli yang sudah beralih ke penjual lain. Namun kecepatan tidak boleh mengorbankan ketepatan. Siapkan jawaban baku untuk pertanyaan yang sering muncul, seperti ketersediaan, ukuran, ongkos kirim, dan cara membayar, lalu biarkan petugas menyesuaikan dengan situasi." },
  { type: "p", text: "Kumpulkan percakapan pelanggan di satu kotak masuk bersama bila memungkinkan, sehingga beberapa petugas bisa melayani tanpa saling menimpa dan riwayat percakapan tidak hilang bila petugas berganti. Beri label pada percakapan menurut status, misalnya bertanya, siap memesan, menunggu pembayaran, atau butuh tindak lanjut. Dengan begitu tidak ada calon pembeli yang terlupakan." },
  { type: "p", text: "Tetapkan jam layanan dan sampaikan secara jujur. Balasan otomatis yang menyebut jam kerja dan perkiraan waktu balasan lebih baik daripada diam. Untuk keluhan, tanggapi dengan tenang dan arahkan ke alur penyelesaian yang jelas. Percakapan keluhan yang bisa dilihat publik di kolom komentar sebaiknya dipindahkan ke pesan pribadi setelah ditanggapi singkat dan sopan." },
  { type: "h2", text: "Mengelola data pelanggan dengan bertanggung jawab" },
  { type: "p", text: "Penjualan lewat media sosial menghasilkan data pelanggan: nama, nomor kontak, alamat, dan riwayat pembelian. Data ini berharga, tetapi juga membawa tanggung jawab. Kumpulkan hanya yang diperlukan untuk memproses pesanan, beri tahu tujuannya, dan jangan menggunakannya untuk hal lain tanpa izin. Simpan di tempat yang aman, bukan di grup percakapan yang diikuti banyak orang atau di perangkat pribadi karyawan tanpa kendali." },
  { type: "p", text: "Jangan menambahkan pelanggan ke grup promosi tanpa persetujuan, dan sediakan cara berhenti menerima pesan. Selain menghormati pelanggan, praktik ini mengurangi risiko akun dilaporkan dan dibatasi. Periksa juga ketentuan perlindungan data pribadi yang berlaku saat ini, karena aturannya dapat berubah dan berlaku untuk penjual berskala berapa pun." },
  { type: "h2", text: "Mengukur hasil per saluran" },
  { type: "p", text: "Sulit memperbaiki yang tidak diukur. Catat sumber setiap pesanan, baik dari unggahan, siaran langsung, iklan, atau rujukan, lalu bandingkan hasil antarsaluran. Lihat tidak hanya jumlah penjualan, tetapi juga nilai rata-rata pesanan, tingkat pembatalan, tingkat retur, dan apakah pelanggan membeli lagi." },
  { type: "ul", items: [
    "Jumlah pesanan dan nilai penjualan per saluran dan per kampanye",
    "Proporsi pesanan yang dibayar dibandingkan yang dibatalkan atau tidak dibayar",
    "Waktu rata-rata dari pesan pertama sampai pembayaran",
    "Produk yang paling sering ditanyakan tetapi jarang dibeli",
    "Tingkat pelanggan yang membeli ulang dari tiap saluran",
    "Biaya yang dikeluarkan, termasuk iklan, waktu tim, dan potongan, dibandingkan dengan margin",
  ] },
  { type: "p", text: "Hati-hati menafsirkan angka. Jangkauan dan tayangan tinggi tidak sama dengan penjualan. Siaran yang ramai penonton tetapi sedikit pesanan mungkin menandakan produk, harga, atau alur pemesanan yang bermasalah. Bandingkan juga dengan biaya sebenarnya, termasuk jam kerja tim, karena saluran yang tampak laris bisa saja tidak menguntungkan setelah semua biaya dihitung." },
  { type: "h2", text: "Risiko yang perlu dijaga" },
  { type: "p", text: "Ketergantungan pada satu platform adalah risiko utama. Karena itu, bangun aset yang Anda miliki sendiri: daftar kontak yang diizinkan, toko atau katalog sendiri, dan merek yang dikenal orang di luar platform. Dengan begitu, perubahan aturan atau pembatasan akun tidak melumpuhkan bisnis." },
  { type: "ul", items: [
    "Ikuti ketentuan layanan dan kebijakan iklan platform agar akun tidak dibatasi",
    "Waspadai penipuan yang mengatasnamakan toko Anda dan beri tahu pelanggan jalur resmi yang sah",
    "Jangan menjanjikan khasiat atau klaim yang tidak bisa dibuktikan, terutama pada produk yang diatur ketentuan khusus",
    "Lindungi akun dengan autentikasi berlapis dan batasi siapa saja yang memiliki akses",
    "Cadangkan daftar pelanggan dan riwayat pesanan di sistem yang Anda kendalikan",
    "Pastikan ulasan, testimoni, dan konten influencer jujur dan sesuai ketentuan yang berlaku",
  ] },
  { type: "p", text: "Bila Anda bekerja sama dengan pembuat konten atau influencer, tuangkan kesepakatan secara tertulis: apa yang dipromosikan, bagaimana imbalannya, dan apa yang boleh dan tidak boleh disampaikan. Periksa aturan keterbukaan promosi yang berlaku saat ini agar kemitraan tidak berubah menjadi masalah hukum atau reputasi." },
  { type: "h2", text: "Kapan sebaiknya membangun sistem sendiri" },
  { type: "p", text: "Pada tahap awal, alat bawaan platform dan lembar kerja sederhana sudah cukup. Namun ada tanda-tanda bahwa Anda perlu sistem yang lebih serius: pesanan harian sudah sulit dilacak, stok sering selisih, tim menghabiskan banyak waktu mengetik ulang pesanan, atau Anda tidak bisa menjawab pertanyaan sederhana seperti produk apa yang paling untung bulan ini." },
  { type: "p", text: "Pada titik itu, toko online sendiri yang terhubung dengan stok, pembayaran, dan pengiriman, serta mungkin dengan sistem kasir dan ERP, memberi fondasi yang tumbuh bersama bisnis. Media sosial tetap menjadi sumber perhatian dan percakapan, tetapi seluruh pencatatan terjadi di sistem yang Anda kendalikan. Kesalahan umum adalah membangun terlalu dini yang terlalu rumit; mulailah dari kebutuhan nyata dan kembangkan bertahap." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Mengandalkan pesan langsung sebagai satu-satunya pencatatan pesanan",
    "Menjual melebihi stok demi terlihat laku saat siaran langsung",
    "Menerima bukti pembayaran lewat tangkapan layar tanpa verifikasi",
    "Menyimpan data pelanggan di grup percakapan atau perangkat pribadi tanpa kendali",
    "Hanya mengukur jangkauan dan tayangan, bukan pesanan yang dibayar dan margin",
    "Menggantungkan seluruh bisnis pada satu akun tanpa aset milik sendiri",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Buat satu katalog produk dengan kode barang dan harga yang seragam untuk semua saluran",
    "Siapkan formulir atau keranjang yang mencatat pesanan langsung ke satu daftar bersama",
    "Tentukan alur pembayaran dengan batas waktu dan tautan pembayaran yang jelas",
    "Susun daftar periksa siaran langsung: produk, stok, harga, peran tim, dan alur pesanan",
    "Mulai mencatat sumber setiap pesanan dan tinjau hasilnya tiap minggu",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Media sosial dan siaran langsung adalah cara ampuh menjangkau dan meyakinkan pelanggan, tetapi nilai sebenarnya baru terasa ketika penjualan yang dihasilkan tercatat rapi, stok terkendali, dan pelanggan terlayani dengan baik. Satu alur pesanan, satu sumber stok, pembayaran yang jelas, dan pengukuran yang jujur mengubah keramaian menjadi bisnis yang bisa tumbuh." },
  { type: "p", text: "Mulailah dari yang sederhana, rapikan pencatatan sebelum menambah keramaian, dan bangun aset yang Anda miliki sendiri. Dengan begitu perhatian yang Anda peroleh di media sosial benar-benar berubah menjadi penjualan yang berkelanjutan." },
  {
    type: "cta",
    title: "Ingin penjualan dari media sosial tercatat rapi dan terhubung ke stok dan pembayaran?",
    text: "Tim AG·SORA membangun toko online dan sistem pemesanan yang menyatukan pesanan dari media sosial, siaran langsung, dan toko fisik dalam satu alur. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
