import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Banyak bisnis menyusun anggaran sekali setahun, biasanya pada akhir tahun, dengan tabel hitung dan banyak tebakan. Setelah disetujui, dokumen itu disimpan dan hanya dibuka ketika ada yang bertanya mengapa biaya melebihi rencana. Pada pertengahan tahun, kenyataan sudah jauh berbeda dari asumsi, dan anggaran kehilangan fungsinya sebagai pegangan." },
  { type: "p", text: "Anggaran dan peramalan yang baik bukan upaya menebak masa depan dengan tepat. Fungsinya adalah memberi arah, membuat pilihan menjadi eksplisit, dan memungkinkan pemilik melihat lebih awal ketika keadaan menyimpang dari rencana. Data yang tersimpan dalam ERP adalah bahan baku terbaik untuk tujuan itu, karena merekam apa yang benar-benar terjadi." },
  { type: "p", text: "Artikel ini membahas cara menyusun anggaran dan peramalan yang praktis untuk bisnis kecil dan menengah dengan memanfaatkan data operasional: bedanya anggaran dan peramalan, cara memulai dari data historis, menentukan asumsi, memantau selisih, dan memperbarui rencana secara berkala. Kami tidak memakai angka rekaan; fokusnya adalah kerangka berpikir yang bisa Anda terapkan." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Anggaran adalah rencana dan target; peramalan adalah perkiraan terbaru tentang apa yang akan terjadi",
      "Mulailah dari data historis yang rapi, lalu tambahkan asumsi yang eksplisit dan masuk akal",
      "Pantau selisih antara rencana dan kenyataan secara rutin, bukan hanya di akhir tahun",
      "Perbarui peramalan secara berkala agar tetap mencerminkan keadaan",
      "Buatlah sederhana: model yang dipahami dan dipakai lebih berharga daripada model yang rumit",
    ],
  },
  { type: "h2", text: "Anggaran, peramalan, dan perbedaannya" },
  { type: "p", text: "Anggaran adalah pernyataan tentang apa yang ingin dicapai dan sumber daya yang disiapkan untuk itu: target penjualan, batas biaya, dan investasi yang direncanakan. Ia bersifat sebagai komitmen dan pegangan, serta biasanya ditetapkan di awal periode dan tidak sering diubah." },
  { type: "p", text: "Peramalan adalah perkiraan terkini tentang di mana bisnis akan berakhir pada akhir periode, berdasarkan apa yang sudah terjadi dan apa yang diketahui sekarang. Peramalan diperbarui secara berkala. Bila anggaran menjawab apa yang kami rencanakan, peramalan menjawab apa yang tampaknya akan terjadi." },
  { type: "p", text: "Membedakan keduanya penting. Anggaran yang terus diubah mengikuti kenyataan kehilangan fungsinya sebagai tolok ukur, sedangkan peramalan yang membeku pada angka awal tidak menolong pengambilan keputusan. Memakai keduanya berdampingan memungkinkan Anda melihat selisih terhadap rencana sekaligus apa yang mungkin terjadi." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1543286386-713bdd548da4",
    alt: "Kertas berisi grafik garis naik di samping penggaris dan pena di meja kayu",
    caption: "Anggaran memberi arah; peramalan yang diperbarui memberi tahu seberapa jauh bisnis menyimpang dari arah itu.",
  },
  { type: "h2", text: "Mengapa data ERP menjadi fondasi" },
  { type: "p", text: "Anggaran yang disusun dari ingatan atau intuisi cenderung terlalu optimistis atau terlalu konservatif. Data penjualan, biaya, stok, dan arus kas yang tercatat dalam ERP memberi pegangan: berapa penjualan per bulan, produk apa yang naik atau turun, biaya apa yang tetap dan apa yang bervariasi, dan bagaimana pola musimannya." },
  { type: "p", text: "Keunggulan lain adalah konsistensi. Ketika anggaran dan realisasi memakai struktur akun dan kategori yang sama, perbandingan menjadi langsung. Tanpa struktur yang sama, setiap perbandingan memerlukan penerjemahan manual yang memakan waktu dan rawan salah." },
  { type: "p", text: "Data harus terpercaya agar bermanfaat. Pembukuan yang tertinggal, kategori yang berubah-ubah, atau stok yang tidak akurat akan membuat anggaran dibangun di atas pasir. Merapikan pencatatan sering menjadi langkah pertama yang paling berharga dari seluruh upaya perencanaan." },
  { type: "h2", text: "Memulai dari data historis" },
  { type: "p", text: "Ambil data realisasi dua sampai tiga tahun terakhir bila ada, atau selama yang tersedia, dan lihat polanya. Perhatikan tren, yaitu arah umum naik atau turun, serta musiman, yaitu bulan-bulan yang konsisten ramai atau sepi. Pisahkan peristiwa sekali jalan seperti proyek besar atau pembelian aset agar tidak menyesatkan." },
  { type: "p", text: "Pecah penjualan menurut dimensi yang bermakna bagi bisnis Anda: produk, kanal, wilayah, atau segmen pelanggan. Pergerakan total sering menyembunyikan cerita yang berbeda di tiap bagian, misalnya satu kanal tumbuh sedangkan yang lain menurun." },
  { type: "p", text: "Pisahkan biaya menjadi biaya tetap, yang relatif tidak berubah dengan volume, dan biaya variabel, yang bergerak sesuai penjualan. Pemisahan ini sangat membantu ketika menjalankan skenario karena Anda bisa memperkirakan bagaimana biaya bereaksi bila penjualan naik atau turun." },
  { type: "h2", text: "Menetapkan asumsi yang eksplisit" },
  { type: "p", text: "Anggaran pada dasarnya adalah data historis ditambah asumsi tentang masa depan. Tuliskan setiap asumsi dengan jelas: pertumbuhan penjualan yang diharapkan dan sumbernya, perubahan harga, jumlah pelanggan baru, biaya tambahan karena karyawan baru, atau kenaikan harga dari pemasok." },
  { type: "p", text: "Asumsi yang tertulis dapat diperiksa dan diperdebatkan. Ketika kenyataan menyimpang, Anda bisa menunjuk asumsi mana yang meleset dan belajar darinya. Asumsi yang hanya ada di kepala membuat selisih terasa sebagai kejutan tanpa penjelasan." },
  { type: "p", text: "Bedakan asumsi yang berada dalam kendali Anda, seperti jadwal perekrutan dan anggaran pemasaran, dari yang di luar kendali, seperti nilai tukar dan harga bahan baku. Untuk yang di luar kendali, bersiaplah dengan rentang, bukan satu angka tunggal." },
  { type: "callout", title: "Rentang lebih jujur daripada satu angka", text: "Masa depan tidak bisa dipastikan. Menyusun skenario sederhana, misalnya skenario dasar, baik, dan berat, membantu Anda menyiapkan tindakan untuk tiap keadaan, bukan terkejut oleh yang tidak diharapkan." },
  { type: "h2", text: "Skenario sederhana yang berguna" },
  { type: "p", text: "Tidak perlu model rumit untuk berpikir dalam skenario. Cukup tentukan beberapa pengungkit utama, misalnya volume penjualan, harga rata-rata, dan biaya bahan, lalu lihat bagaimana laba dan kas berubah bila masing-masing bergerak ke atas atau ke bawah dalam batas yang masuk akal." },
  { type: "p", text: "Fokus pada pertanyaan yang membantu keputusan. Bila penjualan turun sebagian dalam tiga bulan, kapan kas mulai menipis? Bila pemasok menaikkan harga, berapa yang bisa diteruskan kepada pelanggan? Bila kami menambah satu karyawan, berapa penjualan tambahan yang diperlukan agar impas?" },
  { type: "p", text: "Siapkan juga rencana tindakan untuk tiap skenario. Skenario berat bukan untuk menakut-nakuti, melainkan untuk menentukan lebih awal apa yang akan ditunda atau dihemat dan pada tanda apa keputusan itu dijalankan. Keputusan yang dipikirkan dalam keadaan tenang biasanya lebih baik daripada yang diambil saat panik." },
  { type: "h2", text: "Anggaran per bagian dan tanggung jawab" },
  { type: "p", text: "Anggaran yang hanya dimiliki bagian keuangan jarang berhasil. Libatkan pemimpin tiap bagian dalam menyusun anggaran untuk wilayah mereka, karena mereka yang paling paham kebutuhan dan batasnya. Anggaran yang mereka bantu susun terasa sebagai komitmen mereka sendiri, bukan beban dari atas." },
  { type: "p", text: "Tetapkan pemilik untuk setiap pos yang signifikan. Pemilik bertanggung jawab menjelaskan selisih dan mengusulkan tindakan. Dengan begitu, rapat peninjauan berfokus pada tindakan, bukan pada mencari siapa yang salah." },
  { type: "p", text: "Sediakan ruang untuk pengecualian yang disetujui. Peluang atau kebutuhan mendadak akan muncul, dan anggaran yang terlalu kaku mendorong orang mencari jalan pintas. Tetapkan siapa yang boleh menyetujui pengeluaran di luar anggaran dan batas nilainya." },
  { type: "h2", text: "Memantau selisih secara rutin" },
  { type: "p", text: "Bandingkan realisasi dengan anggaran setiap bulan, tidak menunggu akhir tahun. Selisih kecil yang ditemukan lebih awal masih mudah dikoreksi, sedangkan selisih yang baru diketahui di akhir tahun tinggal menjadi penyesalan." },
  { type: "p", text: "Jangan hanya melihat angka selisihnya; tanyakan penyebabnya. Selisih penjualan bisa berasal dari volume, harga, atau campuran produk, dan masing-masing membutuhkan tindakan berbeda. Selisih biaya bisa karena harga, jumlah pemakaian, atau waktu pencatatan." },
  { type: "p", text: "Buat laporan ringkas satu halaman yang menyorot hal yang berarti: pos dengan selisih terbesar, tren selama beberapa bulan terakhir, dan perkiraan terbaru akhir tahun. Laporan yang terlalu panjang tidak dibaca, dan keputusan tetap diambil dengan perasaan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3",
    alt: "Laptop menampilkan dashboard berisi grafik dan tabel laporan",
    caption: "Laporan satu halaman yang menyorot selisih terpenting lebih berguna daripada tabel panjang yang tak dibaca.",
  },
  { type: "h2", text: "Memperbarui peramalan secara bergulir" },
  { type: "p", text: "Alih-alih berhenti pada akhir tahun, banyak bisnis memakai peramalan bergulir: setiap bulan, periode yang sudah lewat digantikan realisasi, dan satu periode baru ditambahkan di ujung depan sehingga selalu ada pandangan ke depan untuk beberapa bulan atau beberapa kuartal." },
  { type: "p", text: "Cara ini membuat perencanaan menjadi kegiatan berkelanjutan, bukan peristiwa tahunan yang melelahkan. Anda tidak perlu menyusun ulang dari nol; cukup memperbarui asumsi yang berubah berdasarkan apa yang baru dipelajari." },
  { type: "p", text: "Fokuskan pembaruan pada hal-hal yang paling memengaruhi hasil dan kas, bukan setiap baris rincian. Peramalan yang hampir benar dan diperbarui tepat waktu lebih berguna daripada yang sangat rinci tetapi selalu terlambat." },
  { type: "h2", text: "Kas, bukan hanya laba" },
  { type: "p", text: "Bisnis yang menguntungkan di atas kertas tetap bisa kehabisan kas. Penjualan dengan tempo, pembelian stok di muka, cicilan, dan pajak yang jatuh tempo memengaruhi waktu kas masuk dan keluar. Karena itu, peramalan kas harus menjadi bagian dari perencanaan, bukan sekadar laporan laba rugi." },
  { type: "p", text: "Susun perkiraan kas mingguan atau bulanan untuk beberapa bulan ke depan: kas awal, penerimaan yang diharapkan dari piutang dan penjualan tunai, pengeluaran yang terjadwal, dan kas akhir. Data umur piutang dan utang usaha dari ERP membuat perkiraan ini jauh lebih realistis." },
  { type: "p", text: "Tetapkan batas kas minimum yang nyaman dan tanda peringatan dini. Bila perkiraan menunjukkan kas akan menyentuh batas itu dalam beberapa minggu, Anda punya waktu untuk menagih lebih cepat, menunda pembelian, atau mengatur pendanaan, bukan bereaksi ketika sudah mendesak." },
  { type: "h2", text: "Keputusan investasi dan pertumbuhan" },
  { type: "p", text: "Anggaran membantu menjawab pertanyaan besar: apakah kami mampu menambah karyawan, membuka cabang, atau membeli mesin? Ubah pertanyaan itu menjadi angka yang bisa diuji: berapa biaya di muka, berapa tambahan penjualan atau penghematan yang diperlukan, dan kapan kira-kira balik modal." },
  { type: "p", text: "Uji asumsi yang paling menentukan, bukan semuanya. Bila investasi hanya menguntungkan jika penjualan naik jauh lebih tinggi dari biasanya, itu peringatan. Bila ia masih masuk akal pada skenario yang konservatif, Anda bisa lebih percaya diri." },
  { type: "p", text: "Setelah keputusan dijalankan, pantau hasilnya terhadap asumsi awal. Proses ini tidak hanya mengoreksi investasi yang sedang berjalan, tetapi juga membuat penilaian Anda terhadap usulan berikutnya lebih tajam." },
  { type: "h2", text: "Anggaran untuk bisnis kecil: versi yang ringan" },
  { type: "p", text: "Bisnis kecil tidak memerlukan proses anggaran yang berat. Versi ringan sudah cukup: satu lembar yang memuat target penjualan per bulan, biaya tetap utama, biaya variabel sebagai persentase penjualan, dan perkiraan kas. Perbarui setiap bulan dalam satu jam, dan Anda sudah lebih siap daripada kebanyakan bisnis sejenis." },
  { type: "p", text: "Mulailah dari hal yang paling menekan: kas dan biaya terbesar. Bila sebagian besar biaya adalah gaji, sewa, dan bahan, fokuslah pada tiga hal itu dan jangan terjebak pada rincian kecil yang sedikit dampaknya." },
  { type: "p", text: "Seiring bisnis tumbuh, tambahkan kedalaman secara bertahap: per bagian, per produk, per cabang. Setiap lapisan baru sebaiknya hanya ditambahkan ketika ada keputusan nyata yang memerlukannya." },
  { type: "h2", text: "Peran teknologi: dari tabel hitung ke sistem terpadu" },
  { type: "p", text: "Tabel hitung adalah alat yang bagus untuk memulai, tetapi mulai menyulitkan ketika data dikumpulkan manual dari beberapa sumber, banyak orang mengubah berkas yang sama, dan versi saling bertabrakan. Kesalahan rumus yang tidak terdeteksi adalah risiko yang nyata pada model yang tumbuh besar." },
  { type: "p", text: "Sistem terpadu menarik realisasi langsung dari transaksi, menyimpan anggaran dalam struktur yang sama, dan menyajikan perbandingan otomatis. Waktu yang tadinya habis untuk menyalin dan merapikan data dapat dipakai untuk menganalisis dan berdiskusi." },
  { type: "p", text: "Apa pun alatnya, jaga kendali: siapa yang boleh mengubah anggaran, bagaimana versi dicatat, dan di mana asumsi disimpan. Alat yang canggih tidak menggantikan kebiasaan yang disiplin." },
  { type: "h2", text: "Membangun budaya perencanaan yang sehat" },
  { type: "p", text: "Anggaran sering ditakuti karena dikaitkan dengan pemotongan dan penilaian. Ubah suasananya: jadikan anggaran alat bersama untuk memperjelas prioritas, bukan alat untuk menyalahkan. Tim yang merasa aman menyampaikan kabar buruk lebih awal akan memberi Anda waktu lebih banyak untuk bereaksi." },
  { type: "p", text: "Bagikan gambaran besarnya kepada tim: apa target perusahaan tahun ini, mengapa, dan bagaimana pekerjaan masing-masing berkontribusi. Orang yang memahami tujuan lebih mudah menjaga pengeluaran dan mengusulkan perbaikan yang masuk akal." },
  { type: "p", text: "Rayakan ketika perencanaan menolong keputusan yang baik, termasuk ketika ia membuat Anda menunda sesuatu yang menarik tetapi belum mampu. Disiplin semacam itu membangun ketahanan bisnis dalam jangka panjang." },
  { type: "h2", text: "Menyelaraskan anggaran dengan strategi" },
  { type: "p", text: "Anggaran yang baik adalah strategi yang diterjemahkan menjadi angka. Bila bisnis ingin masuk ke kanal baru, mempertahankan harga, atau memperbaiki margin, keinginan itu harus terlihat dalam alokasi biaya dan target. Anggaran yang hanya mengulang tahun lalu dengan kenaikan sekian persen tidak mencerminkan pilihan apa pun." },
  { type: "p", text: "Gunakan anggaran untuk memaksa pilihan. Bila semua usulan disetujui, sumber daya akan tersebar tipis dan tidak ada yang berhasil. Tanyakan hal yang paling berdampak terhadap tujuan tahun ini, dan berani menunda sisanya sampai ada ruang." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menyusun anggaran sekali setahun lalu menyimpannya tanpa pernah ditinjau",
    "Membangun anggaran di atas data yang tidak rapi atau terlambat dicatat",
    "Menyembunyikan asumsi sehingga selisih tidak bisa dijelaskan",
    "Hanya memperhatikan laba dan melupakan arus kas",
    "Membuat model yang terlalu rumit sehingga tidak ada yang memahami dan memakainya",
    "Menjadikan rapat peninjauan sebagai ajang mencari kesalahan, bukan menentukan tindakan",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Ambil data penjualan dan biaya dua tahun terakhir dan lihat tren serta pola musimannya",
    "Tuliskan lima asumsi terpenting untuk tahun ini dan sumbernya",
    "Susun tiga skenario sederhana untuk penjualan dan lihat dampaknya pada kas",
    "Tetapkan pemilik untuk lima pos biaya terbesar",
    "Jadwalkan peninjauan singkat bulanan dengan laporan satu halaman",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Perencanaan keuangan yang baik tidak menuntut ramalan yang sempurna. Ia menuntut data yang jujur, asumsi yang tertulis, kebiasaan memeriksa kenyataan secara rutin, dan kesediaan menyesuaikan rencana. Dengan ERP yang menyimpan catatan operasional yang rapi, semua itu menjadi jauh lebih mudah." },
  { type: "p", text: "Mulailah dengan sederhana, tinjau setiap bulan, dan perbaiki seiring waktu. Hasilnya adalah bisnis yang lebih siap menghadapi perubahan, dengan pemilik yang memutuskan berdasarkan angka, bukan perasaan." },
  {
    type: "cta",
    title: "Ingin anggaran dan peramalan bisnis berbasis data yang rapi?",
    text: "Tim AG·SORA menerapkan ERP yang menyatukan penjualan, biaya, stok, dan kas, lengkap dengan laporan anggaran versus realisasi yang mudah dibaca. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/erp",
    label: "Konsultasi gratis",
  },
];
