import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Di banyak perusahaan B2B, hubungan dengan pelanggan dan pemasok masih berjalan lewat surel, pesan singkat, telepon, dan lembar kerja yang dikirim bolak-balik. Pelanggan menanyakan status pesanan, pemasok menanyakan jadwal pembayaran, dan sales harus mencari jawabannya satu per satu di berbagai sistem. Setiap pertanyaan sederhana memakan waktu dua pihak, dan pertanyaan yang sama muncul lagi minggu depan." },
  { type: "p", text: "Portal pelanggan dan pemasok menjawab masalah itu dengan memberi mitra bisnis akses terbatas ke informasi yang memang menjadi hak mereka. Pelanggan bisa memesan ulang, melihat riwayat pembelian, mengunduh faktur, dan melacak pengiriman tanpa menelepon. Pemasok bisa melihat pesanan pembelian, mengonfirmasi jadwal, dan mengunggah dokumen tanpa menunggu balasan surel. Hasilnya bukan hanya efisiensi, melainkan juga kesan profesional yang membedakan Anda dari pesaing." },
  { type: "p", text: "Artikel ini membahas cara merencanakan dan membangun portal B2B yang benar-benar dipakai. Kami membahas manfaat, fitur yang layak didahulukan, hubungannya dengan ERP dan CRM, hak akses dan keamanan, pengalaman pengguna, adopsi oleh mitra, dan cara mengukur keberhasilan. Kami tidak memakai angka rekaan tentang penghematan atau peningkatan penjualan; yang kami tawarkan adalah prinsip dan daftar periksa yang bisa diterapkan pada perusahaan berbagai skala." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Portal berguna jika menjawab pertanyaan yang berulang dan memangkas pekerjaan administratif di kedua sisi",
      "Mulai dari beberapa fitur bernilai tinggi, seperti status pesanan, faktur, dan pemesanan ulang, lalu tambah bertahap",
      "Portal sebaiknya membaca data dari ERP dan CRM, bukan menjadi tempat data baru yang harus dirawat terpisah",
      "Hak akses harus ketat: setiap mitra hanya melihat datanya sendiri, dan setiap tindakan tercatat",
      "Adopsi tidak terjadi otomatis; perlu pelatihan, insentif, dan dukungan yang jelas bagi mitra",
    ],
  },
  { type: "h2", text: "Masalah yang diselesaikan portal" },
  { type: "p", text: "Coba hitung berapa banyak pesan dan panggilan yang diterima tim Anda setiap minggu dengan pertanyaan yang serupa: apakah pesanan saya sudah dikirim, bisakah dikirim ulang salinan faktur, kapan pembayaran saya cair, atau berapa sisa stok untuk barang ini. Setiap pertanyaan tampak kecil, tetapi tim penjualan, keuangan, dan layanan pelanggan menghabiskan sebagian besar harinya untuk menjawabnya." },
  { type: "p", text: "Dari sisi mitra, mereka menunggu jawaban dan sering tidak tahu pada siapa harus bertanya. Pelanggan yang butuh kepastian jadwal kirim untuk proyeknya tidak ingin mengejar sales hingga tiga kali. Pemasok yang ingin tahu apakah faktur sudah diterima tidak ingin menelepon bagian keuangan setiap pekan. Portal memberi mereka jawaban kapan pun dibutuhkan, termasuk di luar jam kerja." },
  { type: "p", text: "Ada juga manfaat kualitas data. Ketika mitra memasukkan pesanan atau mengonfirmasi jadwal sendiri, kesalahan salin-tempel dan salah dengar berkurang. Dokumen yang diunggah langsung terkait dengan pesanan yang benar, bukan tersebar di kotak masuk pribadi karyawan yang kemudian pindah divisi." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40",
    alt: "Dua orang berdiskusi sambil menunjuk dokumen dalam pertemuan bisnis",
    caption: "Portal tidak menggantikan hubungan antarpersonel, tetapi membebaskan percakapan dari pertanyaan administratif yang bisa dijawab sistem.",
  },
  { type: "h2", text: "Portal pelanggan dan portal pemasok: apa bedanya" },
  { type: "p", text: "Keduanya sering dibahas bersama karena kerangka teknisnya mirip, tetapi kebutuhannya berbeda. Portal pelanggan berfokus pada kemudahan membeli dan kepercayaan setelah membeli. Portal pemasok berfokus pada koordinasi pasokan dan penyelesaian pembayaran. Memahami perbedaannya membantu menentukan fitur yang layak didahulukan." },
  { type: "h3", text: "Portal pelanggan" },
  { type: "ul", items: [
    "Katalog dengan harga dan ketersediaan khusus untuk pelanggan tersebut sesuai perjanjian",
    "Pemesanan ulang cepat dari riwayat pembelian atau daftar barang favorit",
    "Status pesanan dan pelacakan pengiriman",
    "Faktur, surat jalan, dan bukti pembayaran yang bisa diunduh",
    "Saldo piutang, jatuh tempo, dan riwayat pembayaran",
    "Pengajuan klaim, retur, atau permintaan penawaran",
  ] },
  { type: "h3", text: "Portal pemasok" },
  { type: "ul", items: [
    "Pesanan pembelian yang bisa dikonfirmasi atau diubah jadwalnya oleh pemasok",
    "Penerimaan barang dan status inspeksi",
    "Pengunggahan faktur dan dokumen pendukung, serta status pemrosesannya",
    "Jadwal pembayaran dan riwayat pembayaran",
    "Permintaan penawaran dan pemberitahuan kebutuhan mendatang",
    "Penilaian kinerja dan umpan balik mutu",
  ] },
  { type: "p", text: "Tidak perlu membangun keduanya sekaligus. Pilih sisi yang paling banyak menghabiskan waktu tim Anda dan paling terasa dampaknya, mulailah dari sana, lalu gunakan fondasi yang sama untuk sisi lainnya." },
  { type: "h2", text: "Fitur yang layak didahulukan" },
  { type: "p", text: "Kesalahan umum adalah membuat portal dengan terlalu banyak fitur sejak awal, lalu tidak ada yang memakainya karena membingungkan. Cara yang lebih sehat adalah mengidentifikasi pertanyaan dan tugas yang paling sering muncul, lalu membangun portal untuk menjawabnya. Data dari kotak masuk, catatan layanan, dan masukan tim penjualan adalah sumber yang jauh lebih jujur daripada tebakan." },
  { type: "ol", items: [
    "Daftar pertanyaan dan permintaan mitra selama beberapa bulan terakhir, lalu kelompokkan menurut jenis",
    "Urutkan menurut frekuensi dan waktu yang dihabiskan untuk menjawabnya",
    "Pilih tiga sampai lima yang teratas sebagai fitur versi pertama",
    "Pastikan data yang dibutuhkan tersedia dan akurat di sistem sumber",
    "Luncurkan kepada beberapa mitra yang bersedia, kumpulkan masukan, lalu perluas",
  ] },
  { type: "p", text: "Fitur yang hampir selalu masuk daftar awal adalah status pesanan dan pengiriman, akses faktur dan dokumen, serta pemesanan ulang. Ketiganya menjawab pertanyaan paling umum dan relatif mudah dibangun jika data sudah rapi di sistem dasar. Fitur seperti negosiasi harga, konfigurator produk, atau penilaian pemasok yang rumit sebaiknya menyusul setelah portal terbukti dipakai." },
  { type: "h2", text: "Portal sebagai jendela ke ERP dan CRM" },
  { type: "p", text: "Prinsip terpenting dalam merancang portal adalah ia bukan sistem baru yang berdiri sendiri, melainkan jendela ke sistem yang sudah ada. Data pesanan, stok, faktur, dan pembayaran berada di ERP. Data hubungan, kontak, dan riwayat interaksi berada di CRM. Portal membaca dan, bila perlu, menulis kembali ke sistem tersebut." },
  { type: "p", text: "Jika portal memiliki salinan data sendiri yang harus dirawat terpisah, selisih tak terhindarkan: stok di portal berbeda dari stok di ERP, status pesanan tidak mutakhir, dan faktur yang dilihat pelanggan berbeda dari catatan keuangan. Kepercayaan mitra hilang begitu mereka menemukan satu angka yang salah. Karena itu, rancang aliran data dengan jelas: sumber kebenaran ada di sistem inti, dan portal menampilkan data itu dengan penundaan sekecil mungkin." },
  { type: "ul", items: [
    "Gunakan antarmuka pemrograman yang terdokumentasi untuk membaca dan menulis data dari ERP dan CRM",
    "Tentukan data mana yang boleh diubah mitra, seperti konfirmasi jadwal, dan mana yang hanya bisa dibaca",
    "Perlakukan perubahan dari portal sebagai usulan yang melalui alur persetujuan internal bila menyangkut harga atau jumlah",
    "Catat setiap perubahan beserta pelakunya agar bisa ditelusuri",
    "Rancang penanganan kegagalan: apa yang ditampilkan bila sistem inti sedang tidak dapat dijangkau",
  ] },
  { type: "p", text: "Bila ERP Anda belum memiliki antarmuka yang memadai, itu sinyal bahwa fondasi perlu dibenahi lebih dulu. Membangun portal di atas data yang berantakan hanya membuat kekacauan terlihat oleh pihak luar. Kadang pekerjaan terbesar dalam proyek portal justru merapikan data induk, seperti kode barang, daftar pelanggan, dan struktur harga." },
  { type: "h2", text: "Hak akses dan keamanan" },
  { type: "p", text: "Portal membuka sebagian data internal kepada pihak luar, sehingga keamanannya tidak boleh ditawar. Prinsip utamanya: setiap pengguna hanya melihat data organisasinya sendiri dan hanya melakukan tindakan yang memang diizinkan. Kesalahan paling berbahaya adalah satu pelanggan dapat melihat harga atau pesanan pelanggan lain." },
  { type: "ul", items: [
    "Pisahkan data per organisasi pada tingkat basis data dan aplikasi, bukan hanya pada tampilan",
    "Terapkan peran yang berbeda dalam satu organisasi mitra, misalnya pemesan, pembayar, dan pengamat",
    "Wajibkan autentikasi yang kuat, termasuk verifikasi berlapis untuk tindakan sensitif",
    "Tetapkan kebijakan sandi dan sesi, serta cara aman memulihkan akun",
    "Catat semua tindakan penting dalam jejak audit yang tidak bisa diubah pengguna",
    "Batasi dan awasi unggahan berkas agar tidak menjadi jalan masuk program berbahaya",
    "Lakukan pengujian keamanan sebelum peluncuran dan secara berkala setelahnya",
  ] },
  { type: "p", text: "Siapkan juga proses untuk mengelola akun mitra. Ketika karyawan mitra berhenti bekerja, akunnya harus bisa dinonaktifkan dengan cepat. Berikan administrator di sisi mitra kemampuan mengelola pengguna mereka sendiri dalam batas yang ditetapkan, agar tim Anda tidak menjadi hambatan setiap ada pergantian orang. Data pribadi pengguna tunduk pada ketentuan perlindungan data yang berlaku saat ini, sehingga perlu diperiksa dan dipatuhi." },
  { type: "callout", title: "Portal adalah wajah perusahaan di depan mitra", text: "Satu kebocoran data atau satu angka yang salah dapat merusak kepercayaan yang dibangun bertahun-tahun. Keamanan dan keakuratan data lebih penting daripada fitur tambahan apa pun." },
  { type: "h2", text: "Pengalaman pengguna yang membuat mitra mau memakai" },
  { type: "p", text: "Portal bersaing dengan kebiasaan lama: menelepon atau mengirim pesan. Selama cara lama terasa lebih cepat, mitra akan tetap memakainya. Karena itu, pengalaman pengguna menentukan keberhasilan. Tugas utama harus bisa diselesaikan dalam beberapa langkah, tanpa pelatihan panjang, dan dengan bahasa yang dipahami orang awam, bukan istilah internal perusahaan." },
  { type: "ul", items: [
    "Tampilkan hal terpenting di halaman awal: pesanan berjalan, tagihan jatuh tempo, dan tindakan yang menunggu",
    "Sediakan pencarian dan penyaringan yang cepat untuk pesanan, faktur, dan barang",
    "Pastikan nyaman dipakai di ponsel karena banyak pengguna lapangan membukanya dari sana",
    "Sediakan notifikasi untuk peristiwa penting, seperti pesanan dikirim atau faktur diterbitkan",
    "Tulis pesan kesalahan yang menjelaskan apa yang harus dilakukan, bukan kode teknis",
    "Sediakan bantuan yang terjangkau: panduan singkat, pertanyaan umum, dan kontak manusia bila perlu",
  ] },
  { type: "p", text: "Kecepatan juga bagian dari pengalaman. Portal yang lambat memuat daftar pesanan memancing kembali ke telepon. Perhatikan kinerja sejak awal, terutama untuk pelanggan dengan ribuan baris riwayat, dan uji dengan data sebesar data nyata." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44",
    alt: "Laptop menampilkan halaman web dengan tombol ajakan bertindak, tangan di trackpad",
    caption: "Portal yang berhasil membuat tugas utama mitra selesai dalam hitungan klik, bukan dalam hitungan telepon.",
  },
  { type: "h2", text: "Membuat mitra benar-benar memakai portal" },
  { type: "p", text: "Banyak portal diluncurkan dengan penuh harapan lalu sepi pengguna. Penyebabnya hampir selalu bukan teknologi, melainkan adopsi. Mitra tidak otomatis tahu portal itu ada, tidak otomatis mau mengubah kebiasaan, dan tidak otomatis percaya bahwa portal lebih baik daripada menelepon orang yang sudah mereka kenal." },
  { type: "ol", items: [
    "Libatkan beberapa mitra penting sejak perancangan agar portal menjawab kebutuhan nyata mereka",
    "Luncurkan bertahap kepada kelompok kecil, perbaiki, lalu perluas",
    "Latih tim internal lebih dulu agar mereka mampu mengarahkan mitra, bukan menjawab semuanya secara manual",
    "Tawarkan pelatihan singkat atau panduan bergambar untuk pengguna mitra",
    "Arahkan pertanyaan rutin ke portal secara sopan, misalnya dengan menyertakan tautan status pesanan dalam setiap jawaban",
    "Berikan alasan yang jelas bagi mitra untuk memakainya, seperti kecepatan, pemesanan di luar jam kerja, atau harga khusus",
  ] },
  { type: "p", text: "Perlu kesabaran dan konsistensi. Selama sebagian tim tetap melayani permintaan yang bisa dilakukan lewat portal tanpa mengarahkannya, kebiasaan lama akan bertahan. Pastikan pimpinan dan tim penjualan mendukung peralihan ini dan memahami manfaatnya bagi mereka sendiri, yaitu waktu yang dibebaskan untuk pekerjaan bernilai lebih tinggi." },
  { type: "h2", text: "Integrasi dengan proses dan pembayaran" },
  { type: "p", text: "Nilai portal meningkat ketika ia tidak hanya menampilkan informasi tetapi juga memungkinkan tindakan. Pelanggan yang dapat memesan ulang, menyetujui penawaran, atau membayar faktur langsung dari portal menghemat langkah di kedua sisi. Namun setiap tindakan yang menyentuh uang atau komitmen harus melewati kontrol yang tepat." },
  { type: "p", text: "Untuk pembayaran, hubungkan dengan metode yang lazim digunakan mitra dan pastikan status pembayaran terhubung otomatis ke catatan piutang. Untuk pemesanan, terapkan aturan bisnis yang sama seperti jalur lain, seperti batas kredit, harga kontrak, dan minimum pemesanan, agar portal tidak menjadi jalan pintas yang melanggar kebijakan. Untuk persetujuan, catat siapa yang menyetujui dan kapan." },
  { type: "p", text: "Pertimbangkan juga integrasi dengan sistem mitra bila volume transaksi besar. Pelanggan besar sering ingin pesanan mengalir langsung dari sistem pengadaan mereka tanpa pengetikan ulang, dan pemasok besar ingin menukar dokumen secara otomatis. Antarmuka pertukaran data yang terdokumentasi dapat melayani kebutuhan itu, tetapi sebaiknya dibangun setelah fitur dasar portal berjalan stabil." },
  { type: "h2", text: "Membangun sendiri, membeli, atau menggabungkan" },
  { type: "p", text: "Ada tiga jalur umum. Pertama, memakai modul portal yang disediakan ERP atau CRM Anda. Ini cepat dan terintegrasi, tetapi fleksibilitas tampilan dan alurnya terbatas. Kedua, memakai platform portal siap pakai yang dihubungkan ke sistem Anda lewat antarmuka. Ini seimbang untuk banyak kasus. Ketiga, membangun portal khusus yang mengikuti proses dan merek Anda, dengan fleksibilitas tertinggi tetapi biaya dan tanggung jawab perawatan paling besar." },
  { type: "ul", items: [
    "Nilai seberapa unik proses Anda: jika standar, modul bawaan sering cukup",
    "Periksa kemampuan integrasi sistem inti Anda sebelum memilih jalur",
    "Hitung biaya total jangka panjang, termasuk lisensi, perawatan, dan perubahan",
    "Pertimbangkan seberapa penting identitas merek dan pengalaman khas bagi mitra Anda",
    "Mulai dengan lingkup kecil yang bisa diluncurkan cepat, bukan portal sempurna yang selesai setahun lagi",
  ] },
  { type: "p", text: "Apa pun jalurnya, tetapkan siapa pemilik portal di dalam perusahaan. Portal yang tidak memiliki pemilik akan basi: informasi tidak diperbarui, masukan tidak ditindaklanjuti, dan mitra berhenti memakainya. Pemilik ini biasanya berasal dari bagian yang paling bergantung padanya, seperti penjualan atau pengadaan, dengan dukungan tim teknologi." },
  { type: "h2", text: "Mengukur keberhasilan" },
  { type: "p", text: "Tentukan sejak awal bagaimana Anda tahu portal berhasil. Ukuran yang berguna berkaitan dengan perilaku yang ingin diubah. Jika tujuannya mengurangi pertanyaan status, pantau jumlah pertanyaan semacam itu yang masuk lewat telepon dan surel sebelum dan sesudah peluncuran. Jika tujuannya mempercepat pemesanan ulang, pantau proporsi pesanan yang masuk lewat portal." },
  { type: "ul", items: [
    "Proporsi mitra aktif dari seluruh mitra yang diundang",
    "Proporsi pesanan atau dokumen yang diproses lewat portal dibanding jalur lain",
    "Jumlah pertanyaan administratif yang masuk lewat telepon dan surel dari waktu ke waktu",
    "Waktu rata-rata dari pesanan sampai konfirmasi, dan dari faktur sampai pembayaran",
    "Kepuasan mitra berdasarkan umpan balik langsung dan alasan mereka tidak memakai",
    "Kesalahan data atau pengaduan yang berkaitan dengan portal",
  ] },
  { type: "p", text: "Jangan terpaku pada jumlah masuk saja. Mitra yang masuk sekali lalu kembali menelepon menandakan ada hambatan. Tanyakan langsung kepada mereka apa yang menyulitkan, dan perlakukan masukan itu sebagai bahan prioritas perbaikan berikutnya." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Membangun portal dengan data baru yang terpisah dari ERP sehingga selisih tak terhindarkan",
    "Meluncurkan terlalu banyak fitur sekaligus sehingga membingungkan",
    "Mengabaikan hak akses sehingga satu mitra bisa melihat data mitra lain",
    "Tidak melatih tim internal sehingga mereka terus melayani lewat jalur lama",
    "Tidak menunjuk pemilik portal sehingga isinya cepat usang",
    "Mengukur keberhasilan hanya dari jumlah akun yang dibuat, bukan penggunaan nyata",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Catat selama dua minggu pertanyaan dan permintaan rutin dari pelanggan dan pemasok",
    "Pilih tiga pertanyaan yang paling sering dan menghabiskan waktu paling banyak",
    "Periksa apakah datanya tersedia dan akurat di ERP dan CRM, dan rapikan bila perlu",
    "Tentukan tiga sampai lima mitra yang bersedia menjadi pengguna awal",
    "Tunjuk pemilik portal dan tetapkan ukuran keberhasilan sebelum membangun",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Portal pelanggan dan pemasok yang dirancang dengan baik menghemat waktu kedua pihak, mengurangi kesalahan, dan menunjukkan keseriusan perusahaan dalam melayani mitra. Kuncinya ada pada fokus pada pertanyaan yang benar-benar berulang, data yang bersumber dari sistem inti, hak akses yang ketat, pengalaman yang sederhana, dan upaya serius agar mitra mau memakainya." },
  { type: "p", text: "Mulailah dari yang kecil dan bernilai tinggi, ukur penggunaannya, dan kembangkan berdasarkan umpan balik nyata. Dengan begitu portal bukan sekadar proyek teknologi, melainkan cara kerja baru yang menguatkan hubungan bisnis Anda." },
  {
    type: "cta",
    title: "Ingin portal untuk pelanggan atau pemasok yang terhubung langsung ke ERP dan CRM Anda?",
    text: "Tim AG·SORA membangun portal B2B dengan hak akses yang ketat, data yang bersumber dari sistem inti, dan pengalaman yang mudah dipakai mitra. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/erp",
    label: "Konsultasi gratis",
  },
];
