import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Setiap hari toko online menerima pesanan dan pembayaran lewat berbagai jalur: transfer bank, dompet digital, kartu, kode QR, bayar di tempat, dan kadang cicilan. Di sisi lain, uang masuk ke rekening bank dengan jeda waktu, dipotong biaya, dan sering digabung dalam satu setoran dari penyedia pembayaran. Ketika akhir bulan tiba, pertanyaan sederhana muncul: apakah uang yang masuk di rekening sama dengan penjualan yang tercatat di sistem?" },
  { type: "p", text: "Menjawab pertanyaan itu adalah tugas rekonsiliasi pembayaran. Tanpanya, bisnis bisa mengira penjualannya sehat padahal ada pesanan yang tidak pernah dibayar, pembayaran yang tersangkut, pengembalian dana yang tidak tercatat, atau biaya layanan yang membengkak tanpa disadari. Banyak toko mengerjakannya secara manual dengan lembar kerja, dan pekerjaan itu makin menyiksa seiring bertambahnya transaksi." },
  { type: "p", text: "Artikel ini membahas cara merancang rekonsiliasi pembayaran yang rapi dan, sejauh mungkin, otomatis untuk toko online dan aplikasi. Kami membahas sumber selisih, kunci pencocokan, alur harian dan bulanan, penanganan pengecualian, pencatatan biaya, pengendalian internal, dan pilihan alat. Kami tidak memakai angka rekaan tentang biaya layanan atau waktu pencairan; ketentuan itu berbeda per penyedia dan perlu diperiksa pada perjanjian dan dokumentasi terbaru Anda." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Rekonsiliasi mencocokkan tiga hal: pesanan di sistem, laporan penyedia pembayaran, dan mutasi rekening bank",
      "Siapkan kunci pencocokan yang unik sejak awal, seperti nomor pesanan yang ikut terkirim ke penyedia pembayaran",
      "Otomatiskan pencocokan yang jelas dan sisakan perhatian manusia untuk pengecualian",
      "Catat biaya layanan, pengembalian dana, dan sengketa sebagai transaksi terpisah agar laporan laba akurat",
      "Lakukan rutin harian dan tutup buku bulanan dengan pembagian tugas yang jelas",
    ],
  },
  { type: "h2", text: "Mengapa rekonsiliasi layak mendapat perhatian" },
  { type: "p", text: "Toko online hidup dari kepercayaan bahwa angka penjualan mencerminkan uang yang benar-benar diterima. Selisih kecil yang dibiarkan menumpuk berubah menjadi masalah besar: laporan keuangan yang tidak bisa dipercaya, pajak yang dihitung dari angka keliru, keputusan pembelian stok yang bertumpu pada pendapatan semu, dan kesulitan ketika auditor atau investor meminta penjelasan." },
  { type: "p", text: "Rekonsiliasi juga berfungsi sebagai alat deteksi dini. Pesanan yang berstatus dibayar tetapi dananya tidak pernah masuk bisa menandakan kesalahan integrasi atau percobaan penipuan. Biaya layanan yang tiba-tiba naik menandakan perubahan tarif atau jenis transaksi. Pengembalian dana yang berulang pada satu produk menunjukkan masalah mutu. Banyak temuan penting justru datang dari upaya mencocokkan angka." },
  { type: "p", text: "Dari sisi operasional, rekonsiliasi yang rapi membuat tutup buku bulanan berjalan hitungan hari, bukan hitungan minggu. Tim keuangan tidak lagi memburu bukti pembayaran satu per satu, dan tim layanan pelanggan bisa menjawab pertanyaan tentang status pembayaran dengan pasti." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1553877522-43269d4ea984",
    alt: "Dokumen laporan keuangan dan kalkulator di atas meja kerja",
    caption: "Rekonsiliasi memastikan angka di laporan sama dengan uang yang benar-benar diterima di rekening.",
  },
  { type: "h2", text: "Tiga sumber data yang harus dicocokkan" },
  { type: "p", text: "Rekonsiliasi pembayaran toko online pada dasarnya mencocokkan tiga catatan yang dibuat oleh pihak berbeda. Masing-masing benar menurut sudut pandangnya, dan selisih di antara ketiganya menunjukkan sesuatu yang perlu dijelaskan." },
  { type: "ol", items: [
    "Catatan pesanan di sistem toko atau ERP: pesanan apa saja yang dibuat, berapa nilainya, dan apa statusnya",
    "Laporan transaksi dari penyedia pembayaran: pembayaran apa yang berhasil, gagal, dikembalikan, atau disengketakan, beserta biaya dan tanggal pencairannya",
    "Mutasi rekening bank: berapa uang yang benar-benar masuk, kapan, dan dalam bentuk setoran seperti apa",
  ] },
  { type: "p", text: "Pencocokan tiga arah ini mengungkap berbagai situasi. Pesanan ada tetapi tidak ada transaksi pembayaran berarti pesanan belum dibayar atau pembayaran tidak terhubung. Transaksi berhasil tetapi tidak ada di pesanan berarti ada pembayaran yang tidak terkait dengan pesanan mana pun. Transaksi ada tetapi setoran bank tidak cocok berarti ada biaya, potongan, atau jeda yang perlu dijelaskan." },
  { type: "h3", text: "Mengapa jumlah setoran sering berbeda dari jumlah penjualan" },
  { type: "ul", items: [
    "Biaya layanan dipotong penyedia sebelum dana disetorkan",
    "Beberapa transaksi digabung dalam satu setoran sehingga jumlahnya tidak cocok dengan satu pesanan",
    "Ada jeda antara tanggal pembayaran dan tanggal pencairan, dan jeda itu bisa melintasi pergantian bulan",
    "Pengembalian dana dan sengketa mengurangi setoran berikutnya",
    "Pembayaran sebagian, kelebihan bayar, atau kode unik yang menambah nominal transfer",
    "Perbedaan mata uang dan kurs ketika pelanggan membayar dalam mata uang lain",
  ] },
  { type: "h2", text: "Kunci pencocokan: fondasi otomatisasi" },
  { type: "p", text: "Pencocokan otomatis hanya mungkin jika setiap transaksi punya kunci yang bisa dipakai untuk menghubungkan ketiga catatan. Tanpa kunci, orang terpaksa menebak berdasarkan nominal dan tanggal, yang rawan salah ketika banyak transaksi bernilai sama. Kunci yang baik unik, stabil, dan terbawa di semua catatan." },
  { type: "p", text: "Kunci paling andal adalah nomor pesanan yang Anda kirim ke penyedia pembayaran sebagai rujukan saat transaksi dibuat. Penyedia akan menyimpannya dan mencantumkannya di laporan, sehingga setiap baris laporan bisa dipasangkan dengan pesanan secara otomatis. Selain itu, simpan nomor transaksi dari penyedia di pesanan Anda agar pencarian bisa dilakukan dari dua arah." },
  { type: "ul", items: [
    "Kirim nomor pesanan sebagai rujukan pada setiap permintaan pembayaran ke penyedia",
    "Simpan nomor transaksi penyedia pada catatan pembayaran di sistem Anda",
    "Untuk transfer bank manual, gunakan kode unik atau nomor rekening virtual per pesanan agar setiap mutasi bisa dikenali",
    "Pastikan nomor pesanan tidak pernah dipakai ulang atau diubah setelah pembayaran dibuat",
    "Catat juga nomor setoran atau batch pencairan dari penyedia untuk mencocokkan dengan mutasi bank",
  ] },
  { type: "p", text: "Rekening virtual per pesanan atau per pelanggan sangat membantu untuk transfer bank, karena setiap dana yang masuk sudah membawa identitas pesanannya. Tanpa itu, pembeli yang mentransfer dengan nominal berbeda atau lupa menulis berita transfer akan menjadi sumber pengecualian yang melelahkan." },
  { type: "h2", text: "Alur harian yang ringan" },
  { type: "p", text: "Rekonsiliasi yang dikerjakan sekali sebulan menumpuk masalah sampai sulit dilacak. Rutinitas harian yang ringan jauh lebih efektif karena selisih ditemukan ketika ingatan masih segar dan bukti mudah dicari. Sebagian besar langkah bisa diotomatiskan dengan antarmuka pemrograman penyedia dan impor mutasi bank." },
  { type: "ol", items: [
    "Tarik laporan transaksi hari sebelumnya dari penyedia pembayaran, secara otomatis bila memungkinkan",
    "Cocokkan setiap transaksi berhasil dengan pesanan berdasarkan nomor rujukan, lalu tandai pesanan sebagai terbayar dan terverifikasi",
    "Tandai pesanan yang statusnya dibayar di sistem tetapi tidak ditemukan di laporan, serta transaksi di laporan yang tidak punya pesanan",
    "Catat pengembalian dana dan sengketa baru terhadap pesanan terkait",
    "Setiap kali ada setoran dari penyedia, cocokkan dengan mutasi bank dan catat selisih berupa biaya dan potongan",
    "Tinjau daftar pengecualian dan tetapkan siapa menanganinya serta batas waktunya",
  ] },
  { type: "p", text: "Tujuan alur harian bukan menutup semua selisih sekaligus, melainkan menjaga daftar pengecualian tetap pendek dan setiap butirnya punya pemilik. Daftar yang pendek dan terkelola jauh lebih mudah ditangani daripada tumpukan ratusan butir yang tidak jelas asalnya." },
  { type: "h2", text: "Menangani pengecualian" },
  { type: "p", text: "Setelah pencocokan otomatis, sisa yang tidak cocok adalah pengecualian yang memerlukan keputusan manusia. Kelompokkan menurut jenisnya agar penanganannya terarah, dan tetapkan tindakan baku untuk tiap jenis supaya keputusan konsisten antarpetugas." },
  { type: "ul", items: [
    "Pesanan dibayar tetapi tidak ada transaksi: periksa apakah pembayaran gagal atau notifikasi dari penyedia tidak sampai ke sistem, lalu perbarui status",
    "Transaksi tanpa pesanan: periksa apakah pelanggan membayar dua kali atau pesanan dibuat ulang, lalu putuskan pengembalian atau penggabungan",
    "Nominal tidak cocok: periksa pembayaran sebagian, kelebihan bayar, atau perbedaan ongkos kirim dan diskon",
    "Setoran lebih kecil dari yang diharapkan: periksa biaya, pengembalian dana, sengketa, dan potongan lain",
    "Pembayaran tertunda terlalu lama: hubungi penyedia atau pelanggan sesuai jalur yang disepakati",
    "Transaksi duplikat: pastikan tidak ada pengiriman ganda dan kembalikan kelebihan bila perlu",
  ] },
  { type: "p", text: "Beri setiap pengecualian status dan batas waktu. Pengecualian yang dibiarkan berminggu-minggu akan melewati tutup buku dan menimbulkan koreksi berantai. Catat juga penyebab akar dari pengecualian yang berulang, karena sering menunjuk pada celah integrasi yang bisa ditutup sekali dan selamanya." },
  { type: "h2", text: "Mencatat biaya, pengembalian dana, dan sengketa" },
  { type: "p", text: "Salah satu kesalahan pembukuan yang paling umum adalah mencatat penjualan sebesar uang yang masuk setelah dipotong. Dengan cara itu, biaya layanan tersembunyi dan laporan tidak bisa menunjukkan berapa biaya sebenarnya menerima pembayaran. Catat penjualan sebesar nilai kotor, lalu catat biaya layanan sebagai pengeluaran tersendiri. Dengan begitu Anda bisa membandingkan biaya antarmetode pembayaran dan menilai apakah masih masuk akal." },
  { type: "p", text: "Pengembalian dana harus tercatat sebagai pengurang penjualan yang terkait dengan pesanan asalnya, bukan sebagai pengeluaran biasa. Sengketa atau tagihan balik dari penyedia kartu juga perlu dicatat dan ditindaklanjuti dengan bukti pengiriman dan komunikasi pelanggan dalam batas waktu yang diberikan penyedia. Bila bukti tidak tersedia, dana bisa hilang, sehingga pengarsipan dokumen pengiriman dan bukti serah terima penting." },
  { type: "p", text: "Uang yang sudah dibayar pelanggan tetapi belum cair ke rekening adalah piutang dari penyedia pembayaran, bukan kas. Perlakukan sebagai akun peralihan yang dikosongkan ketika setoran diterima. Akun ini sekaligus menjadi alat kontrol: saldonya harus selalu dapat dijelaskan oleh transaksi yang belum dicairkan, dan saldo yang membesar tanpa sebab menandakan ada yang tertinggal." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1",
    alt: "Pelanggan menempelkan kartu pembayaran ke mesin pembaca nontunai",
    caption: "Setiap pembayaran yang berhasil harus bisa ditelusuri sampai ke pesanan dan ke setoran di rekening.",
  },
  { type: "h2", text: "Pembayaran di tempat dan kanal lain" },
  { type: "p", text: "Bayar di tempat membawa tantangan rekonsiliasi tersendiri. Uang dipegang kurir atau perusahaan ekspedisi lalu disetorkan dalam beberapa hari, sering digabung dari banyak paket dan dipotong biaya layanan. Rekonsiliasinya mencocokkan daftar paket yang terkirim dan tertagih dengan setoran dari ekspedisi. Paket yang gagal kirim atau dikembalikan tidak boleh ikut dihitung sebagai pendapatan." },
  { type: "p", text: "Bila toko juga menjual lewat marketplace, setiap marketplace menyetorkan dana menurut jadwalnya sendiri setelah memotong komisi, ongkos kirim, dan biaya promosi. Pelajari laporan penyelesaian dari tiap marketplace dan pasangkan dengan pesanan serta mutasi bank. Laporan itu biasanya memuat rincian per pesanan sehingga selisih antara nilai penjualan dan dana diterima bisa dijelaskan." },
  { type: "p", text: "Untuk penjualan di toko fisik, rekonsiliasi kas dan non-tunai dilakukan terhadap laporan sistem kasir. Memakai satu sistem pencatatan untuk semua kanal membuat pencocokan jauh lebih mudah karena nomor pesanan, kode barang, dan struktur data seragam." },
  { type: "h2", text: "Tutup buku bulanan yang tidak menegangkan" },
  { type: "p", text: "Dengan rutinitas harian yang berjalan, tutup buku bulanan menjadi verifikasi akhir, bukan pencarian besar-besaran. Tetapkan tanggal batas yang konsisten untuk menarik laporan, menyelesaikan pengecualian, dan menyetujui hasilnya. Perhatikan transaksi yang melintasi pergantian bulan, seperti pembayaran di akhir bulan yang baru cair di awal bulan berikutnya, dan perlakukan secara konsisten sesuai kebijakan akuntansi Anda." },
  { type: "ol", items: [
    "Pastikan semua laporan penyedia dan mutasi bank untuk periode itu sudah lengkap",
    "Selesaikan atau beri keterangan semua pengecualian yang tersisa",
    "Cocokkan saldo akun peralihan penyedia dengan daftar transaksi yang belum cair",
    "Periksa total penjualan, pengembalian dana, biaya, dan setoran terhadap laporan keuangan",
    "Minta persetujuan penanggung jawab keuangan dan arsipkan hasil beserta bukti pendukungnya",
  ] },
  { type: "callout", title: "Saldo peralihan harus bisa dijelaskan", text: "Akun yang menampung dana belum cair adalah indikator kesehatan rekonsiliasi. Jika saldonya tidak bisa dijelaskan oleh transaksi nyata yang belum dicairkan, ada selisih yang perlu dicari sebelum buku ditutup." },
  { type: "h2", text: "Pengendalian internal yang sederhana tetapi efektif" },
  { type: "p", text: "Karena rekonsiliasi menyentuh uang, ia perlu pengendalian yang sederhana tetapi disiplin. Prinsip utamanya adalah pemisahan tugas: orang yang menerima atau mengeluarkan uang sebaiknya bukan orang yang menyetujui rekonsiliasinya. Pada bisnis kecil dengan sedikit karyawan, pemisahan sempurna mungkin tidak mungkin, tetapi pemilik dapat menjadi peninjau independen atas ringkasan bulanan." },
  { type: "ul", items: [
    "Batasi siapa yang boleh mengubah status pembayaran secara manual dan catat setiap perubahan",
    "Wajibkan keterangan dan persetujuan untuk koreksi atau penyesuaian di atas batas tertentu",
    "Pisahkan hak akses antara memproses pengembalian dana dan menyetujuinya",
    "Tinjau secara berkala pola pengembalian dana dan pembatalan menurut petugas atau pelanggan",
    "Simpan laporan penyedia dan mutasi bank asli sebagai bukti, jangan hanya ringkasannya",
    "Lindungi kunci akses ke antarmuka penyedia pembayaran dan batasi penggunaannya",
  ] },
  { type: "p", text: "Perhatikan juga keamanan data pembayaran. Toko tidak perlu dan sebaiknya tidak menyimpan data kartu lengkap; serahkan pemrosesan ke penyedia pembayaran yang berwenang dan simpan hanya rujukan transaksi. Periksa ketentuan keamanan data pembayaran yang berlaku saat ini bila toko Anda menangani data kartu dalam bentuk apa pun." },
  { type: "h2", text: "Memilih alat dan tingkat otomatisasi" },
  { type: "p", text: "Pilihan alat bergantung pada volume transaksi dan kerumitan kanal. Pada volume kecil, lembar kerja dengan impor laporan dan rumus pencocokan bisa cukup, asalkan kunci pencocokan konsisten. Ketika transaksi mencapai ratusan per hari atau kanal bertambah, otomatisasi menjadi investasi yang terbayar." },
  { type: "ul", items: [
    "Fitur rekonsiliasi bawaan sistem toko, ERP, atau perangkat lunak akuntansi Anda, bila tersedia",
    "Impor otomatis laporan transaksi dari penyedia pembayaran lewat antarmuka atau berkas terjadwal",
    "Impor mutasi bank dalam format terstruktur, bukan salin tempel manual",
    "Aturan pencocokan yang bisa diatur, misalnya menurut nomor rujukan, nominal, dan rentang tanggal",
    "Laporan pengecualian yang jelas dengan pemilik dan batas waktu",
    "Jejak audit yang mencatat siapa mencocokkan apa dan kapan",
  ] },
  { type: "p", text: "Apa pun alatnya, uji dengan data nyata sebelum diandalkan. Jalankan secara paralel dengan cara lama selama satu atau dua periode, bandingkan hasilnya, dan perbaiki aturan yang salah. Otomatisasi yang tidak diuji hanya mempercepat kesalahan." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Tidak mengirim nomor pesanan sebagai rujukan ke penyedia pembayaran sehingga pencocokan harus ditebak",
    "Mencatat penjualan sebesar uang bersih yang masuk sehingga biaya layanan tersembunyi",
    "Mengerjakan rekonsiliasi hanya saat tutup bulan",
    "Membiarkan pengecualian menumpuk tanpa pemilik dan batas waktu",
    "Mencatat pengembalian dana sebagai pengeluaran biasa",
    "Menyimpan data kartu sendiri tanpa kebutuhan dan tanpa pengamanan yang memadai",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Periksa apakah nomor pesanan sudah dikirim sebagai rujukan ke penyedia pembayaran, dan perbaiki bila belum",
    "Unduh laporan satu bulan dari penyedia dan mutasi bank, lalu coba cocokkan manual untuk memahami jenis selisihnya",
    "Buat daftar jenis pengecualian yang ditemukan beserta tindakan bakunya",
    "Pisahkan pencatatan penjualan kotor, biaya layanan, dan pengembalian dana",
    "Jadwalkan rutinitas harian atau mingguan dengan penanggung jawab yang jelas",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Rekonsiliasi pembayaran bukan pekerjaan administratif yang membosankan semata, melainkan cara memastikan bahwa angka bisnis Anda dapat dipercaya. Kunci pencocokan yang konsisten, rutinitas harian, penanganan pengecualian yang disiplin, pencatatan biaya dan pengembalian yang benar, serta pengendalian sederhana membuat tutup buku menjadi proses yang tenang." },
  { type: "p", text: "Mulailah dari memastikan setiap pembayaran membawa nomor rujukan, lalu otomatiskan bagian yang berulang. Dengan begitu tim keuangan bisa menghabiskan waktu pada hal yang benar-benar butuh penilaian manusia, dan pemilik bisnis bisa mempercayai laporan yang ada di tangannya." },
  {
    type: "cta",
    title: "Ingin pembayaran toko online tercocokkan otomatis dengan pesanan dan pembukuan?",
    text: "Tim AG·SORA membangun integrasi pembayaran, rekonsiliasi otomatis, dan laporan keuangan yang terhubung dengan toko online dan ERP Anda. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/erp",
    label: "Konsultasi gratis",
  },
];
