import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Retur adalah bagian tak terhindarkan dari berjualan online. Barang bisa rusak dalam perjalanan, ukurannya tidak pas, warnanya tampak berbeda dari foto, atau salah kirim. Pelanggan yang berbelanja tanpa menyentuh barang secara wajar ingin tahu bahwa mereka bisa mengembalikannya bila ada masalah. Karena itu, cara toko menangani retur sering menjadi penentu apakah pelanggan akan membeli lagi atau tidak." },
  { type: "p", text: "Banyak toko menganggap retur sebagai gangguan yang harus ditekan sekecil mungkin. Pandangan yang lebih berguna adalah menganggapnya sebagai bagian dari proses penjualan yang perlu dirancang. Retur yang ditangani rapi menjaga kepercayaan, memberi data tentang kualitas produk dan deskripsi, serta tidak menimbulkan selisih stok maupun selisih uang. Retur yang ditangani seadanya menimbulkan sengketa, ulasan buruk, dan pembukuan yang berantakan." },
  { type: "p", text: "Artikel ini membahas cara merancang proses retur dan pengembalian dana untuk toko online dan aplikasi belanja. Kami membahas kebijakan, alur permintaan, pemeriksaan barang, pengembalian dana, pengaruhnya pada stok dan pembukuan, serta cara mengurangi retur dari sumbernya. Kami tidak memakai angka rekaan tentang tingkat retur; yang kami tawarkan adalah prinsip dan daftar periksa yang bisa diterapkan pada toko berbagai skala." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Tulis kebijakan retur yang jelas, singkat, dan mudah ditemukan sebelum pelanggan membeli",
      "Buat alur permintaan retur yang terdaftar di sistem, bukan lewat pesan acak yang mudah terlewat",
      "Periksa barang yang kembali dengan standar tetap dan putuskan nasib stoknya: jual lagi, perbaiki, atau hapus",
      "Kembalikan dana lewat jalur dan jangka waktu yang dijanjikan, dan catat di pembukuan",
      "Pelajari alasan retur untuk memperbaiki foto, deskripsi, kemasan, dan pemasok",
    ],
  },
  { type: "h2", text: "Mengapa retur layak dirancang dengan serius" },
  { type: "p", text: "Dari sudut pandang pelanggan, kemudahan retur adalah pengganti hak mencoba di toko. Calon pembeli yang ragu sering memutuskan berdasarkan seberapa mudah mereka bisa mundur. Kebijakan yang jelas dan adil mengurangi keraguan itu dan membuat orang berani membeli, terutama untuk barang yang ukuran atau kecocokannya sulit dipastikan dari foto." },
  { type: "p", text: "Dari sudut pandang operasional, retur menyentuh banyak bagian sekaligus: layanan pelanggan menerima permintaan, gudang menerima dan memeriksa barang, tim keuangan mengembalikan dana, dan tim stok memperbarui jumlah. Bila setiap bagian bekerja dengan catatannya sendiri, satu retur bisa menimbulkan empat versi cerita yang tidak cocok." },
  { type: "p", text: "Dari sudut pandang bisnis, retur membawa informasi berharga. Barang yang sering dikembalikan karena ukuran tidak pas menunjukkan panduan ukuran yang kurang baik. Barang yang sering rusak menunjukkan masalah kemasan atau pemasok. Toko yang membaca pola ini bisa memperbaiki sumber masalahnya, bukan hanya menanggung akibatnya." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d",
    alt: "Gudang distribusi besar dengan rak dan tumpukan kontainer kuning",
    caption: "Barang yang kembali harus melewati pemeriksaan yang sama rapinya dengan barang yang keluar dari gudang.",
  },
  { type: "h2", text: "Menyusun kebijakan retur yang jelas" },
  { type: "p", text: "Kebijakan retur yang baik menjawab pertanyaan pelanggan sebelum mereka bertanya. Barang apa yang bisa dikembalikan, dalam berapa hari setelah diterima, dalam kondisi seperti apa, siapa yang menanggung ongkos kirim kembali, dan bagaimana dananya dikembalikan. Tulis dengan bahasa sehari-hari dan taruh di tempat yang mudah ditemukan, seperti halaman produk, halaman pembayaran, dan footer toko." },
  { type: "p", text: "Pisahkan beberapa situasi yang berbeda karena perlakuannya tidak sama. Barang rusak atau salah kirim adalah kesalahan toko, sehingga ongkos kirim kembali biasanya ditanggung toko. Barang yang tidak cocok atau berubah pikiran adalah keputusan pelanggan, sehingga kebijakan bisa lebih ketat dan ongkos ditanggung pelanggan. Kategori barang tertentu, seperti barang yang mudah rusak, produk kebersihan pribadi, atau barang yang dibuat sesuai pesanan, sering dikecualikan dan pengecualian itu harus ditulis jelas." },
  { type: "p", text: "Periksa juga ketentuan perlindungan konsumen dan transaksi elektronik yang berlaku saat ini sebelum menetapkan kebijakan. Aturan dapat berubah, dan kebijakan toko tidak boleh bertentangan dengan hak yang dijamin hukum. Jika ragu, mintalah masukan dari penasihat hukum dan rujuk sumber resmi terkini, bukan ingatan atau kebiasaan toko lain." },
  { type: "callout", title: "Jelas lebih baik daripada longgar atau ketat", text: "Kebijakan yang paling merugikan bukan yang terlalu ketat atau terlalu longgar, melainkan yang tidak jelas. Pelanggan dan tim sama-sama tahu apa yang berlaku, sehingga sengketa bisa diselesaikan tanpa debat." },
  { type: "h2", text: "Alur permintaan retur yang terdaftar" },
  { type: "p", text: "Permintaan retur yang masuk lewat pesan pribadi, komentar, dan telepon yang tersebar mudah hilang dan sulit dilacak. Sediakan jalur resmi: formulir di akun pelanggan atau tombol di riwayat pesanan yang membuat permintaan terdaftar di sistem dengan nomor rujukan. Dengan begitu pelanggan bisa memantau status, dan tim tidak perlu menelusuri percakapan lama untuk mengetahui kelanjutannya." },
  { type: "p", text: "Minta informasi yang cukup untuk memutuskan tanpa bolak-balik. Biasanya itu berarti nomor pesanan, barang yang dikembalikan, alasan yang dipilih dari daftar, penjelasan singkat, dan foto bila barang rusak atau tidak sesuai. Daftar alasan yang baku sangat berguna untuk analisis nanti; kolom teks bebas saja menyulitkan penghitungan." },
  { type: "p", text: "Tetapkan status yang jelas dan terlihat pelanggan, misalnya diajukan, disetujui, barang dalam perjalanan, diterima, diperiksa, dana dikembalikan, atau ditolak. Setiap perubahan status sebaiknya memicu pemberitahuan agar pelanggan tidak perlu bertanya. Banyak keluhan sebenarnya bukan soal keputusan, melainkan soal tidak tahu sampai di mana prosesnya." },
  { type: "ol", items: [
    "Pelanggan mengajukan permintaan lewat akun dan memilih alasan baku",
    "Sistem memeriksa otomatis syarat dasar, seperti batas waktu dan kategori barang",
    "Petugas meninjau kasus yang memerlukan keputusan, misalnya kerusakan yang diklaim",
    "Pelanggan menerima instruksi pengiriman kembali beserta label atau nomor rujukan",
    "Gudang menerima, memeriksa, dan mencatat kondisi barang",
    "Keuangan mengembalikan dana dan sistem memperbarui stok serta pembukuan",
  ] },
  { type: "h2", text: "Pengiriman kembali dan pelacakannya" },
  { type: "p", text: "Pengiriman kembali sering menjadi titik paling rapuh. Barang yang dikirim tanpa nomor rujukan tiba di gudang tanpa konteks: siapa pengirimnya, pesanan yang mana, dan apa alasannya. Minta pelanggan menyertakan nomor retur di paket, atau sediakan label yang sudah memuat informasi itu, sehingga petugas gudang dapat mencocokkannya dengan cepat." },
  { type: "p", text: "Jika toko menanggung ongkos kirim kembali, pertimbangkan jalur yang sudah disepakati dengan jasa pengiriman agar biayanya terkendali dan nomor resinya otomatis terhubung ke permintaan retur. Jika pelanggan menanggung, jelaskan sejak awal agar tidak ada kejutan. Dalam kedua kasus, simpan nomor resi karena menjadi bukti ketika barang hilang di perjalanan." },
  { type: "p", text: "Sarankan pelanggan mengemas barang dengan layak dan memfotonya sebelum dikirim. Barang yang rusak karena pengiriman kembali menimbulkan perselisihan baru tentang siapa yang bertanggung jawab. Foto sebelum kirim dan foto saat terima di gudang memberi dasar untuk memutuskan secara adil." },
  { type: "h2", text: "Memeriksa barang yang kembali" },
  { type: "p", text: "Pemeriksaan adalah tahap yang menentukan nasib barang dan dana. Tetapkan daftar periksa tetap: apakah barang sesuai dengan yang dipesan, apakah kondisinya sesuai dengan klaim, apakah segel, label, dan kelengkapan masih ada, serta apakah ada tanda pemakaian yang melampaui wajar. Catat hasilnya dan foto bila perlu, lalu simpan di catatan retur." },
  { type: "p", text: "Putuskan nasib barang secara tegas dan catat di sistem. Barang yang kondisinya baik dikembalikan ke stok dan bisa dijual lagi. Barang dengan cacat ringan bisa diperbaiki atau dijual sebagai barang sisa dengan harga khusus dan keterangan jelas. Barang rusak berat dikembalikan ke pemasok bila ada jaminan, atau dihapus dari stok dengan catatan alasan. Jangan biarkan barang retur menumpuk di sudut gudang tanpa status, karena itulah sumber selisih stok yang paling sering terjadi." },
  { type: "p", text: "Konsistenkan standar pemeriksaan di antara petugas agar dua pelanggan dengan kasus serupa mendapat keputusan serupa. Buat panduan bergambar yang menunjukkan contoh kondisi yang diterima dan yang ditolak. Keadilan yang terasa oleh pelanggan sebagian besar datang dari konsistensi ini." },
  { type: "h2", text: "Pengembalian dana dan pilihan penggantinya" },
  { type: "p", text: "Setelah barang diterima dan diperiksa, pelanggan mengharapkan kejelasan soal uangnya. Tentukan pilihan yang ditawarkan: pengembalian dana ke metode pembayaran asal, penggantian dengan barang yang sama atau berbeda, atau kredit toko yang bisa dipakai untuk pembelian berikutnya. Beberapa pelanggan lebih suka ganti barang daripada uang, dan menawarkan pilihan bisa menyelamatkan penjualan." },
  { type: "p", text: "Kembalikan dana lewat jalur yang sama dengan pembayaran awal bila memungkinkan, dan beri tahu jangka waktu yang wajar. Pengembalian ke kartu, dompet digital, atau transfer bank memiliki waktu proses berbeda yang dipengaruhi penyedia layanan; sampaikan perkiraan secara jujur dan jangan menjanjikan tanggal yang tidak bisa Anda kendalikan. Bila Anda memakai penyedia pembayaran, pelajari alur pengembalian dana mereka dan hubungkan ke sistem agar prosesnya tidak manual." },
  { type: "p", text: "Putuskan apakah ongkos kirim awal dikembalikan, dan perlakukan promo dengan hati-hati. Jika pesanan memakai voucher atau diskon, tentukan bagaimana nilainya dihitung ketika sebagian barang saja yang dikembalikan. Aturan ini sebaiknya ditulis dalam kebijakan dan diterapkan otomatis di sistem, agar tidak ditentukan ulang setiap kasus oleh orang berbeda." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1563013544-824ae1b704d3",
    alt: "Seseorang memegang kartu pembayaran sambil berbelanja di laptop",
    caption: "Pelanggan yang meminta pengembalian dana ingin kepastian jalur dan waktu, bukan sekadar janji.",
  },
  { type: "h2", text: "Dampak retur pada stok dan pembukuan" },
  { type: "p", text: "Retur menyentuh dua buku sekaligus: stok dan keuangan. Di sisi stok, barang yang kembali dan lolos pemeriksaan menambah jumlah yang bisa dijual, sedangkan barang rusak tidak. Jika petugas hanya menambahkan stok begitu paket tiba tanpa pemeriksaan, toko bisa menjual barang yang sebenarnya cacat. Jika sebaliknya stok tidak pernah ditambahkan, barang baik hilang dari catatan dan muncul sebagai selisih saat penghitungan." },
  { type: "p", text: "Di sisi keuangan, pengembalian dana mengurangi pendapatan dan harus tercatat pada periode yang benar dengan rujukan ke penjualan asalnya. Bila toko berjualan di beberapa kanal, pastikan retur dari tiap kanal masuk ke laporan yang sama. Retur yang dicatat sebagai pengeluaran biasa, bukan sebagai pengurang penjualan, membuat laporan laba tampak lebih baik atau lebih buruk dari kenyataan." },
  { type: "p", text: "Sistem ERP atau kasir yang baik mencatat retur sebagai transaksi yang terhubung dengan penjualan asli, sehingga stok, penjualan bersih, dan pengembalian dana bergerak bersamaan. Jika Anda masih memakai catatan terpisah, setidaknya samakan nomor rujukan di semua catatan agar pencocokan bisa dilakukan saat tutup buku." },
  { type: "h2", text: "Penyalahgunaan dan cara menanganinya dengan adil" },
  { type: "p", text: "Sebagian kecil permintaan retur memang tidak jujur: barang yang sudah dipakai lalu dikembalikan, klaim tidak diterima padahal paket sampai, atau pengembalian barang yang berbeda dari yang dibeli. Menghadapinya dengan kecurigaan terhadap semua pelanggan akan merusak pengalaman mayoritas yang jujur. Yang lebih efektif adalah mengandalkan proses yang menghasilkan bukti." },
  { type: "ul", items: [
    "Dokumentasikan kondisi barang saat dikemas dan saat diterima kembali dengan foto atau pindaian",
    "Catat nomor seri atau penanda unik pada barang bernilai tinggi agar pengembalian bisa dicocokkan",
    "Simpan bukti pengiriman dan serah terima dari jasa kurir",
    "Pantau pelanggan dengan pola retur sangat tinggi dan tinjau kasusnya satu per satu, bukan menghukum secara otomatis",
    "Tetapkan jalur banding yang jelas bagi pelanggan yang permintaannya ditolak",
  ] },
  { type: "p", text: "Perlakukan penolakan dengan hormat dan penjelasan. Pelanggan yang ditolak dengan alasan konkret dan bukti foto cenderung menerima, sedangkan penolakan singkat tanpa alasan memancing eskalasi ke ulasan publik atau lembaga pengaduan. Biaya sebagian kecil retur yang tidak jujur biasanya jauh lebih murah daripada biaya kehilangan pelanggan jujur karena prosedur yang menuduh." },
  { type: "h2", text: "Mengurangi retur dari sumbernya" },
  { type: "p", text: "Cara paling murah menangani retur adalah mencegahnya. Alasan retur yang tercatat rapi menunjukkan di mana perbaikan paling berpengaruh. Jika banyak retur karena warna tampak berbeda, perbaiki foto dan pencahayaan. Jika karena ukuran, tambahkan tabel ukuran yang akurat dan panduan cara mengukur. Jika karena barang rusak, perbaiki kemasan atau tinjau pemasok." },
  { type: "ul", items: [
    "Samakan foto dan deskripsi dengan barang sebenarnya, termasuk ukuran dan warna",
    "Tambahkan panduan ukuran, kompatibilitas, dan contoh penggunaan pada halaman produk",
    "Perbaiki kemasan untuk barang yang mudah rusak dan uji dengan pengiriman nyata",
    "Periksa mutu barang sebelum dikirim, terutama untuk pesanan bernilai besar",
    "Konfirmasi alamat dan pilihan varian pada pesanan yang tampak janggal sebelum dikirim",
    "Tinjau pemasok dengan tingkat cacat tinggi dan bicarakan perbaikan atau penggantian",
  ] },
  { type: "p", text: "Ulasan dan pertanyaan pelanggan melengkapi data retur. Kalimat seperti lebih kecil dari yang dikira atau warnanya agak berbeda adalah petunjuk berharga. Masukkan temuan itu kembali ke deskripsi produk sehingga pembeli berikutnya mendapat informasi yang lebih baik sebelum memutuskan." },
  { type: "h2", text: "Layanan pelanggan selama proses retur" },
  { type: "p", text: "Cara toko berkomunikasi selama retur sering lebih diingat daripada hasilnya. Balas permintaan dengan cepat dan sopan, akui masalah tanpa defensif, dan jelaskan langkah berikutnya dengan konkret. Pelanggan yang merasa didengar biasanya bersedia menunggu proses yang wajar; pelanggan yang merasa diabaikan menjadi sumber ulasan buruk." },
  { type: "p", text: "Siapkan templat jawaban untuk situasi yang sering muncul, tetapi biarkan petugas menyesuaikannya. Jawaban yang terasa disalin mentah-mentah mengurangi kesan peduli. Berikan petugas wewenang yang jelas untuk memutuskan kasus kecil, misalnya mengganti barang bernilai rendah tanpa persetujuan berlapis, agar penyelesaian cepat." },
  { type: "p", text: "Informasikan batas waktu internal kepada tim, misalnya berapa lama permintaan boleh menunggu tinjauan atau berapa lama dana boleh tertunda setelah barang diterima. Pantau pelanggaran batas itu. Kasus yang menggantung berminggu-minggu hampir selalu berujung keluhan, walau keputusan akhirnya sebenarnya menguntungkan pelanggan." },
  { type: "h2", text: "Mengukur kinerja proses retur" },
  { type: "p", text: "Beberapa indikator sederhana cukup untuk memantau proses ini. Pantau jumlah retur menurut alasan, produk, dan pemasok; waktu rata-rata dari pengajuan sampai dana kembali; proporsi barang retur yang bisa dijual lagi; serta selisih antara stok catatan dan stok fisik untuk barang retur. Hindari mengejar satu angka saja, misalnya tingkat retur serendah mungkin, karena dapat mendorong kebijakan yang menyulitkan pelanggan dan merugikan kepercayaan." },
  { type: "p", text: "Tinjau angka-angka ini secara berkala dan kaitkan dengan tindakan. Jika waktu proses memanjang, periksa tahap mana yang macet. Jika satu produk menonjol, selidiki sebabnya. Jika proporsi barang yang bisa dijual lagi rendah, tinjau kemasan pengiriman kembali dan standar pemeriksaan. Ukuran berguna hanya bila diikuti keputusan." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menyembunyikan kebijakan retur sehingga pelanggan baru menemukannya setelah ada masalah",
    "Menerima permintaan retur lewat banyak kanal tanpa pencatatan terpusat",
    "Menambah stok otomatis begitu paket tiba tanpa pemeriksaan",
    "Membiarkan barang retur menumpuk tanpa status dan tanpa keputusan",
    "Menunda pengembalian dana tanpa penjelasan dan tanpa batas waktu internal",
    "Tidak pernah membaca alasan retur sehingga masalah yang sama terus berulang",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Tulis atau rapikan kebijakan retur dalam bahasa sederhana dan tempatkan di halaman produk dan pembayaran",
    "Buat daftar alasan retur yang baku dan formulir permintaan yang menghasilkan nomor rujukan",
    "Sediakan area khusus dan daftar periksa di gudang untuk menerima dan memeriksa barang retur",
    "Hubungkan pengembalian dana dengan pembukuan dan stok sehingga tercatat sebagai transaksi yang terkait penjualan asal",
    "Baca alasan retur sebulan terakhir dan perbaiki satu penyebab terbesar pada deskripsi, foto, atau kemasan",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Retur yang dirancang dengan baik bukan beban, melainkan bagian dari layanan yang membangun kepercayaan. Kebijakan yang jelas, alur permintaan yang terdaftar, pemeriksaan yang konsisten, pengembalian dana yang tepat waktu, dan pencatatan stok serta keuangan yang rapi membuat pelanggan merasa aman berbelanja dan tim bekerja tanpa kebingungan." },
  { type: "p", text: "Gunakan data retur untuk memperbaiki sumber masalah, bukan hanya menangani akibatnya. Dengan begitu retur berkurang secara alami, pelanggan kembali berbelanja, dan toko Anda tumbuh di atas dasar yang lebih sehat." },
  {
    type: "cta",
    title: "Butuh sistem toko online yang menangani retur, stok, dan pembukuan secara terpadu?",
    text: "Tim AG·SORA membangun toko online dan sistem pendukung dengan alur retur yang terdaftar, pembaruan stok otomatis, dan pencatatan keuangan yang terhubung. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
