import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Bisnis jasa menjual sesuatu yang tidak bisa disimpan di gudang: waktu. Kursi salon yang kosong pada pukul dua siang, ruang praktik yang menganggur, lapangan yang tidak terpakai, atau teknisi yang menunggu tanpa pekerjaan adalah pendapatan yang hilang dan tidak bisa dijual kembali besok. Karena itu cara sebuah bisnis jasa mengatur jadwalnya sangat menentukan penghasilannya." },
  { type: "p", text: "Di banyak tempat, jadwal masih diatur lewat buku tulis, telepon, dan obrolan. Pelanggan mengirim pesan pada malam hari, baru dibalas keesokan paginya, lalu terjadi tawar-menawar waktu selama beberapa pesan. Sebagian pelanggan sudah memesan di tempat lain sebelum balasan tiba. Sebagian lagi datang pada jam yang ternyata sudah terisi karena dua petugas mencatat di tempat berbeda." },
  { type: "p", text: "Artikel ini membahas cara merancang sistem booking dan reservasi online untuk bisnis jasa, baik lewat website maupun aplikasi mobile. Kami membahas ketersediaan dan kapasitas, alur pemesanan, uang muka, pengingat, perubahan jadwal, hubungan dengan kasir dan data pelanggan, serta ukuran yang layak dipantau. Tidak ada angka rekaan di sini; yang kami tawarkan adalah prinsip yang bisa disesuaikan dengan jenis jasa Anda." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Booking online membuka pintu pemesanan di luar jam kerja dan mengurangi bolak-balik pesan",
      "Aturan ketersediaan harus mencerminkan keadaan nyata: durasi layanan, petugas, ruangan, dan jeda",
      "Pengingat otomatis dan uang muka adalah dua alat utama untuk mengurangi pelanggan yang tidak datang",
      "Satu kalender bersama mencegah pesanan ganda antara pesanan online, telepon, dan pelanggan langsung",
      "Riwayat kunjungan pelanggan menjadi dasar layanan yang lebih pribadi dan pemesanan ulang",
    ],
  },
  { type: "h2", text: "Mengapa pemesanan lewat obrolan tidak cukup" },
  { type: "p", text: "Memesan lewat obrolan terasa akrab, tetapi mahal bagi kedua pihak. Setiap pemesanan memerlukan beberapa pesan untuk mencari jam yang cocok, dan petugas yang seharusnya melayani pelanggan di tempat harus bolak-balik melihat ponsel. Pada jam sibuk, pesan menumpuk tanpa terbalas, dan justru pada saat itulah calon pelanggan paling banyak bertanya." },
  { type: "p", text: "Banyak orang memutuskan memesan jasa di luar jam kerja: malam hari setelah pulang, akhir pekan, atau saat istirahat. Jika pintu pemesanan hanya terbuka ketika admin sedang memegang ponsel, sebagian permintaan itu hilang. Sistem booking online menerima pesanan kapan saja dan langsung memberi kepastian, tanpa menunggu siapa pun." },
  { type: "p", text: "Buku jadwal manual juga tidak menyimpan pengetahuan. Ia tidak tahu pelanggan mana yang sering batal, layanan mana yang paling diminati pada hari apa, atau petugas mana yang jadwalnya selalu penuh. Semua informasi itu ada, tetapi tidak bisa ditanyakan. Sistem yang mencatat pemesanan secara terstruktur menjadikannya bahan keputusan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1556745757-8d76bdb6984b",
    alt: "Pemilik toko melayani transaksi menggunakan perangkat kasir tablet di meja kasir",
    caption: "Petugas yang tidak sibuk membalas pesan jadwal punya lebih banyak waktu untuk pelanggan di depannya.",
  },
  { type: "h2", text: "Jenis bisnis yang cocok" },
  { type: "p", text: "Hampir semua bisnis yang menjual waktu atau tempat bisa memanfaatkan booking online, walau bentuknya berbeda. Yang perlu dipahami adalah apa sebenarnya yang dipesan pelanggan, karena itulah yang menentukan rancangan sistemnya." },
  { type: "ul", items: [
    "Janji temu dengan petugas tertentu: salon, klinik, konsultan, bengkel, les privat",
    "Tempat duduk atau meja untuk jangka waktu tertentu: restoran dan kafe",
    "Ruang atau fasilitas per jam: lapangan olahraga, studio, ruang rapat",
    "Kursi dalam sesi berkapasitas terbatas: kelas kebugaran, pelatihan, tur",
    "Kunjungan petugas ke lokasi pelanggan: servis pendingin udara, kebersihan, perbaikan rumah",
    "Sewa per hari: penginapan, kendaraan, peralatan",
  ] },
  { type: "p", text: "Setiap jenis punya aturan sendiri. Janji temu bergantung pada jadwal orang, sesi kelas bergantung pada jumlah kursi, dan kunjungan ke lokasi bergantung pada waktu tempuh. Sistem yang cocok untuk salon belum tentu cocok untuk jasa servis keliling. Kenali jenis Anda sebelum memilih atau membangun alatnya." },
  { type: "h2", text: "Ketersediaan dan kapasitas: inti sistem" },
  { type: "p", text: "Bagian terpenting dari sistem booking adalah aturan yang menentukan jam mana yang boleh ditawarkan. Aturan ini harus mencerminkan keadaan nyata. Jika sistem menawarkan jam yang sebenarnya tidak bisa dilayani, pelanggan kecewa. Jika sistem terlalu berhati-hati, jam yang bisa dijual tampak penuh." },
  { type: "p", text: "Mulailah dari durasi tiap layanan, termasuk waktu persiapan dan pembersihan sesudahnya. Potong rambut dan pewarnaan memerlukan waktu yang sangat berbeda. Kemudian tetapkan siapa yang bisa mengerjakan layanan apa, jam kerja masing-masing, hari libur, dan jam istirahat. Bila layanan memerlukan ruangan atau alat tertentu, ketersediaannya juga harus diperhitungkan." },
  { type: "p", text: "Tambahkan aturan yang melindungi operasional: jeda antarjanji, batas paling cepat dan paling lambat pemesanan dapat dibuat, serta jumlah pesanan maksimal per jam. Untuk kunjungan ke lokasi, perhitungkan waktu perjalanan antaralamat. Aturan-aturan kecil inilah yang membedakan jadwal yang rapi di layar dari jadwal yang benar-benar bisa dijalankan." },
  { type: "callout", title: "Satu kalender untuk semua pintu", text: "Pesanan online, pesanan lewat telepon, dan pelanggan yang datang langsung harus masuk ke kalender yang sama. Begitu ada dua buku jadwal, pesanan ganda hanya soal waktu. Petugas depan perlu cara cepat untuk memasukkan pesanan manual ke sistem yang sama." },
  { type: "h2", text: "Alur pemesanan yang singkat" },
  { type: "p", text: "Pelanggan ingin memesan dalam hitungan detik. Alur yang baik hanya menanyakan hal yang diperlukan: layanan apa, dengan siapa bila relevan, tanggal dan jam berapa, lalu nama dan nomor yang bisa dihubungi. Setiap pertanyaan tambahan menambah kemungkinan pelanggan berhenti di tengah jalan." },
  { type: "ol", items: [
    "Pelanggan memilih layanan dan melihat harga serta perkiraan durasinya",
    "Pelanggan memilih petugas, atau membiarkan sistem memilihkan yang tersedia",
    "Sistem menampilkan hanya jam yang benar-benar kosong",
    "Pelanggan mengisi data kontak dan catatan singkat bila ada",
    "Pelanggan membayar uang muka bila diwajibkan",
    "Sistem mengirim konfirmasi beserta alamat, petunjuk, dan tautan untuk mengubah jadwal",
  ] },
  { type: "p", text: "Jangan mewajibkan pembuatan akun sebelum pelanggan boleh memesan. Tawarkan pembuatan akun setelah pemesanan selesai, ketika manfaatnya jelas: melihat riwayat, memesan ulang dengan cepat, dan menyimpan preferensi. Rancang alur ini untuk layar ponsel terlebih dahulu, karena di sanalah sebagian besar pemesanan dilakukan." },
  { type: "h2", text: "Mengurangi pelanggan yang tidak datang" },
  { type: "p", text: "Pelanggan yang memesan lalu tidak muncul adalah masalah klasik bisnis jasa. Jam yang sudah dicadangkan tidak bisa dijual kepada orang lain dan petugas menganggur. Sebagian besar ketidakhadiran bukan karena niat buruk; orang lupa, jadwalnya berubah, atau merasa sungkan membatalkan." },
  { type: "p", text: "Pengingat otomatis adalah obat pertama. Kirim pengingat sehari sebelumnya dan beberapa jam sebelum waktu janji, lewat kanal yang paling dibaca pelanggan Anda. Sertakan tautan untuk mengonfirmasi, mengubah, atau membatalkan dengan satu ketukan. Pelanggan yang diberi jalan mudah untuk membatalkan lebih mungkin memberi tahu daripada menghilang, sehingga jamnya masih bisa ditawarkan kepada orang lain." },
  { type: "p", text: "Alat kedua adalah uang muka atau jaminan. Pelanggan yang sudah membayar sebagian cenderung datang. Sesuaikan dengan jenis jasa dan kebiasaan pelanggan Anda; uang muka masuk akal untuk layanan berdurasi panjang, jam sibuk, atau pelanggan baru, tetapi bisa terasa berlebihan untuk layanan kecil bagi pelanggan tetap." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1556742111-a301076d9d18",
    alt: "Dua tangan melakukan pembayaran nirsentuh dengan ponsel pada mesin pembaca kartu",
    caption: "Uang muka yang dibayar saat memesan membuat pelanggan lebih mungkin hadir sesuai janji.",
  },
  { type: "h2", text: "Uang muka, pembayaran, dan kebijakan pembatalan" },
  { type: "p", text: "Jika Anda meminta uang muka, hubungkan sistem booking dengan penyedia pembayaran sehingga pesanan terkonfirmasi otomatis begitu dana diterima. Pesanan yang menunggu pembayaran sebaiknya menahan jam hanya untuk waktu singkat, lalu dilepas bila tidak dibayar, agar jam tidak tersandera." },
  { type: "p", text: "Tulis kebijakan pembatalan dengan jelas dan tampilkan sebelum pelanggan membayar: sampai kapan pembatalan masih mendapat pengembalian penuh, kapan uang muka hangus, dan apa yang terjadi bila pelanggan terlambat. Kebijakan yang diketahui sejak awal jarang menimbulkan sengketa. Sesuaikan isinya dengan ketentuan perlindungan konsumen yang berlaku." },
  { type: "p", text: "Pastikan uang muka tercatat dengan benar di pembukuan. Uang muka adalah titipan sampai layanan diberikan, dan harus dipotongkan dari tagihan akhir di kasir. Sistem booking yang tidak terhubung dengan kasir sering membuat petugas lupa memotongnya, atau memotongnya dua kali." },
  { type: "h2", text: "Perubahan jadwal dan daftar tunggu" },
  { type: "p", text: "Jadwal selalu berubah. Pelanggan ingin pindah jam, petugas sakit, atau layanan sebelumnya molor. Sistem yang baik memudahkan perubahan tanpa membuat kekacauan. Izinkan pelanggan memindahkan jadwalnya sendiri dalam batas yang Anda tetapkan, sehingga tidak semua perubahan harus melewati admin." },
  { type: "p", text: "Ketika bisnis yang harus mengubah jadwal, misalnya karena petugas berhalangan, sistem perlu membantu menemukan semua janji yang terdampak dan memberi tahu pelanggan dengan pilihan waktu pengganti. Menghubungi dua puluh pelanggan satu per satu pada pagi yang sibuk adalah resep untuk kesalahan." },
  { type: "p", text: "Daftar tunggu mengubah pembatalan menjadi kesempatan. Pelanggan yang menginginkan jam yang sudah penuh dapat mendaftar, dan ketika ada yang batal mereka diberi tahu secara otomatis. Jam sibuk yang kosong karena pembatalan mendadak sering bisa terisi kembali tanpa campur tangan petugas." },
  { type: "h2", text: "Mengenal pelanggan lewat riwayat kunjungan" },
  { type: "p", text: "Setiap pemesanan menambah catatan tentang pelanggan: layanan yang dipilih, petugas yang disukai, seberapa sering datang, dan catatan khusus seperti alergi atau preferensi. Bila tersimpan rapi, petugas dapat menyambut pelanggan dengan pengetahuan itu, dan pelanggan merasa dikenali walau dilayani oleh orang yang berbeda." },
  { type: "p", text: "Riwayat ini juga memungkinkan pengingat pemesanan ulang. Layanan yang berulang secara alami, seperti perawatan berkala atau servis rutin, dapat diingatkan ketika waktunya tiba. Pengingat seperti ini terasa sebagai bantuan, bukan promosi, asalkan pelanggan memang bersedia menerimanya." },
  { type: "p", text: "Karena data ini bersifat pribadi, dan dalam bidang seperti kesehatan sangat peka, perlakukan dengan hati-hati. Kumpulkan hanya yang diperlukan, batasi siapa yang boleh melihat, dan patuhi ketentuan pelindungan data pribadi yang berlaku. Untuk layanan kesehatan, periksa pula aturan khusus sektornya bersama penasihat yang memahami bidang itu." },
  { type: "h2", text: "Hubungan dengan kasir, ERP, dan kalender" },
  { type: "p", text: "Booking bukan pulau tersendiri. Ketika pelanggan datang, janji temunya berubah menjadi transaksi di kasir. Bila kedua sistem terhubung, petugas tinggal membuka janji tersebut dan menyelesaikan pembayaran, dengan uang muka sudah diperhitungkan. Bila tidak terhubung, data diketik dua kali dan laporan penjualan per layanan menjadi tidak akurat." },
  { type: "p", text: "Hubungan dengan data karyawan juga berguna. Jadwal kerja dan cuti yang tercatat di sistem kepegawaian dapat langsung memengaruhi ketersediaan, dan jumlah layanan yang dikerjakan tiap petugas dapat menjadi dasar perhitungan komisi. Tanpa hubungan itu, komisi dihitung manual dari catatan yang sering diperdebatkan." },
  { type: "p", text: "Banyak petugas juga mengandalkan kalender pribadi di ponselnya. Sinkronisasi dengan kalender tersebut mencegah bentrokan dengan urusan lain, tetapi atur dengan hati-hati agar rincian pelanggan tidak ikut tersebar ke tempat yang tidak semestinya." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1551650975-87deedd944c3",
    alt: "Tangan memegang ponsel yang menampilkan aplikasi dasbor dengan laptop di latar belakang",
    caption: "Jadwal yang bisa dilihat dari ponsel membantu pemilik dan petugas mengetahui keadaan hari itu dalam sekejap.",
  },
  { type: "h2", text: "Website, aplikasi, atau pihak ketiga" },
  { type: "p", text: "Ada beberapa tempat untuk menaruh pintu pemesanan. Halaman booking di website sendiri adalah dasar yang hampir selalu diperlukan, karena bisa ditautkan dari profil media sosial, peta, dan pesan. Aplikasi mobile masuk akal bila pelanggan Anda memesan berulang kali dan Anda ingin memberi pengalaman yang lebih pribadi dengan pemberitahuan dan pemesanan ulang cepat." },
  { type: "p", text: "Platform pemesanan pihak ketiga dapat mendatangkan pelanggan baru, tetapi biasanya memungut komisi dan memegang hubungan dengan pelanggan. Banyak bisnis memakai keduanya: platform untuk ditemukan orang baru, kanal sendiri untuk pelanggan yang kembali. Bila memakai beberapa pintu, pastikan semuanya tersinkron ke satu kalender." },
  { type: "p", text: "Untuk memilih antara layanan siap pakai dan sistem yang dibangun khusus, lihat kerumitan aturan Anda. Layanan siap pakai cukup untuk aturan yang umum. Sistem khusus menjadi layak ketika aturan ketersediaan Anda tidak biasa, ketika Anda memerlukan hubungan erat dengan kasir dan sistem lain, atau ketika pemesanan adalah inti pengalaman merek Anda." },
  { type: "h2", text: "Ukuran yang layak dipantau" },
  { type: "ul", items: [
    "Tingkat keterisian jadwal per hari, per jam, dan per petugas",
    "Proporsi janji yang tidak dihadiri dan yang dibatalkan mendadak",
    "Proporsi pemesanan yang dibuat secara online dibanding lewat telepon atau obrolan",
    "Jarak waktu antara pemesanan dibuat dan waktu layanan",
    "Proporsi pelanggan yang memesan kembali dalam jangka waktu yang wajar",
    "Jam dan hari yang selalu kosong atau selalu penuh",
  ] },
  { type: "p", text: "Angka-angka ini menuntun keputusan nyata. Jam yang selalu kosong bisa ditawarkan dengan harga berbeda atau dipakai untuk layanan lain. Jam yang selalu penuh mungkin menandakan perlunya menambah petugas. Petugas yang selalu penuh sementara yang lain longgar menunjukkan perlunya pembagian yang lebih baik atau pelatihan tambahan." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menjalankan dua buku jadwal sehingga pesanan ganda tidak terhindarkan",
    "Menawarkan jam tanpa memperhitungkan durasi layanan dan jeda",
    "Mewajibkan pembuatan akun sebelum pelanggan boleh memesan",
    "Tidak mengirim pengingat dan tidak menyediakan cara mudah untuk membatalkan",
    "Menyembunyikan kebijakan pembatalan dan uang muka",
    "Tidak menghubungkan booking dengan kasir sehingga uang muka tidak tercatat benar",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Daftar semua layanan beserta durasi nyata, termasuk waktu persiapan dan pembersihan",
    "Tulis jam kerja, hari libur, dan layanan yang dapat dikerjakan tiap petugas",
    "Hitung berapa janji yang tidak dihadiri dalam sebulan terakhir dari catatan yang ada",
    "Tulis kebijakan pembatalan dan uang muka dalam bahasa sederhana",
    "Satukan semua pesanan ke satu kalender, walau awalnya kalender bersama biasa",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Sistem booking online yang baik menjual waktu Anda dengan lebih efisien. Pelanggan memesan kapan saja tanpa menunggu balasan, jadwal terisi lebih rapat, ketidakhadiran berkurang, dan petugas bisa memusatkan perhatian pada pelanggan di depannya. Di baliknya ada aturan ketersediaan yang jujur, satu kalender bersama, pengingat yang tepat waktu, dan hubungan dengan kasir serta data pelanggan." },
  { type: "p", text: "Mulailah dari memahami apa yang sebenarnya dipesan pelanggan Anda dan aturan apa yang mengatur ketersediaannya. Setelah itu jelas, memilih atau membangun alatnya menjadi jauh lebih mudah, dan hasilnya langsung terlihat pada jadwal yang lebih penuh." },
  {
    type: "cta",
    title: "Ingin pelanggan bisa memesan jasa Anda kapan saja dari ponsel?",
    text: "Tim AG·SORA membangun sistem booking di website dan aplikasi mobile dengan aturan ketersediaan sesuai bisnis Anda, uang muka, pengingat otomatis, dan hubungan langsung ke kasir. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
