import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Pada tahap awal, gudang sering hanyalah sebuah ruangan atau rak di belakang toko. Pemilik tahu di mana setiap barang berada, dan stok bisa dihitung dengan mata. Seiring penjualan tumbuh, ruangan itu bertambah penuh, jumlah jenis barang bertambah, dan tidak ada lagi satu orang yang memegang semuanya di kepala." },
  { type: "p", text: "Gejalanya mudah dikenali: pesanan terlambat karena barang tidak ditemukan, stok di sistem berbeda dari yang ada di rak, barang menumpuk di sudut yang tak terlihat, dan karyawan baru memerlukan waktu lama untuk belajar letak barang. Semua itu mengonsumsi waktu dan uang tanpa terlihat di laporan laba rugi." },
  { type: "p", text: "Artikel ini membahas kapan bisnis perlu beralih dari pencatatan stok biasa ke sistem manajemen gudang, apa saja yang dikelolanya, dan bagaimana menerapkannya secara bertahap. Kami tidak mengklaim angka efisiensi tertentu; fokusnya adalah memahami masalah, memilih tingkat sistem yang sesuai, dan menghindari kerumitan yang tidak perlu." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Stok yang benar dimulai dari kebiasaan mencatat setiap pergerakan barang pada saat terjadinya",
      "Penomoran lokasi dan tata letak yang rapi sering memberi manfaat lebih besar daripada perangkat lunak canggih",
      "Pindai kode batang pada penerimaan, penyimpanan, pengambilan, dan pengiriman untuk mengurangi kesalahan",
      "Hitung stok secara bergilir dan selidiki selisih untuk menemukan akar masalahnya",
      "Pilih tingkat sistem sesuai kerumitan gudang Anda, bukan sesuai tren",
    ],
  },
  { type: "h2", text: "Apa bedanya pencatatan stok dan manajemen gudang" },
  { type: "p", text: "Pencatatan stok menjawab pertanyaan berapa jumlah barang yang kita punya. Sistem manajemen gudang menjawab pertanyaan yang lebih terperinci: di mana tepatnya barang itu, dalam keadaan apa, milik pesanan mana, dan apa yang harus dilakukan orang gudang berikutnya. Perbedaannya terletak pada lokasi dan pada alur kerja." },
  { type: "p", text: "Pada gudang kecil dengan sedikit jenis barang, pencatatan stok di sistem penjualan atau ERP sudah memadai. Pada gudang dengan banyak lokasi simpan, banyak jenis barang, tanggal kedaluwarsa, nomor lot, atau pesanan yang harus diambil dan dikemas dengan cepat, kebutuhan akan pengelolaan lokasi dan tugas mulai muncul." },
  { type: "p", text: "Penting dipahami bahwa manajemen gudang bukan hanya perangkat lunak. Ia adalah kombinasi tata letak, aturan kerja, kebiasaan pencatatan, dan alat bantu. Perangkat lunak tanpa disiplin akan menghasilkan data yang rapi tetapi salah; disiplin tanpa perangkat lunak sering sudah menyelesaikan sebagian besar masalah pada gudang yang masih sederhana." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d",
    alt: "Gudang distribusi besar dengan rak dan tumpukan kontainer kuning",
    caption: "Semakin besar gudang, semakin penting tata letak dan penomoran lokasi yang konsisten.",
  },
  { type: "h2", text: "Tanda gudang Anda sudah membutuhkan sistem yang lebih baik" },
  { type: "ul", items: [
    "Pesanan sering terlambat atau salah kirim karena barang salah ambil atau tidak ditemukan",
    "Stok di sistem sering berbeda dari hasil hitung fisik",
    "Penambahan karyawan gudang memerlukan waktu pelatihan yang panjang karena letak barang tidak terdokumentasi",
    "Ada barang yang menumpuk dan kedaluwarsa karena tidak terpantau urutan masuknya",
    "Waktu pengambilan barang terasa lama karena rute berkeliling gudang tidak teratur",
    "Pengembalian barang dan barang rusak tercampur dengan stok yang layak jual",
  ] },
  { type: "p", text: "Satu atau dua tanda saja belum tentu berarti harus membeli sistem baru. Sering kali perbaikan tata letak dan aturan sudah banyak membantu. Namun bila sebagian besar tanda terpenuhi dan bisnis terus tumbuh, perbaikan manual akan mencapai batasnya." },
  { type: "h2", text: "Fondasi: lokasi, kode, dan satuan yang konsisten" },
  { type: "p", text: "Sebelum memikirkan perangkat lunak, rapikan dasarnya. Beri setiap lokasi simpan kode yang unik dan mudah dibaca, misalnya berdasarkan area, lorong, rak, dan tingkat. Tempelkan label yang jelas sehingga siapa pun, termasuk karyawan baru, dapat menemukan lokasi tanpa bertanya." },
  { type: "p", text: "Pastikan setiap barang memiliki kode tunggal, satuan yang jelas, dan keterangan yang tidak ambigu. Barang yang sama tercatat dengan dua kode adalah awal dari selisih stok. Tetapkan juga satuan dasar dan aturan konversinya, misalnya satu dus berisi dua belas buah, agar penerimaan dan penjualan memakai ukuran yang sama." },
  { type: "p", text: "Rancang tata letak berdasarkan pergerakan. Barang yang sering diambil sebaiknya ditempatkan dekat area pengemasan dan pada ketinggian yang mudah dijangkau, sedangkan barang yang jarang bergerak dapat ditempatkan lebih jauh atau lebih tinggi. Tata letak yang mengikuti pergerakan memangkas jarak tempuh karyawan setiap hari." },
  { type: "h2", text: "Alur dasar: terima, simpan, ambil, kirim" },
  { type: "p", text: "Penerimaan barang adalah titik pertama kebenaran stok. Barang yang datang diperiksa terhadap pesanan pembelian dan surat jalan, dihitung, diperiksa kondisinya, lalu dicatat sebelum disimpan. Barang yang diterima tanpa dicatat hari ini akan menjadi selisih yang sulit dilacak bulan depan." },
  { type: "p", text: "Penyimpanan berarti mencatat lokasi tempat barang diletakkan. Pada sistem sederhana, ini cukup dengan memindai kode lokasi dan kode barang. Sistem kemudian tahu bahwa barang tertentu ada di lokasi tertentu, sehingga pengambilan dapat diarahkan dengan tepat." },
  { type: "p", text: "Pengambilan dan pengemasan mengubah pesanan menjadi paket. Daftar ambil yang disusun berdasarkan lokasi mengurangi jarak berjalan, dan pemindaian saat mengambil memastikan barang yang benar terambil. Pemeriksaan sebelum pengemasan menangkap kesalahan sebelum paket meninggalkan gudang, yang jauh lebih murah daripada menanganinya setelah sampai ke pelanggan." },
  { type: "callout", title: "Catat saat terjadi, bukan di akhir hari", text: "Pencatatan yang dilakukan di akhir hari bergantung pada ingatan dan rawan terlewat. Pencatatan yang dilakukan saat barang bergerak, misalnya lewat pemindai atau tablet, menghasilkan data yang benar-benar mencerminkan keadaan gudang saat ini." },
  { type: "h2", text: "Peran kode batang dan perangkat pindai" },
  { type: "p", text: "Kode batang mengubah pencatatan dari mengetik menjadi memindai. Memindai lebih cepat dan jauh lebih sedikit salah daripada mengetik kode barang. Perangkat yang dipakai bisa berupa pemindai khusus, ponsel, atau tablet dengan kamera, tergantung volume dan kondisi gudang Anda." },
  { type: "p", text: "Gunakan kode batang pada tiga titik utama: penerimaan, pengambilan, dan pengiriman. Bila memungkinkan, beri kode pada lokasi simpan juga. Dengan begitu, sistem dapat memeriksa bahwa barang yang benar diambil dari lokasi yang benar, dan memberi peringatan bila tidak cocok." },
  { type: "p", text: "Pertimbangkan kondisi nyata: sinyal jaringan di dalam gudang, kebersihan dan kelembapan, serta daya tahan baterai perangkat. Gudang yang sinyalnya lemah memerlukan perangkat yang dapat bekerja tanpa jaringan sementara dan menyinkronkan data kemudian." },
  { type: "h2", text: "Menghitung stok tanpa menghentikan operasi" },
  { type: "p", text: "Penghitungan besar yang menghentikan seluruh gudang sehari atau dua hari merugikan dan jarang menghasilkan angka yang benar-benar bersih. Alternatifnya adalah penghitungan bergilir: sebagian kecil lokasi atau barang dihitung setiap hari atau minggu, dengan barang bernilai tinggi dan bergerak cepat dihitung lebih sering." },
  { type: "p", text: "Setiap selisih adalah petunjuk. Alih-alih sekadar mengoreksi angka, selidiki penyebabnya: salah pindai, barang salah letak, kesalahan penerimaan, atau kehilangan. Pola yang berulang pada lokasi atau orang tertentu mengarah ke perbaikan proses, bukan sekadar koreksi." },
  { type: "p", text: "Catat setiap penyesuaian stok beserta alasannya dan siapa yang menyetujui. Penyesuaian tanpa catatan adalah celah penyalahgunaan sekaligus menghapus peluang belajar dari kesalahan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1553413077-190dd305871c",
    alt: "Lorong gudang dengan rak tinggi berisi tumpukan kardus",
    caption: "Lokasi yang diberi kode dan label jelas membuat pengambilan barang lebih cepat dan minim salah.",
  },
  { type: "h2", text: "Barang kedaluwarsa, lot, dan urutan keluar" },
  { type: "p", text: "Untuk barang yang memiliki masa simpan, seperti makanan, kosmetik, atau obat, pencatatan nomor lot dan tanggal kedaluwarsa menjadi penting. Barang yang lebih dulu kedaluwarsa harus keluar lebih dulu. Tanpa pencatatan, aturan ini hanya bergantung pada ingatan dan kebiasaan peletakan." },
  { type: "p", text: "Sistem dapat mengarahkan pengambilan berdasarkan tanggal kedaluwarsa terdekat dan memperingatkan barang yang mendekati batas. Ini mengurangi pemusnahan barang yang sebenarnya bisa dijual lebih awal, misalnya dengan promosi atau pengalihan ke kanal lain." },
  { type: "p", text: "Lot juga penting untuk penelusuran. Bila ada keluhan atau penarikan produk, Anda perlu tahu pelanggan mana yang menerima lot tertentu. Pencatatan yang rapi mengubah penarikan produk dari krisis menjadi tindakan terbatas dan terarah." },
  { type: "h2", text: "Retur, barang rusak, dan area karantina" },
  { type: "p", text: "Barang retur dan barang rusak sering menjadi sumber kekacauan stok. Bila dikembalikan ke rak yang sama tanpa pemeriksaan, barang cacat bisa terkirim lagi ke pelanggan. Siapkan area terpisah untuk barang yang menunggu pemeriksaan dan buat statusnya jelas di sistem." },
  { type: "p", text: "Setiap barang retur sebaiknya melewati pemeriksaan sederhana dengan hasil yang dicatat: layak jual, perlu perbaikan, kembali ke pemasok, atau dimusnahkan. Dengan begitu stok yang tersedia untuk dijual hanya berisi barang yang memang layak." },
  { type: "p", text: "Catat juga alasan retur. Pola alasan yang berulang, seperti ukuran tidak cocok atau kemasan rusak saat kirim, adalah informasi berharga bagi bagian pembelian, pemasaran, dan pengemasan." },
  { type: "h2", text: "Integrasi dengan toko online, kasir, dan keuangan" },
  { type: "p", text: "Gudang tidak berdiri sendiri. Penjualan dari toko online, kasir, dan marketplace harus mengurangi stok yang sama, dan penerimaan barang harus memperbarui nilai persediaan di keuangan. Bila sistem-sistem ini tidak terhubung, selisih akan muncul dan penelusurannya memakan waktu." },
  { type: "p", text: "Tetapkan satu sumber kebenaran untuk stok dan alirkan perubahan dari sana ke kanal lain. Stok yang berbeda antarkanal menyebabkan penjualan barang yang sebenarnya habis, pembatalan pesanan, dan kekecewaan pelanggan." },
  { type: "p", text: "Pertimbangkan juga stok pengaman per kanal bila perlu, agar satu kanal yang ramai tidak menghabiskan seluruh stok yang juga dijanjikan kepada kanal lain. Aturan ini sederhana tetapi mencegah banyak pembatalan." },
  { type: "h2", text: "Memilih tingkat sistem yang sesuai" },
  { type: "p", text: "Tidak semua gudang memerlukan sistem manajemen gudang penuh. Ada tiga tingkat yang umum. Pertama, modul persediaan dalam ERP atau sistem kasir dengan lokasi sederhana. Kedua, modul gudang dengan pemindaian dan daftar ambil. Ketiga, sistem manajemen gudang khusus dengan optimasi rute, gelombang pengambilan, dan otomasi." },
  { type: "p", text: "Pilih tingkat terendah yang menyelesaikan masalah Anda sekarang dan bisa berkembang. Sistem yang terlalu canggih membebani tim dengan proses yang tidak dibutuhkan, sedangkan yang terlalu sederhana cepat terlampaui. Tanyakan kepada calon penyedia bagaimana jalur peningkatannya." },
  { type: "p", text: "Libatkan orang gudang dalam pemilihan. Mereka yang akan memakainya setiap hari paling tahu kendala nyata, dan sistem yang tidak mereka terima akan dilewati dengan jalan pintas yang merusak data." },
  { type: "h2", text: "Mengukur kinerja gudang dengan indikator sederhana" },
  { type: "p", text: "Sistem yang baik memberi Anda angka yang bisa dipakai untuk memperbaiki pekerjaan. Mulailah dengan beberapa indikator: ketepatan stok, yaitu seberapa sering hitungan fisik cocok dengan sistem; ketepatan pesanan, yaitu berapa banyak paket yang dikirim sesuai pesanan; dan waktu proses, yaitu rentang dari pesanan masuk sampai paket diserahkan kepada kurir." },
  { type: "p", text: "Tambahkan indikator yang mencerminkan masalah Anda sendiri, seperti jumlah retur akibat salah kirim, persentase barang yang tidak ditemukan saat diambil, atau jumlah barang yang kedaluwarsa. Pilih sedikit indikator dan pantau secara konsisten; daftar panjang yang tidak dibaca tidak memperbaiki apa pun." },
  { type: "p", text: "Bagikan hasilnya kepada tim gudang secara terbuka dan rayakan perbaikan. Angka yang dipakai untuk menyalahkan orang membuat mereka menyembunyikan kesalahan, sedangkan angka yang dipakai untuk belajar bersama membuat masalah muncul lebih awal." },
  { type: "h2", text: "Keselamatan kerja dan kenyamanan karyawan gudang" },
  { type: "p", text: "Tata letak yang baik juga soal keselamatan. Lorong yang cukup lebar, barang berat di rak bawah, tangga yang aman, dan pencahayaan yang memadai mengurangi risiko cedera. Cedera bukan hanya masalah kemanusiaan; ia juga menghentikan pekerjaan dan menaikkan biaya." },
  { type: "p", text: "Perhatikan beban kerja yang diciptakan sistem. Pemindaian yang menambah banyak langkah pada setiap pekerjaan akan ditinggalkan. Rancang alur sehingga pencatatan terasa bagian alami dari pekerjaan, bukan beban tambahan yang harus dikerjakan sambil mengejar target." },
  { type: "p", text: "Lakukan pelatihan singkat dan berulang, bukan satu kali di awal. Karyawan baru, perubahan alur, dan perangkat yang diperbarui memerlukan penyegaran. Tunjuk satu atau dua orang yang paham sebagai tempat bertanya agar masalah kecil tidak menumpuk menjadi kebiasaan buruk." },
  { type: "h2", text: "Rencana peralihan agar operasi tetap berjalan" },
  { type: "p", text: "Peralihan ke sistem baru adalah momen paling rawan. Rencanakan di luar periode tersibuk, siapkan data induk yang bersih sebelum hari peralihan, dan lakukan hitung stok awal yang akurat. Data awal yang salah akan terbawa ke seluruh pekerjaan sesudahnya." },
  { type: "p", text: "Mulailah dari area atau kelompok barang terbatas sebagai percontohan, lalu perluas setelah alurnya terbukti. Jalankan sistem lama dan baru berdampingan dalam waktu singkat bila memungkinkan, sehingga Anda dapat membandingkan hasil dan menangkap kesalahan sebelum berdampak besar." },
  { type: "p", text: "Sediakan dukungan ekstra pada minggu-minggu pertama. Masalah kecil seperti label yang tidak terbaca atau perangkat yang kehilangan sinyal akan muncul, dan respons cepat menentukan apakah tim akan menerima atau menolak sistem baru." },
  { type: "h2", text: "Biaya dan manfaat yang perlu dihitung" },
  { type: "p", text: "Biaya sistem gudang tidak hanya perangkat lunaknya. Ada perangkat pindai, label dan pencetak, perapian rak, pelatihan, dan waktu tim selama peralihan. Catat semuanya agar perbandingan dengan manfaat menjadi jujur, dan jangan lupa biaya perawatan setelah sistem berjalan." },
  { type: "p", text: "Manfaatnya biasanya tersebar di banyak tempat dan perlu dihitung dengan hati-hati: berkurangnya salah kirim dan retur, berkurangnya barang kedaluwarsa atau hilang, waktu pengambilan yang lebih singkat, serta modal kerja yang lebih ringan karena stok lebih tepat. Gunakan data Anda sendiri sebagai dasar, bukan angka dari brosur." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Membeli sistem canggih sebelum tata letak dan penamaan barang dirapikan",
    "Mencatat pergerakan barang di akhir hari atau akhir pekan",
    "Mencampur barang retur dan rusak dengan stok yang layak jual",
    "Mengoreksi selisih stok tanpa menyelidiki penyebabnya",
    "Tidak melibatkan karyawan gudang dalam perancangan dan pelatihan",
    "Membiarkan stok berbeda antara kanal penjualan dan gudang",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Gambar denah gudang sederhana dan beri kode pada setiap lokasi simpan",
    "Tandai barang yang paling sering keluar dan pindahkan dekat area pengemasan",
    "Tetapkan aturan bahwa setiap penerimaan dan pengiriman dicatat saat terjadi",
    "Mulai penghitungan bergilir untuk sepuluh barang dengan nilai terbesar",
    "Siapkan area dan status terpisah untuk barang retur dan rusak",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Gudang yang tertata membuat seluruh bisnis lebih tenang: pesanan keluar tepat waktu, stok bisa dipercaya, dan pembelian dapat direncanakan dengan data. Sebaliknya, gudang yang berantakan merembes ke penjualan, layanan pelanggan, dan keuangan." },
  { type: "p", text: "Mulailah dari yang mendasar: lokasi yang jelas, kode yang konsisten, dan kebiasaan mencatat saat terjadi. Tambahkan pemindaian dan sistem yang lebih canggih sesuai pertumbuhan. Peningkatan bertahap yang disiplin hampir selalu mengungguli proyek besar yang terburu-buru." },
  {
    type: "cta",
    title: "Gudang makin penuh dan stok sulit dipercaya?",
    text: "Tim AG·SORA menerapkan ERP dan modul gudang dengan lokasi simpan, pemindaian kode batang, penghitungan bergilir, dan integrasi ke toko online serta kasir. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/erp",
    label: "Konsultasi gratis",
  },
];
