import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Pertanyaan pelanggan datang dari mana-mana: pesan percakapan, surel, telepon, kolom komentar media sosial, dan formulir di website. Pada awalnya satu atau dua orang menanganinya dari ponsel masing-masing. Ketika volume bertambah, mulailah muncul pertanyaan yang tidak terjawab, jawaban yang berbeda untuk masalah yang sama, dan pelanggan yang harus menjelaskan ulang ceritanya setiap kali berpindah petugas." },
  { type: "p", text: "Sistem tiket dukungan dirancang untuk merapikan kekacauan itu. Setiap permintaan menjadi satu tiket yang memiliki pemilik, status, riwayat, dan tenggat. Bagi pelanggan, ini berarti masalahnya tidak hilang. Bagi bisnis, ini berarti ada data tentang apa yang paling sering dikeluhkan dan seberapa cepat tim merespons." },
  { type: "p", text: "Artikel ini membahas cara merancang layanan dukungan yang tertib untuk bisnis kecil dan menengah: kapan sistem tiket diperlukan, bagaimana menyusun kategori dan prioritas, apa itu perjanjian tingkat layanan, bagaimana memakai basis pengetahuan, dan bagaimana mengukur mutu layanan tanpa terjebak angka. Tidak ada angka rekaan; yang kami berikan adalah kerangka kerja." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Satu permintaan, satu tiket, satu pemilik: pelanggan tidak perlu mengulang cerita",
      "Kumpulkan semua kanal ke satu antrean agar tidak ada yang terlewat",
      "Tetapkan kategori, prioritas, dan target waktu respons yang realistis",
      "Bangun basis pengetahuan dari pertanyaan yang paling sering muncul",
      "Ukur dengan beberapa indikator yang bermakna dan gunakan untuk memperbaiki proses",
    ],
  },
  { type: "h2", text: "Tanda Anda sudah memerlukan sistem tiket" },
  { type: "ul", items: [
    "Pelanggan harus menjelaskan ulang masalahnya kepada petugas yang berbeda",
    "Ada pesan yang tidak terjawab karena masuk ke ponsel pribadi atau kotak surat yang tidak dipantau",
    "Tidak ada yang tahu persis berapa permintaan yang sedang terbuka dan sudah berapa lama",
    "Pertanyaan yang sama dijawab berbeda oleh orang yang berbeda",
    "Tim tidak punya data tentang masalah apa yang paling sering muncul",
    "Ketika petugas cuti atau berhenti, riwayat percakapan ikut hilang",
  ] },
  { type: "p", text: "Sebagian bisnis kecil dapat bertahan lama dengan kotak masuk bersama yang rapi. Namun begitu lebih dari satu orang menangani permintaan atau volume mulai terasa, sistem yang memberi struktur akan menghemat waktu dan menjaga kepercayaan pelanggan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1626863905121-3b0c0ed7b94c",
    alt: "Dua perempuan memakai headset di ruang kerja kantor yang terang",
    caption: "Layanan dukungan yang baik dimulai dari antrean yang jelas dan riwayat yang bisa dilihat siapa pun yang menangani.",
  },
  { type: "h2", text: "Satu antrean untuk semua kanal" },
  { type: "p", text: "Pelanggan memilih kanal yang paling nyaman bagi mereka, bukan yang paling nyaman bagi Anda. Karena itu, kumpulkan permintaan dari surel, formulir, percakapan, dan kanal lain ke satu antrean. Petugas tidak perlu membuka lima aplikasi, dan tidak ada permintaan yang tertinggal di kanal yang jarang dibuka." },
  { type: "p", text: "Satukan juga identitas pelanggan. Bila orang yang sama menulis lewat surel kemarin dan lewat percakapan hari ini, riwayatnya sebaiknya terlihat dalam satu profil. Pelanggan merasa dikenali, dan petugas tidak mengulang pertanyaan yang sudah dijawab." },
  { type: "p", text: "Tentukan kanal mana yang Anda layani dan pada jam berapa. Lebih baik melayani tiga kanal dengan baik daripada tujuh kanal dengan setengah hati. Sampaikan jam layanan dengan jelas agar harapan pelanggan sesuai dengan kenyataan." },
  { type: "h2", text: "Merancang kategori, prioritas, dan status" },
  { type: "p", text: "Kategori membantu mengarahkan tiket ke orang yang tepat dan menghasilkan data yang berguna. Mulailah dengan sedikit kategori yang mencerminkan jenis masalah nyata: pesanan, pembayaran, pengiriman, akun, produk, dan lain-lain. Terlalu banyak kategori membuat petugas bingung dan data menjadi tidak konsisten." },
  { type: "p", text: "Prioritas menentukan urutan pengerjaan. Rancang dengan sederhana, misalnya tinggi untuk masalah yang menghentikan pelanggan menyelesaikan pembayaran atau akses, normal untuk pertanyaan biasa, dan rendah untuk saran. Tuliskan contoh agar semua petugas menilai dengan cara yang sama." },
  { type: "p", text: "Status menunjukkan posisi tiket: baru, sedang ditangani, menunggu pelanggan, menunggu pihak lain, dan selesai. Status yang jelas mencegah tiket diam tanpa ada yang tahu siapa yang sedang ditunggu. Tiket yang menunggu pelanggan sebaiknya otomatis ditutup setelah batas waktu tertentu dengan pemberitahuan terlebih dahulu." },
  { type: "h2", text: "Perjanjian tingkat layanan: janji yang bisa ditepati" },
  { type: "p", text: "Perjanjian tingkat layanan, sering disingkat SLA, adalah target waktu yang Anda tetapkan, misalnya waktu respons pertama dan waktu penyelesaian untuk tiap prioritas. Bagi pelanggan, SLA memberi kepastian. Bagi tim, SLA memberi ukuran jelas tentang apa yang harus dikerjakan lebih dulu." },
  { type: "p", text: "Kunci SLA yang sehat adalah realistis. Janji yang tidak bisa ditepati lebih merusak kepercayaan daripada janji yang lebih longgar tetapi selalu ditepati. Mulailah dari target yang sesuai kapasitas Anda saat ini, ukur selama beberapa bulan, lalu perketat bertahap." },
  { type: "p", text: "Bedakan waktu respons pertama dari waktu penyelesaian. Respons pertama menunjukkan bahwa permintaan diterima dan sedang ditangani, dan bisa sangat singkat. Penyelesaian bergantung pada kerumitan masalah. Hitung waktu hanya pada jam layanan yang Anda umumkan, dan jeda saat menunggu pelanggan." },
  { type: "callout", title: "Respons cepat bukan berarti selesai cepat", text: "Pelanggan paling terganggu oleh keheningan. Balasan singkat yang menyatakan bahwa tiket diterima, siapa yang menangani, dan kapan kabar berikutnya dapat diharapkan sudah menurunkan kecemasan secara signifikan, bahkan sebelum masalahnya selesai." },
  { type: "h2", text: "Basis pengetahuan: menjawab sekali, membantu berkali-kali" },
  { type: "p", text: "Pertanyaan yang sama muncul berulang. Alih-alih menjawab satu per satu, tulis jawaban terbaiknya sekali dalam bentuk artikel bantuan, lalu pakai berulang. Basis pengetahuan internal membantu petugas menjawab konsisten, sedangkan yang terbuka untuk pelanggan membantu mereka menyelesaikan masalah sendiri kapan saja." },
  { type: "p", text: "Bangun dari data. Lihat kategori dan pertanyaan yang paling sering muncul di tiket, lalu tulis artikel untuk sepuluh teratas lebih dulu. Gunakan bahasa pelanggan, bukan istilah internal, dan sertakan langkah yang jelas serta gambar bila membantu." },
  { type: "p", text: "Rawat secara berkala. Artikel yang usang lebih berbahaya daripada tidak ada artikel. Tetapkan pemilik tiap artikel, dan perbarui saat produk, harga, atau kebijakan berubah. Tiket yang diselesaikan dengan jawaban baru adalah kandidat untuk menjadi artikel baru." },
  { type: "h2", text: "Jawaban siap pakai dan otomasi yang membantu" },
  { type: "p", text: "Jawaban siap pakai mempercepat balasan untuk pertanyaan yang berulang, asalkan disesuaikan dengan konteks dan tidak terdengar seperti robot. Gunakan sebagai kerangka, lalu tambahkan nama pelanggan dan rincian yang relevan. Pelanggan cepat merasakan balasan yang disalin tanpa dibaca." },
  { type: "p", text: "Otomasi yang bermanfaat meliputi penetapan tiket ke orang atau tim berdasarkan kategori, pengingat saat tiket mendekati batas waktu, penutupan otomatis tiket yang lama menunggu pelanggan, dan survei kepuasan singkat setelah tiket selesai. Otomasi ini mengurangi pekerjaan administratif, bukan percakapan manusia." },
  { type: "p", text: "Bila memakai asisten percakapan otomatis, jelaskan batasnya dan sediakan jalur mudah untuk berbicara dengan manusia. Asisten yang menjebak pelanggan dalam lingkaran jawaban yang tidak relevan merusak reputasi lebih cepat daripada tidak ada asisten sama sekali." },
  { type: "h2", text: "Eskalasi dan kerja sama antarbagian" },
  { type: "p", text: "Banyak tiket tidak bisa diselesaikan oleh petugas dukungan sendiri. Masalah pembayaran perlu bagian keuangan, masalah pengiriman perlu gudang, dan bug perlu pengembang. Tetapkan jalur eskalasi yang jelas: kepada siapa, lewat apa, dan berapa lama mereka diharapkan menanggapi." },
  { type: "p", text: "Pastikan tiket tetap terlihat oleh petugas dukungan selama ditangani pihak lain, sehingga mereka bisa memberi kabar kepada pelanggan. Pelanggan tidak peduli bagian mana yang sedang bekerja; mereka ingin tahu bahwa masalahnya bergerak." },
  { type: "p", text: "Bagikan temuan kepada bagian lain secara berkala. Tiket adalah sumber masukan paling jujur tentang produk dan layanan. Pola keluhan yang berulang seharusnya sampai kepada orang yang bisa memperbaiki penyebabnya, bukan berhenti di meja dukungan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1531482615713-2afd69097998",
    alt: "Beberapa anggota tim berdiskusi sambil melihat layar komputer di ruang kerja",
    caption: "Pola keluhan dari tiket menjadi bahan diskusi lintas bagian untuk memperbaiki penyebabnya.",
  },
  { type: "h2", text: "Mengukur mutu layanan dengan bijak" },
  { type: "p", text: "Pilih sedikit indikator yang benar-benar dipakai: waktu respons pertama, waktu penyelesaian, jumlah tiket terbuka, persentase tiket yang selesai pada kontak pertama, dan kepuasan pelanggan. Kombinasi ini memberi gambaran kecepatan, efektivitas, dan rasa." },
  { type: "p", text: "Waspadai angka yang mudah dipermainkan. Bila tim dinilai hanya dari kecepatan menutup tiket, tiket akan ditutup sebelum masalahnya selesai. Gabungkan ukuran kecepatan dengan ukuran hasil, dan sesekali baca langsung percakapan untuk menilai mutu yang tidak tertangkap angka." },
  { type: "p", text: "Gunakan data untuk belajar, bukan untuk menghukum. Tinjau tiket yang bermasalah bersama tim: apa yang membuatnya lama, apa yang bisa dicegah, dan apa yang perlu ditambahkan ke basis pengetahuan. Tim yang merasa aman membicarakan kesalahan akan memperbaiki proses lebih cepat." },
  { type: "h2", text: "Nada, empati, dan keterampilan petugas" },
  { type: "p", text: "Sistem hanyalah kerangka; yang dirasakan pelanggan adalah manusia di balik tiket. Latih petugas untuk membaca masalah dengan teliti sebelum menjawab, mengakui kekesalan pelanggan tanpa defensif, dan menjelaskan langkah berikutnya dengan jelas." },
  { type: "p", text: "Buat panduan nada yang sederhana: sapaan, cara meminta maaf, cara menolak permintaan yang tidak bisa dipenuhi, dan cara menutup percakapan. Panduan ini menjaga konsistensi tanpa mematikan kepribadian." },
  { type: "p", text: "Berikan petugas wewenang yang cukup untuk menyelesaikan masalah umum tanpa selalu meminta persetujuan atasan, misalnya pengembalian dana kecil atau penggantian barang. Pelanggan menghargai penyelesaian di tempat, dan tim merasa dipercaya." },
  { type: "h2", text: "Privasi dan keamanan data pelanggan" },
  { type: "p", text: "Tiket sering memuat data pribadi dan kadang informasi sensitif. Batasi siapa yang bisa melihat apa, hindari meminta pelanggan mengirim kata sandi atau data kartu lewat tiket, dan sediakan cara aman untuk menerima dokumen bila memang diperlukan." },
  { type: "p", text: "Tetapkan berapa lama riwayat disimpan dan bagaimana permintaan penghapusan data ditangani. Rincian kewajiban hukum dapat berbeda dan berubah, sehingga rujuk aturan perlindungan data pribadi yang berlaku saat ini dan konsultasikan dengan penasihat hukum bila perlu." },
  { type: "p", text: "Pastikan akses ke sistem tiket diamankan dengan verifikasi dua langkah dan dicabut saat petugas berhenti. Riwayat percakapan pelanggan adalah aset sekaligus tanggung jawab." },
  { type: "h2", text: "Menangani pelanggan yang sedang kesal" },
  { type: "p", text: "Cepat atau lambat, setiap tim dukungan menghadapi pelanggan yang marah. Hal pertama yang perlu diingat adalah bahwa kemarahan biasanya ditujukan pada masalah, bukan pada petugas. Respons yang baik dimulai dengan mengakui dampak masalah itu bagi pelanggan, lalu menjelaskan apa yang akan dilakukan dan kapan." },
  { type: "p", text: "Hindari kalimat yang terdengar membela diri atau menyalahkan, seperti itu bukan kesalahan kami. Fokuslah pada penyelesaian, dan jujur tentang apa yang tidak bisa dilakukan. Pelanggan lebih bisa menerima penolakan yang jelas dan sopan daripada janji kosong yang tidak ditepati." },
  { type: "p", text: "Sediakan jalur untuk situasi yang memanas: petugas boleh meminta rekan senior mengambil alih, dan kasus yang menyangkut keselamatan, uang besar, atau potensi masalah hukum diteruskan kepada penanggung jawab. Petugas yang merasa didukung akan menangani tekanan dengan lebih baik." },
  { type: "h2", text: "Dukungan proaktif: mengabari sebelum ditanya" },
  { type: "p", text: "Sebagian besar tiket muncul karena pelanggan tidak tahu apa yang sedang terjadi: di mana pesanan saya, mengapa saya ditagih, kapan masalah ini selesai. Pemberitahuan proaktif mencegah banyak tiket sebelum dibuat. Kabari saat pesanan dikirim, saat ada keterlambatan, dan saat gangguan layanan terjadi." },
  { type: "p", text: "Saat ada gangguan yang memengaruhi banyak pelanggan, siapkan satu pesan yang jelas dan pasang di tempat yang mudah dilihat, termasuk di kanal dukungan. Satu pengumuman yang jujur lebih baik daripada ratusan balasan individual yang berisi hal yang sama." },
  { type: "p", text: "Ubah pola tiket menjadi perbaikan produk. Bila banyak pelanggan bertanya cara melakukan sesuatu, mungkin antarmukanya yang perlu diperjelas. Bila banyak yang bertanya status pesanan, mungkin halaman pelacakan perlu diperbaiki. Dukungan terbaik adalah yang membuat dukungan makin jarang diperlukan." },
  { type: "h2", text: "Menyiapkan tim saat volume melonjak" },
  { type: "p", text: "Kampanye besar, peluncuran produk, atau musim belanja akan menaikkan volume permintaan secara tiba-tiba. Rencanakan sebelumnya: tambahkan artikel bantuan untuk pertanyaan yang diperkirakan muncul, siapkan jawaban siap pakai, dan tentukan siapa yang menjadi cadangan." },
  { type: "p", text: "Tentukan aturan prioritas khusus untuk masa sibuk, misalnya masalah pembayaran dan pengiriman didahulukan dibanding pertanyaan umum. Komunikasikan kepada pelanggan bila waktu respons akan lebih lama dari biasa; transparansi mengurangi tekanan pada tim." },
  { type: "p", text: "Setelah masa sibuk berlalu, lakukan tinjauan singkat: apa yang terlewat, apa yang berhasil, dan apa yang perlu disiapkan lebih awal pada musim berikutnya. Setiap lonjakan adalah latihan yang membuat tim lebih siap." },
  { type: "h2", text: "Memilih alat yang sesuai skala" },
  { type: "p", text: "Pilihan alat mulai dari kotak masuk bersama dengan fitur penugasan, sistem tiket khusus, hingga modul layanan pelanggan di dalam CRM. Pilih yang paling sederhana yang memenuhi kebutuhan Anda sekarang dan dapat tumbuh. Kemampuan yang paling penting adalah antrean bersama, riwayat per pelanggan, penugasan, dan laporan dasar." },
  { type: "p", text: "Periksa integrasinya dengan sistem lain. Petugas yang dapat melihat riwayat pesanan, pembayaran, dan pengiriman pelanggan dari dalam tiket menyelesaikan masalah jauh lebih cepat daripada yang harus berpindah-pindah aplikasi." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Membiarkan permintaan tersebar di ponsel pribadi dan kotak surat berbeda",
    "Menetapkan SLA yang terlalu ambisius sehingga selalu dilanggar",
    "Membuat terlalu banyak kategori dan status yang membingungkan",
    "Menutup tiket demi angka tanpa memastikan masalahnya selesai",
    "Menulis basis pengetahuan sekali lalu tidak pernah memperbaruinya",
    "Mengandalkan asisten otomatis tanpa jalur mudah menuju manusia",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Daftar semua kanal tempat pelanggan menghubungi Anda dan siapa yang memantau masing-masing",
    "Kumpulkan sepuluh pertanyaan yang paling sering muncul dan tulis jawaban terbaiknya",
    "Tetapkan tiga kategori dan tiga prioritas awal dengan contoh jelas",
    "Tentukan target waktu respons pertama yang bisa Anda tepati",
    "Pilih satu orang sebagai pemilik kualitas layanan dan basis pengetahuan",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Layanan dukungan yang baik membuat pelanggan merasa didengar dan masalahnya bergerak. Itu bukan hasil dari alat tertentu, melainkan dari kebiasaan: satu antrean, pemilik yang jelas, janji yang realistis, dan belajar dari pola keluhan." },
  { type: "p", text: "Sistem tiket membantu menjalankan kebiasaan itu secara konsisten saat volume tumbuh. Mulailah sederhana, ukur dengan bijak, dan perbaiki bertahap. Pelanggan yang puas dengan penanganan masalahnya sering menjadi pelanggan yang paling setia." },
  {
    type: "cta",
    title: "Pertanyaan pelanggan tersebar dan sulit dipantau?",
    text: "Tim AG·SORA membantu menerapkan CRM dan sistem tiket yang menyatukan semua kanal, lengkap dengan kategori, target layanan, dan basis pengetahuan. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/crm",
    label: "Konsultasi gratis",
  },
];
