import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Setiap bisnis yang mulai serius mendigitalkan operasionalnya akan menghadapi satu pertanyaan besar: siapa yang akan membangun dan merawat semua ini? Apakah merekrut tim pengembang sendiri, menyerahkannya kepada vendor atau software house, atau menggabungkan keduanya? Jawabannya memengaruhi biaya, kecepatan, kendali atas sistem, dan seberapa tenang Anda saat ada masalah di tengah malam." },
  { type: "p", text: "Tidak ada jawaban tunggal yang benar untuk semua bisnis. Perusahaan rintisan yang produk intinya adalah software berbeda kebutuhannya dengan toko ritel yang hanya butuh sistem kasir dan website. Bisnis dengan anggaran terbatas dan kebutuhan yang jelas punya pertimbangan lain dari perusahaan besar yang sistemnya berubah setiap bulan. Keputusan yang tepat bergantung pada tahap, skala, dan sifat kebutuhan Anda." },
  { type: "p", text: "Artikel ini membantu pemilik bisnis menimbang tiga model: tim internal, vendor eksternal, dan model gabungan. Kami membahas kelebihan dan kekurangan masing-masing, hal-hal yang sering luput dihitung, tanda-tanda model mana yang cocok, serta cara mengatur kerja sama agar tidak ada pihak yang dirugikan. Kami tidak memakai angka gaji atau tarif tertentu karena sangat bervariasi menurut wilayah, pengalaman, dan waktu; gunakan pembanding terkini dari pasar Anda sendiri." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Ada tiga model utama: tim internal, vendor eksternal, dan gabungan; masing-masing punya pertukaran antara biaya, kendali, kecepatan, dan risiko",
      "Tim internal unggul pada kendali dan pemahaman bisnis jangka panjang, tetapi menuntut biaya tetap, perekrutan, dan pengelolaan",
      "Vendor unggul pada kecepatan memulai dan keahlian beragam, tetapi menuntut spesifikasi jelas, kontrak yang baik, dan pengelolaan hubungan",
      "Model gabungan sering paling realistis: vendor untuk pembangunan awal dan keahlian khusus, orang internal sebagai pemilik produk dan penjaga pengetahuan",
      "Apa pun modelnya, pastikan Anda memiliki dokumentasi, akses, dan pengetahuan inti agar tidak tersandera satu pihak",
    ],
  },
  { type: "h2", text: "Mengapa keputusan ini lebih besar dari kelihatannya" },
  { type: "p", text: "Pertanyaan \"bikin sendiri atau serahkan ke vendor\" tampak seperti keputusan pengadaan biasa, padahal ia menentukan struktur biaya dan risiko bisnis selama bertahun-tahun. Sistem digital bukan pembelian sekali jadi. Ia perlu dirawat, diperbarui, diamankan, dan disesuaikan ketika bisnis berubah. Siapa yang melakukan semua itu, dan bagaimana mereka dibayar, akan terasa lama setelah proyek awal selesai." },
  { type: "p", text: "Ada pula dimensi pengetahuan. Orang yang membangun sistem memahami mengapa ia dirancang begitu, di mana titik rapuhnya, dan bagaimana memperbaikinya dengan cepat. Jika pengetahuan itu hanya ada di kepala satu orang atau satu perusahaan di luar Anda, Anda berada dalam posisi rentan. Jika orang itu pergi atau vendor berhenti beroperasi, Anda menghadapi sistem yang tidak dipahami siapa pun." },
  { type: "p", text: "Karena itu, jangan memutuskan hanya berdasarkan biaya di bulan pertama. Pertimbangkan biaya total selama beberapa tahun, risiko ketergantungan, kecepatan menghadapi perubahan, dan seberapa strategis sistem itu bagi bisnis Anda. Sistem yang menjadi inti keunggulan kompetitif layak mendapat kendali lebih besar daripada sistem pendukung yang fungsinya mirip dengan milik perusahaan lain." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1553028826-f4804a6dba3b",
    alt: "Tim bekerja dengan laptop di sebuah meja kerja bersama yang panjang",
    caption: "Siapa yang membangun dan merawat sistem sama pentingnya dengan sistem apa yang dibangun.",
  },
  { type: "h2", text: "Model pertama: tim internal" },
  { type: "p", text: "Dalam model ini, Anda mempekerjakan pengembang, perancang, dan mungkin penguji sebagai karyawan. Tim bekerja penuh waktu pada sistem perusahaan Anda, memahami bisnis dari dalam, dan berada dalam jangkauan sehari-hari." },
  { type: "p", text: "Kelebihan utamanya adalah kendali dan pemahaman. Tim internal belajar bisnis Anda dari waktu ke waktu, sehingga rekomendasi dan solusinya makin tepat. Perubahan kecil bisa dikerjakan cepat tanpa negosiasi kontrak atau antrean di vendor. Pengetahuan tentang sistem tersimpan di dalam perusahaan, dan prioritas tim sepenuhnya mengikuti prioritas bisnis Anda. Untuk sistem yang menjadi inti usaha dan berubah sering, model ini sangat masuk akal." },
  { type: "p", text: "Namun kekurangannya nyata. Biaya bersifat tetap: gaji, tunjangan, perangkat, dan pelatihan dibayar setiap bulan, baik pekerjaan sedang padat maupun sepi. Merekrut pengembang yang baik memakan waktu dan upaya, dan tim kecil rentan terhadap kepergian satu orang. Sulit mendapatkan semua keahlian sekaligus: satu orang jarang ahli pada tampilan, server, keamanan, dan aplikasi seluler sekaligus. Dan tim memerlukan pengelolaan yang baik, termasuk pemimpin teknis yang mampu mengarahkan kualitas." },
  { type: "p", text: "Model ini paling cocok jika sistem digital adalah pusat bisnis, kebutuhan perubahan konstan, dan anggaran mendukung biaya tetap. Untuk bisnis kecil dengan kebutuhan terbatas, tim internal penuh waktu sering berlebihan dan sulit diisi dengan pekerjaan yang cukup." },
  { type: "h3", text: "Hal yang sering luput dihitung" },
  { type: "p", text: "Gaji hanyalah sebagian biaya. Tambahkan biaya perekrutan, perangkat dan lisensi, pelatihan, tunjangan, ruang kerja, dan waktu manajemen yang diperlukan untuk memimpin tim teknis. Pertimbangkan pula biaya ketika seseorang keluar: waktu mencari pengganti dan pengetahuan yang ikut hilang jika tidak terdokumentasi." },
  { type: "h2", text: "Model kedua: vendor atau software house eksternal" },
  { type: "p", text: "Dalam model ini, Anda menugaskan pihak luar untuk membangun, dan kadang merawat, sistem. Vendor datang dengan tim, proses, dan pengalaman dari banyak proyek lain." },
  { type: "p", text: "Kelebihan utamanya adalah kecepatan memulai dan keahlian beragam. Anda tidak perlu merekrut; vendor dapat memulai dalam waktu relatif singkat dengan tim yang sudah terbentuk. Mereka biasanya membawa perspektif dari berbagai industri dan pola solusi yang sudah teruji. Biaya cenderung terikat pada proyek, sehingga lebih mudah dianggarkan untuk kebutuhan yang jelas dan terbatas. Untuk proyek sekali jalan, keahlian yang tidak dibutuhkan terus-menerus, atau tenggat yang ketat, vendor sering lebih efisien." },
  { type: "p", text: "Kekurangannya juga perlu dilihat. Vendor tidak otomatis mengerti bisnis Anda sedalam orang internal; Anda perlu menjelaskan kebutuhan dengan jelas dan terlibat aktif. Kualitas sangat bervariasi antar vendor, sehingga pemilihan yang teliti penting. Perubahan di tengah jalan bisa memerlukan negosiasi dan biaya tambahan. Dan ada risiko ketergantungan: jika pengetahuan dan kode hanya ada di vendor, berpindah ke pihak lain bisa sulit dan mahal." },
  { type: "p", text: "Model ini cocok untuk kebutuhan yang terdefinisi baik, proyek dengan batas jelas, bisnis yang belum memiliki kapasitas merekrut tim teknis, dan keahlian khusus yang jarang dipakai. Sebelum memilih vendor, pelajari panduan kami tentang membaca proposal software house dan daftar periksa memilih vendor agar keputusan Anda berdasar." },
  { type: "h3", text: "Mengelola vendor dengan baik" },
  { type: "p", text: "Hubungan dengan vendor berhasil bila ada kejelasan. Tuliskan ruang lingkup, hasil yang diharapkan, jadwal, dan cara menangani perubahan. Tentukan siapa dari pihak Anda yang menjadi penghubung dan pengambil keputusan, agar vendor tidak menunggu lama atau menerima instruksi yang bertentangan. Lakukan tinjauan kemajuan berkala dan uji hasil secara bertahap, bukan hanya di akhir. Pastikan kepemilikan kode, dokumentasi, dan akses diatur jelas dalam kontrak, sebagaimana dibahas dalam artikel kami tentang poin penting kontrak pengembangan software." },
  { type: "h2", text: "Model ketiga: gabungan" },
  { type: "p", text: "Banyak bisnis menemukan bahwa jawaban terbaik ada di tengah. Dalam model gabungan, pembagian peran dirancang agar masing-masing pihak mengerjakan hal yang paling cocok bagi mereka." },
  { type: "p", text: "Pola yang umum dan masuk akal adalah menempatkan satu atau dua orang internal sebagai pemilik produk atau penghubung teknis, sementara pekerjaan pembangunan dan keahlian khusus dikerjakan vendor. Orang internal memahami bisnis, menetapkan prioritas, menguji hasil dari sudut pandang pengguna, dan menjaga pengetahuan inti di dalam perusahaan. Vendor menyediakan kapasitas pembangunan dan keahlian yang tidak perlu Anda miliki tetap." },
  { type: "p", text: "Pola lain adalah vendor membangun sistem awal, lalu tim internal yang lebih kecil mengambil alih perawatan dan perubahan kecil harian, dengan vendor tetap tersedia untuk pekerjaan besar atau masalah rumit. Pola ini menjaga biaya tetap moderat sambil memberi Anda kendali sehari-hari." },
  { type: "p", text: "Model gabungan menuntut koordinasi yang baik, karena ada lebih banyak pihak yang harus selaras. Tetapkan batas tanggung jawab dengan jelas, jalur komunikasi yang rutin, dan standar bersama untuk dokumentasi serta kualitas. Tanpa itu, model gabungan bisa berubah menjadi saling menunjuk ketika terjadi masalah." },
  {
    type: "callout",
    title: "Peran internal yang paling penting",
    text: "Bahkan jika seluruh pembangunan diserahkan ke vendor, tetap tunjuk satu orang internal yang bertanggung jawab atas sistem: memahami tujuannya, memegang akses penting, dan menjadi lawan bicara vendor. Tanpa peran ini, tidak ada yang memiliki keputusan di pihak Anda.",
  },
  { type: "h2", text: "Membandingkan ketiga model" },
  { type: "p", text: "Perbandingan berikut membantu melihat pertukaran utama. Ini bukan aturan baku, tetapi kerangka berpikir." },
  {
    type: "ul",
    items: [
      "Biaya awal: vendor dan gabungan sering lebih rendah di awal; tim internal membutuhkan komitmen biaya tetap sejak perekrutan",
      "Biaya jangka panjang: tergantung volume pekerjaan; jika pekerjaan konstan dan besar, tim internal bisa lebih ekonomis, sedangkan untuk pekerjaan sporadis vendor sering lebih efisien",
      "Kecepatan memulai: vendor biasanya paling cepat; perekrutan tim internal butuh waktu",
      "Kendali dan prioritas: tim internal paling tinggi; vendor perlu dikelola lewat kontrak dan komunikasi",
      "Pengetahuan bisnis: tim internal tumbuh paling dalam seiring waktu; vendor perlu waktu dan penjelasan",
      "Keragaman keahlian: vendor biasanya lebih luas; tim internal kecil terbatas pada keahlian yang dimiliki",
      "Risiko ketergantungan: tim internal bergantung pada orang kunci; vendor bergantung pada hubungan dan dokumentasi",
      "Beban pengelolaan: tim internal menuntut pengelolaan karyawan; vendor menuntut pengelolaan kontrak dan proyek",
    ],
  },
  { type: "p", text: "Jangan menafsirkan daftar ini sebagai skor yang dijumlahkan. Beberapa faktor jauh lebih penting bagi bisnis tertentu daripada yang lain. Untuk bisnis yang sangat menghargai kecepatan peluncuran, faktor kecepatan memulai bisa mengalahkan semua yang lain. Untuk bisnis yang sistemnya menyimpan rahasia dagang atau keunggulan utama, kendali dan pengetahuan di dalam perusahaan bisa menjadi pertimbangan utama." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf",
    alt: "Dua rekan kerja saling tos di meja rapat",
    caption: "Kerja sama yang sehat antara tim internal dan vendor lahir dari peran yang jelas dan tujuan yang sama.",
  },
  { type: "h2", text: "Pertanyaan yang membantu menentukan pilihan" },
  { type: "p", text: "Alih-alih langsung memilih model, jawab beberapa pertanyaan berikut dengan jujur. Jawabannya biasanya mengarahkan Anda dengan sendirinya." },
  {
    type: "ol",
    items: [
      "Seberapa strategis sistem ini? Jika ia inti keunggulan bisnis Anda, kendali dan pengetahuan internal makin penting",
      "Seberapa sering sistem akan berubah? Perubahan konstan mendukung tim internal; perubahan jarang cocok dengan vendor atau dukungan berkala",
      "Seberapa jelas kebutuhan Anda? Kebutuhan yang terdefinisi baik memudahkan vendor bekerja dengan harga dan jadwal yang pasti",
      "Apa kapasitas anggaran dan manajemen Anda? Tim internal butuh komitmen biaya tetap dan kemampuan memimpin pekerjaan teknis",
      "Seberapa cepat Anda perlu hasil? Tenggat ketat sering mengarah ke vendor atau model gabungan",
      "Apa risiko jika sistem berhenti? Sistem yang kritis memerlukan rencana dukungan yang kuat, apa pun modelnya",
      "Siapa yang akan memegang pengetahuan jangka panjang? Pastikan jawabannya bukan hanya satu orang atau satu pihak luar tanpa cadangan",
    ],
  },
  { type: "p", text: "Pertimbangkan juga tahap bisnis. Pada tahap awal, ketika kebutuhan masih berubah dan anggaran ketat, vendor atau platform siap pakai biasanya lebih masuk akal. Ketika bisnis tumbuh dan sistem menjadi pusat, perlahan membangun kapasitas internal menjadi layak. Model yang tepat hari ini mungkin bukan yang tepat tiga tahun lagi, dan tidak apa-apa berpindah seiring pertumbuhan." },
  { type: "h2", text: "Melindungi diri dari ketergantungan" },
  { type: "p", text: "Apa pun model yang dipilih, lindungi bisnis Anda dari ketergantungan pada satu pihak. Beberapa praktik sederhana sangat membantu. Pastikan Anda memegang akun dan akses ke hal penting seperti nama domain, hosting, penyimpanan kode, dan layanan pihak ketiga, bukan hanya vendor atau karyawan tertentu. Minta dokumentasi yang memadai: cara sistem bekerja, cara dipasang, dan cara dipulihkan." },
  { type: "p", text: "Atur kepemilikan dalam kontrak dengan jelas, termasuk hak atas kode sumber dan data. Simpan cadangan secara berkala di tempat yang Anda kendalikan. Jika memakai vendor, tanyakan apa yang terjadi jika kerja sama berakhir dan bagaimana proses serah terimanya. Jika memakai karyawan, dorong kebiasaan mendokumentasikan dan berbagi pengetahuan agar tidak ada informasi yang hanya hidup di satu kepala." },
  { type: "p", text: "Terakhir, ujilah ketahanannya. Tanyakan, apa yang terjadi jika orang kunci pergi besok, atau vendor tiba-tiba tidak merespons? Jika jawabannya adalah kekacauan, perkuat dokumentasi dan pembagian pengetahuan sekarang, selagi semuanya tenang." },
  { type: "h2", text: "Keputusan bertahap: mulai kecil, ubah bila perlu" },
  { type: "p", text: "Anda tidak harus memutuskan model final sejak awal. Pendekatan bertahap sering lebih bijak. Mulailah dengan proyek yang terdefinisi baik bersama vendor atau platform siap pakai, pelajari kebutuhan nyata, lalu evaluasi. Jika sistem terbukti penting dan terus berubah, mulailah membangun kapasitas internal secara bertahap, misalnya dengan satu orang sebagai pemilik produk. Jika kebutuhan stabil, pertahankan dukungan vendor berkala." },
  { type: "p", text: "Evaluasi model Anda secara berkala, misalnya setahun sekali. Tanyakan apakah biaya masih sepadan, apakah kecepatan mengikuti kebutuhan bisnis, dan apakah ada risiko ketergantungan yang meningkat. Menyesuaikan model seiring tumbuhnya bisnis adalah tanda pengelolaan yang sehat, bukan kegagalan keputusan awal." },
  { type: "h2", text: "Kesalahan umum yang perlu dihindari" },
  { type: "p", text: "Beberapa kesalahan sering terjadi. Memilih berdasarkan harga termurah di muka tanpa memperhitungkan biaya jangka panjang adalah yang paling umum. Merekrut tim internal terlalu cepat sebelum kebutuhan jelas dan pekerjaan cukup juga sering terjadi. Menyerahkan semuanya kepada vendor tanpa ada orang internal yang bertanggung jawab membuat Anda kehilangan kendali. Tidak mengatur kepemilikan kode, akses, dan dokumentasi menciptakan ketergantungan berbahaya." },
  { type: "p", text: "Kesalahan lain adalah menganggap salah satu model otomatis lebih baik, misalnya \"tim sendiri pasti lebih baik\" atau \"vendor pasti lebih murah\". Keduanya bisa salah tergantung konteks. Putuskan berdasarkan kebutuhan, bukan prasangka, dan siap menyesuaikan." },
  { type: "h2", text: "Langkah praktis menentukan model" },
  {
    type: "ol",
    items: [
      "Petakan sistem digital yang Anda punya atau rencanakan, dan nilai seberapa strategis tiap-tiapnya",
      "Perkirakan seberapa sering tiap sistem akan berubah dan seberapa cepat Anda memerlukan hasil",
      "Hitung biaya total beberapa tahun untuk tiap model, termasuk biaya tersembunyi, bukan hanya biaya awal",
      "Tentukan siapa orang internal yang akan menjadi pemilik tiap sistem, apa pun modelnya",
      "Atur kepemilikan, akses, dan dokumentasi sejak awal agar tidak bergantung pada satu pihak",
      "Evaluasi model secara berkala dan ubah seiring pertumbuhan bisnis",
    ],
  },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Tim internal, vendor, dan model gabungan bukan pilihan benar atau salah, melainkan pertukaran yang harus ditimbang sesuai keadaan bisnis Anda. Yang terpenting adalah memilih dengan mata terbuka: memahami biaya sebenarnya, menjaga kendali atas hal-hal yang strategis, dan tidak membiarkan pengetahuan inti hanya berada di satu tempat." },
  { type: "p", text: "Jika Anda masih ragu, mulailah dari yang kecil dan jelas, belajar dari pengalaman, lalu sesuaikan. Mitra yang baik, baik karyawan maupun vendor, adalah mereka yang membantu bisnis Anda tumbuh tanpa membuat Anda tersandera." },
  {
    type: "cta",
    title: "Bingung memilih model pengembangan sistem untuk bisnis Anda?",
    text: "Tim AG·SORA siap berdiskusi tentang kebutuhan, anggaran, dan tahap bisnis Anda, serta membantu merancang kerja sama yang transparan dan tidak membuat Anda bergantung pada satu pihak. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/contact",
    label: "Hubungi kami",
  },
];
