import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Di banyak perusahaan, laporan keuangan bulan lalu baru selesai ketika bulan berjalan sudah hampir habis. Tim keuangan menghabiskan minggu-minggu pertama mengejar nota yang belum masuk, mencocokkan rekening, dan memperbaiki catatan yang keliru. Ketika laporan akhirnya tiba di meja pemilik, isinya sudah menjadi sejarah: keputusan yang seharusnya diambil berdasarkan angka itu sudah terlanjur diambil dengan perkiraan." },
  { type: "p", text: "Tutup buku yang lambat jarang disebabkan oleh tim keuangan yang lambat. Penyebabnya hampir selalu berada di hulu: transaksi yang dicatat terlambat, data yang tersebar di beberapa tempat, dan pekerjaan pencocokan yang ditumpuk sampai akhir bulan. Tim keuangan hanya berada di ujung alur, tempat semua keterlambatan itu berkumpul." },
  { type: "p", text: "Artikel ini membahas cara mempercepat tutup buku bulanan dengan bantuan ERP dan disiplin proses. Kami membahas kalender penutupan, rekonsiliasi, pisah batas, persediaan, jurnal penyesuaian, pemeriksaan, dan peran otomasi. Tidak ada angka rekaan tentang berapa hari yang ideal; setiap bisnis berbeda. Yang kami tawarkan adalah cara berpikir dan urutan kerja yang bisa diterapkan bertahap." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Tutup buku yang cepat dimulai dari pencatatan harian yang rapi, bukan dari kerja lembur di akhir bulan",
      "Buat kalender penutupan dengan tugas, pemilik, dan tenggat yang jelas",
      "Lakukan rekonsiliasi sepanjang bulan, bukan sekali di akhir",
      "Tetapkan aturan pisah batas agar transaksi masuk ke periode yang benar",
      "Kunci periode setelah ditutup dan catat setiap perubahan sesudahnya",
    ],
  },
  { type: "h2", text: "Mengapa kecepatan tutup buku penting" },
  { type: "p", text: "Laporan keuangan adalah alat kemudi. Laporan yang tiba tiga minggu setelah bulan berakhir hanya bisa dipakai untuk melihat ke belakang. Laporan yang tiba beberapa hari setelah bulan berakhir masih bisa memengaruhi keputusan bulan berjalan: harga yang perlu ditinjau, biaya yang membengkak, piutang yang menumpuk, atau produk yang ternyata merugi." },
  { type: "p", text: "Kecepatan juga berkaitan dengan mutu. Ini terdengar berlawanan, tetapi tutup buku yang lama biasanya justru lebih banyak salahnya. Semakin jauh jarak antara transaksi dan pemeriksaannya, semakin sulit orang mengingat konteksnya, dan semakin banyak penyesuaian yang dilakukan dengan menebak. Proses yang cepat memaksa masalah diselesaikan saat masih segar." },
  { type: "p", text: "Selain itu ada manfaat bagi tim. Tim keuangan yang setiap bulan terjebak dalam pekerjaan penutupan tidak punya waktu untuk analisis. Mempercepat penutupan berarti membebaskan orang-orang yang paling memahami angka perusahaan untuk mengerjakan hal yang lebih berguna daripada mengejar nota." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1554224154-26032ffc0d07",
    alt: "Dokumen keuangan, kalkulator, dan secangkir kopi di atas meja kerja",
    caption: "Semakin banyak pekerjaan yang diselesaikan sepanjang bulan, semakin ringan beban di hari-hari penutupan.",
  },
  { type: "h2", text: "Dari mana keterlambatan berasal" },
  { type: "p", text: "Sebelum memperbaiki, pahami dulu di mana waktu terbuang. Mintalah tim keuangan mencatat selama satu siklus penutupan apa saja yang mereka tunggu dan apa saja yang mereka ulang. Hasilnya biasanya menunjuk ke beberapa sumber yang sama di hampir setiap perusahaan." },
  { type: "ul", items: [
    "Nota dan tagihan pemasok yang baru diserahkan setelah bulan berakhir",
    "Penjualan dari kasir, toko online, dan marketplace yang harus diketik ulang ke pembukuan",
    "Rekening bank yang baru dicocokkan sekali sebulan sehingga selisihnya menumpuk",
    "Stok di gudang yang tidak cocok dengan catatan dan harus dihitung ulang",
    "Pengeluaran karyawan yang dilaporkan terlambat dan tanpa bukti lengkap",
    "Koreksi yang berputar-putar karena tidak jelas siapa yang berwenang memutuskan",
  ] },
  { type: "p", text: "Perhatikan bahwa sebagian besar butir di atas bukan pekerjaan tim keuangan, melainkan pekerjaan bagian lain yang hasilnya dibutuhkan keuangan. Itulah sebabnya mempercepat tutup buku adalah proyek seluruh perusahaan, dan memerlukan dukungan pemilik atau direksi agar bagian lain ikut mengubah kebiasaannya." },
  { type: "h2", text: "Kalender penutupan dan pemiliknya" },
  { type: "p", text: "Penutupan yang teratur dimulai dari kalender tertulis. Kalender ini mencantumkan setiap tugas, siapa pemiliknya, kapan tenggatnya, dan tugas mana yang harus selesai lebih dulu. Hari pertama setelah bulan berakhir disebut hari kerja pertama penutupan, dan setiap tugas diberi nomor hari relatif terhadapnya." },
  { type: "p", text: "Menuliskan kalender sering sudah memperlihatkan masalah. Tugas yang saling menunggu tanpa urutan jelas, tugas yang hanya bisa dikerjakan satu orang, dan tugas yang sebenarnya bisa diselesaikan sebelum bulan berakhir akan terlihat begitu semuanya dijajarkan. Pindahkan sebanyak mungkin pekerjaan ke sebelum tanggal penutupan." },
  { type: "p", text: "Sampaikan tenggat kepada bagian lain jauh hari, misalnya batas penyerahan tagihan pemasok dan laporan pengeluaran. Tenggat yang diumumkan dan ditegakkan secara konsisten lama-kelamaan menjadi kebiasaan. Tenggat yang selalu dilonggarkan mengajarkan semua orang bahwa terlambat tidak apa-apa." },
  { type: "h2", text: "Pencatatan di sumbernya" },
  { type: "p", text: "Prinsip terpenting dalam ERP adalah transaksi dicatat sekali, di tempat terjadinya, oleh orang yang melakukannya. Kasir mencatat penjualan, gudang mencatat penerimaan barang, bagian pembelian mencatat pesanan, dan semuanya mengalir ke pembukuan tanpa diketik ulang. Tim keuangan memeriksa, bukan menyalin." },
  { type: "p", text: "Agar aliran ini berjalan, pemetaan akun harus disiapkan dengan benar. Setiap jenis transaksi perlu tahu ke akun mana ia dicatat: penjualan produk tertentu ke akun pendapatan tertentu, pembelian bahan ke akun persediaan, biaya pengiriman ke akun biaya. Pemetaan yang dikerjakan teliti di awal menghemat ribuan jurnal manual sesudahnya." },
  { type: "p", text: "Sistem yang berjalan terpisah, seperti toko online atau aplikasi kasir yang belum terhubung, sebaiknya disambungkan lewat integrasi daripada lewat ekspor dan impor berkas bulanan. Integrasi harian membuat selisih terlihat pada hari yang sama, ketika penyebabnya masih mudah dilacak." },
  { type: "callout", title: "Tutup buku adalah hasil, bukan kegiatan", text: "Bila pencatatan harian rapi, tutup buku hanya memastikan dan merangkum. Bila pencatatan harian berantakan, tutup buku menjadi upaya menyusun ulang sebulan penuh dalam beberapa hari. Perbaikan paling besar hampir selalu ada di kebiasaan harian." },
  { type: "h2", text: "Rekonsiliasi sepanjang bulan" },
  { type: "p", text: "Rekonsiliasi berarti memastikan dua catatan tentang hal yang sama benar-benar cocok: buku kas dengan rekening koran, buku piutang dengan daftar tagihan, buku persediaan dengan stok fisik. Bila hanya dilakukan sekali di akhir bulan, satu selisih kecil pada tanggal tiga harus dicari di antara ratusan transaksi." },
  { type: "p", text: "Cocokkan rekening bank setiap hari atau setidaknya setiap minggu. Banyak ERP dapat mengimpor mutasi rekening dan mengusulkan pasangannya secara otomatis, sehingga petugas hanya menangani yang tidak cocok. Lakukan hal yang sama untuk pencairan dana dari penyedia pembayaran dan marketplace, yang biasanya tiba setelah dipotong biaya." },
  { type: "p", text: "Tinjau juga akun sementara dan akun selisih secara berkala. Akun seperti ini wajar ada, tetapi saldonya tidak boleh dibiarkan tumbuh. Saldo akun sementara yang terus membesar adalah tanda ada jenis transaksi yang belum punya aturan pencatatan jelas." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1707902665498-a202981fb5ac",
    alt: "Seseorang duduk di meja dengan kalkulator dan buku catatan",
    caption: "Pencocokan yang dilakukan rutin menghemat waktu pencarian selisih di akhir bulan.",
  },
  { type: "h2", text: "Pisah batas: transaksi di periode yang benar" },
  { type: "p", text: "Pisah batas adalah aturan tentang transaksi mana yang masuk ke bulan ini dan mana yang masuk ke bulan depan. Barang yang dikirim pada hari terakhir bulan tetapi ditagih pada hari pertama bulan berikutnya, atau tagihan pemasok bertanggal bulan lalu yang baru tiba hari ini, memerlukan perlakuan yang konsisten." },
  { type: "p", text: "Tetapkan aturan tertulis dan terapkan sama setiap bulan. Misalnya, kapan penjualan diakui, sampai tanggal berapa tagihan pemasok untuk bulan lalu masih diterima, dan bagaimana memperlakukan barang yang sudah diterima tetapi tagihannya belum datang. Konsistensi lebih penting daripada kesempurnaan, karena laporan dibandingkan dari bulan ke bulan." },
  { type: "p", text: "Untuk biaya yang sudah terjadi tetapi tagihannya belum tiba, buatlah pencadangan berdasarkan perkiraan yang masuk akal lalu balik pada bulan berikutnya ketika tagihan sebenarnya datang. Cara ini membuat Anda tidak perlu menunggu setiap tagihan sebelum menutup buku. Perlakuan akuntansi yang tepat untuk bisnis Anda sebaiknya dibahas dengan akuntan." },
  { type: "h2", text: "Persediaan dan harga pokok" },
  { type: "p", text: "Bagi bisnis yang menjual barang, persediaan sering menjadi sumber kejutan terbesar di akhir bulan. Nilai persediaan memengaruhi harga pokok penjualan, dan harga pokok memengaruhi laba. Jika stok fisik tidak cocok dengan catatan, laba yang dilaporkan ikut keliru." },
  { type: "p", text: "Gantikan penghitungan besar sekali sebulan dengan penghitungan bergilir: sebagian kecil barang dihitung setiap hari atau setiap minggu, dengan barang bernilai tinggi dan bergerak cepat dihitung lebih sering. Selisih diselidiki dan dikoreksi saat ditemukan, sehingga angka persediaan pada akhir bulan sudah bisa dipercaya." },
  { type: "p", text: "Pastikan penerimaan barang, perpindahan antargudang, barang rusak, dan retur dicatat pada hari kejadian. Persediaan yang dicatat belakangan menghasilkan stok negatif di sistem atau harga pokok yang melonjak aneh, dan keduanya menghabiskan waktu tim keuangan untuk menelusurinya." },
  { type: "h2", text: "Jurnal penyesuaian yang berulang" },
  { type: "p", text: "Setiap bulan ada jurnal yang polanya sama: penyusutan aset, pembebanan biaya dibayar di muka seperti sewa dan asuransi, pencadangan gaji dan tunjangan, serta pembebanan bunga. Jurnal seperti ini tidak perlu dibuat dari nol setiap bulan." },
  { type: "p", text: "ERP umumnya menyediakan jurnal berulang dan daftar aset tetap yang menghitung penyusutan otomatis. Siapkan sekali, tinjau ketika ada perubahan, dan biarkan sistem membuatnya sesuai jadwal. Peran tim keuangan bergeser dari membuat jurnal menjadi meninjau apakah jurnal otomatis itu masih mencerminkan keadaan." },
  { type: "p", text: "Batasi jurnal manual dan wajibkan keterangan serta lampiran pada setiap jurnal manual. Jurnal manual tanpa penjelasan adalah sumber pertanyaan saat pemeriksaan dan sumber kebingungan ketika orang yang membuatnya sudah tidak ada." },
  { type: "h2", text: "Pemeriksaan sebelum ditutup" },
  { type: "p", text: "Sebelum periode dikunci, lakukan pemeriksaan kewajaran. Bandingkan angka bulan ini dengan bulan lalu dan dengan anggaran, lalu cari pergerakan yang tidak bisa dijelaskan. Akun yang tiba-tiba naik tajam atau turun tajam sering menunjukkan salah catat, bukan perubahan bisnis." },
  { type: "ol", items: [
    "Pastikan semua rekonsiliasi kas dan bank selesai dan selisihnya dijelaskan",
    "Cocokkan saldo buku besar piutang dan utang dengan rinciannya",
    "Tinjau saldo akun sementara dan selesaikan yang bisa diselesaikan",
    "Bandingkan pendapatan, harga pokok, dan biaya utama dengan bulan sebelumnya",
    "Periksa jurnal manual bernilai besar beserta lampirannya",
    "Minta persetujuan penanggung jawab keuangan sebelum periode dikunci",
  ] },
  { type: "p", text: "Pemeriksaan ini sebaiknya dilakukan orang yang berbeda dari yang membuat catatan. Pemisahan tugas bukan soal curiga kepada karyawan, melainkan pengaman agar kesalahan jujur tidak lolos dan agar tidak ada satu orang yang memegang seluruh alur dari awal sampai akhir." },
  { type: "h2", text: "Mengunci periode" },
  { type: "p", text: "Setelah ditutup, periode harus dikunci di sistem sehingga transaksi baru tidak bisa dicatat dengan tanggal mundur. Tanpa kunci, laporan yang sudah diserahkan bisa berubah diam-diam, dan angka yang dipegang pemilik tidak lagi sama dengan angka di sistem." },
  { type: "p", text: "Koreksi atas periode yang sudah ditutup tetap mungkin terjadi, tetapi harus melalui prosedur: siapa yang boleh membuka kunci, dengan persetujuan siapa, dan catatan apa yang ditinggalkan. Untuk koreksi kecil, sering lebih baik mencatatnya di periode berjalan dengan keterangan jelas daripada membuka kembali periode lama." },
  { type: "p", text: "Jejak audit yang mencatat siapa mengubah apa dan kapan adalah kemampuan dasar ERP yang patut dimanfaatkan. Ia melindungi perusahaan sekaligus melindungi karyawan, karena setiap perubahan punya penanggung jawab yang jelas." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3",
    alt: "Laptop menampilkan dashboard berisi grafik dan tabel laporan",
    caption: "Laporan yang tiba lebih awal masih bisa memengaruhi keputusan bulan berjalan.",
  },
  { type: "h2", text: "Dari laporan ke keputusan" },
  { type: "p", text: "Tujuan mempercepat tutup buku bukan memenangkan lomba kecepatan, melainkan menyediakan informasi saat masih berguna. Sepakati paket laporan standar yang terbit setiap bulan dengan bentuk yang sama: laba rugi, neraca, arus kas, umur piutang dan utang, serta beberapa ukuran operasional yang penting bagi bisnis Anda." },
  { type: "p", text: "Sertakan penjelasan singkat untuk pergerakan besar. Angka tanpa cerita memaksa pembaca menebak. Satu halaman berisi tiga atau empat hal yang berubah dan sebabnya lebih bermanfaat bagi pemilik daripada dua puluh halaman tabel." },
  { type: "p", text: "Jadwalkan pertemuan tinjauan bulanan pada tanggal tetap segera setelah laporan terbit. Jadwal yang tetap memberi tekanan sehat pada proses penutupan dan memastikan laporan benar-benar dibaca dan ditindaklanjuti, bukan sekadar diarsipkan." },
  { type: "h2", text: "Peran otomasi dan batasnya" },
  { type: "p", text: "Otomasi sangat membantu pada pekerjaan yang berulang dan beraturan: mengimpor mutasi bank, mencocokkan pembayaran, membaca tagihan pemasok, membuat jurnal berulang, dan menyusun laporan. Alat bantu berbasis kecerdasan buatan mulai dipakai untuk mengusulkan pencocokan dan menandai transaksi yang janggal." },
  { type: "p", text: "Namun otomasi mempercepat proses yang sudah jelas; ia tidak memperbaiki proses yang kabur. Jika aturan pisah batas tidak pernah diputuskan atau pemetaan akun keliru, otomasi hanya menghasilkan kesalahan dengan lebih cepat. Rapikan aturan terlebih dahulu, lalu otomatiskan. Keputusan yang memerlukan pertimbangan tetap harus ditinjau manusia." },
  { type: "p", text: "Ukur kemajuan dengan cara sederhana. Catat pada hari kerja keberapa laporan terbit setiap bulan, berapa banyak jurnal koreksi yang dibuat setelah penutupan, dan tugas mana yang paling sering terlambat. Tiga catatan ini cukup untuk menunjukkan apakah perbaikan Anda bekerja, dan memberi tim keuangan bukti yang bisa dibawa ketika meminta bagian lain mengubah kebiasaannya." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menumpuk semua rekonsiliasi di hari-hari terakhir",
    "Menganggap tutup buku urusan tim keuangan saja tanpa melibatkan bagian lain",
    "Tidak mengunci periode sehingga laporan lama berubah tanpa diketahui",
    "Membiarkan akun sementara menumpuk tanpa pernah ditinjau",
    "Mengetik ulang penjualan dari sistem lain ke pembukuan",
    "Mengejar kecepatan dengan melewatkan pemeriksaan kewajaran",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Catat selama satu siklus penutupan apa saja yang ditunggu dan diulang tim keuangan",
    "Susun kalender penutupan dengan tugas, pemilik, dan tenggat relatif terhadap akhir bulan",
    "Mulai mencocokkan rekening bank setiap minggu, bukan setiap bulan",
    "Tetapkan dan umumkan batas penyerahan tagihan serta laporan pengeluaran",
    "Daftar jurnal yang berulang setiap bulan dan siapkan sebagai jurnal otomatis",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Tutup buku yang cepat bukan hasil kerja lembur, melainkan hasil kebiasaan harian yang rapi dan sistem yang menyatukan data. Ketika transaksi dicatat di sumbernya, rekonsiliasi dilakukan sepanjang bulan, dan aturan pisah batas dipegang konsisten, hari-hari penutupan berubah dari masa darurat menjadi rutinitas yang tenang." },
  { type: "p", text: "Mulailah dari menemukan sumber keterlambatan terbesar, perbaiki satu per satu, dan ukur kemajuannya setiap bulan. Hasilnya bukan hanya laporan yang lebih cepat, tetapi juga angka yang lebih bisa dipercaya dan tim keuangan yang punya waktu untuk membantu Anda mengambil keputusan." },
  {
    type: "cta",
    title: "Laporan keuangan selalu terlambat dan penuh koreksi?",
    text: "Tim AG·SORA menerapkan ERP yang menyatukan penjualan, pembelian, persediaan, dan pembukuan, lengkap dengan rekonsiliasi bank, jurnal berulang, dan penguncian periode. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/erp",
    label: "Konsultasi gratis",
  },
];
