import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Ada momen yang dikenal baik oleh siapa pun yang pernah menunggu proyek software selesai: tim pengembang menyatakan aplikasi sudah jadi, demo berjalan mulus, dan semua orang bersiap meluncurkan. Lalu seminggu setelah dipakai sungguhan, daftar keluhan mulai berdatangan. Laporan tidak sesuai kebiasaan tim keuangan, alur persetujuan tidak cocok dengan cara kerja di lapangan, dan beberapa kasus yang jarang tetapi penting ternyata tidak tertangani." },
  { type: "p", text: "Jarak antara \"sudah sesuai spesifikasi\" dan \"sudah sesuai kebutuhan\" sering lebih lebar dari perkiraan. Pengembang menguji bahwa aplikasi bekerja seperti yang dirancang. Hanya pengguna yang bisa menjawab apakah rancangan itu memang sesuai cara kerja mereka. Di sinilah uji penerimaan pengguna, atau UAT dari istilah User Acceptance Testing, mengambil peran: tahap terakhir sebelum peluncuran di mana pengguna sungguhan mencoba aplikasi dengan skenario nyata dan menyatakan layak atau tidak." },
  { type: "p", text: "Artikel ini menjelaskan UAT untuk pemilik bisnis dan pengelola proyek, bukan untuk penguji profesional. Kami membahas apa bedanya dengan pengujian lain, bagaimana merencanakannya, menulis skenario, memilih penguji, mencatat dan memprioritaskan temuan, hingga menentukan kapan aplikasi boleh diluncurkan. Kami tidak memakai angka rekaan tentang jumlah cacat atau durasi ideal; setiap proyek berbeda. Yang kami tawarkan adalah kerangka kerja praktis yang bisa Anda sesuaikan." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "UAT adalah pengujian oleh pengguna sungguhan terhadap skenario kerja nyata, untuk memastikan aplikasi memenuhi kebutuhan bisnis, bukan hanya spesifikasi teknis",
      "Rencanakan UAT sejak awal proyek: tentukan waktu, penguji, lingkungan uji, dan kriteria lulus sebelum pengembangan selesai",
      "Tulis skenario berdasarkan pekerjaan sehari-hari, termasuk kasus tidak biasa dan kesalahan, bukan hanya jalur sempurna",
      "Catat setiap temuan secara terstruktur, prioritaskan menurut dampak bisnis, dan putuskan mana yang wajib diperbaiki sebelum peluncuran",
      "Tetapkan kriteria peluncuran yang disepakati dan siapkan rencana jika terjadi masalah setelah tayang",
    ],
  },
  { type: "h2", text: "Apa itu UAT dan apa bedanya dengan pengujian lain" },
  { type: "p", text: "Pengembangan software melibatkan beberapa lapis pengujian dengan tujuan berbeda. Pengujian unit memeriksa potongan kode kecil secara terpisah. Pengujian integrasi memeriksa apakah bagian-bagian itu bekerja bersama. Pengujian sistem oleh tim penguji memastikan seluruh aplikasi berfungsi sesuai spesifikasi. Semua ini umumnya dilakukan oleh tim teknis dan menjawab pertanyaan, \"Apakah kami membangun sesuai yang direncanakan?\"" },
  { type: "p", text: "UAT menjawab pertanyaan lain: \"Apakah yang kami bangun benar-benar menyelesaikan pekerjaan kami?\" Pengujinya bukan orang teknis melainkan pengguna bisnis: kasir, staf gudang, admin keuangan, manajer penjualan. Mereka menjalankan aplikasi dengan data dan skenario yang mirip pekerjaan harian mereka, lalu menilai apakah alurnya masuk akal, hasilnya benar, dan aplikasi layak dipakai." },
  { type: "p", text: "Perbedaan ini penting karena spesifikasi bisa saja salah atau tidak lengkap. Sebuah fitur yang dibangun persis sesuai dokumen kebutuhan masih bisa tidak berguna jika dokumen itu melewatkan satu langkah kerja penting. Hanya pengguna yang mengalami pekerjaannya setiap hari yang akan menyadari, \"Eh, di sini kami biasanya juga perlu mencatat ini.\"" },
  { type: "p", text: "Karena itu, UAT bukan formalitas tanda tangan di akhir proyek. Ia adalah jaring pengaman terakhir antara kesalahan pemahaman dan operasional nyata. Menyingkatnya demi mengejar jadwal hampir selalu berujung pada biaya yang lebih besar setelah peluncuran, ketika perbaikan harus dilakukan sambil bisnis berjalan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    alt: "Layar laptop menampilkan kode program berwarna di editor",
    caption: "Tim teknis memastikan kode bekerja sesuai rancangan; UAT memastikan rancangan itu sesuai pekerjaan nyata.",
  },
  { type: "h2", text: "Merencanakan UAT sejak awal proyek" },
  { type: "p", text: "UAT yang baik tidak dimulai ketika aplikasi sudah jadi, tetapi ketika proyek direncanakan. Jika baru dipikirkan di akhir, biasanya waktu tinggal sedikit, penguji tidak tersedia, dan tekanan untuk segera meluncurkan membuat temuan diabaikan." },
  { type: "p", text: "Hal pertama yang perlu disepakati adalah waktu. Alokasikan periode UAT yang cukup dalam jadwal, termasuk waktu untuk memperbaiki temuan dan menguji ulang. Banyak jadwal proyek gagal karena UAT dianggap hanya satu atau dua hari, padahal siklus uji, perbaikan, dan uji ulang biasanya berulang beberapa kali. Sisakan ruang untuk itu sejak awal." },
  { type: "p", text: "Kedua, tentukan siapa yang terlibat dan pastikan mereka benar-benar diberi waktu. Penguji adalah karyawan dengan pekerjaan harian. Jika mereka diminta menguji sambil tetap mengerjakan semua tugas, kualitas UAT akan buruk. Dapatkan dukungan atasan agar penguji punya waktu khusus. Ketiga, tentukan lingkungan ujinya: salinan aplikasi terpisah dari sistem sungguhan, berisi data uji yang realistis, agar eksperimen tidak merusak data bisnis." },
  { type: "p", text: "Keempat, tentukan kriteria lulus sejak awal. Apa yang harus terpenuhi agar aplikasi dinyatakan siap? Misalnya semua skenario inti berjalan tanpa cacat berat, tidak ada cacat yang menghalangi pekerjaan utama, dan pemangku kepentingan utama menyetujui. Kesepakatan di awal mencegah perdebatan di akhir ketika tekanan sedang tinggi." },
  { type: "h3", text: "Peran dan tanggung jawab" },
  { type: "p", text: "Tentukan siapa yang mengoordinasi UAT, biasanya pengelola proyek dari sisi bisnis. Tentukan juga siapa yang menerima laporan temuan di sisi pengembang, siapa yang memutuskan prioritas, dan siapa yang berwenang menyatakan lulus. Satu penanggung jawab yang jelas mencegah temuan jatuh di antara dua pihak yang masing-masing mengira pihak lain yang mengurus." },
  { type: "h2", text: "Menulis skenario uji yang berguna" },
  { type: "p", text: "Skenario uji adalah rangkaian langkah yang meniru pekerjaan nyata beserta hasil yang diharapkan. Kualitas skenario menentukan kualitas UAT. Skenario yang baik berangkat dari proses bisnis, bukan dari daftar fitur." },
  { type: "p", text: "Mulailah dengan mendaftar pekerjaan utama yang akan dilakukan pengguna dengan aplikasi ini, misalnya membuat pesanan, menerima barang, menutup kas harian, mengajukan cuti, atau menyetujui pembelian. Untuk tiap pekerjaan, tuliskan langkah dari awal sampai selesai, data yang dipakai, dan hasil yang diharapkan, seperti stok berkurang sekian atau laporan menunjukkan angka tertentu." },
  { type: "p", text: "Jangan hanya menguji jalur sempurna. Pekerjaan nyata penuh dengan kejadian yang tidak mulus: pelanggan membatalkan di tengah, pembayaran sebagian, barang retur, data salah ketik, atau persetujuan yang ditolak. Tambahkan skenario untuk kasus tidak biasa dan kesalahan, karena di sanalah banyak masalah tersembunyi." },
  {
    type: "ol",
    items: [
      "Gunakan bahasa dan istilah yang dipakai pengguna sehari-hari, bukan istilah teknis tim pengembang",
      "Tulis langkah cukup rinci agar orang yang baru pertama kali mencoba bisa mengikutinya",
      "Sertakan data uji yang realistis, termasuk contoh sulit seperti nama panjang, angka besar, dan karakter khusus",
      "Cantumkan hasil yang diharapkan yang bisa diperiksa dengan jelas, bukan sekadar \"berfungsi baik\"",
      "Sertakan skenario lintas peran, misalnya pesanan dibuat oleh kasir lalu disetujui manajer lalu dilaporkan ke keuangan",
      "Sertakan skenario untuk laporan, karena laporan sering menjadi alasan utama aplikasi dibangun",
    ],
  },
  { type: "h3", text: "Uji dengan data dan situasi mendekati nyata" },
  { type: "p", text: "Aplikasi yang tampak mulus dengan lima baris data contoh bisa melambat atau membingungkan dengan ribuan data sungguhan. Jika memungkinkan, muat data uji yang mendekati jumlah dan ragam data nyata, misalnya hasil migrasi sebagian data lama yang sudah dianonimkan. Uji juga pada perangkat dan koneksi yang benar-benar dipakai pengguna, termasuk yang paling sederhana. Pengujian di laptop pengembang yang cepat tidak mewakili toko dengan tablet tua dan sinyal lemah." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44",
    alt: "Laptop menampilkan halaman web dengan tombol ajakan bertindak, tangan di trackpad",
    caption: "Penguji bisnis memeriksa apakah tampilan dan alur benar-benar masuk akal untuk pekerjaan mereka.",
  },
  { type: "h2", text: "Memilih dan menyiapkan penguji" },
  { type: "p", text: "Penguji terbaik adalah orang yang akan memakai aplikasi sehari-hari, karena mereka paling paham pekerjaannya. Pilih perwakilan dari setiap peran utama, termasuk yang kritis dan skeptis. Penguji yang antusias membantu, tetapi penguji yang cermat dan berani mengatakan \"ini tidak cocok\" jauh lebih berharga bagi kualitas aplikasi." },
  { type: "p", text: "Jumlahnya tidak perlu besar. Beberapa orang per peran biasanya sudah cukup untuk menemukan sebagian besar masalah alur kerja. Yang lebih penting adalah keragaman: pengguna berpengalaman dan pemula, orang yang cepat dan yang lambat, karena masing-masing mengungkap masalah berbeda." },
  { type: "p", text: "Siapkan penguji sebelum mulai. Jelaskan tujuan UAT, apa yang diharapkan dari mereka, dan bagaimana mencatat temuan. Berikan pelatihan singkat agar mereka tahu dasar aplikasi, tetapi jangan terlalu banyak membimbing sampai menutupi masalah kegunaan yang seharusnya terlihat. Jika penguji tersangkut dan perlu bertanya terlalu sering, itu sendiri adalah temuan yang berharga tentang kejelasan aplikasi." },
  {
    type: "callout",
    title: "Perhatikan, bukan hanya dengarkan",
    text: "Amati penguji saat bekerja bila memungkinkan. Tempat mereka ragu, salah klik, atau menghela napas sering lebih jujur daripada laporan tertulis. Catat juga pertanyaan yang mereka ajukan, karena itu petunjuk bagian yang kurang jelas.",
  },
  { type: "h2", text: "Menjalankan UAT dan mencatat temuan" },
  { type: "p", text: "Selama UAT berlangsung, ciptakan kebiasaan mencatat yang konsisten. Setiap temuan sebaiknya dicatat dengan format yang sama agar mudah ditindaklanjuti. Isinya mencakup deskripsi singkat masalah, langkah untuk mereproduksinya, hasil yang diharapkan dan yang terjadi, tangkapan layar bila membantu, dan siapa yang menemukannya." },
  { type: "p", text: "Hindari catatan yang samar seperti \"laporan salah\". Catatan yang baik berbunyi seperti: \"Pada laporan penjualan harian, total untuk tanggal tertentu berbeda dari jumlah transaksi di daftar; dari data uji tertentu, total muncul sekian padahal seharusnya sekian.\" Rincian ini menghemat banyak waktu pengembang dan mengurangi bolak-balik pertanyaan." },
  { type: "p", text: "Kumpulkan semua temuan di satu tempat, bukan tersebar di pesan pribadi dan percakapan kelompok. Satu daftar bersama, bahkan sekadar spreadsheet, memudahkan pelacakan status setiap temuan: baru, sedang diperbaiki, siap diuji ulang, atau selesai. Ini juga mencegah temuan yang sama dilaporkan berkali-kali dan memberi gambaran kemajuan yang jelas bagi semua pihak." },
  { type: "p", text: "Rutin tinjau temuan bersama, misalnya setiap hari atau dua hari sekali selama UAT berjalan. Pertemuan singkat antara perwakilan bisnis dan pengembang mengklarifikasi temuan yang ambigu, menyepakati prioritas, dan menjaga ritme perbaikan." },
  { type: "h2", text: "Memprioritaskan temuan" },
  { type: "p", text: "Tidak semua temuan sama pentingnya, dan tidak semua harus diperbaiki sebelum peluncuran. Pengelompokan berdasarkan dampak bisnis membantu membuat keputusan yang rasional di bawah tekanan waktu." },
  {
    type: "ul",
    items: [
      "Kritis: menghalangi pekerjaan utama atau menyebabkan data salah, kerugian uang, atau risiko keamanan; wajib diperbaiki sebelum peluncuran",
      "Penting: pekerjaan masih bisa dilakukan tetapi dengan cara yang merepotkan atau hasilnya kurang tepat; sebaiknya diperbaiki sebelum peluncuran, atau ada solusi sementara yang disepakati",
      "Kecil: gangguan kenyamanan atau tampilan yang tidak memengaruhi hasil kerja; bisa dijadwalkan setelah peluncuran",
      "Usulan: gagasan peningkatan yang sebenarnya di luar lingkup awal; dicatat untuk tahap berikutnya, bukan untuk ditambahkan di menit-menit akhir",
    ],
  },
  { type: "p", text: "Perhatikan perbedaan antara cacat dan perubahan kebutuhan. Cacat berarti aplikasi tidak bekerja seperti yang disepakati. Perubahan kebutuhan berarti pengguna menyadari mereka menginginkan sesuatu yang berbeda dari yang disepakati. Keduanya sah dan berharga, tetapi penanganannya berbeda: cacat diperbaiki dalam lingkup proyek, sedangkan perubahan kebutuhan dinilai dampaknya pada waktu dan biaya, lalu diputuskan bersama. Mencampur keduanya adalah salah satu sumber utama pembengkakan proyek." },
  { type: "h3", text: "Menghindari jebakan \"ya sudah, nanti saja\"" },
  { type: "p", text: "Menjelang tenggat, godaan terbesar adalah menunda semua temuan dengan alasan akan diperbaiki setelah peluncuran. Sebagian memang bisa, tetapi terlalu banyak utang perbaikan membuat pengguna kehilangan kepercayaan sejak hari pertama. Pesan pertama yang diterima pengguna dari aplikasi baru sangat berpengaruh pada penerimaan mereka. Jika hari pertama dipenuhi masalah yang sebenarnya sudah ditemukan, mereka akan sulit diyakinkan lagi." },
  { type: "h2", text: "Menentukan kapan aplikasi layak diluncurkan" },
  { type: "p", text: "Keputusan meluncurkan sebaiknya berdasarkan kriteria yang sudah disepakati, bukan perasaan atau tekanan. Tinjau kriteria lulus yang ditetapkan di awal dan periksa satu per satu. Apakah semua skenario inti lulus? Apakah tidak ada temuan kritis yang tersisa? Apakah temuan penting yang tersisa punya solusi sementara yang disetujui? Apakah perwakilan setiap peran utama menyatakan siap?" },
  { type: "p", text: "Dokumentasikan keputusan itu. Persetujuan tertulis dari pemangku kepentingan utama bukan sekadar birokrasi; ia memastikan semua pihak memahami kondisi aplikasi saat diluncurkan, termasuk temuan yang diterima sebagai risiko. Ini juga menghindari kesalahpahaman di kemudian hari tentang apa yang sudah dan belum disepakati." },
  { type: "p", text: "Jika kriteria belum terpenuhi, berani menunda peluncuran sering kali lebih murah daripada meluncurkan aplikasi yang belum siap. Peluncuran yang tergesa dan kemudian harus ditarik atau diperbaiki dalam kekacauan menimbulkan biaya yang jauh lebih besar, baik uang maupun kepercayaan. Pertimbangkan juga peluncuran bertahap, misalnya dimulai dari satu cabang atau satu tim, untuk membatasi dampak jika masalah muncul." },
  { type: "h2", text: "Setelah peluncuran: menjaga siklus belajar" },
  { type: "p", text: "UAT tidak berarti pengujian berakhir. Setelah peluncuran, siapkan masa pendampingan intensif di mana tim pengembang dan perwakilan bisnis siaga menangani masalah yang muncul. Sediakan jalur laporan yang mudah bagi pengguna dan tanggapi dengan cepat, karena respons cepat pada hari-hari awal sangat menentukan penerimaan." },
  { type: "p", text: "Siapkan rencana mundur, yaitu cara kembali ke cara kerja lama atau versi sebelumnya jika terjadi masalah serius. Rencana ini jarang dipakai, tetapi keberadaannya membuat keputusan meluncurkan jauh lebih tenang. Pastikan pula data yang masuk selama masa awal tidak hilang jika harus mundur." },
  { type: "p", text: "Kumpulkan pelajaran dari proses UAT untuk proyek berikutnya: skenario mana yang paling banyak mengungkap masalah, apa yang terlewat sampai setelah peluncuran, dan bagaimana kerja sama antara bisnis dan pengembang bisa diperbaiki. Dari proyek ke proyek, proses ini akan semakin ringan dan semakin efektif." },
  { type: "h2", text: "Kesalahan umum dalam UAT" },
  { type: "p", text: "Beberapa kesalahan berulang muncul pada banyak proyek. Menjadwalkan UAT terlalu singkat dan terlalu dekat dengan tenggat peluncuran adalah yang paling sering. Memakai pengembang atau pihak yang tidak mengenal pekerjaan sebagai penguji pengganti pengguna sungguhan adalah yang lain. Menguji hanya jalur sempurna, memakai data uji yang terlalu sedikit dan terlalu rapi, serta tidak mencatat temuan secara terstruktur juga sangat umum." },
  { type: "p", text: "Kesalahan lain adalah tidak melibatkan pengambil keputusan hingga akhir, sehingga persetujuan datang terlambat dan disertai perubahan permintaan besar. Libatkan pemangku kepentingan utama sejak awal, termasuk dalam peninjauan kemajuan UAT, agar tidak ada kejutan di menit terakhir." },
  { type: "h2", text: "Langkah praktis menjalankan UAT" },
  {
    type: "ol",
    items: [
      "Masukkan UAT ke jadwal proyek sejak awal, termasuk waktu untuk perbaikan dan uji ulang",
      "Tetapkan koordinator, penguji dari tiap peran, lingkungan uji, dan kriteria lulus",
      "Tulis skenario dari pekerjaan nyata, termasuk kasus tidak biasa, kesalahan, dan laporan",
      "Siapkan data uji yang realistis dan beri penguji waktu khusus serta penjelasan singkat",
      "Catat semua temuan di satu daftar bersama dengan format seragam dan tinjau rutin",
      "Prioritaskan menurut dampak, putuskan peluncuran berdasarkan kriteria, dan siapkan rencana mundur",
    ],
  },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "UAT adalah investasi kecil yang melindungi investasi besar. Aplikasi yang dibangun dengan biaya tinggi bisa gagal diterima hanya karena beberapa hal yang tidak cocok dengan cara kerja nyata, dan hal-hal itu hampir selalu bisa ditemukan sebelum peluncuran jika pengguna sungguhan diberi kesempatan mencoba. Dengan perencanaan yang baik, skenario yang realistis, dan keputusan yang berdasarkan kriteria, UAT mengubah peluncuran dari taruhan menjadi langkah yang terukur." },
  { type: "p", text: "Jika Anda sedang mengerjakan proyek software atau sistem baru, jangan menunggu aplikasi selesai untuk memikirkan UAT. Rencanakan sejak awal, libatkan orang yang tepat, dan beri waktu yang cukup. Aplikasi yang diterima dengan baik pada hari pertama adalah hasil dari persiapan yang dilakukan jauh sebelumnya." },
  {
    type: "cta",
    title: "Sedang merencanakan proyek software atau aplikasi bisnis?",
    text: "Tim AG·SORA mendampingi proyek dari kebutuhan hingga peluncuran, termasuk menyusun skenario uji bersama pengguna Anda agar aplikasi benar-benar siap dipakai. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/custom-software",
    label: "Konsultasi gratis",
  },
];
