import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Banyak keputusan tentang website diambil dengan cara yang sama: seseorang berpendapat tombol sebaiknya berwarna lain, judul sebaiknya lebih pendek, atau formulir sebaiknya dikurangi kolomnya. Yang bersuara paling keras atau berpangkat paling tinggi biasanya menang. Hasilnya kadang bagus, kadang tidak, dan hampir tidak pernah ada yang tahu pasti mengapa." },
  { type: "p", text: "Uji A/B menawarkan cara yang lebih tenang: tunjukkan dua versi kepada pengunjung yang berbeda pada waktu yang sama, lalu lihat mana yang lebih sering menghasilkan tindakan yang Anda inginkan. Alih-alih berdebat, Anda membiarkan perilaku pengunjung yang menjawab. Namun uji A/B juga mudah disalahgunakan, dan banyak hasil yang tampak meyakinkan sebenarnya menyesatkan." },
  { type: "p", text: "Artikel ini menjelaskan cara memulai pengujian secara sehat untuk website dan toko online bisnis kecil dan menengah: kapan pengujian layak dilakukan, bagaimana merumuskan hipotesis, apa yang harus diukur, seberapa lama pengujian berjalan, dan bagaimana menghindari kesimpulan keliru. Kami tidak memberi angka peningkatan yang pasti, karena setiap situs berbeda." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Uji A/B membandingkan dua versi pada pengunjung yang dibagi acak untuk melihat mana yang lebih berhasil",
      "Mulailah dari masalah yang ditemukan lewat data dan pengamatan, bukan dari selera",
      "Ubah satu hal pada satu waktu dan tentukan ukuran keberhasilan sebelum pengujian dimulai",
      "Beri pengujian waktu dan jumlah pengunjung yang cukup sebelum menyimpulkan",
      "Bila lalu lintas terlalu kecil, perbaikan berdasarkan pengamatan sering lebih bermanfaat daripada pengujian",
    ],
  },
  { type: "h2", text: "Apa itu uji A/B, dengan bahasa sederhana" },
  { type: "p", text: "Bayangkan sebuah toko fisik yang ingin tahu apakah menaruh produk unggulan di dekat pintu menaikkan penjualan. Cara yang adil adalah menata dua toko serupa secara berbeda pada periode yang sama dan membandingkan hasilnya. Bila hanya mengubah satu toko dan membandingkannya dengan bulan lalu, hasilnya bercampur dengan musim, promo, dan cuaca." },
  { type: "p", text: "Uji A/B pada website bekerja dengan prinsip yang sama. Setiap pengunjung dibagi secara acak ke versi A, yang biasanya halaman yang sedang berjalan, atau versi B, yaitu varian yang diuji. Karena kedua kelompok melihat halaman pada periode yang sama, perbedaan hasil yang cukup besar dapat dikaitkan dengan perubahan itu, bukan dengan faktor lain." },
  { type: "p", text: "Ada varian lain seperti pengujian beberapa versi sekaligus atau pengujian beberapa elemen yang digabung. Untuk kebanyakan bisnis, uji A/B sederhana dengan dua versi sudah cukup dan jauh lebih mudah ditafsirkan dengan benar." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1460925895917-afdab827c52f",
    alt: "Layar laptop menampilkan grafik dan laporan analitik bisnis",
    caption: "Pengujian hanya bermanfaat bila hasilnya dibaca dengan data yang cukup dan ukuran keberhasilan yang jelas.",
  },
  { type: "h2", text: "Kapan pengujian layak dilakukan, dan kapan tidak" },
  { type: "p", text: "Pengujian membutuhkan pengunjung dalam jumlah memadai. Bila halaman Anda hanya dikunjungi beberapa puluh orang sehari dan hanya sedikit yang melakukan tindakan target, perbedaan antara dua versi baru akan terlihat setelah waktu sangat lama, dan itu pun rapuh. Pada kondisi ini, hasil pengujian lebih sering kebetulan daripada kenyataan." },
  { type: "p", text: "Bila lalu lintas kecil, ada cara yang lebih efektif: perbaiki masalah yang jelas terlihat. Tonton rekaman sesi pengunjung, periksa halaman di ponsel, baca pertanyaan yang sering masuk ke layanan pelanggan, dan wawancarai beberapa pelanggan. Masalah seperti tombol yang tertutup, formulir yang membingungkan, atau harga yang tidak jelas biasanya tidak perlu diuji; cukup diperbaiki." },
  { type: "p", text: "Pengujian paling berguna ketika masalahnya sudah jelas tetapi solusinya mengundang beberapa pendapat yang masuk akal, dan ketika dampak yang diharapkan cukup besar untuk membenarkan usaha. Memilih warna tombol jarang termasuk di dalamnya; mengubah penawaran, urutan langkah checkout, atau cara menampilkan harga lebih sering layak diuji." },
  { type: "h2", text: "Mulai dari masalah, lalu rumuskan hipotesis" },
  { type: "p", text: "Pengujian yang baik dimulai dari pengamatan, bukan dari ide. Misalnya, data analitik menunjukkan banyak pengunjung mengisi keranjang tetapi berhenti di halaman pengiriman. Dari situ muncul dugaan: biaya pengiriman baru terlihat di akhir sehingga mengejutkan pembeli." },
  { type: "p", text: "Rumuskan dugaan itu menjadi hipotesis yang bisa diuji: jika kami menampilkan perkiraan ongkos kirim di halaman produk, lebih banyak pengunjung akan menyelesaikan pembelian karena tidak terkejut di akhir. Hipotesis menyebut perubahan, alasannya, dan hasil yang diharapkan. Alasan ini penting karena membuat Anda belajar sesuatu bahkan ketika hasilnya tidak sesuai harapan." },
  { type: "p", text: "Tuliskan hipotesis dan ukuran keberhasilan sebelum pengujian berjalan. Menetapkan ukuran setelah melihat hasil membuka pintu bagi pembenaran yang dicari-cari: bila ukuran utama tidak naik, selalu ada ukuran lain yang kebetulan naik." },
  { type: "callout", title: "Satu perubahan, satu pertanyaan", text: "Bila Anda mengubah judul, gambar, dan tombol sekaligus, Anda tidak akan tahu mana yang berpengaruh. Ubah satu hal yang mewakili satu hipotesis. Perubahan besar yang disatukan boleh diuji sebagai satu paket, tetapi akui bahwa Anda mengujinya sebagai paket." },
  { type: "h2", text: "Memilih ukuran keberhasilan" },
  { type: "p", text: "Ukuran utama sebaiknya satu dan terkait langsung dengan tujuan bisnis: persentase pengunjung yang menyelesaikan pembelian, mengirim formulir permintaan penawaran, atau mendaftar. Ukuran yang lebih dangkal seperti jumlah klik pada tombol mudah naik tanpa membawa manfaat nyata." },
  { type: "p", text: "Selain ukuran utama, tetapkan ukuran pengaman, yaitu hal yang tidak boleh memburuk. Misalnya, bila Anda menyederhanakan formulir untuk mendapat lebih banyak kiriman, periksa juga mutu prospek yang masuk. Peningkatan jumlah yang disertai penurunan mutu bukan kemenangan." },
  { type: "p", text: "Pastikan pelacakan bekerja sebelum pengujian dimulai. Banyak pengujian sia-sia karena peristiwa yang diukur tidak tercatat dengan benar di salah satu versi. Uji pelacakan dengan melakukan tindakan target sendiri pada kedua versi dan memeriksa bahwa semuanya tercatat." },
  { type: "h2", text: "Berapa lama pengujian berjalan" },
  { type: "p", text: "Godaan terbesar adalah menghentikan pengujian begitu satu versi tampak unggul. Pada beberapa hari pertama, angka naik-turun karena kebetulan, dan versi yang tampak menang sering kehilangan keunggulannya kemudian. Menghentikan di titik yang menguntungkan adalah cara paling umum mendapatkan kemenangan semu." },
  { type: "p", text: "Tentukan sebelumnya berapa banyak pengunjung atau berapa lama pengujian akan berjalan, lalu patuhi. Jalankan setidaknya satu siklus mingguan penuh agar pola hari kerja dan akhir pekan terwakili, dan lebih lama bila bisnis Anda memiliki siklus pembelian yang panjang. Alat pengujian umumnya menyediakan kalkulator ukuran sampel yang bisa membantu." },
  { type: "p", text: "Hindari menjalankan pengujian saat ada kejadian tidak biasa seperti kampanye besar, libur panjang, atau gangguan teknis. Peristiwa itu mengubah komposisi pengunjung dan dapat menggeser hasil dengan cara yang tidak berkaitan dengan perubahan yang diuji." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44",
    alt: "Laptop menampilkan halaman web dengan tombol ajakan bertindak, tangan di trackpad",
    caption: "Unsur seperti judul, penawaran, dan tombol ajakan bertindak menjadi kandidat pengujian yang paling lazim.",
  },
  { type: "h2", text: "Membaca hasil tanpa tertipu" },
  { type: "p", text: "Hasil pengujian biasanya disertai ukuran keyakinan statistik. Pahami secara garis besar maknanya: seberapa besar kemungkinan perbedaan yang terlihat hanya akibat kebetulan. Ukuran keyakinan yang tinggi berarti perbedaannya kemungkinan nyata, tetapi tidak menjamin dampaknya besar atau berarti bagi bisnis Anda." },
  { type: "p", text: "Perhatikan juga ukuran dampaknya. Peningkatan yang nyata tetapi sangat kecil mungkin tidak sepadan dengan biaya menerapkannya. Sebaliknya, hasil yang tampak besar tetapi didasarkan pada sedikit data harus diperlakukan sebagai petunjuk untuk diuji ulang, bukan sebagai bukti." },
  { type: "p", text: "Bila Anda menjalankan banyak pengujian atau menggali banyak kelompok pengunjung sekaligus, peluang menemukan pola kebetulan meningkat. Pembagian per perangkat atau per sumber lalu lintas boleh dipakai untuk menghasilkan ide, tetapi temuannya perlu diuji sendiri sebelum dipercaya." },
  { type: "h2", text: "Apa yang layak diuji pertama kali" },
  { type: "ul", items: [
    "Pernyataan nilai di bagian atas halaman: apakah pengunjung langsung paham apa yang Anda tawarkan",
    "Penawaran dan cara menyampaikannya, misalnya garansi, gratis ongkir, atau uji coba",
    "Jumlah kolom dan urutan langkah pada formulir atau checkout",
    "Cara menampilkan harga, biaya tambahan, dan opsi pembayaran",
    "Bukti sosial seperti ulasan, jumlah pelanggan, atau logo mitra, bila benar adanya",
    "Teks dan penempatan tombol ajakan bertindak utama",
  ] },
  { type: "p", text: "Urutkan berdasarkan perkiraan dampak dan kemudahan. Perubahan yang tinggi dampaknya dan mudah diterapkan dikerjakan lebih dulu. Mengerjakan daftar ide dengan cara ini mencegah tim menghabiskan minggu-minggu untuk pengujian yang hasilnya paling banter kecil." },
  { type: "h2", text: "Gambaran satu pengujian dari awal sampai akhir" },
  { type: "p", text: "Sebagai gambaran hipotetis, sebuah toko perlengkapan olahraga mendapati banyak pengunjung berhenti di halaman keranjang. Rekaman sesi memperlihatkan pengunjung menggulir naik-turun mencari informasi ongkos kirim. Hipotesisnya: menampilkan perkiraan ongkos kirim dan estimasi tiba langsung di keranjang akan membuat lebih banyak pengunjung melanjutkan ke pembayaran." },
  { type: "p", text: "Tim menetapkan ukuran utama berupa persentase keranjang yang berlanjut ke pembayaran, ukuran pengaman berupa tingkat pembatalan dan retur, dan durasi tiga minggu agar mencakup beberapa siklus mingguan. Pelacakan diuji lebih dulu pada kedua versi, lalu lalu lintas dibagi rata secara acak." },
  { type: "p", text: "Setelah periode berakhir, tim membaca hasilnya terhadap ukuran yang sudah ditetapkan, memeriksa ukuran pengaman, dan memutuskan menerapkan perubahan itu ke seluruh pengunjung atau tidak. Apa pun hasilnya, hipotesis, angka, dan pelajaran dicatat. Contoh ini sengaja sederhana; kuncinya adalah urutan kerja yang tertib, bukan besarnya perubahan." },
  { type: "h2", text: "Hal teknis agar pengujian dapat dipercaya" },
  { type: "p", text: "Pastikan pembagian pengunjung benar-benar acak dan konsisten. Seorang pengunjung harus selalu melihat versi yang sama selama pengujian, termasuk bila ia kembali keesokan harinya. Pembagian yang tidak konsisten membuat pengalaman membingungkan dan merusak data." },
  { type: "p", text: "Waspadai kedipan, yaitu keadaan ketika pengunjung sekilas melihat versi asli sebelum versi uji muncul. Selain mengganggu, kedipan memengaruhi perilaku dan menyimpang dari pengalaman sebenarnya. Pengujian yang dijalankan di sisi server atau dengan teknik yang tepat biasanya menghindari masalah ini." },
  { type: "p", text: "Saring lalu lintas bukan manusia, seperti perayap mesin pencari dan bot, serta lalu lintas internal dari tim Anda sendiri. Keduanya dapat membelokkan hasil terutama pada situs dengan pengunjung yang sedikit. Terakhir, periksa bahwa kedua versi dimuat dengan kecepatan yang setara, karena versi yang lebih lambat akan kalah karena alasan yang tidak ada hubungannya dengan rancangannya." },
  { type: "h2", text: "Pengujian pada aplikasi dan pengalaman mobile" },
  { type: "p", text: "Prinsip yang sama berlaku pada aplikasi mobile, dengan beberapa catatan. Pembaruan aplikasi memerlukan waktu untuk sampai ke pengguna, sehingga pengujian sering dijalankan lewat pengaturan jarak jauh yang mengaktifkan varian tertentu tanpa merilis versi baru. Pastikan aplikasi dirancang untuk mendukung hal ini sejak awal." },
  { type: "p", text: "Pengguna aplikasi juga cenderung lebih sedikit dan lebih setia daripada pengunjung situs, sehingga perubahan pada alur awal pengguna baru, seperti pendaftaran dan pengenalan fitur, sering menjadi tempat pengujian yang paling bermakna. Perhatikan pula kebijakan toko aplikasi dan aturan privasi saat mengumpulkan data perilaku." },
  { type: "h2", text: "Kapan menghentikan, menerapkan, atau mengulang" },
  { type: "p", text: "Setelah pengujian selesai, ada tiga kemungkinan. Bila versi baru jelas lebih baik dan ukuran pengaman aman, terapkan ke seluruh pengunjung dan pantau beberapa minggu untuk memastikan hasilnya bertahan. Bila hasilnya tidak berbeda, pilih versi yang lebih sederhana atau lebih murah dirawat." },
  { type: "p", text: "Bila hasilnya tidak meyakinkan karena data kurang, Anda boleh memperpanjang pengujian dengan aturan yang ditetapkan sejak awal, atau menguji perubahan yang lebih berani agar perbedaannya lebih mudah terdeteksi. Perubahan yang terlalu halus sulit dibuktikan, dan sering kali memang tidak berarti bagi pengunjung." },
  { type: "h2", text: "Etika, privasi, dan menjaga kepercayaan" },
  { type: "p", text: "Pengujian bukan izin untuk memanipulasi pengunjung. Hindari pola yang menyesatkan seperti hitung mundur palsu, klaim stok menipis yang tidak benar, atau menyembunyikan opsi berhenti berlangganan. Selain merusak kepercayaan, praktik seperti ini dapat melanggar aturan perlindungan konsumen." },
  { type: "p", text: "Perhatikan privasi. Beri tahu pengunjung tentang pengumpulan data lewat kebijakan privasi, minta persetujuan sesuai ketentuan yang berlaku, dan jangan mengumpulkan data pribadi yang tidak diperlukan untuk pengujian. Rujuk aturan perlindungan data pribadi yang berlaku saat ini." },
  { type: "p", text: "Terakhir, jangan biarkan pengujian membuat pengalaman terasa tidak konsisten. Pengunjung yang kembali sebaiknya melihat versi yang sama dengan kunjungan sebelumnya, dan semua versi harus berfungsi baik di semua perangkat." },
  { type: "h2", text: "Membangun kebiasaan belajar, bukan sekadar mencari pemenang" },
  { type: "p", text: "Nilai terbesar dari pengujian bukan kemenangan tunggal, melainkan pemahaman yang menumpuk tentang pelanggan Anda. Simpan catatan setiap pengujian: hipotesis, perubahan, hasil, dan apa yang dipelajari. Catatan ini mencegah tim mengulang pengujian yang sama dan memperlihatkan pola tentang apa yang penting bagi pelanggan." },
  { type: "p", text: "Pengujian yang gagal juga berharga. Hasil yang menunjukkan bahwa perubahan tidak berpengaruh membebaskan Anda dari terus membahasnya, dan hasil yang menunjukkan perubahan merugikan menyelamatkan Anda dari kesalahan yang bisa saja diterapkan ke seluruh situs." },
  { type: "p", text: "Jadikan pengujian bagian dari ritme kerja yang ringan, misalnya satu atau dua pengujian aktif pada satu waktu dengan tinjauan bulanan. Tim kecil yang konsisten belajar sedikit demi sedikit biasanya melampaui tim yang melakukan pengujian besar sekali setahun." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Menghentikan pengujian begitu satu versi tampak unggul",
    "Menguji banyak perubahan sekaligus lalu mengklaim tahu mana yang berpengaruh",
    "Menentukan ukuran keberhasilan setelah melihat hasil",
    "Menguji pada lalu lintas yang terlalu kecil dan menganggap hasilnya pasti",
    "Mengabaikan mutu hasil demi menaikkan jumlah tindakan",
    "Tidak mencatat hasil sehingga pelajaran hilang",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Tentukan satu tindakan utama di website Anda dan pastikan pelacakannya akurat",
    "Cari satu titik di mana banyak pengunjung berhenti lewat data dan rekaman sesi",
    "Tulis hipotesis lengkap dengan alasan dan ukuran keberhasilan",
    "Tetapkan sebelumnya durasi atau jumlah pengunjung yang dibutuhkan",
    "Siapkan lembar catatan sederhana untuk menyimpan setiap pengujian dan pelajarannya",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Uji A/B adalah alat yang kuat untuk mengganti perdebatan dengan bukti, tetapi hanya bila dijalankan dengan disiplin: masalah yang jelas, hipotesis tertulis, ukuran yang ditetapkan lebih dulu, dan kesabaran menunggu data yang cukup." },
  { type: "p", text: "Bila lalu lintas Anda belum memadai, jangan memaksakan pengujian. Perbaiki hal-hal yang jelas terlihat bermasalah, lakukan pengamatan langsung terhadap pengunjung, dan simpan pengujian untuk saat volume sudah mendukung. Peningkatan yang pasti dari perbaikan dasar sering lebih besar daripada yang dijanjikan pengujian yang terburu-buru." },
  {
    type: "cta",
    title: "Website Anda ramai dikunjungi tetapi sedikit yang menjadi pelanggan?",
    text: "Tim AG·SORA membantu menganalisis perilaku pengunjung, memperbaiki halaman dan alur checkout, serta menyiapkan pengukuran yang bisa dipercaya. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
