import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Ketika toko online menerima pesanan, banyak hal yang seharusnya terjadi hampir bersamaan: stok berkurang, gudang menerima perintah, pelanggan mendapat konfirmasi, dan keuangan mencatat penjualan. Bila setiap langkah menunggu seseorang memindahkan data secara manual atau menunggu jadwal sinkronisasi malam hari, selalu ada jeda tempat kesalahan dan keterlambatan bersembunyi." },
  { type: "p", text: "Webhook adalah salah satu cara paling sederhana untuk menghilangkan jeda itu. Alih-alih satu sistem bertanya berulang kali apakah ada yang baru, sistem yang mengalami kejadian langsung mengabari sistem lain. Konsepnya sederhana, tetapi penerapannya yang sehat memerlukan beberapa kebiasaan yang sering terlewat." },
  { type: "p", text: "Artikel ini menjelaskan webhook dan integrasi real-time dengan bahasa untuk pemilik bisnis dan pengelola produk: apa bedanya dengan cara lain, kapan layak dipakai, apa saja yang perlu dirancang agar andal, dan bagaimana menghindari masalah yang umum. Tidak ada klaim kinerja rekaan; yang ditawarkan adalah pemahaman agar Anda dapat berdiskusi dengan tim teknis secara efektif." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Webhook adalah pemberitahuan otomatis dari satu sistem ke sistem lain saat suatu kejadian terjadi",
      "Ia menggantikan kebiasaan memeriksa berkala dengan kabar langsung, sehingga data lebih segar",
      "Pemberitahuan bisa terlewat atau datang berulang; rancang agar aman terhadap keduanya",
      "Verifikasi asal pemberitahuan dan batasi data yang dikirim",
      "Pantau dan catat setiap integrasi karena kegagalannya sering tidak terlihat",
    ],
  },
  { type: "h2", text: "Dua cara sistem saling bertukar kabar" },
  { type: "p", text: "Cara pertama adalah bertanya berkala, sering disebut polling. Sistem A menanyakan kepada sistem B setiap beberapa menit: apakah ada pesanan baru? Cara ini mudah dipahami dan mudah dibuat, tetapi boros, karena sebagian besar pertanyaan dijawab tidak ada, dan lambat, karena kabar baru diketahui paling cepat pada pertanyaan berikutnya." },
  { type: "p", text: "Cara kedua adalah diberi kabar, yaitu webhook. Sistem B mengirim pesan kepada sistem A tepat ketika pesanan baru terjadi. Tidak ada pertanyaan yang sia-sia dan tidak ada jeda yang tidak perlu. Analogi yang mudah: polling seperti Anda berulang kali membuka kotak surat untuk melihat apakah ada kiriman, sedangkan webhook seperti kurir yang membunyikan bel saat paket tiba." },
  { type: "p", text: "Kedua cara punya tempat. Webhook cocok untuk kejadian yang perlu ditindaklanjuti cepat. Polling tetap berguna sebagai jaring pengaman untuk memastikan tidak ada kejadian yang terlewat, dan untuk sistem yang tidak menyediakan webhook. Banyak integrasi yang andal memakai keduanya." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    alt: "Papan sirkuit elektronik dengan chip dan komponen, tampak dekat",
    caption: "Integrasi yang baik menghubungkan sistem-sistem seperti jalur sirkuit: sederhana di permukaan, teliti di dalam.",
  },
  { type: "h2", text: "Contoh kejadian yang cocok memakai webhook" },
  { type: "ul", items: [
    "Pesanan baru atau pembayaran berhasil di toko online, diteruskan ke gudang dan sistem keuangan",
    "Perubahan stok di gudang, diteruskan ke semua kanal penjualan agar tidak terjual berlebih",
    "Status pengiriman berubah, diteruskan untuk memberi tahu pelanggan",
    "Pelanggan baru mendaftar, diteruskan ke CRM dan sistem email",
    "Tiket dukungan dibuka atau ditutup, diteruskan ke tim yang bertanggung jawab",
    "Pembayaran dari penyedia pembayaran dikonfirmasi, diteruskan untuk memperbarui status pesanan",
  ] },
  { type: "p", text: "Pola umumnya sama: ada kejadian yang penting di satu sistem dan sistem lain perlu bereaksi segera. Bila reaksi tidak perlu cepat, misalnya laporan mingguan, tidak perlu memaksa memakai webhook; jadwal berkala yang sederhana lebih mudah dirawat." },
  { type: "h2", text: "Cara kerjanya, tanpa terlalu teknis" },
  { type: "p", text: "Penerima menyediakan sebuah alamat di internet yang siap menerima pesan. Pengirim diberi tahu alamat itu dan jenis kejadian yang diinginkan. Ketika kejadian muncul, pengirim mengirim pesan berisi ringkasan kejadian ke alamat tersebut. Penerima memproses pesan dan membalas bahwa ia sudah menerimanya." },
  { type: "p", text: "Isi pesan biasanya berupa data terstruktur: jenis kejadian, waktu, dan pengenal objek terkait, seperti nomor pesanan. Sering kali pesan hanya memuat pengenal itu, dan penerima mengambil rinciannya sendiri lewat antarmuka pemrograman. Pendekatan ini menjaga pesan tetap ringan dan membatasi data sensitif yang berpindah." },
  { type: "p", text: "Balasan penerima penting. Bila pengirim tidak menerima balasan sukses, ia menganggap pesan belum sampai dan akan mencoba lagi. Karena itu penerima sebaiknya membalas cepat dan memproses pekerjaan berat di belakang layar, bukan membuat pengirim menunggu." },
  { type: "h2", text: "Masalah klasik: pesan terlewat dan pesan ganda" },
  { type: "p", text: "Jaringan tidak sempurna. Penerima bisa sedang dalam pemeliharaan, jaringan terputus, atau server kelebihan beban. Pengirim yang baik mencoba mengirim ulang beberapa kali dengan jeda yang makin panjang, tetapi tidak ada jaminan bahwa semua pesan akan sampai." },
  { type: "p", text: "Sebaliknya, pengiriman ulang berarti pesan yang sama bisa datang lebih dari sekali. Bila penerima memproses pesanan baru setiap kali pesan datang, satu pesanan bisa menjadi dua, dan stok berkurang dua kali. Inilah masalah yang paling sering menggigit tim yang baru memakai webhook." },
  { type: "p", text: "Solusinya adalah rancangan yang tahan terhadap pengulangan. Setiap pesan memuat pengenal unik, dan penerima mencatat pengenal yang sudah diproses. Bila pengenal yang sama datang lagi, penerima mengenalinya dan tidak mengerjakan ulang. Istilah teknisnya idempoten, dan ini adalah syarat dasar integrasi yang sehat." },
  { type: "callout", title: "Anggap pesan bisa terlewat dan bisa ganda", text: "Rancang penerima agar aman bila pesan datang dua kali, dan sediakan pemeriksaan berkala untuk menangkap pesan yang tidak pernah datang. Dua kebiasaan ini mencegah sebagian besar masalah data antar sistem." },
  { type: "h2", text: "Urutan kejadian tidak selalu sesuai harapan" },
  { type: "p", text: "Pesan tidak selalu tiba sesuai urutan kejadian. Pesanan dibayar dan pesanan dikirim bisa tiba terbalik bila salah satu sempat tertahan dan dikirim ulang. Penerima yang mengasumsikan urutan akan menghasilkan status yang salah, misalnya pesanan yang tampak belum dibayar padahal sudah dikirim." },
  { type: "p", text: "Pastikan setiap pesan memuat waktu kejadian atau nomor versi, dan penerima hanya menerapkan pesan yang lebih baru daripada keadaan yang sudah tercatat. Cara lain adalah menjadikan pesan sebagai pemicu untuk mengambil keadaan terkini dari sumbernya, sehingga urutan kedatangan tidak lagi menentukan hasil." },
  { type: "p", text: "Pertimbangkan juga lonjakan. Kampanye besar bisa menghasilkan ribuan pesan dalam waktu singkat. Antrean di sisi penerima menjaga sistem tetap stabil dengan memproses satu per satu sesuai kapasitas, alih-alih tumbang saat banjir pesan datang." },
  { type: "h2", text: "Keamanan: memastikan pesan benar dan aman" },
  { type: "p", text: "Alamat penerima webhook terbuka di internet, sehingga siapa pun bisa mencoba mengirim pesan palsu. Pengirim yang baik menandatangani pesannya dengan rahasia bersama, dan penerima memeriksa tanda tangan itu sebelum memprosesnya. Pesan tanpa tanda tangan yang valid ditolak." },
  { type: "p", text: "Batasi data yang dikirim ke yang benar-benar perlu. Hindari menaruh data pribadi sensitif dalam pesan bila cukup mengirim pengenal. Gunakan koneksi terenkripsi, simpan rahasia di tempat yang aman, dan ganti secara berkala atau saat ada staf yang berhenti dan pernah mengaksesnya." },
  { type: "p", text: "Tolak pesan yang terlalu lama atau terlalu besar, dan batasi laju penerimaan agar penerima tidak mudah dibuat kewalahan. Keamanan integrasi sering terlupakan karena tidak terlihat oleh pengguna akhir, padahal ia menyentuh data pelanggan dan transaksi." },
  { type: "h2", text: "Pemantauan dan pencatatan" },
  { type: "p", text: "Integrasi yang gagal sering tidak ketahuan sampai ada yang mengeluh: stok yang tidak sinkron, pesanan yang tidak sampai ke gudang, atau pelanggan yang tidak mendapat konfirmasi. Catat setiap pesan yang diterima dan diproses, termasuk hasil dan kesalahannya, sehingga penelusuran bisa dilakukan tanpa menebak." },
  { type: "p", text: "Pasang pemberitahuan untuk gejala yang penting: banyak kegagalan beruntun, antrean yang terus membesar, atau tidak ada pesan sama sekali dalam waktu yang tidak wajar. Ketiadaan pesan sering merupakan tanda masalah yang paling sunyi dan paling mahal." },
  { type: "p", text: "Sediakan cara memproses ulang pesan yang gagal setelah masalahnya diperbaiki. Tanpa kemampuan ini, perbaikan harus dilakukan manual satu per satu dan sulit dipastikan lengkap." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74",
    alt: "Layar menampilkan panel metrik dengan grafik garis kecil dan angka performa",
    caption: "Panel pemantauan yang sederhana membantu menangkap integrasi yang gagal sebelum pelanggan merasakannya.",
  },
  { type: "h2", text: "Kapan memakai alat penghubung siap pakai, kapan membangun sendiri" },
  { type: "p", text: "Banyak kebutuhan sederhana dapat dipenuhi dengan layanan penghubung siap pakai yang menghubungkan aplikasi populer tanpa menulis kode. Untuk alur yang jelas dan volumenya wajar, ini cepat dan murah, dan dapat dirawat oleh staf non-teknis." },
  { type: "p", text: "Membangun sendiri layak dipertimbangkan ketika volume tinggi, aturan bisnis rumit, data sangat sensitif, atau integrasi menjadi bagian inti operasional yang tidak boleh bergantung pada pihak ketiga. Dengan membangun sendiri, Anda mendapat kendali penuh, tetapi juga tanggung jawab perawatan." },
  { type: "p", text: "Sering kali pendekatan campuran paling masuk akal: layanan siap pakai untuk alur pendukung, dan integrasi khusus untuk alur yang menyentuh uang, stok, dan data pelanggan secara langsung. Dokumentasikan keduanya agar tidak ada integrasi yang hanya diketahui satu orang." },
  { type: "h2", text: "Gambaran alur pesanan dari kejadian sampai tindakan" },
  { type: "p", text: "Sebagai gambaran, bayangkan pelanggan membayar pesanan di toko online. Penyedia pembayaran mengirim kabar bahwa pembayaran berhasil. Toko menerima kabar itu, memeriksa tanda tangannya, mengubah status pesanan menjadi dibayar, lalu mengabari sistem gudang agar menyiapkan barang. Gudang mengurangi stok yang dicadangkan dan mengabari semua kanal bahwa stok berubah." },
  { type: "p", text: "Ketika paket diserahkan kepada kurir, sistem gudang mengabari toko, dan toko mengirim pesan kepada pelanggan dengan nomor resi. Setiap langkah dipicu oleh kejadian sebelumnya, tanpa seorang pun perlu menyalin data. Di belakang itu, sistem keuangan menerima kabar yang sama dan mencatat penjualan." },
  { type: "p", text: "Alur ini terlihat mulus bagi pelanggan, tetapi masing-masing sambungan perlu tahan terhadap pesan ganda, keterlambatan, dan kegagalan. Menuliskan alurnya sebagai diagram sederhana dengan kejadian dan tindakannya adalah cara yang baik untuk menemukan titik lemah sebelum dibangun." },
  { type: "h2", text: "Menguji integrasi sebelum dan sesudah peluncuran" },
  { type: "p", text: "Uji bukan hanya jalur yang mulus. Simulasikan pesan ganda, pesan yang datang terbalik urutannya, penerima yang mati sementara, dan pesan dengan tanda tangan yang salah. Sistem yang hanya diuji pada kasus normal akan terkejut di hari pertama volume tinggi." },
  { type: "p", text: "Gunakan lingkungan percobaan yang terpisah dari data nyata. Banyak penyedia menyediakan lingkungan uji dan alat untuk mengirim pesan contoh. Setelah peluncuran, lakukan pemeriksaan rekonsiliasi berkala: bandingkan jumlah kejadian di sistem pengirim dengan yang tercatat di penerima untuk menangkap selisih lebih awal." },
  { type: "p", text: "Jadwalkan uji ulang bila ada perubahan besar, misalnya pembaruan sistem, perubahan format data, atau penambahan kanal. Integrasi yang berjalan baik hari ini bisa rusak oleh perubahan yang tampak tidak berkaitan." },
  { type: "h2", text: "Batas pemakaian dan perilaku yang sopan" },
  { type: "p", text: "Banyak layanan pihak ketiga membatasi jumlah permintaan yang boleh Anda kirim dalam waktu tertentu. Melampauinya bisa membuat permintaan ditolak atau akun dibatasi. Rancang integrasi agar menghormati batas itu, misalnya dengan antrean dan jeda, serta menangani penolakan dengan mencoba lagi secara bertahap." },
  { type: "p", text: "Hindari mengambil data lebih banyak dari yang diperlukan atau terlalu sering. Pengambilan yang berlebihan membuang sumber daya, memperlambat sistem, dan dapat melanggar ketentuan layanan. Webhook justru membantu karena Anda hanya bertindak ketika ada kejadian nyata." },
  { type: "h2", text: "Dokumentasi dan kepemilikan" },
  { type: "p", text: "Setiap integrasi sebaiknya punya catatan sederhana: sistem mana yang terhubung, kejadian apa yang dipicu, siapa pemiliknya, di mana rahasia disimpan, dan apa yang dilakukan bila gagal. Dokumen satu halaman sudah cukup dan sangat berharga ketika ada pergantian orang." },
  { type: "p", text: "Pastikan akun dan kunci akses atas nama bisnis, bukan atas nama perorangan atau vendor. Integrasi yang bergantung pada akun pribadi seorang karyawan akan putus ketika orang itu pergi. Tinjau daftar integrasi secara berkala dan matikan yang sudah tidak dipakai." },
  { type: "p", text: "Rencanakan perubahan. Penyedia sistem dapat memperbarui antarmuka mereka, dan pesan yang formatnya berubah bisa merusak penerima tanpa tanda. Ikuti pengumuman perubahan dari penyedia dan uji integrasi pada lingkungan percobaan sebelum perubahan berlaku." },
  { type: "h2", text: "Biaya dan kompleksitas yang perlu dihitung" },
  { type: "p", text: "Integrasi real-time memberi nilai, tetapi bukan tanpa biaya. Ada biaya membangun, biaya layanan penghubung atau infrastruktur penerima, dan biaya perawatan terus-menerus ketika pihak lain mengubah sistemnya. Hitung semuanya dan bandingkan dengan nilai yang dihasilkan, misalnya berkurangnya kesalahan stok atau waktu staf yang dihemat." },
  { type: "p", text: "Mulailah dari alur yang nilainya paling jelas, buktikan, lalu perluas. Banyak bisnis membangun puluhan integrasi sekaligus lalu kewalahan merawatnya. Sedikit integrasi yang andal dan terdokumentasi lebih berharga daripada banyak yang rapuh." },
  { type: "h2", text: "Menjelaskan kebutuhan kepada tim teknis" },
  { type: "p", text: "Pemilik bisnis tidak perlu memahami setiap detail teknis, tetapi perlu menyampaikan kebutuhan dengan jelas. Jelaskan kejadian apa yang penting, tindakan apa yang harus mengikutinya, seberapa cepat, dan apa akibatnya bila terlambat atau terlewat. Contoh konkret seperti satu pesanan dari awal sampai tiba di pelanggan jauh lebih membantu daripada daftar fitur." },
  { type: "p", text: "Minta tim teknis menjelaskan balik rancangannya dalam bahasa yang Anda pahami: apa yang terjadi bila pesan datang dua kali, bagaimana mereka tahu bila ada yang gagal, dan siapa yang dihubungi pada tengah malam. Jawaban yang jelas menandakan integrasi yang dirancang dengan matang." },
  { type: "h2", text: "Kesalahan umum yang sebaiknya dihindari" },
  { type: "ul", items: [
    "Mengasumsikan setiap pesan hanya datang satu kali dan sesuai urutan",
    "Memproses pekerjaan berat sebelum membalas pengirim sehingga pesan dianggap gagal",
    "Tidak memverifikasi asal pesan sehingga siapa pun bisa mengirim pesan palsu",
    "Tidak memiliki pencatatan dan pemberitahuan sehingga kegagalan tidak terlihat",
    "Menaruh data pribadi sensitif dalam pesan padahal pengenal sudah cukup",
    "Membiarkan integrasi bergantung pada akun pribadi atau satu orang",
  ] },
  { type: "h2", text: "Langkah awal yang bisa dimulai minggu ini" },
  { type: "ol", items: [
    "Daftar tempat di bisnis Anda yang masih memindahkan data manual atau menunggu sinkronisasi terjadwal",
    "Pilih satu alur bernilai tinggi, misalnya pesanan ke gudang, sebagai percontohan",
    "Tanyakan kepada tim teknis bagaimana pesan ganda dan pesan terlewat akan ditangani",
    "Pastikan ada pencatatan dan pemberitahuan untuk kegagalan integrasi",
    "Buat dokumen satu halaman untuk setiap integrasi yang berjalan saat ini",
  ] },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Webhook dan integrasi real-time membuat sistem-sistem bisnis bekerja seperti satu kesatuan: stok, pesanan, pembayaran, dan layanan pelanggan saling mengabari tanpa menunggu tangan manusia. Manfaatnya terasa pada ketepatan data dan kecepatan reaksi." },
  { type: "p", text: "Namun keandalannya lahir dari detail: ketahanan terhadap pesan ganda, pemeriksaan pesan yang terlewat, keamanan, dan pemantauan. Bila detail itu diperhatikan sejak awal, integrasi menjadi tulang punggung operasional yang tenang, bukan sumber kejutan." },
  {
    type: "cta",
    title: "Data antar sistem masih dipindahkan manual atau sering tidak sinkron?",
    text: "Tim AG·SORA merancang integrasi antara toko online, ERP, kasir, dan layanan pihak ketiga dengan pencatatan, pemantauan, dan penanganan kegagalan yang rapi. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/api-integration",
    label: "Konsultasi gratis",
  },
];
