import type { Block } from "@/config/blog";

export const body: Block[] = [
  { type: "p", text: "Internet menghapus banyak batas geografis. Bisnis di satu kota kini dapat dilihat calon pelanggan di negara lain, entah mereka mencari pemasok, mitra, atau layanan. Namun kemampuan untuk terlihat tidak sama dengan kemampuan untuk dipahami. Pengunjung yang tiba di website dalam bahasa yang tidak mereka kuasai biasanya pergi dalam hitungan detik, betapapun bagus produk di baliknya." },
  { type: "p", text: "Website multibahasa menjawab masalah itu dengan menyajikan konten dalam bahasa pengunjung. Bagi bisnis yang melayani wisatawan, mengekspor produk, bermitra dengan perusahaan asing, atau menarget komunitas berbahasa lain di dalam negeri, ini bisa menjadi pembeda yang nyata. Akan tetapi, pelaksanaannya penuh jebakan: terjemahan yang kaku, struktur alamat yang membingungkan mesin pencari, dan konten yang tidak terawat sehingga bahasa-bahasa berjalan tidak seirama." },
  { type: "p", text: "Artikel ini membahas cara merancang dan mengelola website multibahasa dengan baik. Kami membahas kapan benar-benar perlu, bagaimana memilih bahasa, struktur alamat yang ramah mesin pencari, tanda hreflang, kualitas terjemahan dan penyesuaian budaya, pengalaman pengguna, serta proses pemeliharaan jangka panjang. Kami tidak memakai angka rekaan tentang peningkatan kunjungan karena hasil sangat bergantung pada pasar dan konten; yang kami tawarkan adalah prinsip dan daftar periksa yang bisa Anda terapkan." },
  { type: "h2", text: "Ringkasan" },
  {
    type: "ul",
    items: [
      "Tambah bahasa karena ada pelanggan atau pasar nyata yang dituju, bukan sekadar agar terlihat internasional",
      "Mulai dari sedikit bahasa yang dikerjakan dengan baik, lalu tambah bertahap, daripada banyak bahasa dengan kualitas buruk",
      "Gunakan alamat terpisah yang jelas untuk tiap bahasa dan tandai hubungannya dengan hreflang agar mesin pencari menayangkan versi yang tepat",
      "Terjemahan yang baik menyesuaikan nada, istilah, dan budaya, bukan hanya mengganti kata; libatkan penutur asli",
      "Rencanakan pemeliharaan sejak awal agar semua bahasa tetap mutakhir dan seirama",
    ],
  },
  { type: "h2", text: "Kapan website multibahasa benar-benar diperlukan" },
  { type: "p", text: "Sebelum menambah bahasa, tanyakan siapa yang ingin Anda jangkau dan apakah mereka benar-benar akan terbantu. Beberapa situasi membuat website multibahasa sangat masuk akal. Bisnis pariwisata, perhotelan, dan kuliner di daerah dengan banyak pengunjung asing mendapat manfaat langsung dari konten dalam bahasa wisatawan. Eksportir dan pemasok yang mencari pembeli di luar negeri perlu tampil meyakinkan di depan calon mitra. Perusahaan jasa yang melayani klien dari berbagai negara atau komunitas bahasa juga terbantu." },
  { type: "p", text: "Di sisi lain, jika hampir semua pelanggan Anda berbahasa sama dan tidak ada rencana nyata melayani yang lain, menambah bahasa hanya menambah beban pemeliharaan tanpa hasil. Terjemahan yang tidak dirawat lebih buruk daripada tidak ada terjemahan, karena memberi kesan bisnis yang tidak profesional atau sudah tidak aktif." },
  { type: "p", text: "Pertimbangkan juga kemampuan melayani. Jika pengunjung membaca website dalam bahasa mereka, mereka akan berharap bisa dilayani dalam bahasa itu juga: pertanyaan dijawab, dukungan tersedia, dan pesanan diproses dengan jelas. Menjanjikan lewat website namun tidak sanggup menindaklanjuti menciptakan kekecewaan. Pastikan Anda atau tim punya cara menangani pertanyaan dari tiap bahasa yang ditawarkan, setidaknya dengan alur yang jujur tentang batas layanan." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1451187580459-43490279c0fa",
    alt: "Foto bumi dari luar angkasa dengan cahaya kota di malam hari",
    caption: "Menjangkau dunia dimulai dari berbicara dalam bahasa pelanggan, bukan hanya dari menayangkan website di internet.",
  },
  { type: "h2", text: "Memilih bahasa yang tepat" },
  { type: "p", text: "Pilih bahasa berdasarkan data dan tujuan, bukan tebakan. Lihat dari mana pengunjung website Anda sekarang datang, bahasa apa yang dipakai browser mereka, dan dari mana pertanyaan atau pesanan berasal. Lihat juga pasar yang ingin Anda masuki dan seberapa besar kemungkinan mereka mencari produk atau jasa Anda dalam bahasa tertentu." },
  { type: "p", text: "Mulailah dari satu atau dua bahasa tambahan yang paling jelas manfaatnya. Menyajikan sedikit bahasa dengan kualitas tinggi jauh lebih baik daripada sepuluh bahasa dengan terjemahan seadanya. Setiap bahasa tambahan membawa beban: terjemahan awal, peninjauan, pembaruan setiap ada perubahan, dukungan pelanggan, dan pengujian. Tambahkan bahasa baru ketika Anda yakin mampu merawat yang sudah ada." },
  { type: "p", text: "Perhatikan bahwa bahasa dan negara bukan hal yang sama. Satu bahasa dipakai di banyak negara dengan variasi istilah, ejaan, mata uang, dan kebiasaan, sementara satu negara bisa memakai beberapa bahasa. Tentukan apakah Anda menarget bahasa, negara, atau keduanya, karena ini memengaruhi struktur alamat, mata uang, harga, dan ketentuan pengiriman yang ditampilkan." },
  { type: "h2", text: "Struktur alamat yang ramah mesin pencari" },
  { type: "p", text: "Cara Anda menata alamat tiap versi bahasa sangat memengaruhi seberapa baik mesin pencari memahami dan menayangkannya. Ada tiga pendekatan umum, masing-masing dengan kelebihan dan kekurangan." },
  {
    type: "ol",
    items: [
      "Subdirektori: bahasa ditandai di jalur alamat, misalnya nama situs diikuti penanda bahasa lalu halaman; paling sederhana dikelola dan menjaga semua versi di bawah satu situs",
      "Subdomain: tiap bahasa di subdomain terpisah; memberi fleksibilitas teknis tetapi sering diperlakukan lebih terpisah oleh mesin pencari",
      "Domain terpisah per negara: tiap pasar punya nama domain sendiri; sinyal negara paling kuat tetapi biaya, pengelolaan, dan upaya membangun reputasi berlipat",
    ],
  },
  { type: "p", text: "Untuk kebanyakan bisnis kecil dan menengah, subdirektori adalah pilihan paling praktis. Satu situs menyatukan seluruh reputasi, pemeliharaan lebih sederhana, dan penambahan bahasa baru mudah. Domain terpisah baru layak dipertimbangkan jika Anda punya operasi nyata dan tim lokal di tiap negara." },
  { type: "p", text: "Hindari pendekatan yang menampilkan bahasa berbeda pada alamat yang sama berdasarkan lokasi atau pengaturan browser pengunjung tanpa memberi alamat terpisah. Mesin pencari hanya melihat satu versi, sehingga versi lain tidak pernah muncul di hasil pencarian. Selain itu, pengunjung tidak bisa membagikan tautan ke bahasa tertentu. Selalu berikan alamat unik untuk setiap versi bahasa, dan biarkan pengunjung berganti bahasa dengan bebas." },
  { type: "h3", text: "Alamat halaman yang konsisten" },
  { type: "p", text: "Pertahankan struktur yang paralel di semua bahasa agar mudah dikelola. Jika halaman layanan ada pada jalur tertentu di satu bahasa, halaman yang sama di bahasa lain mengikuti pola serupa. Gunakan bagian alamat yang bermakna dan, bila memungkinkan, diterjemahkan agar terbaca wajar bagi penutur bahasa itu, tetapi tetap konsisten dan stabil. Hindari mengubah alamat setelah terbit tanpa pengalihan yang tepat." },
  { type: "h2", text: "Memberi tahu mesin pencari tentang hubungan antarversi" },
  { type: "p", text: "Ketika konten yang sama tersedia dalam beberapa bahasa, mesin pencari perlu tahu bahwa versi-versi itu saling terkait, bukan duplikat. Di sinilah tanda hreflang berperan. Tanda ini memberi tahu mesin pencari versi bahasa mana yang tersedia untuk halaman tertentu, sehingga pengguna yang mencari dalam bahasa Mandarin diarahkan ke versi Mandarin, pengguna berbahasa Inggris ke versi Inggris, dan seterusnya." },
  { type: "p", text: "Beberapa prinsip penerapan hreflang perlu diingat. Setiap versi harus menyebut dirinya sendiri dan semua versi lain secara timbal balik; jika halaman A menunjuk halaman B, halaman B harus menunjuk balik ke A. Sertakan juga penanda untuk versi bawaan bagi pengunjung yang bahasanya tidak tersedia. Gunakan kode bahasa yang benar, dan tambahkan kode wilayah hanya jika Anda memang membedakan konten per wilayah. Anda dapat menerapkannya lewat bagian kepala halaman, header, atau peta situs." },
  { type: "p", text: "Kesalahan umum meliputi hreflang yang tidak timbal balik, kode bahasa yang salah, dan menunjuk ke halaman yang sudah dialihkan atau tidak ada. Setelah penerapan, periksa dengan alat bantu pengujian dan laporan di alat webmaster dari mesin pencari. Pastikan juga peta situs memuat semua versi bahasa sehingga mudah ditemukan perayap." },
  { type: "p", text: "Perlu dicatat bahwa halaman yang hanya tersedia di satu bahasa sebaiknya tidak menampilkan versi bahasa lain yang sebenarnya hanya salinan bahasa asli. Menayangkan teks berbahasa Indonesia di bawah alamat berlabel Inggris membuat pengunjung bingung dan mesin pencari menganggapnya duplikat yang salah label. Tayangkan versi bahasa hanya untuk halaman yang benar-benar sudah diterjemahkan." },
  {
    type: "callout",
    title: "Satu bahasa, satu halaman, satu alamat",
    text: "Setiap halaman dalam tiap bahasa sebaiknya punya alamat sendiri, bahasa yang konsisten di seluruh isinya, dan hubungan timbal balik yang jelas dengan versi bahasa lainnya.",
  },
  { type: "h2", text: "Kualitas terjemahan dan penyesuaian budaya" },
  { type: "p", text: "Terjemahan yang baik lebih dari mengganti kata satu per satu. Ia menyampaikan makna, nada, dan maksud dengan cara yang terasa wajar bagi penutur asli. Terjemahan kaku yang jelas hasil mesin tanpa penyuntingan merusak kepercayaan, terutama pada website bisnis yang harus tampak profesional." },
  { type: "p", text: "Alat terjemahan otomatis kini cukup baik untuk membuat draf, tetapi hasilnya tetap perlu ditinjau oleh penutur asli yang memahami konteks bisnis Anda. Peninjauan menangkap kesalahan istilah teknis, nada yang tidak sesuai, ungkapan yang terdengar janggal, dan arti yang bergeser. Untuk halaman terpenting seperti beranda, halaman layanan, dan halaman kontak, pertimbangkan terjemahan atau penyuntingan manual yang cermat." },
  { type: "p", text: "Buatlah daftar istilah baku yang dipakai konsisten di semua bahasa, seperti nama produk, nama layanan, dan istilah teknis khusus. Putuskan mana yang tidak diterjemahkan, misalnya nama merek, dan mana yang diterjemahkan. Konsistensi istilah membuat website terlihat rapi dan memudahkan penerjemah baru bekerja." },
  { type: "h3", text: "Menyesuaikan dengan budaya dan kebiasaan" },
  { type: "p", text: "Penyesuaian budaya sering lebih penting daripada terjemahan kata. Perhatikan hal-hal seperti format tanggal, jam, angka, dan mata uang, satuan ukuran, serta cara menulis alamat dan nama. Warna, gambar, dan contoh yang akrab di satu budaya bisa terasa asing atau bahkan tidak pantas di budaya lain. Cara menyapa dan tingkat keformalan juga berbeda; sebagian pasar menyukai bahasa langsung, sebagian menghargai kesantunan yang lebih berlapis." },
  { type: "p", text: "Pikirkan pula soal praktis seperti metode pembayaran yang lazim di tiap pasar, opsi pengiriman, kebijakan retur, dan jam layanan sesuai zona waktu. Pengunjung yang membaca harga dalam mata uang yang tidak mereka kenal, atau tidak menemukan metode bayar yang biasa mereka pakai, mungkin mengurungkan niat meski terjemahannya sempurna. Pertimbangkan juga ketentuan hukum yang berlaku di tiap pasar, seperti kebijakan privasi dan perlindungan konsumen, dan rujuklah ketentuan terbaru dari otoritas yang berwenang, bukan ringkasan yang mungkin usang." },
  { type: "h2", text: "Pengalaman pengguna pada website multibahasa" },
  { type: "p", text: "Pengunjung harus mudah menemukan dan berganti bahasa. Letakkan pemilih bahasa di tempat yang konsisten dan mudah terlihat, biasanya di kepala halaman. Tulis nama tiap bahasa dalam bahasa itu sendiri, misalnya bahasa Mandarin ditulis dengan aksara Mandarin, agar penutur bisa mengenalinya meski tidak memahami bahasa sekitarnya. Hindari memakai bendera negara sebagai pengganti bahasa, karena satu bahasa tidak identik dengan satu negara dan bendera dapat menimbulkan salah paham." },
  { type: "p", text: "Pertimbangkan menyarankan bahasa berdasarkan pengaturan browser pengunjung, tetapi jangan memaksa. Tampilkan usulan yang bisa diabaikan, dan ingat pilihan pengunjung agar ia tidak harus memilih ulang setiap kali. Ketika pengunjung berganti bahasa, arahkan ke halaman yang setara di bahasa tujuan, bukan selalu kembali ke beranda." },
  { type: "p", text: "Perhatikan pula aspek tampilan. Teks dalam bahasa berbeda memiliki panjang berbeda; judul yang pas dalam satu bahasa bisa meluap pada bahasa lain. Aksara tertentu memerlukan jenis huruf yang mendukungnya dengan baik dan ukuran serta jarak baris yang sesuai. Beberapa bahasa ditulis dari kanan ke kiri dan memerlukan penyesuaian tata letak. Uji setiap versi bahasa pada ukuran layar ponsel dan desktop, bukan hanya di bahasa asli." },
  {
    type: "image",
    src: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89",
    alt: "Laptop dan monitor di meja dekat jendela besar",
    caption: "Setiap versi bahasa perlu diuji di layar nyata, karena panjang teks dan aksara berbeda memengaruhi tata letak.",
  },
  { type: "h2", text: "Menjaga kecepatan dan teknis yang sehat" },
  { type: "p", text: "Menambah bahasa tidak boleh memperlambat website. Pastikan halaman versi apa pun tetap cepat dimuat, gambar dioptimalkan, dan tidak ada sumber daya yang dimuat berlebihan hanya karena ada banyak bahasa. Muat hanya konten untuk bahasa yang sedang dilihat, bukan seluruh terjemahan sekaligus." },
  { type: "p", text: "Pastikan juga atribut bahasa pada halaman diisi benar agar pembaca layar dan mesin pencari tahu bahasa konten. Terapkan metadata seperti judul dan deskripsi yang diterjemahkan dengan baik untuk setiap bahasa, karena inilah yang tampil di hasil pencarian dan sering menentukan apakah orang mengklik. Terjemahkan juga teks alternatif gambar dan data terstruktur, bukan hanya teks yang tampak di halaman." },
  { type: "p", text: "Peta situs perlu memuat semua versi bahasa dengan hubungan antarversinya, dan halaman tidak boleh terblokir dari perayap. Untuk situs yang dibangun dengan kerangka kerja modern, pastikan halaman bahasa dirender sehingga mesin pencari menerima isi lengkap, tidak hanya kerangka kosong yang diisi belakangan." },
  { type: "h2", text: "Memelihara konten di semua bahasa" },
  { type: "p", text: "Tantangan terbesar website multibahasa bukan membangunnya, melainkan merawatnya. Setiap kali konten bahasa asli berubah, versi lain harus ikut diperbarui, jika tidak, mereka menyimpang dan akhirnya memuat informasi yang usang atau bertentangan. Informasi harga, kebijakan, atau ketentuan yang berbeda antar bahasa bisa menimbulkan masalah serius." },
  { type: "p", text: "Susun proses yang jelas. Tentukan siapa yang bertanggung jawab atas tiap bahasa, bagaimana perubahan di bahasa asli dikomunikasikan kepada penerjemah, dan bagaimana hasil terjemahan ditinjau sebelum terbit. Gunakan penanda atau daftar yang menunjukkan halaman mana yang sudah diterjemahkan dan masih mutakhir, serta mana yang tertinggal. Alat manajemen konten yang mendukung beberapa bahasa membantu melacak ini." },
  { type: "p", text: "Atur alur kerja agar konten baru diterbitkan serentak, atau secara jelas dilabeli bila ada bahasa yang menyusul. Lebih baik menunda versi yang belum siap daripada menayangkan terjemahan setengah jadi. Jadwalkan peninjauan berkala atas halaman penting di setiap bahasa, dan minta umpan balik dari pengunjung atau pelanggan berbahasa itu tentang bagian yang janggal atau keliru." },
  { type: "h2", text: "Mengukur hasil per bahasa" },
  { type: "p", text: "Seperti bagian bisnis lain, website multibahasa perlu diukur agar Anda tahu apakah investasinya berhasil. Pisahkan data per bahasa: berapa pengunjung yang datang, dari mana mereka berasal, halaman mana yang mereka baca, dan apakah mereka melakukan tindakan penting seperti mengisi formulir atau menghubungi Anda." },
  { type: "p", text: "Bandingkan antar bahasa untuk menemukan pola. Bahasa dengan banyak kunjungan tetapi sedikit tindakan mungkin memiliki masalah pada terjemahan, penyesuaian budaya, atau ketersediaan layanan. Bahasa dengan kunjungan sedikit tetapi tindakan tinggi mungkin layak diperkuat dengan lebih banyak konten dan promosi. Berikan waktu yang cukup sebelum menilai, karena versi bahasa baru butuh waktu untuk dikenali mesin pencari." },
  { type: "p", text: "Tanyakan juga langsung kepada pelanggan dari pasar tertentu bagaimana pengalaman mereka dengan website. Masukan kualitatif sering mengungkap hal yang tidak terlihat dari angka, seperti istilah yang janggal atau informasi pengiriman yang kurang jelas." },
  { type: "h2", text: "Kesalahan umum yang perlu dihindari" },
  { type: "p", text: "Beberapa kesalahan sering terjadi. Menambah terlalu banyak bahasa sekaligus tanpa kemampuan merawatnya adalah yang paling umum. Mengandalkan terjemahan mesin mentah tanpa peninjauan juga sering. Menayangkan bahasa berbeda di alamat yang sama, tidak memakai hreflang atau memakainya dengan salah, dan menampilkan halaman berbahasa asli di bawah alamat versi bahasa lain juga kerap terjadi." },
  { type: "p", text: "Kesalahan lain meliputi mengabaikan penyesuaian budaya dan hal praktis seperti mata uang dan pembayaran, tidak menyiapkan layanan pelanggan untuk bahasa yang ditawarkan, serta membiarkan versi bahasa tertinggal dari versi asli. Hindari semuanya dengan memulai kecil, mengerjakan dengan baik, dan merencanakan pemeliharaan sejak hari pertama." },
  { type: "h2", text: "Langkah praktis membangun website multibahasa" },
  {
    type: "ol",
    items: [
      "Tentukan pasar dan bahasa tujuan berdasarkan data pengunjung dan rencana bisnis, mulai dari satu atau dua bahasa",
      "Pilih struktur alamat yang konsisten, umumnya subdirektori, dengan alamat unik untuk tiap bahasa dan halaman",
      "Terapkan hreflang timbal balik dan peta situs yang memuat semua versi",
      "Libatkan penutur asli untuk menerjemahkan atau meninjau, dan buat daftar istilah baku",
      "Sesuaikan budaya, mata uang, pembayaran, pengiriman, dan ketentuan hukum untuk tiap pasar",
      "Rencanakan pemeliharaan dan pengukuran per bahasa, dan tambah bahasa baru hanya jika yang ada sudah terawat",
    ],
  },
  { type: "h2", text: "Penutup" },
  { type: "p", text: "Website multibahasa adalah cara ampuh memperluas jangkauan bisnis, asalkan dikerjakan dengan serius. Terjemahan yang baik, struktur teknis yang benar, penyesuaian budaya, dan pemeliharaan yang konsisten membuat pengunjung dari berbagai bahasa merasa dilayani, dan mesin pencari memahami siapa yang harus melihat versi mana." },
  { type: "p", text: "Mulailah dari pasar yang paling nyata bagi bisnis Anda, kerjakan dengan baik, dan perluas bertahap. Dengan begitu website Anda tidak hanya bisa diakses dari mana saja, tetapi benar-benar dapat dipahami oleh orang-orang yang ingin Anda layani." },
  {
    type: "cta",
    title: "Ingin website yang bisa melayani pelanggan dalam beberapa bahasa?",
    text: "Tim AG·SORA membangun website multibahasa dengan struktur ramah mesin pencari, hreflang yang benar, dan alur pemeliharaan yang rapi. Konsultasi awal gratis dan tanpa kewajiban.",
    href: "/services/website",
    label: "Konsultasi gratis",
  },
];
